### ISSUE TITLE
AWX 19.0.0: Inventory Source Openstack doesn't work

### ISSUE THREAD

**Issue by per-lind** [ansible/awx#10043]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: kubernetes via operator 0.8.0

##### STEPS TO REPRODUCE

Add an Inventory in AWX
Add Inventory Source as Openstack + set appropriate credentials
Sync the inventory

##### EXPECTED RESULTS

Successfull sync

##### ACTUAL RESULTS

`ansible-inventory [core 2.11.0b4] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
redirecting (type: inventory) ansible.builtin.openstack to openstack.cloud.openstack
Loading collection openstack.cloud from /usr/share/ansible/collections/ansible_collections/openstack/cloud
Valid plugin config file found
plugin config file, but not for us: openstack
[WARNING]:  * Failed to parse /runner/openstack.yml with auto plugin: plugin
config file, but not for us: openstack
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/share/ansible/collections/ansible_collections/openstack/cloud/plugins/inventory/openstack.py", line 167, in parse
    raise AnsibleParserError(msg)
[WARNING]: Unable to parse /runner/openstack.yml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.`

##### ADDITIONAL INFORMATION

Looks very much like https://github.com/ansible/awx/issues/9746
Same error https://github.com/ansible/awx/issues/9165#issuecomment-821498824

**Comment by AlanCoding** [comment]
I only just now saw this issue but have been discussing it in other forms with @pabelanger @jladdjr and others. I will copy some information here.

----

The bug here is that the openstack inventory plugin will no longer work with Ansible 2.11. You can test an inventory file (named `openstack.yml`) with either of these syntaxes:
1. plugin: openstack
2. plugin: openstack.cloud.openstack

The first option errors due to custom validation present in openstack's own inventory plugin:

> [WARNING]:  * Failed to parse /home/alancoding/repos/awx/testing/openstack/openstack.yml with auto plugin: plugin
config file, but not for us: openstack

Because this was written back before FQCNs (fully-qualified collection names) were a thing. Before it migrated to a collection, "openstack" was the expectation, but then self.NAME for the inventory plugin changed to "openstack.cloud.openstack", meaning that "openstack" by itself would no longer work. That made sense until Ansible core introduced routing where it would recognize "openstack" and route it to "openstack.cloud.openstack" for purposes of the "auto" inventory plugin routing. See the routing entry at:

https://github.com/ansible/ansible/blob/2cbfd1e350cbe1ca195d33306b5a9628667ddda8/lib/ansible/config/ansible_builtin_runtime.yml#L9548

The second option errors with:

> [WARNING]:  * Failed to parse /home/alancoding/repos/awx/testing/openstack_fqcn/openstack.yml with auto plugin:
Invalid value "openstack.cloud.openstack" for configuration option "plugin_type: inventory plugin:
ansible_collections.openstack.cloud.plugins.inventory.openstack setting: plugin ", valid values are: ['openstack']

This is due to Ansible core enforcing stricter validation of options. Merged in this PR https://github.com/ansible/ansible/pull/73162

That broke many inventory plugins because the practice before the migration to collections was to list the name in the choices for the "plugin" option. This has been fixed in other collections.

Because neither of these options work, the inventory plugin is not usable in recent Ansible versions.

Suggested patch here:

https://github.com/AlanCoding/ansible-collections-openstack/compare/fqcn_name?expand=1

This allows the user to use either syntax, because there's an argument for the validity of both.

----

The reason that I have not raised this patch is because I have ran out of time debugging my account / credential / gerrit integration to work with opendev.org

**Comment by per-lind** [comment]
Would it help if I tried and made a PR from the fix?

**Comment by AlanCoding** [comment]
yeah, sure

**Comment by per-lind** [comment]
https://review.opendev.org/c/openstack/ansible-collections-openstack/+/792138

**Comment by AlanCoding** [comment]
Left a +1

thanks

**Comment by shanemcd** [comment]
@AlanCoding @jladdjr Is this still blocked? Looks like the patch has been merged.

**Comment by jladdjr** [comment]
On a local dev instance:
* Updated awx_ee:0.2.0 to include the latest `openstack.cloud` (installed HEAD of associated git repo) and created new image (locally) based on this
* In awx, created new execution_environment pointed at this image
* Created openstack inv source configured to use the new EE
* Ran inv source update and verified it was successful

Requested new collection release from openstack team:
https://review.opendev.org/c/openstack/ansible-collections-openstack/+/792138

Once we have a new version of the collection, then can update awx to source the new release.

**Comment by Zokormazo** [comment]
ee's are already shipping this

**Comment by HolmfryWrk** [comment]
I apologize -is this issue fixed or no?  I'm still getting the openstack inventory issue with awx 21, latest -ee

failed to parse /runner/inventory/openstack.yml with auto plugin: 'region'.  Whether region is populated or not in the credential.

**Comment by EffectShapiro** [comment]
@HolmfryWrk FYI https://github.com/ansible/awx/issues/9165#issuecomment-1193767485

Or did you find a solution meanwhile ?
