### ISSUE TITLE
Stop using alpha software and improve upgrades

### ISSUE THREAD

**Issue by yurtesen** [ansible/awx#10166]
It could be a great feature if you could make installation and upgrades easier and make the project more stable.

##### ISSUE TYPE
It is very difficult to install AWX and upgrades are even more difficult, even impossible.
https://github.com/ansible/awx/issues/9540

##### SUMMARY
I had a problem upgrading AWX (see bug above) and thought I could perhaps do a fresh install. Then I found out the suggested installation method says unsupported, alpha, and use your own risk...

Releases of a tool like AWX should subject to higher standards and maturity. 

When I check the AWX installation manual:
https://github.com/ansible/awx/blob/devel/INSTALL.md#installing-awx
```
Starting in version 18.0, the AWX Operator is the preferred way to install AWX.

AWX can also alternatively be installed and run in Docker, but this install path is only recommended for development/test-oriented deployments, and has no official published release.
```

Then there is a warning which stops one from using the latest Minikube version
```
If you're about to install minikube or have already installed it, please be sure you're using Minikube v1.18.1. There's a bug right now that will not allow you to run it using Minikube v1.19.x.
```

Meanwhile I believe docker was a supported installation method in the past. Now it seems docker is abandoned for another tool (quite prematurely) which is unsupported, has alpha status and should be used at own risk!

https://github.com/ansible/awx-operator
````
Note that the operator is not supported by Red Hat, and is in alpha status. For now, use it at your own risk!
````

Not to mention, there are no more upgrade instructions for AWX if it is installed with Minikube.

Please bring some stability to this project. It could be the greatest feature addition to it.

**Comment by bandwiches** [comment]
I second this.  I also question why the move to minikube and labelling docker as a developer only model when minikube can be argued to be a developer only deployment model.

The default requirements have also caused us heartache when deploying with the new operator since the machine now requires more CPU and RAM than what was previously required when deploying with Docker.

Related Tickets
#10117 

Related Operator Tickets
[awx/operator-#284](https://github.com/ansible/awx-operator/issues/284)

Edit -

I have to stop because I've wasted a week now trying to understand the different components and I'm still no further along than I was when I started.  The operator is alpha and warns you to use it at your own risk and awx chose to use that as their preferred method and I'll leave it at that.

Going back to version 17 w/Docker.

Further Issues:
- Once deployed, there's no instruction on how to gracefully stop the pods and services.  Could be argued this is K8S and not AWX but it's unreasonable to think users can move from older deployment methods to Minikube/K8S overnight.
  - Deleting services just makes them redeploy
  - Deleting pods just makes them redeploy
  - Deleting deployments prevents all but postgres from redeploying
  - Deleting the entire minikube environment is the only surefire way to remove everything
- [INSTALL.md](https://github.com/ansible/awx/blob/devel/INSTALL.md)
  - Services are not reachable externally by default, this is a huge wtf considering AWX is meant to be a shared resource within an organization.
    - External requests must be routed to the **host** first in order to be routed to the appropriate minikube service.  This requires some networking knowledge which is more knowledge than should be required to install an application.
    - Subnetting
      - There is no control or consideration for organizational overlap when the pods and services are assigned networks.
      - Rebuilding the environment will just populate more random IPs everywhere which is even more threatening to organizational overlap.
    - Specifying `NodePort` is supposed to be an alternative, but it fails to configure the service to the actual host IP.
  - Actual service ports from `minikube service awx-service --url` aren't even listed in iptables, therefor blocked by default
  - The service ports that are allowed in iptables just return "unauthorized" and nothing more.

**Comment by bandwiches** [comment]
For the record - I did figure out the issue behind accessing the services remotely.  IPTABLES never gets updated when minikube finishes the install, hence the host itself is blocking it.

Adding a rule to the `DOCKER` chain on the service port fixed the issue.

Minikube + AWX = Nightmare.

**Comment by shanemcd** [comment]
Hi folks. Friendly reminder that you're using free software. Yes - It's true that we completely changed how everything worked recently. We make no guarantees about stability, as stated here: https://www.ansible.com/products/awx-project/faq. I predict things will stabilize naturally over time... and then change drastically again at some point in the future when we need to. That being said, if you run into specific issues, please continue to open them.

**Comment by bandwiches** [comment]
> Hi folks. Friendly reminder that you're using free software. Yes - It's true that we completely changed how everything worked recently. We make no guarantees about stability, as stated here: https://www.ansible.com/products/awx-project/faq. I predict things will stabilize naturally over time... and then change drastically again at some point in the future when we need to. That being said, if you run into specific issues, please continue to open them.

We understand this is free, but why move to an alpha launcher that literally has a disclaimer saying use at your own risk?  This just seems like poor planning.  I suggest taking a page from the `awx-operator` repo where they actually discuss issues rather than close them based on the title.

**Comment by shanemcd** [comment]
> We understand this is free, but why move to an alpha launcher that literally has a disclaimer saying use at your own risk? This just seems like poor planning.

You're using everything here at your own risk. We're not going to stop innovating just because some people get cranky when debugging.

>  I suggest taking a page from the awx-operator repo where they actually discuss issues rather than close them based on the title.

Sure, I'm the top contributor of that repo.

**Comment by bandwiches** [comment]
I won't argue, but I feel as a maintainer you should have some sense of concern when it comes to installing and upgrading the package.  There is a pattern with AWX when it comes to both of these processes and neither are friendly, regardless of how those feelings are expressed by end users here.

Thanks!

**Comment by shanemcd** [comment]
We genuinely try to fix problems when people find them. We knew that the switch to the operator would be a little bumpy, and we're trying our best to work through all of the legitimate issues people run into. 

You seem to think there is a split between the AWX and awx-operator teams. We're the same tiny team of people who work at Red Hat, with a tiny fraction of contributions from our community. It's pretty cool that we get to work out in the open and make our software available to people before productizing it, but that does also imply that community users will be the first to encounter any issues.

Like I said above, I suspect things will stabilize over time. In the meantime, keep opening issues and PRs.

**Comment by bandwiches** [comment]
> You seem to think there is a split between the AWX and awx-operator teams.

That's correct, thanks for bringing that to my attention and I apologize if that was an issue.  I've been familiar with ansible, received a t-shirt shaped like a semi, got to enjoy training (3 or 4 years back) on that same automobile.  I've met with reps and all the like to learn about Ansible and I do believe it is a gem of a tool for network engineers.

I also don't believe OP was trying to stifle innovation or drag the project down, there have been patterns of issues when it comes to upgrading and installing and the premature move to Minikube didn't alleviate any issues, it just created additional paint points in our eyes.  Neither of you are wrong, we (consumers) just don't have any way to express that other than this board.

For the record - I don't think either of you are wrong.

**Comment by yurtesen** [comment]
@shanemcd Thank you for your response and you are right. It is free software. I think the issue is that we are generally accustomed free software to be more stable. Usually, free version of a paid product usually works as good as the real thing but with limited functionality.

You said `We make no guarantees about stability` but at installation manual is a clear text -> https://github.com/ansible/awx/blob/devel/INSTALL.md
```
AWX can also alternatively be installed and run in Docker, but this install path is only recommended for development/test-oriented deployments, and has no official published release.
```
This gives me the impression that the Minikube method is for using outside `development/test-oriented deployments`. Forgive me for reading between lines but it gives the impression of production systems and stability. I am now getting conflicting signals here. Is this project only a testbed of sorts or a production quality project?

Sure, the project maintainers can decide to use this project as a testbed. It is up to them. But then it would only be fair that there would clearly be a big note in the project `README.md` in the first line with bold text, that this is a testbed project which should not be used in production environments. -> https://github.com/ansible/awx/blob/devel/README.md

I feel somewhat cheated because my original impression was that this project could be used in production. It now feels like it was just some marketing ploy to lure people to use it.

**Comment by shanemcd** [comment]
Last comment from me here. I'll do my best to address any misinformation or misunderstandings.

First, on the topic of Minikube. One of the first things in the INSTALL.md is this:

> If you don't have an existing OpenShift or Kubernetes cluster, minikube is a fast and easy way to get up and running.

I am confused how anyone could read this and think it sounds like minikube is suitable for production.

>  I think the issue is that we are generally accustomed free software to be more stable. Usually, free version of a paid product usually works as good as the real thing but with limited functionality.

As tempted as I am to say something snarky here, no. That's not how this project works.

Again, going back to the FAQ, which is linked in the README: https://www.ansible.com/products/awx-project/faq

```
AWX is designed to be a frequently released, fast-moving project where all new development happens.

Ansible Tower is produced by taking selected releases of AWX, hardening them for long-term supportability, and making them available to customers as the Ansible Tower offering.

This is a tested and trusted method of software development for Red Hat, which follows a similar model to Fedora and Red Hat Enterprise Linux.
```

> Sure, the project maintainers can decide to use this project as a testbed. It is up to them. But then it would only be fair that there would clearly be a big note in the project README.md in the first line with bold text, that this is a testbed project which should not be used in production environments.

This project is *not* a testbed, the only branch is literally called `devel`. This is an *upstream* project for a downstream product, as covered above.

> I feel somewhat cheated because my original impression was that this project could be used in production. It now feels like it was just some marketing ploy to lure people to use it.

Not even sure where to begin here. Who told you AWX should be used in production? The FAQ has said the same thing since the beginning of time:

```
Q: Does Red Hat recommend AWX for production environments?

No.
```

There has never been a "marketing ploy" around AWX. Our marketing team sells our actual products, and have little to no involvement with the upstream project or community.
