### ISSUE TITLE
AWX local build - could not find or access /dist/awx-.tar.gz

### ISSUE THREAD

**Issue by shailigum** [ansible/awx#1017]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
When trying to build docker image locally to include additional modules, this error is encountered:

`
TASK [image_build : Stage sdist] ************************************************************************************************************************************************************************************************************
task path: /usr/local/awx/installer/image_build/tasks/main.yml:104
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 457, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 986, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 386, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
AnsibleFileNotFound: Could not find or access '../dist/awx-.tar.gz'
Searched in:
        /usr/local/awx/installer/image_build/files/../dist/awx-.tar.gz
        /usr/local/awx/installer/image_build/../dist/awx-.tar.gz
        /usr/local/awx/installer/image_build/tasks/files/../dist/awx-.tar.gz
        /usr/local/awx/installer/image_build/tasks/../dist/awx-.tar.gz
        /usr/local/awx/installer/files/../dist/awx-.tar.gz
        /usr/local/awx/installer/../dist/awx-.tar.gz

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "msg": "Could not find or access '../dist/awx-.tar.gz'\nSearched in:\n\t/usr/local/awx/installer/image_build/files/../dist/awx-.tar.gz\n\t/usr/local/awx/installer/image_build/../dist/awx-.tar.gz\n\t/usr/local/awx/installer/image_build/tasks/files/../dist/awx-.tar.gz\n\t/usr/local/awx/installer/image_build/tasks/../dist/awx-.tar.gz\n\t/usr/local/awx/installer/files/../dist/awx-.tar.gz\n\t/usr/local/awx/installer/../dist/awx-.tar.gz"
}
        to retry, use: --limit @/usr/local/awx/installer/install.retry
`
##### ENVIRONMENT
* AWX version: Latest
* AWX install method: docker on linux
* Ansible version:  Latest
* Operating System:  Centos7
* Web Browser: None

##### STEPS TO REPRODUCE

Adjustments to inventory file made as follows:

Commented the following:
'
#dockerhub_base=ansible
#dockerhub_version=latest
'
Uncommented the following (but did not adjust):

'
docker_registry=172.30.1.1:5000
docker_registry_repository=awx
docker_registry_username=developer
'

Uncommented the following (and adjusted):
'
use_container_for_build=false
'
##### EXPECTED RESULTS

Local build of image
##### ACTUAL RESULTS

See error in summary

##### ADDITIONAL INFORMATION

Built on Centos7 with all dependencies in place.  What is awx-.tar.gz and where does it come from?  I was unable to find this anywhere on my instance.

**Comment by matburt** [comment]
You need to run the build from a checked-out copy of the source tree.

**Comment by tomammon** [comment]
@matburt I am running in to the same issue. I've cloned the devel branch, is this what you mean by a copy of the source tree? It looks like there is a mismatch between the version that is being requested by the build process (awx-1.0.4.151.tar.gz) and what is available at the location it's looking in (awx-1.0.4.56.tar.gz), see output below. 

My end goal is to build a custom container because I want to be able to use custom ansible modules inside of AWX, and the easiest way to do that is mount a volume inside the task container, as far as I can see.

TASK [image_build : Stage sdist] *************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/opt/awxbuild/awx/installer/../dist/awx-1.0.4.151.tar.gz
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '../dist/awx-1.0.4.151.tar.gz'\nSearched in:\n\t/opt/awxbuild/awx/installer/image_build/files/../dist/awx-1.0.4.151.tar.gz\n\t/opt/awxbuild/awx/installer/image_build/../dist/awx-1.0.4.151.tar.gz\n\t/opt/awxbuild/awx/installer/image_build/tasks/files/../dist/awx-1.0.4.151.tar.gz\n\t/opt/awxbuild/awx/installer/image_build/tasks/../dist/awx-1.0.4.151.tar.gz\n\t/opt/awxbuild/awx/installer/files/../dist/awx-1.0.4.151.tar.gz\n\t/opt/awxbuild/awx/installer/../dist/awx-1.0.4.151.tar.gz"}

and the file that is in that location:

[root@localhost]# ls
awx-1.0.4.56.tar.gz
[root@localhost]# pwd
/opt/awxbuild/awx/dist

**Comment by pchauncey** [comment]
For anyone else who finds this issue:

Ensure that whatever version of **git** is called by your installation is supported.
