### ISSUE TITLE
Show content of failed webhook notification to know why it failed

### ISSUE THREAD

**Issue by AL1L** [ansible/awx#10196]
https://github.com/ansible/awx/blob/09801d0a9aa9020da9057a8e0e7fb13a7d107198/awx/main/notifications/webhook_backend.py#L78-L81

It's currently almost impossible to know what is wrong with your request, took me forever to find out that the test notification fails because it doesn't actually use any of custom messages.

**Comment by wenottingham** [comment]
This is more or less #8798, closing as a duplicate

**Comment by AL1L** [comment]
@wenottingham I dont think so, #8799 just calls out the format of the request, while I did mention that, the main focus is the fact that the error message is non informative. @jmhbnz does mention it, but still not the main focus of the Issue.

**Comment by wenottingham** [comment]
Oh, that.

This is intentional behavior - in both credential plugins and webhooks, it's possible to use the test endpoint to probe for details and inspect the results.  It was changed here (https://github.com/ansible/awx/commit/b7f37d5e26e16f682c4d1486a54f22a03aff74b7#diff-1c6b981835cbb265d6a14f3ff77b86ed2fbf1e64932e6a09a3e623141a7e543d)

**Comment by AL1L** [comment]
That seems good for UI purposes, but a bad idea for function and usefulness, how are people supposed to know what the issue is in the webhook configuration? There should be some type of log or something to view the failed tests in detail.
