### ISSUE TITLE
awx install old version

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#1039]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

redeploy existing AWX 1.0.2.372 today with latest get version 1.0.2.72  with clean db.
##### ENVIRONMENT
* AWX version: 1.0.2.372
* AWX install method:  docker on centos7
* Ansible version:  2.4.2
* Operating System: centos7
* Web Browser: n/a

##### STEPS TO REPRODUCE

install AWX 1.0.2.372, delete axw_web and awx_task. install agin with latest
##### EXPECTED RESULTS

 install of AWX 1.0.2.372 ?
##### ACTUAL RESULTS

clean install of AWX 1.0.2.72
##### ADDITIONAL INFORMATION
https://hub.docker.com/r/ansible/awx_task/tags/  have only rebuild/update old 10.0.2.7x  last week.

**Comment by jakemcdermott** [comment]
Hello, hemskgren.

By default, the awx installer will pull from the public docker repo using the 'latest' tag. This is expected behavior and not something we intend to change. 

If you would like to use an earlier version, you'll need to either override the default `awx_*_image` variables when running the installer or build those images locally with the earlier version checked out.

If you have questions, you can stop by our irc channel (ansible-awx on freenode) or drop us a line on the awx project mailing list.

**Comment by hemskgren** [comment]
The latest build/tag today look to be 1.0.2.73.
Still we think 1.0.2.372 is a higher number.

**Comment by mkempster22** [comment]
@hemskgren  1.02.73 is higher, its a decimal place therefore it is essentially .730 which is higher than .372
