### ISSUE TITLE
Installed fails with git version installed from Centos7 base repo.

### ISSUE THREAD

**Issue by savealive** [ansible/awx#1045]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installed needs git version newer than shipped with Centos/RHEL7.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4

##### STEPS TO REPRODUCE
Git package from Centos/RHEL repository git-1.8.3.1-12.el7_4 doesn't support "describe --first-parent" option.
`
$ git describe --long --first-parent
error: unknown option first-parent
usage: git describe [options] <committish>*
   or: git describe [options] --dirty

    --contains            find the tag that comes after the commit
    --debug               debug search strategy on stderr
    --all                 use any ref
    --tags                use any tag, even unannotated
    --long                always use long format
    --abbrev[=<n>]        use <n> digits to display SHA-1s
    --exact-match         only output exact matches
    --candidates <n>      consider <n> most recent tags (default: 10)
    --match <pattern>     only consider tags matching <pattern>
    --always              show abbreviated commit object as fallback
    --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")
`

So installer fails due to AWX version detection failure:
`TASK [image_build : AWX Distribution] ********************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "awx-.tar.gz"
}`

##### EXPECTED RESULTS
Installer detects AWX version and continues build.

##### ACTUAL RESULTS
Installer fails.

##### ADDITIONAL INFORMATION
To work around the issue user have to remove git installed from Centos7 base repo and install newer git form third-party repo.
`
yum install -y https://centos7.iuscommunity.org/ius-release.rpm;
yum remove git;
yum install git2u
`

It's related to #985 but I believe it was closed but not resolved. Issue is related to *local* git version as well as to one in sdist build image.

**Comment by jakemcdermott** [comment]
Hello savealive. 

> Issue is related to local git version

Based on the information in your bug report, I believe you are correct here. 

Git, ansible, and other prerequisites for running the installer must already be in place before using the installer. The awx installer does not install these things for you. This is expected behavior and not something we're planning on changing at the moment.

The installation docs already list git as a prerequisite, but since a minimum version is required I've gone ahead and added that information here: 

https://github.com/ansible/awx/pull/1049

If you have questions, please stop by our irc channel (ansible-awx on freenode) or drop us a line on the awx project mailing list.
