### ISSUE TITLE
cannot create directory ‘/var/lib/postgresql/data’: Permission denied

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#1047]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
AWX web page shows internal server error, postgres container stuck restarting with the message:
mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied

Due to AWX upgrading not being functional I deleted my database and cleaned up /var/lib/docker then installed AWX from the beginning, The only previous mention of this error i've seen was fixed by adding :Z to the installer volume line.

##### ENVIRONMENT
* AWX version: Latest
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: RHEL7
* Web Browser: N/A

##### STEPS TO REPRODUCE
Clone AWX repo, (My changes to the inventory script are setting postgres to be stored in /opt/pgdocker/) Run the installer which runs correctly.

##### EXPECTED RESULTS
AWX To start normally

##### ACTUAL RESULTS
Internal Server error
Postgres container stuck restarting

**Comment by mkempster22** [comment]
Noticed #1046 afterwards, Actual database error experienced wasn't put in issue but I assume these are both from the same issue

**Comment by savealive** [comment]
you must have file permissions issue. Try to create /opt/pgdocker manually.

**Comment by mkempster22** [comment]
Unfortunately that's not the cause :( I had initially created that folder manually and it had been used by the previous install before I wiped it. The installation did actually add files into there successfully

Based upon another person submitting an identical issue with 30 mins of this one there might be some issue with the installer?

**Comment by shanemcd** [comment]
You indeed have a permissions issue. My guess is that `/opt/pgdocker/` is owned by root and you are running docker as your personal user account.

Since this is not an issue with AWX, I am going to close this issue. For general help, please see the "WHERE CAN I FIND SUPPORT FOR AWX?" section [here](https://www.ansible.com/products/awx-project/faq)

**Comment by mkempster22** [comment]
I'm fairly sure this is an issue with AWX (I may be wrong?) due to multiple other people reporting it all on the same day which seems odd. I am running everything on that server as root currently and it had worked the exact same way the previous day, then the day I got the error there were other people reporting this issue.

#1046
&
https://groups.google.com/forum/#!topic/awx-project/JfIf0D6bBFs

All permissions on the pgdocker folder are okay and are the same as my dev server which is on the previous update, I tried to update my dev server and it ran into the same issue

Edit: Currently fixed it by downgrading to an earlier version

**Comment by mrj1m0thy** [comment]
If anyone runs into this again try to run the setup.py script with parameter install before running the installer playbook. I think this might have been the issue.
- python setup.py install

**Comment by twobombs** [comment]
<img width="734" alt="Screenshot 2021-08-04 at 10 24 34" src="https://user-images.githubusercontent.com/12692227/128148481-1678c225-6190-4112-bb80-4f3e06efd5c3.png">

saw this thing pop up with awx operator the 0.12.0 tag under k3s. 
followed the vanilla install but instead of using minicube I used k3s.

<img width="1406" alt="Screenshot 2021-08-04 at 10 31 07" src="https://user-images.githubusercontent.com/12692227/128149118-8aae1db9-adc2-4f59-ad0c-b6c07259d986.png">
