### ISSUE TITLE
Custom Authentication and Authorization System

### ISSUE THREAD

**Issue by emailvenkatm** [ansible/awx#1051]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 
##### SUMMARY
We have an internal Auth/Autz system which is being used by all our apps for authentication and authorization purpose.  This is kind of centralized system where we manage the user's permissions for a specific application. Our authorization stuff is exposed as a REST API. So wondering if we can integrate our access management system with AWX in any way instead of making the changes to the existing codebase.   Like creating separate plugins for Authentication and Authorization may be? Please help.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by jakemcdermott** [comment]
Hey emailventkatm, thanks for reaching out.

There are no plans to add awx-specific pluggable auth at this time.

If you have questions, please stop by our irc channel (ansible-awx on freenode) or drop us a line on the awx project mailing list.

**Comment by cchurch** [comment]
@emailvenkatm It would be possible to write a [custom Django authentication backend](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/) and add it to `AUTHENTICATION_BACKENDS` in a Python settings file (similar to how the current LDAP and RADIUS backends work). That would only handle the authentication step. You'd be on your own to maintain that backend separately across AWX upgrades.

For authorization, there's not really a pluggable way to customize it, since AWX doesn't use the permissions/authorization part of Django. You *could* implement a way to sync organizations/teams in a way similar to [how we update those from LDAP](https://github.com/ansible/awx/blob/devel/awx/sso/backends.py#L338).
