### ISSUE TITLE
Dashboard data not available for certain users profiles

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10605]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Dashboard data not available for certain users profiles even though the API is responding to the user request with data.

### AWX version

devel after 19.0.2

### Installation method

docker for mac

### Modifications

no

### Operating system

see above^ Installation method

### Steps to reproduce

1. Create a normal user `foo`
2. Login with the `foo`

### Expected results

User being able to see data on the dashboard.

### Actual results

No data available on the dashboard.

![image](https://user-images.githubusercontent.com/9053044/124778949-606a1300-df0f-11eb-92d8-78464b1901fa.png)

### Additional information

System admin 

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/9053044/124779310-ab842600-df0f-11eb-8428-c1a40d46093d.png">

**Comment by AlexSCorey** [comment]
the `/dashboard` end point will be deprecated at some point in a future release
![Screen Shot 2021-07-19 at 11 46 20 AM](https://user-images.githubusercontent.com/39280967/126189875-67aca15b-90f0-49e1-8f47-de80e531f6c3.png)

According to https://github.com/ansible/awx/commit/d6ecb486d24 and @jbradberry we should use `/metrics` to get the count/totals data.  However, a normal user doesn't have access to the data from that `/metrics` end point.

perhaps @wenottingham  can chime in about next steps here.

**Comment by AlanCoding** [comment]
It appears the counts will only count things that the current user has the ability to see.

https://github.com/ansible/awx/blob/6a17e5b65bf9421c2e650d23817c79ce81248c6f/awx/api/views/__init__.py#L258

I'm pretty sure that the metrics endpoint is absolute (no counting specific to current user's access). We're getting close to conflicting requirements here

**Comment by jbradberry** [comment]
Ok, I went and did some digging.  I still am unable to find a matching issue for the pull request that marked the dashboard endpoint as deprecated, but the word from @wenottingham in our Slack history seems to be: "it's deprecated in that it's **only** for use by the UI".  I think that this means we should fix whatever is broken with this endpoint (if anything, given that there are RBAC restrictions on the data returned), rather than trying to aggregate what we need from other endpoints.

**Comment by AlanCoding** [comment]
This endpoint isn't broken. When it was introduced, the intent was that underprivileged users should not have access to get the _total_ counts of jobs / project updates / etc., because that would be counting things they don't have permission to view. It only counts the jobs (and such) that they have read permission to.

That can be changed, but it's not a bug fix, it's a product decision with security implications.

**Comment by ffirg** [comment]
We need to respect the RBAC model, so it's working as required. A user should only have the ability to see what the RBAC model privileges allow them to see.

**Comment by AlexSCorey** [comment]
Since this is not a UI bug I am going to remove UI related labels/tags from it.

**Comment by jbradberry** [comment]
@nixocio given the RBAC restrictions involved, can you confirm that this is an actual bug?  Can you construct a situation where an ordinary user can see a particular job directly but cannot see that job reflected in the graph?

**Comment by nixocio** [comment]
I re-evaluate this using the old app as reference. And it is behaving in the same way, taking the RBAC in consideration and not showing data on the dashboard for `Normal User` without any other level of privilege.
