### ISSUE TITLE
Instalation: Activate postgres container fails

### ISSUE THREAD

**Issue by sboldt1978** [ansible/awx#1065]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Task "Activate postgres container" fails: 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling postgres - code: None message: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/postgres/images. You may want to check your internet connection or if you are behind a proxy."}

I'm sitting behind a proxy but the proxy settings have been made. I guess there is an issue with the URL, because if I access this URL with my normal browser or curl I only get an opening and closing bracket:

# curl https://index.docker.io/v1/repositories/library/postgres/images && echo
[]
#

##### ENVIRONMENT
* AWX version: Latest 
* AWX install method: docker
* Ansible version:  2.4.2.0-1.el7.noarch
* Operating System: CentOS 7
* Web Browser: Chrome / lynx

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/awx
Adapt http and https proxy settings inventory
run "ansible-playbook -i inventory install.yml" in installer directory

##### EXPECTED RESULTS

Pull Docker image and install AWX

##### ACTUAL RESULTS

All Task ran fine until:
TASK [local_docker : Activate postgres container] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling postgres - code: None message: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/postgres/images. You may want to check your internet connection or if you are behind a proxy."}
        to retry, use: --limit @/root/awx/installer/install.retry

**Comment by matburt** [comment]
Seems like it's not an issue with our install playbook then? You'll need to sort out why your network won't allow you to access dockerhub behind the proxy or provide us with more details on how we can help you.

**Comment by sboldt1978** [comment]
Just for the records: This is a problem with docker under Centos7. It doesn't honor the http_proxy environment variable. This workaround does the trick: https://github.com/tmatilai/vagrant-proxyconf/issues/138#issuecomment-224016507

The referenced /etc/sysconfig/docker file of course has to contain the proxy server:
export http_proxy="http://myproxy.example.com:8080"
export https_proxy="https://myproxy.example.com:8080"

**Comment by gabrieltokyo** [comment]
Hi @matburt @sboldt1978 , sorry for posting in a closed thread, I just want to understand the mechanism.

I was worried about some container tasks having (AWX_Web & AWX_Task) or not having (postgres, memcached, rabbitmq) proxy variables at "env" or at "buildargs".

So I tried this (A):
1) OS settings has proxy variables set,
2) inventory file at AWX installer has proxy variables set,
3) Docker has NO proxy settings

Result => FAIL (on postgres container TASK: Activate postgres container)

4) Comment out postgres, memcached and rabbitmq code to avoid the error and only create AWX_xxx containers because those have proxy variables at set at env.

Result => FAIL (same error as postgres at TASK: Activate AWX Web Container)


Then I tried this (B):
1) OS settings has proxy variables set,
2) inventory file at AWX installer has proxy variables set,
3) Docker has proxy settings

Result => SUCCEED (as expected)

Finally I tried this (C):
1) OS settings has proxy variables set,
2) inventory file at AWX installer has NO proxy variables set,
3) Docker has proxy settings

Result => SUCCEED


If Docker does not honor environment variables (that are also set at playbook with env), does it have any meaning to have those variables at code or are they for logical reasons?
Doing some grep I saw that http_proxy variables are used at other playbook and template.

Which is the recommendation when there is a proxy at installation time?
Set the variables even will be ignored by Docker module because are needed for other code? or for logical reasons? (Someday Docker may honor env variables so that it should be the correct way?)

Thank you!

--------------

\- name: Activate AWX Web container
  docker_container:
    name: awx_web
    state: started
   ...
    env:
      http_proxy: "{{ http_proxy | default('') }}"     <-- Since Docker ignores it, is it only for logical meanings?
      https_proxy: "{{ https_proxy | default('') }}"  <-- Since Docker ignores it, is it only for logical meanings?
      no_proxy: "{{ no_proxy | default('') }}"          <-- Since Docker ignores it, is it only for logical meanings?
      SECRET_KEY: "{{ awx_secret_key }}"
      ...

**Comment by gabrieltokyo** [comment]
Sorry, I see this has many implications at Container (AWX_Task) side environment variables.

So specially when "local_action" are used, you want to have a correct no_proxy, etc variables set.

You better do:
 1- OS settings has proxy variables set,
 2- inventory file at AWX installer has proxy variables set,
 3- Docker has proxy settings

Then (this should be another thread), since tasks are executed at a container, reconsider your automation strategies since an AWX may serve several environments with different variables and how plays that were using local_action may respond to this from a container.
