### ISSUE TITLE
Warning about using the development version of Ansible

### ISSUE THREAD

**Issue by feuertaenzer** [ansible/awx#10749]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We are using version 19.2.0 of Ansible AWX, using the operator version 0.10.0.
For some reason we get the warning:
![Bildschirmfoto 2021-07-26 um 09 53 58](https://user-images.githubusercontent.com/87800757/126953283-5f274715-d185-478c-b561-893fd4ad4c5b.png)

### AWX version

19.2.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

provided by AWX

### Operating system

Ubuntu 18.04

### Web browser

Chrome

### Steps to reproduce

Executing Templates

### Expected results

No such warning

### Actual results

Warning as described above

**Comment by feuertaenzer** [comment]
It was an issue related to awx-eee and was fixed in 0.5.0, see here https://github.com/ansible/awx-ee/issues/72

**Comment by yurtesen** [comment]
But is it? I am still getting it?

**Comment by ffirg** [comment]
This message refers to the fact that you are running the upstream always-in-development version.

**Comment by yurtesen** [comment]
Where do I find the setting to change it? and why is `latest` is an always-in-development version? shouldn't the `devel` be in development instead?
![image](https://user-images.githubusercontent.com/1926599/134985737-e277a7cf-4124-4e90-878d-2da6e54d4aab.png)

**Comment by ffirg** [comment]
The development version warning is referring to the ansible-core version being run, not AWX or the EE. 
AWX is *always* in development, there is no such thing as stable/main/latest.
The awx-ee:latest is just a container image tag.

**Comment by yurtesen** [comment]
@ffirg I am not sure if I understand. If the warning is related to ansible-core version. Why would the AWX not having "stable" matter? There is ansible-core stable. Are you saying there are no EE images with stable ansible-core provided? That I did not know...

If that is the problem. I guess the real question is then how can one use a different EE for controlplane ? I used docker-compose method during installation. I am not able to change it through GUI and there does not seem to be any option which can be set otherwise...

**Comment by ffirg** [comment]
We use elements of ansible throughout the AWX platform. These can be in various versions/states. Just because there is a 'stable' released version of that component does not mean AWX is stable. It never is, it is the upstream, always being refactored/changed. This message simply reflects that. 

To change the control plane, you will need to figure out how to build. We do not allow changes to the control plane post install as it has serious implications for the whole platform.
