### ISSUE TITLE
Feature: Associate vault password with an inventory source

### ISSUE THREAD

**Issue by mjrsnyder** [ansible/awx#110]
### Summary

Syncing an inventory source with a vault file fails because AWX cannot decrypt the vault.

### Environment

* AWX version: 1.0.0.333
* Ansible version:  2.3.1.0
* Operating System: CentOS 7
* Web Browser: Firefox

### Steps To Reproduce:

When configuring an inventory source from a project allow a Vault Credential to be specified and used to decrypt vault files.

### Actual Results:

I get an error saying ```ERROR! Decryption failed on /var/lib/awx/projects/_6__ansible/dev/group_vars/common/vault.yml``` when trying to sync the inventory source

### Additional Information:

This feature would make it much easier to migrate existing Ansible projects to AWX.

**Comment by matburt** [comment]
This is actually on our roadmap and is specced but we have to wait until Ansible Core finishes updating the way they invoke inventory in 2.4+ (the move towards a module-based system).

The reason we can't/don't invoke vault currently is because our inventory import doesn't actually involve `ansible` at all. We just parse the output of the script and pass it through a minimal tool to convert it to our inventory source.

**Comment by mjrsnyder** [comment]
Thanks @matburt, is the roadmap available somewhere so we can get an idea of what's in the pipe?

**Comment by wenottingham** [comment]
At the moment, it's not. Issues are in the process of being migrated to this repo.
