### ISSUE TITLE
Make sure that ansible-runner version gets pinned in AWX

### ISSUE THREAD

**Issue by beeankha** [ansible/awx#11112]

**Comment by sarabrajsingh** [comment]
@beeankha what version are we pinning ansible-runner to? latest is `2.0.2`

https://pypi.org/project/ansible-runner/

**Comment by beeankha** [comment]
@sarabrajsingh it should be `2.1.0` once that's released

**Comment by sarabrajsingh** [comment]
related PR - validation of version happening here - https://github.com/ansible/awx/pull/11213

**Comment by shanemcd** [comment]
I closed this without understanding what the issue was about. It seems like we're still pulling ansible-runner from git: https://github.com/ansible/awx/blob/devel/requirements/requirements_git.txt#L3

I will ping the Executor team about doing the final release of Runner 2.1 so we can move it back into requirements.txt.

**Comment by sarabrajsingh** [comment]
thanks @shanemcd. I had this exact conversation with @AlanCoding a couple of weeks ago. Would we also need to maintain the `ansible-runner` version in other build/install processes as well? such as the `awx-ee` container build/publish jobs?
