### ISSUE TITLE
WFJT creation- adding labels results in 400

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11224]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When a user creates a workflow job template, and wants to add custom labels, they receive an error message. see GIF:
![wfjt-error](https://user-images.githubusercontent.com/63685497/136584744-767a2ba5-b8dd-4fd9-8a26-1e03afe466a1.gif)

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

See GIF

### Expected results

Labels would be successfully added and the user can save their new WFJT

### Actual results

the user sees an error on the screen

**Comment by AlexSCorey** [comment]
@akus062381 I believe that this is a patternfly bug.  This [PR](https://github.com/ansible/awx/pull/11218) will revert the recent PF Upgrade that brought in the bug  and here is the bug [filed](https://github.com/patternfly/patternfly-react/issues/6421) with PF.  This bug is probably a good thing to keep around, though, to help us track that bug when we upgrade PF again and ensure it doesn't come back into our project.

**Comment by nixocio** [comment]
Once we upgrade PF again we should verify this issue and close.

**Comment by nixocio** [comment]
@tiagodread @akus062381 I believe we merged the fix for this one. Can we close this one?

**Comment by akus062381** [comment]
@nixocio yes! this is fixed. closing
