### ISSUE TITLE
"Webhook previously received, aborting."

### ISSUE THREAD

**Issue by joaodlf** [ansible/awx#11317]
Quick one, I'm getting a `Webhook previously received, aborting.` when running a GitHub webhook for a template , I suspect coming from here:
https://github.com/ansible/awx/blob/eec4f8dcc27428cd1aeb1c251d43052a3ea780e8/awx/api/views/webhooks.py#L130

The AWX gui does not show any jobs being queued/waiting/running, how can I clear this error to allow my webhooks to return to normal?

**Comment by HenriWahl** [comment]
Hi @joaodlf - as your issue here is the ONLY hit when searching for this specific error: how did you solve this?

**Comment by Jonas-deLaporte** [comment]
Not sure if this is still relevant since this issue has been closed some time ago, but I encountered and solved this problem today. 

## Context
My goal was to trigger an AWX job template whenever a specific directory in my GitLab repository changes. Note that my use-case is slightly different since GitLab's native webhooks aren't granular enough for directory-specific triggers, so I combined GitLab CI with AWX's webhook feature, instead of using GitLab's webhooks. On AWX's side, the configuration should be the same tough.

After setting up the `.gitlab-ci.yml`, I ran into the same problem described above.

## Root cause
Looking at the AWX code:

```python
kwargs = {'unified_job_template_id': obj.id, 'webhook_service': obj.webhook_service, 'webhook_guid': event_guid}
if WorkflowJob.objects.filter(**kwargs).exists() or Job.objects.filter(**kwargs).exists():
    # Short circuit if this webhook has already been received and acted upon.
    logger.debug("Webhook previously received, returning without action.")
    return Response({'message': _("Webhook previously received, aborting.")}, status=status.HTTP_202_ACCEPTED)
```

AWX checks if a webhook with the same GUID has already been processed. That means each request needs a unique GUID.

## Solution
Include a custom payload to send a unique identifier with each webhook request:

```yaml
# .gitlab-ci.yml
stages:
  - trigger

trigger_awx_job:
  stage: trigger
  image: alpine:latest
  before_script:
    # Install necessary packages
    - apk add --no-cache git curl jq
  script:
    - |
      # Check which files were changed
      CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
      echo "Changed files:"
      echo "$CHANGED_FILES"

      # Check if any files in the target directory were changed
      if echo "$CHANGED_FILES" | grep -E "^path/to/trigger/dir/"; then
        echo "Changes detected in target directory"
        
        # Create a JSON payload with a unique ID
        PAYLOAD=$(jq -n \
          --arg guid "$CI_PIPELINE_ID-$CI_JOB_ID-$(date +%s)" \
          '{"object_kind": "push", "event_guid": $guid, "changes": []}')
          
        echo "Sending webhook with unique GUID..."
        
        curl -k -X POST \
          -H "Content-Type: application/json" \
          -H "X-GitLab-Token: $AWX_TOKEN" \
          -d "$PAYLOAD" \
          <AWX WEBHOOK URL>
      else
        echo "No changes in target directory"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
```

Note: Replace `<AWX WEBHOOK URL>` with the AWX webhook url and set `AWX_TOKEN` in GitLab CI/CD variables. Its vaule is the `Webhook Key` that is generated by AWX when adding a webhook.

Hope this helps anyone that ends up here :D
