### ISSUE TITLE
No Upgrade path from 1.0.2.0 to 1.0.3.0

### ISSUE THREAD

**Issue by orgito** [ansible/awx#1133]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### ENVIRONMENT
* AWX version: 1.0.2.0
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: CentOS 7.4
* Web Browser: Chrome 62

##### STEPS TO REPRODUCE

- Install AWX 1.0.1.X
- Upgrade to AWX 1.0.2.0
- Upgrade to AWX 1.0.3.0

##### EXPECTED RESULTS

Successful upgrade

##### ACTUAL RESULTS

Stuck in AWX is upgrading

##### ADDITIONAL INFORMATION

Can we expect that it will be possible at some point to upgrade from AWX 1.0.2.0 (that was previously upgraded from1.0.1.x) to newer versions?

If I throw everything away and start with a new 1.0.3.x AWX instance, will I be able to upgrade to future versions?

**Comment by jakemcdermott** [comment]
Hello orgito,

Thanks for reaching out. What you've described is expected behavior - When working off of the development branch, we frequently have to re-initialize our database and delete data to restore functionality after integrating new changes. There is no explicit expectation that one should be able to smoothly upgrade from one commit to the next on the devel branch. 

> Can we expect that it will be possible at some point to upgrade from AWX 1.0.2.0 (that was previously upgraded from1.0.1.x) to newer versions?

This is not something that we plan to implement at this time.

> If I throw everything away and start with a new 1.0.3.x AWX instance, will I be able to upgrade to future versions?

You should be able to upgrade to most future container image versions in the `1.0.3.x` series. When a `1.0.4.x` is released, it is likely that upgrades from `1.0.3.x` will be rocky.

If you have any questions please drop us a line on the awx mailing list or stop by the awx irc channel on freenode.
