### ISSUE TITLE
Set a non-default value for Django's `SESSION_COOKIE_NAME`

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11413]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See 

https://docs.djangoproject.com/en/3.2/ref/settings/#session-cookie-name

> Default: 'sessionid'

> The name of the cookie to use for sessions. This can be whatever you want (as long as it’s different from the other cookie names in your application).

Originally attempted in https://github.com/ansible/awx/pull/11348 and then reverted in https://github.com/ansible/awx/pull/11412. The biggest problem that we have is that something is not persisting right between multiple runs of integration tests, probably related to the awxkit connection object.

In addition to that, the current value of "sessionid" is hard-coded in many places by clients:

https://github.com/ansible/awx/search?q=sessionid

Those can be trivially updated, and would obviously need to be for merging this change. We also have clients in a few other places that would need to change. We would also need to very strongly broadcast and release-note this change, as it could break automation that users have built around some custom clients.

**Comment by john-westcott-iv** [comment]
The session ID is used in 2 places in awxkit: ws and the client.

The client is performing an interactive login and we can set the "default" value to be the old sessionid (in case you are connecting to an older instance) and we can have AWX send a special header to indicate what the cookie name is when the session is first established.

The WS is more of a programatic interface and we can modify that to include a session_cookie_name variable but we will default this variable to the new session cookie name because WS may not have a connection object before it attempts to make a connection. So, WS will assume you are connecting to something new and if you need to connect WS to an older instance you will need to change your code to use the old `sessionid` cookie name.

**Comment by CFSNM** [comment]
The validation of this item is done here: https://github.com/ansible/tower-qa/pull/7195#issuecomment-1046633787

**Comment by CFSNM** [comment]
PR merged. Closing it -...

**Comment by tvo318** [comment]
For docs: https://github.com/ansible/product-docs/pull/1651/commits/217be6fd4ffe7e409c510a47c886a22b66bd8d82
