### ISSUE TITLE
Allow Hop Nodes to execute and expose health check data

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11532]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hope nodes are being rendered on the Mesh Visualizer, but  there are never any health checks that occur on them.  For consistency and clarity we should execute health checks  on Hop nodes in the event that a hope node does not 'check in', at the same frequency that health checks occur on other node types.  We should also clear errors on hop nodes as they begin to check in on the expected frequency.
See this [comment](https://github.com/ansible/awx/pull/11454#discussion_r783434257)

**Comment by AlanCoding** [comment]
Health checks work by running the ansible-runner health check command, and hop nodes do not have that installed. In that comment, I meant to say that we would put errors on those nodes if they went missing from the mesh (more or less).

**Comment by shanemcd** [comment]
@AlanCoding Thoughts on installing runner on the hop nodes for the purposes of running the health check?

**Comment by shanemcd** [comment]
Maybe for hop nodes we dont care about capacity, but it would be good to know if it is on or off.

**Comment by AlanCoding** [comment]
^ receptor already does everything we need. The only reason we run the health check is for information related to capacity which is irrelevant for hop nodes.

However, hop nodes _can_ have `errors`, a field we populated in the API. This only matters for AWX mirroring the logic that receptor reports. If a node isn't reachable, then receptor will discover this fact through its own clustering rules. That is reported from `receptorctl status` which AWX regularly checks.

The way I would phrase this work item - if receptor reports that a hop node has become unreachable, this should be reflected in the mesh visualizer in the UI.

**Comment by AlexSCorey** [comment]
@AlanCoding when a hop node becomes unreachable will it be declared on the `errors` field or should we be tracking some other field to show a hop node isn't reachable?  Just seeking clarity here
@kialam just FYI

**Comment by AlanCoding** [comment]
@AlexSCorey that's right, but we may need to check this in the API to assure we're not skipping the hop nodes. I'm not sure if @jbradberry has covered this or not. It shouldn't be hard to check in the dev environment - start up once with execution nodes, and then start up again with 0 execution nodes, so it won't create the hybrid node either. All the execution plane should show as not working in the visualizer.

**Comment by tiagodread** [comment]
Based on https://github.com/ansible/awx/pull/11653#issuecomment-1027250278 after having the health check for hop nodes, @AlexSCorey, maybe, we'll need to stop looking on `errors` field to look at `last_health_check` instead or other.

**Comment by AlanCoding** [comment]
> Based on https://github.com/ansible/awx/pull/11653#issuecomment-1027250278 after having the health check for hop nodes, @AlexSCorey, maybe, we'll need to stop looking on `errors` field to look at `last_health_check` instead or other.

For the UI purposes, a blank `errors` field should indicate the node is functional. Anything else in that field should indicate the node is not functional.

The function of a node depends on its type. We need to leverage the `errors` field here precisely because hop nodes don't run jobs and we `capacity` is intentionally 0.

From prior conversations, I thought the API might have already coded for this, but consistent with your experimentation, I found that it doesn't. I put up https://github.com/ansible/awx/pull/11714 to convey the general idea of filling in `errors` based solely on the `last_seen` field. This was tested in the dev environment with the instructions I described in https://github.com/ansible/awx/issues/11532#issuecomment-1032904083

**Comment by thenets** [comment]
We will need to move this issue to `Needs Docs` once the tests are finished.
It's important to let the user know the differences between `hop` and `execution` instances behaviors.

For example, the UI uses the `error` field of `instances` endpoint to show the message to the user, instead of `execution` behavior that uses the `last_health_check` field.

The UI code that shows the `hop` node status is available here:
https://github.com/ansible/awx/blob/4c9d028a35dab930c8a9c59da70b8e4c8448a666/awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js#L144-L147

Also, the `hop` instances can't be modified through UI or API.

cc: @tvo318

**Comment by AlanCoding** [comment]
> For example, the UI uses the error field of instances endpoint to show the message to the user, instead of execution behavior that uses the last_health_check field.

I don't understand the language here.

If a control/hybrid/execution node has a problem, it should have text in the `errors` field, as well as a value of 0 for `capacity`.

Hop nodes should _always_ have a value of 0 for `capacity`. It has text in the `errors` field, then it is known to be non-functional, but this may or may not impact job functionality (because receptor could route around that node).

The user can manually run a health check against an execution node (if they wish), this refreshes its `capacity` value. Users cannot run health checks against hop nodes, because this doesn't make any sense. (repeating) Because hop nodes should _always_ have a value of 0 for `capacity`, because hop nodes do not perform work, they only route traffic. The notion of capacity pertains to running work.

**Comment by InnocentK** [comment]
> > For example, the UI uses the error field of instances endpoint to show the message to the user, instead of execution behavior that uses the last_health_check field.
> 
> I don't understand the language here.
> 

I think this relates to the UI changes rather than the API changes. 

In the UI the health status for control/hybrid/execution nodes comes from the health check function but the health status for hop nodes comes from the `errors` field.
I don't think this difference would be obvious to users and so it would be important to note in the documentation.

**Comment by InnocentK** [comment]
Confirmed as resolved
