### ISSUE TITLE
Controller UI: the "Elapsed" time keeps unchanged when a job is running

### ISSUE THREAD

**Issue by qiwangrh** [ansible/awx#11555]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

on the new UI elapsed time is not being updated when a job is running.

### AWX version

awx/devel

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

I am using "Ansible Automation Platform Controller 4.1.0". Schedule a job to run from the Controller UI. When the job is running, view the job's details to check if the "elapsed" time is updated or not.

### Expected results

The elapsed time is being updated when a job is running.

### Actual results

![elapsed_time_not_progressing](https://user-images.githubusercontent.com/93540182/149951552-e6512942-770e-45f7-b6a1-064cd1630f1b.gif)

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/issues/5646

**Comment by shanemcd** [comment]
It does seem like we could resolve this along with https://github.com/ansible/awx/issues/5646

**Comment by AlanCoding** [comment]
I put up https://github.com/ansible/awx/pull/12270 to show that it's very trivial to add the started time to the websocket message from the API. Because _this_ issue isn't planned, I'm going to close that now. If the UI picks this up later, you can pretty easily include the diff from that. I don't want to add more data until there is a consumer for that data.
