### ISSUE TITLE
[Tech debt] Task manager fetches resources (instances, jobs, etc.) twice

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11671]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Running the task manager, it repeats itself doing the same thing twice. Documenting partial call stack here. Both start with the main call path to the task manager:

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L674

Both of these ultimately do the same queries, and the only reason we have two is because multiple developers wrote them, probably mutually unaware of the other data structures that were built, or an unwillingness to modify the code in order to combine efforts.

We should combine them. An attempt at this problem was started in https://github.com/ansible/awx/pull/11651

**first fetch**

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L634

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L71

This will then fetch _jobs_ indirectly as `instance.remaining_capacity` is referenced.

**second fetch**

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L662

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L620

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L601

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/managers.py#L237

This case attempts to avoid _fetching the jobs list_ by reusing the main list that the task manager operates on.

Consider this is a sub-issue of https://github.com/ansible/awx/issues/11306

**Comment by kdelee** [comment]
looks like we also fetch jobs indirectly with 
https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L80

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/models/ha.py#L155-L162

**Comment by AlanCoding** [comment]
@kdelee did you fix this in your merges earlier this year?

**Comment by kdelee** [comment]
@AlanCoding we did not fix the 1st fetch you referece or the 3rd one I mentioned. The second one that happens via  `calculate_capacity_consumed` is gone now.


Needs more work to remove/use already fetched jobs because we reference it more:
https://github.com/ansible/awx/blob/ac8204427e241efcadd3bf8152007e1c04179a1e/awx/main/scheduler/task_manager.py#L80


Close to being able to be removed:
https://github.com/ansible/awx/blob/ac8204427e241efcadd3bf8152007e1c04179a1e/awx/main/scheduler/task_manager.py#L82


its ALMOST safe to drop but it is used via https://github.com/ansible/awx/blob/ac8204427e241efcadd3bf8152007e1c04179a1e/awx/main/scheduler/task_manager.py#L518 which then calls https://github.com/ansible/awx/blob/ac8204427e241efcadd3bf8152007e1c04179a1e/awx/main/models/ha.py#L393 which expects `jobs_running` to be in the SimpleNamespace

**Comment by kdelee** [comment]
trying out https://github.com/ansible/awx/pull/12030 to see if we can drop one more of these

**Comment by kdelee** [comment]
Notes from Alan regarding `remaining_capacity`:


> remaining_capacity could optionally take the task manager jobs list. You'd need to avoid using it as a `@property`, so call it get_remaining_capacity. Then this would have an optional kwarg, which would be a full listing of all active jobs. The task manager has such a listing.

> This implementation would be similar to how we pass in tasks to capacity_values, in self.graph = InstanceGroup.objects.capacity_values(tasks=tasks, graph=self.graph). The idea is that these methods will need to be able to compute values based on the in-memory list of tasks, to avoid re-fetching.

**Comment by AlanCoding** [comment]
@kdelee did you fix this with recent merges?

**Comment by kdelee** [comment]
@AlanCoding yep, we dropped references to `remaining_capacity` and `jobs_running` so I think we can close this now
