### ISSUE TITLE
Can't send notification to Slack

### ISSUE THREAD

**Issue by s-cho-a** [ansible/awx#11682]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When set Slack notification, it doesn't work.

### AWX version

19.5.0

### Select the relevant components

- [x] UI
- [x] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

From menu **Notifications** -> **Notification Templates**

# Add notification

- Type: Slack
- Type Details:
   Destination channels: #alert
   Token: (slack app token)

### Expected results

Send notification to Slack.

### Actual results

When test notification, got error:

```
<urlopen error EOF occurred in violation of protocol (_ssl.c:1125)>
```

### Additional information

The Slack Token value always can't been saved. When edit the setting, I can't see it again.
![slack](https://user-images.githubusercontent.com/98935545/152480567-30bfd97e-0589-4d5b-9c48-1872a8dc0028.png)

**Comment by liquidspikes** [comment]
Hello @s-cho-a,

I was just able to verify that the slack notifications are working on the current AWX 19.5.1, I believe it is by design to not expose the token again once the configuration has been saved.

Here are the steps I used to get slack notifications working:

1. Go to **https://api.slack.com/apps**
2. Click "**Create New App**" in the top right corner
3. Enter a name for your App and assign it to slack workspace. Note: The name does not matter, you can name it literally anything. (AWX notifications)
4. Click on "OAuth and Permissions" on the left.
5. Scroll down to Scopes and click "**Add an OAuth Scope**" and type "chat:write" and select the first result.
6. Scroll to the top and click "**Install App to Workspace**"
7. Click "**Allow**" and choose what channel it's going to talk to.
8. Under "**Bot User OAuth Access Token**" click "**copy**"
9. in AWX open **Administration > Notifications > Add**
10. Paste the token within the token field. 
11. Click save and test! 😄

**Comment by s-cho-a** [comment]
@liquidspikes 
Thank you very much for the detailed guide. It works for me!
I will close this issue.
