### ISSUE TITLE
[WARNING]: You are using the awx version of this collection but connecting to Red Hat Ansible Tower 

### ISSUE THREAD

**Issue by lucky-cmdb-code** [ansible/awx#11901]
"response": {"json": {"count": 0, "next": null, "previous": null, "results": []}, "status_code": 200}, "total_results": 0}

**Comment by rebeccahhh** [comment]
Hi @lucky-cmdb-code can you please give us a little more information about what you need so we can try to help you out?

If you're a customer using Ansible Controller (formerly Ansible Tower) the official place to get collections for Ansible Controller is Ansible Automation Hub: https://www.ansible.com/products/automation-hub?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW 

This warning is just letting you know that you're using a free version of this collection, which is absolutely okay. If there is an error present please let us know, but this warning shouldn't prevent you from using the collection. You have a 200 status, which means you're in the clear. 
My favorite way to check http statuses is http.cat, so for this one it's https://http.cat/200 🐱

**Comment by benibr** [comment]
For the record, I have a similar issue which was due to the fact that I mentioned a mispelled SCM credential.
Then I got the Warning + a HTTP 200 without any result. The warning is irrelevant and using the right credential leads to a HTTP 200 with results so the playbook can continue.

**Comment by markfaine** [comment]
I am trying to use jq on the output of ansible-inventory but this Warning makes the output unusable because it is no longer valid json.  How can I prevent it from displaying or filter it out.  I have tried redirecting stderr and that doesn't seem to work.  Is there another option?

Something like `export ANSIBLE_DISABLE_WARNINGS=true` would be great.  At least, `PYTHONWARNINGS="ignore"` should work but I guess it's not implemented as a warning because that seems to do nothing.

This seems to work, but I don't like it, feels like a hack:

```sh
ansible-inventory --export --list | sed '1,2d' > tmp.json
python3 -mjson.tool tmp.json >/dev/null
echo "$?"
0
```

For example, jq will work like this to list hosts:
```sh
 ansible-inventory --export --list | sed '1,2d' \
  | jq  -r '[values[]|.hosts|select(.)[]]|unique[]'
```

Not good though because any script that uses this command will fail if a non-awx inventory is used because the first two lines will be stripped from the json.  I guess you could grep the output for that but still, it's a hack and there should be a way to just disable the warning entirely.
