### ISSUE TITLE
awxkit: Add functions to add/remove labels

### ISSUE THREAD

**Issue by thenets** [ansible/awx#12027]
Would be nice to have functions to add/remove labels.
It's not simple to add and remove labels from other resources, like the `inventory`.

The current solution that I found requires the following steps:

```python
# Get the organization obj
organization = awxkit_client.organization.get(id=<org_id>)

# Create a new label
label = awxkit_client.label.create(name="MyLabel", organization=organization)

# Get the related object of the resource where I'll add the label
inventory = awxkit_client.inventory.get(id=<inv_id>)
labels_pg = inventory.get_related('labels')

# Add and ignore the NoContent exception
try:
    labels_pg.post(dict(associate=True, id=label.id)) 
except awxkit.exceptions.NoContent:
    pass
```

I believe that we should have a very simple way to add and remove labels like this:

```python
# Get the resource obj
inventory = awxkit_client.inventory.get(id=<inv_id>)

# Add label
inventory.add_label("MyLabel")

# Remove label
inventory.remove_label("MyLabel")
```

**Comment by ffirg** [comment]
related to https://github.com/ansible/awx/issues/12044

**Comment by AlanCoding** [comment]
I'm closing in favor of https://github.com/ansible/awx/issues/5830, because the _python_ awxkit client is not user-facing. The CLI shortcomings with associations, however, have a significant user impact. If solving that automatically solves this then fine, but if not, we won't fix it. You have other options.
