### ISSUE TITLE
My not-so-great experience of working with awx

### ISSUE THREAD

**Issue by sllabymkcusicelcric** [ansible/awx#12024]
This might be old. I haven't looked into awx for quite some time, and we are looking forward to moving to an entirely different solution.

And sorry for that, my list below might be a bit toxic, I can't really tell. I know there are a lot of people who are putting a lot of time into this (just like with any other project), and that there are probably reasons why it was this way.

I was basically loosing my mind for a few months when I had to upgrade our setup a year or two ago. I'm still somewhat stressed out when remembering that time. But I had to do it, it was important, noone else could do it, great. This is pretty much unfiltered information that I collected when doing my work.

Please view it as "honest input to your project" instead of "personal attacks". Maybe you can derive some feature requests from it that help you make a more user friendly tool.

1. awx installation playbook doing nothing at all when upgrading from 4.0.0 to devel. but works when upgrading from 2.0.0 to devel. (your documentation on installation and upgrading is bad as well, other than mentioning the installation playbook nothing is explained)
2. awx ui on v17 crashing when editing credentials
3. awx ui on v17 not being able to create certain credentials. It was working at some point, but they just decided to screw up their whole ui for some reason (It's probably because their code is garbage as well so they had to start over)
4. not being able to install new commits on the ui -> not being able to fix previous bugs. I don't remember the specifics here anymore though, add a guide on how to do this.
5. database empty after upgrading to latest devel (fun fact: I'm not the only one with this issue).
6. firefox(!) crashing when using awx.
7. internal server errors without tracebacks to help you fix them. no logs
8. complete reinstallations not being possible. No idea where they put their stuff, even after deleting all docker containers, images, docker prune and running the playbook again the same old stuff was in the containers. There must be some magic directory containing garbage. So you are left with starting over by launching our ansible AMI if you break the awx installation.
9. live update of running jobs is broken and manual browser refreshes are needed
10. you can't search the output of jobs. it's lazily loaded and therefore the page search won't work.
11. looking for info on awx-cli? It always guides you to e.g. [tower-cli stuff](https://manpages.debian.org/testing/ansible-tower-cli/awx-cli.1.en.html) or some ["Building the Documentation" instructions](https://github.com/ansible/awx/tree/devel/awxkit/awxkit/cli/docs).
12. The button "User Details" leads to a broken page "The requested resource could not be found.". Going via the longer menu route works.
13. Migrations were not applied automatically, I had to figure out this stuff and run them myself.
14. What is wrong with your versioning, seriously

I really hope awx improves. As far as I can tell, your versioning looks allright nowadays for example.

If some stuff on this list is already fixed, great. But we are going to move as much stuff as possible to dedicated aws services and are going to stop our ansible server at some point anyway.

**Comment by shanemcd** [comment]
Hi. I'm sorry to hear you've had a negative experience with AWX. I can see you are upset and I understand it can be frustrating when things dont work. 

There's quite a lot to unpack here. First, for your upgrade problems. Versions 2 and 4 are several years old at this point. AWX is a fast moving project, and our team is small. We do not have the resources to test every permutation of possible upgrade scenarios.

For the UI issues - version 17 was the first version that contained our new UI. We know it was buggy and it has stabilized since then.

For the other issues, if you are still experiencing them on a newer version we'd be happy to collaborate with you through the troubleshooting process. But you say that you are planning to move away from AWX, so I understand if you are not interested.

I'm going to close this issue now because I do not see any actionable feedback or any information that would help us diagnose and address the issues. If you would like help troubleshooting anything in the future, please open an issue for each problem you encounter and provide as much information as possible. Take care and have a nice weekend.
