### ISSUE TITLE
AWXKIT: Cannot delete labels

### ISSUE THREAD

**Issue by thenets** [ansible/awx#12044]
If I try to delete a label being used by some resource, I get the following error:

```python
awxkit_client.labels.get(name="MyLabel").delete()
# > awxkit.exceptions.MethodNotAllowed: Method Not Allowed (405) received - {'detail': 'Method "DELETE" not allowed.'}
```

Would be nice to have a method that allows the user to force-delete the label by removing it from any resource and then deleting it. Example:

```python
awxkit_client.labels.get(name="MyLabel").force_delete()
```

**Comment by jbradberry** [comment]
As currently constructed, the only way using the API to delete a label is to unattach it from everything it is attached to.  You could do what you ask for by looping over every object that has this label and doing the unattach operation, but that would not be an atomic operation, nor should we attempt to pretend that it is.  I question, though, whether QE actually needs such a hard constraint.  If you truly need to clean up a label, it would be enough to make sure it was unique when first created (use a UUID?) and to limit the objects it gets attached to.  Otherwise, maybe it is ok for the label to hang around between tests.

Alternatively, an argument could be made that the current behavior of the API is silly, and that we ought to allow sufficiently privileged users to delete labels.  However, I'll point out that that doesn't make QE's lives any easier -- you would still have to support testing versions that do not have this behavior.

**Comment by AlanCoding** [comment]
Closing, because this is a year old and is not user-facing.
