### ISSUE TITLE
API not saving timezones correctly

### ISSUE THREAD

**Issue by kialam** [ansible/awx#12164]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Certain timezones do not save correctly in the API.
Steps to reproduce:
1. Visit the Schedules tab from a Job Template
2. Attempt to save a schedule with `Europe/Skopje` as the timezone
3. Observe the `PATCH` is successful, however inspect the corresponding `GET` request and see:
```
rrule: "DTSTART;TZID=Europe/Skopje:20220707T230000 RRULE:INTERVAL=1;COUNT=1;FREQ=MINUTELY"
timezone: "Europe/Belgrade"
```

### AWX version

21.0.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

See above

### Expected results

API saves correct timezone

### Actual results

Certain timezones get saved as different timezones

**Comment by jbradberry** [comment]
This ultimately stems from recent controversy about how the timezone database (that is used by all languages, not just Python) is maintained.  Some details can be found here: [A fork for the time-zone database?](https://lwn.net/Articles/870478/).  The gist though is that some historical timezones have had their information merged with other more standard ones, and the historical name is now just a link.

My off-the-cuff response to this was to think that we should only expose the standardized non-link timezones now, but upon reflection I think that would be bad UX.  We should probably do something a bit more involved that lets the user know that they can select their old timezone, but standardized timezone X is really what will be used.

**Comment by jbradberry** [comment]
@hesmithrh I no longer think that this is ready to be on deck yet.  There needs to be some discussion on the UI side (led by @kialam) over what to do about this.

**Comment by john-westcott-iv** [comment]
@nixocio and I discussed some potential options:

1. Modify the schedule endpoint to contain both a "ui_selected_tz" and "timezone". The current "timezone" field would not be able to be changed through the UI and would become a computed filed and the new ui_selected_tz would contain the TZ the user actually selected. This field would be used to populate the Local time zone dropdown on edit. 

2. Modify the API to:
    * Return not only the timezone names but also the linked time zone.
    * On the POST/PUT of the schedule, if the timezone changes to a link return a message saying that the timezone was altered because of a link.

    Also modify the UI so if a timezone is selected and it contains a link to something else a warning would appear in the UI saying something like:
    ![image](https://user-images.githubusercontent.com/32551173/169059680-99943d1a-b639-434a-80ed-6f8331121287.png)

3. Perform a release with a note explaining the disappearance of the timezone. Have a migration which converted any linked timezones to their source and modify the API to not return the linked timezones to the UI.

There seem to be both positives and negatives to each approach including when thinking about what would happen if a linked timezone was either removed, reinstated or additional links were added. 

Removed:
In option 1 we would need logic in the UI edit screen to say "try and display ui_selected_tz, if that is no longer available fall back to timezone". Which would work on edit but not on the list mode.
In option 2 this wouldn't be an issue because the field would only point to the linked source.
Option 3 would be fine because we don't display the links already.

Reinstated:
In option 1 you would see the correct TZ in the UI (from ui_selected_tz) but, until the schedule was saved, it would be functionally using the incorrect TZ in "timezone". This, I think, could lead to confusion.
In option 2 the schedule would run and display in the old TZ until someone went into awx and selected the appropriate new TZ. 
Option 3 would behave like option 2.

Additional links:
Options 1 and 2 should work normally but on the next save the ui_selected_tz would be updated for option 1 and in option 2 the selected TZ will flip to its new link with the warning message. Option 3 would fall down here because there likely wouldn't be a migration to update existing schedules to the new source. On edit, the legacy TZ wouldn't be found in the dropdown list and I don't know what the behavior would be in that case.

If this TZ change was static (no new links, nothing removed or reinstated) option 1, I think, would be easier to implement. Option 2 would be more work and an annoyance to users but the UI/API would say what is happening on change and there is no possibility between a mix-match of what is selected vs. what is actually be used.  

Does anyone have any additional thoughts on other solutions and/or comments on either of these options?

**Comment by jbradberry** [comment]
I believe that a data migration could and should happen as part of this fix, so any pre-existing values will be set correctly whichever path we take.

I dislike option 3.  I strongly lean towards option 2.

**Comment by kialam** [comment]
cc @trahman73 

Option 1 would require the least amount of effort on the UI side and would have no visible impact to the user.
Option 2 would require the most amount of work on the UI side and present a new pattern to the user experience and the schedules view.
Option 3 I see as an eventual end goal. If we start with Option 2, we can slowly migrate users with linked time zones over and  afterwards remove those entries from the UI as well as the API response (e.g. the /timezones endpoint) altogether. 

Sites like Google Calendar seem to have already implemented similar changes of removing linked timezones from their dropdown:
<img width="892" alt="Screen Shot 2022-05-18 at 11 55 04 AM" src="https://user-images.githubusercontent.com/2293210/169131615-16356143-d2d4-4de5-8f27-d7268807ebbb.png">



I lean towards implementing Option 2, however I'd also like to see release notes that inform the user of this timezone change/change in UX as part of the work.

**Comment by trahman73** [comment]
@kialam I agree that Option 2 seems to be the best experience going forward. Notifying the user that a selected timezone may contain a link to the adjusted timezone as a warning in the UI is a good approach to make this work.
