### ISSUE TITLE
[Tech Debt] optimize/cache information about preferred instance groups

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12201]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We probably want to fix this in `create_unified_job` or in `signal_start` and save a list of pk's of instance groups OR...even more interesting, instances, in order of preference

sowe would keep preferred_instance_groups as a property but UnifiedJob would have a new field on the model where we cache it once we've calculated it once so we dont calculate it lots of times

**Comment by AlanCoding** [comment]
Our idea here was that we could cache this to some internal field for our own purposes.

However, https://github.com/ansible/awx/issues/5711 is still a relevant RFE. We may want to consider how to turn this into a feature and obtain the performance gains at the same time.

**Comment by kdelee** [comment]
![Screenshot from 2022-07-01 16-16-18](https://user-images.githubusercontent.com/29239279/176962950-db487b82-e1b6-4afd-bf9e-a0606c1aa601.png)
This picture shows how putting instances in an ordered list and picking "first sufficient capacity or first idle instance" retains same behavior

**Comment by AlanCoding** [comment]
I don't know if that's always true. Our main loop for the search is:

https://github.com/ansible/awx/blob/fd671ecc9d49845f1e0fa09ec178d1d6518061fe/awx/main/scheduler/task_manager.py#L542

So we're here, on item `instance_group` in this list, and we do:

https://github.com/ansible/awx/blob/fd671ecc9d49845f1e0fa09ec178d1d6518061fe/awx/main/scheduler/task_manager.py#L555-L557

For illustration, I will denote instance groups with A, B, C, ... and instances with 1, 2, 3, .... Consider a situation where the "idle" criteria returns a match. To further refine that, let's construct this instance situation:

 - 1 has insufficient capacity
 - 2 is idle but has insufficient capacity
 - 3 has sufficient capacity but is not idle

Then assume the mappings:

 - A [1]
 - B [2]
 - C [3]

If you were to "flatten" the instances into an instance-only list, then you would have `[1, 2, 3]`, and the "sufficient capacity" criteria has precedence, so it would pick node 3. This is not the same as our current algorithm, which treats the criteria's precedence as applying only to a single instance group. So treat the preference data model as `[[1], [2], [3]]`. Our second criteria, the existence of an idle instance, would match 2 in the second sub-list (the B instance group).

Thus, I was advocating that we may want to cache the list as a list of sublists. You would still be able to de-duplicate entries, since if the group C had instance 1 in its list, `[[1], [2], [1, 3]]` would be functionally the same as `[[1], [2], [3]]`. Because if the instance 1 isn't matching either criteria in group A, then there's no way it'll match a criteria in group C.

However, read the scenario deeper, and you realize that it implies that instance 3 is larger than instance 2 (it has more free capacity while having running jobs). With execution nodes, this will become more likely, as nodes become more heterogeneous. It would be quite uncommon for the main cluster nodes (control / hybrid) to have varying sizes. I'm not at all clear if it would be _desirable_ to match node 2 or 3 in this scenario. Selecting 3 would better respect our notion of capacity demands, but 2 would better respect the user's expressed desire. I am distrustful of our absolute capacity figures, and fearful of user anger, so I have a slight preference towards keeping the current algorithm in place. I don't think this substantially complicates the work of caching the preference list.

**Comment by fosterseth** [comment]
this work has already been merged into the task_manager_refactor branch -- so we can either close this now, or we can close it when task_manager_refactor is merged into devel @hesmithrh

**Comment by hesmithrh** [comment]
thanks @fosterseth if we have testing and docs already covered in other issues, we should close (cc @jneedle ). if not, we should keep open to track QE and Docs , FYI: @tvo318 not sure if we 1) need docs here and 2)if you have an issue tracking that

thanks!

**Comment by kdelee** [comment]
Let's close, this is internal logic
