### ISSUE TITLE
Projects start SCM update during jobs, even when "update on launch" is not checked.

### ISSUE THREAD

**Issue by lsantiag86** [ansible/awx#1223]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Projects start SCM updates even when the "update on launch" box is not checked on the project when a job starts. This is causing us issues when the internal gitlab server that has all of the our projects source code is down for maintenance or down at all.  All of the jobs triggered fail because gitlab isn't available for the pull.  
We also have an automated service roll that will trigger ansible tower when the gitlab server is alerting and that wont work either to fix the host, since it cant perform the pull.

##### ENVIRONMENT
* Tower 3.2.1
* Ansible 2.4.1.0 

##### STEPS TO REPRODUCE

Run a job.
SCM sync happens before playbook begins

##### EXPECTED RESULTS

Run a job.
SCM sync only happens if "update on launch" is checked.

##### ACTUAL RESULTS

Run a job.
SCM sync happens before playbook begins

**Comment by wenottingham** [comment]
This is expected, there is a checkout that always happens, as there is no guarantee that on any specific Tower node the project is already checked out.

https://github.com/ansible/awx/pull/567 was added to AWX to allow for short-circuiting if the correct version is already checked out, for *git only* (other SCMs don't have enough info to support this.)

**Comment by tombenninger** [comment]
@wenottingham We're trying to use Tower as the primary tool for automation for all of our services, including our Git SCM where we develop and store our playbooks and other Ansible configurations.

I realize there's a bit of circular logic here between Ansible and Git, but it seems like a periodic sync and caching function would support this, and I suspect other people have the same issue. Would this be better treated as a feature request than a bug?

**Comment by wenottingham** [comment]
Already is, but there are many corner cases: https://github.com/ansible/awx/issues/289

**Comment by Testicule** [comment]
> This is expected, there is a checkout that always happens, as there is no guarantee that on any specific Tower node the project is already checked out.

What? I mean, seriously. What?

If a project isn't even checked out, i think AWX should be smart enough to be aware of that fact...

And if you haven't even got a project checked out, then just fail.
Why would anyone expect to be able to run a job vs a project they haven't even checked out once?

On the other hand, if i've just updated my project which contains jobs to manage my SCM server. And I shut down that SCM server for maintenance, i do not expect AWX to hang when I try to launch a job to power on my SCM server...

This bug needs to be fixed.
Until this bug is fixed, it is impossible for AWX to manage the SCM server itself.
And running jobs from any SCM besides git is painfully slow, due to delay before launch.

Whatever your "corner cases" are, they need to be addressed directly. Not evaded by a horrendous kludge like doing a checkout every time a job is launched, when there is zero real need to do so.

**Comment by zx1986** [comment]
We have roles/requirements.yml, and every launch will run the roles update again, life wasting ...
