### ISSUE TITLE
Some minishift installs broken

### ISSUE THREAD

**Issue by matburt** [ansible/awx#124]
With the recent change to use a container to build the python sdist we've broken some minishift installs that can't bind the local volume when running the sdist.

I suspect we'll need to conditionally build that or provide some other alternative for those minishift users.

**Comment by shanemcd** [comment]
Curious what people think about using `oc cluster up` instead of `minishift`: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

I really don't like how using the minishift installer requires hijacking your docker environment, and running docker inside of a VM seems unnecessary since we specify Docker as a prerequisite in the Install Guide. There are a few hoops to jump through (outlined in the link above), but IMO that seems preferable over `eval $(minishift docker-env)`.

**Comment by jdoss** [comment]
I actually prefer to use `minishift` when running Openshift locally because it keeps itself contained in it's own little world and it just works :tm: in most cases.

It looks like you can use https://docs.openshift.org/latest/minishift/using/host-folders.html#sshfs-folder-mount to mount your home dir into the VM. I manually set it up but the build dies with 

```
TASK [image_build : Build AWX distribution] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container 5ba486ae7b406f0fa27bbbdabba8607e0773adf72c0a58640d85d5490c789d70: 500 Server Error: Internal Server Error (\"mkdir /home/jdoss: file exists\")"}
```

I will see if I can move past this error. If so, maybe just having a conditional for setting up this SSHFS mount if on Linux with KVM is an easy path forward?

**Comment by matburt** [comment]
I've reworked the installer a bit to not specifically require the dist build container, check it out here: #182 

This works for me on my local minishift install on macos and arch linux. I'll merge this sometime this weekend.
