### ISSUE TITLE
[Task manager] query UnifiedJob model instead of each job type individually

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12402]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

In the task manager in `get_tasks` we do a bunch of almost identical queries

https://github.com/ansible/awx/blob/923cc671db1e8a76325afc6ed14798bcbc66a64d/awx/main/scheduler/task_manager.py#L127-L137

It would be better if we can collapse these into one query to the UnifiedJob model, preferebly using `non_polymorphic` for reasons I'll let @AlanCoding get into.

Not a blocker, but maybe related:
- work on preferred_instance_groups

This probably takes precedence over
https://github.com/ansible/awx/issues/12157

because we can get into more specific optimizations after just dropping some of these excessive queries.

UnifiedJob has `instance_group` so it is safe to call `prefetch_related('instance_group')` on all of the job types

The only different queries in this code are:
 project updates that call
`ProjectUpdate.objects.filter(status__in=status_list, job_type='check').` we need an equivalent way to say this that only uses properties on the UnifiedJob model. I'm 99% sure this is `launch_type='sync'`
https://github.com/ansible/awx/blob/923cc671db1e8a76325afc6ed14798bcbc66a64d/awx/main/models/unified_jobs.py#L567

Inventory updates say:
        inventory_updates_qs = (
            InventoryUpdate.objects.filter(status__in=status_list)
            .exclude(source='file')
            .prefetch_related('inventory_source', 'instance_group')
            .order_by(*order_by_list)[:limit]
        )
which reference `inventory_source` and `source=file`

To test this:

1) Create an instance group with no capacity/instances
1.5) disable the instances in the controlplane group to hopefully avoid project updates running
2) Enable django debug toolbar
3) put a call to task manager schedule in a view like `/api/v2`
4) Create a bunch of types of jobs -- inventory updates, project updates, system jobs, workflows, ad hoc commands
5) test that things don't blow up and that we do less queries and it takes less time :dagger:  

Might look something like:
```
 UnifiedJob.objects.non_polymorphic().filter(status__in=status_list, launch_type!='sync').prefetch_related('instance_group')
```

MAY be better do the spawning the hard dependencies before the task manager before this work. We're concerned about if we need to later access fields that were not fetch with the query to UnifiedJob

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by AlanCoding** [comment]
the launch type part may have to be a separate action on the queryset like `.exclude(launch_type="sync")`.

The inventory source file type is not managed by the task manager at all. It appears to be created here.

https://github.com/ansible/awx/blob/5bd4aade0e54a3f5cff08014033fa90568b3b2b1/awx/main/management/commands/inventory_import.py#L864-L866

Reading this code, it may be created in the "pending" status, but that's not desirable. It's not meant to go through the task manager, so like the project syncs, it should be created in the "running" status or even successful / finished. That would be pretty trivial to fix, if it needs fixing at all. With that assumption safely established, the task manager should drop that filter.

If there is a file-based inventory update running, then you can count it against capacity. It would be _more_ work to special-case it.

However, project syncs probably shouldn't be counted against capacity. These are created in the "running" status, and never see the "pending" status at all. So the reason we apply that filter (at all) is so that we don't count the running project syncs against capacity. This is fair, and we should continue to do that. However, if our query can be made relatively efficient, filtering may be a greater performance penalty than loading those extra records, so we could just skip syncs in the code that tracks used capacity. That's just an option, we don't have to.

**Comment by kdelee** [comment]
(Edited because I was mostly repeating alan)

so TODO:
Investigate/ensure that inventory_updates with source file type are created in `running`

**Comment by AlanCoding** [comment]
From the code snippet above, it looks like it's not. But you can add `status="running"` to the `_eager_fields` dict. It should really be that easy.

**Comment by kdelee** [comment]
@fosterseth grabbed changes from Alan's branch and adapted them in https://github.com/ansible/awx/pull/12437/files. Since this is internal, going to close
