### ISSUE TITLE
Images at https://quay.io/repository/ansible/awx 

### ISSUE THREAD

**Issue by tcsabina** [ansible/awx#12426]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi!

What is the purpose of images at https://quay.io/repository/ansible/awx? Are these some 'semi-official' images for AWX?
Or a docker image of AWX must be always manuall build based on https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md?

FYI,
I tried to run 'latest' from the above location, but it just hangs with:

> install@qpserver19:~$ docker run quay.io/ansible/awx
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4 of 30
[wait-for-migrations] Waiting 4 seconds before next attempt

### AWX version

don't know

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

docker run quay.io/ansible/awx

### Expected results

an AWX docker container is starting

### Actual results

[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4 of 30
[wait-for-migrations] Waiting 4 seconds before next attempt

**Comment by kurokobo** [comment]
Refer the official installation guide: https://github.com/ansible/awx/blob/devel/INSTALL.md

The image you mentioned is the official image, but it's not designed to run directly and separately using `docker run`. Typically it shoud be used with Kubernetes, OpenShift, or Docker Compose.

If you have any further questions about installation and usage of AWX, the mailing list or IRC channel is the best place to get help since this issue tracker is for tracking feature enhansments and bugs: 

IRC: #ansible-awx on https://libera.chat/
Mailing list: https://groups.google.com/forum/#!forum/awx-project

**Comment by BlueskyFR** [comment]
I agree, it is unclear how to use the image we should reopen this since the installation guide doesn't even mention it
