### ISSUE TITLE
Could the Release Notes of AWX contain the used ansible version?

### ISSUE THREAD

**Issue by tcsabina** [ansible/awx#12425]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I might be mistaken, but I think currently the used ansible version is not listed anywhere. So probably the only way to get the ansible version within AWX is the install it and check it.
Correct?

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by kurokobo** [comment]
The version of Ansible used by AWX totally depends on the Execution Environment used in AWX. Since the EE used in AWX can be determined by the user, therefore the version of Ansible used by AWX is also up to the user.

The default EE for AWX, awx-ee, currently uses Ansible 2.12, but this is not pinned with AWX releases as it also depends on the release cycle of ansible-runner. The release cycle of ansible-runner is different from AWX.

So, in my opinion and in my understanding, since the version of Ansible used by AWX can be easily changed, I don't think it makes much sense to put that in the AWX release notes 🤔

**Comment by shanemcd** [comment]
@kurokobo is correct. Ansible is not installed within AWX itself, it depends on the EE. The latest image of awx-ee just pulls the latest version of Ansible. If you want to pin to a particular version you'll want to build your own EE. For info on how to do that see [Ansible Builder](http://ansible-builder.readthedocs.io/en/stable/)

**Comment by tcsabina** [comment]
Thanks guys,

All clear!
