### ISSUE TITLE
AWX SSO login creating multiple user ids

### ISSUE THREAD

**Issue by venkatasykam** [ansible/awx#12664]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We are using awx 17.1.0 for configuration management and integrated with saml for SSO login. Sometimes, while uses are login using SSO, awx is creating a duplicate id. 
For example, my user ID is VENKAT. When I logged using SSO, it's creating very lengthy and duplicate user id as "VENKATajhdueijdbbxbdh".

Can you please let us know how to fix this issue? 

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.18

### Operating system

Linux

### Web browser

Chrome

### Steps to reproduce

SSO login. Sometimes for some users.

### Expected results

Duplicate user id should not be created.

### Actual results

Saml SSO login should be worked as expected with inquired user id.

**Comment by fosterseth** [comment]
Hi!

This is the expected behavior if user "VENKAT" was already a local user in AWX, and then you tried to use SAML login for an account with the same username. Upon SAML login, a new user will be created with the suffix (VENKATajhdueijdbbxbdh), as you found.

To verify this, you should see that VENKAT exists as a normal (non social) user in AWX.

for example, on the Users page
![image](https://user-images.githubusercontent.com/8745776/185217782-11f607de-34e4-4e82-940a-fb72eacbd24b.png)

awx_admin was first a local user. Then I logged in to SAML with awx_admin, and the newly created social user in AWX has the suffix, as seen in the screenshot above.

let use know if that helps explain the issue.

**Comment by venkatasykam** [comment]
@fosterseth 
Thanks for the explanation. But how the local user already exists ? Because of LDAP ? We use saml login everytime for new user or existing user.

Can you please lets us know how to fix this issue ?

**Comment by venkatasykam** [comment]
Any idea on this please?

**Comment by venkatasykam** [comment]
Anybody have any suggestions on this ??

**Comment by fosterseth** [comment]
at /api/v2/users, what does the `external_account` field say for both `VENKATajhdueijdbbxbdh` and `VENKAT` users?

**Comment by akus062381** [comment]
Hi @venkatasykam,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
