### ISSUE TITLE
SAML Auth reverts "Admin" users to "Normal" users

### ISSUE THREAD

**Issue by rdancel001** [ansible/awx#12729]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

0.26.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

21.4.0

### Web browser

Firefox, Chrome

### Steps to reproduce

We have SAML Auth enabled. My account, prior to upgrading to the current version of AWX, was an admin user. When I log in today, it'll revert my account back to a "normal user". This happens to more than just myself. Every user who once was an admin, gets reverted when they login to their account. 

We login to the local admin account, change the user back to admin user, try to log in to our personal user again and it reverts it back to "normal". I have tried to delete the user, log back in, back to "normal" mode, try to set it again as an admin user from the local admin account, and it still reverts back to "normal" user.

### Expected results

My account should continue to persist as an admin user when logging in using SAML authentication.

### Actual results

After upgrading, our SAML users are constantly reverted back to normal instead of having their account persist as "admin"

**Comment by john-westcott-iv** [comment]
Hello, this issue should have been addressed in v 21.4.0 with the commits from https://github.com/ansible/awx/pull/12522.
This introduced additional settings to the SAML user attribute map one of which is `remove_superusers`. Please try setting that too False and see if the system_admin flag stops being removed.

**Comment by akus062381** [comment]
Hi @rdancel001!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
