### ISSUE TITLE
Can awx/tools/docker-compose/inventory setting project_data_dir??

### ISSUE THREAD

**Issue by CC-Kuoying** [ansible/awx#12765]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'd like to add manual project, How can I do? 

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"

[all:vars]

# AWX-Managed Database Settings
# If left blank, these will be generated upon install.
# Values are written out to tools/docker-compose/_sources/secrets/
# pg_password=""
# broadcast_websocket_secret=""
# secret_key=""

# External Database Settings
# pg_host=""
# pg_password=""
# pg_username=""
# pg_hostname=""

# awx_image="ghcr.io/ansible/awx_devel"
# migrate_local_docker=false
project_data_dir=/var/lib/awx/projects
```

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

no

### Expected results

no

### Actual results

no

**Comment by djyasin** [comment]
Hello,
At this time we do not recommend using manual projects. Is there any particular reason that you are trying to use a manual project vs using the SCM projects?

If you'd like to proceed with manual projects, we would suggest referring to this persistent project directory.
You can look into using a persistent volume when deploying the awx spec file. 
https://github.com/ansible/awx-operator#persisting-projects-directory

**Comment by akus062381** [comment]
Hi @CC-Kuoying!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
