### ISSUE TITLE
Can't edit node in workflow (getting an error "This field may not be blank")

### ISSUE THREAD

**Issue by AlekseiSaff** [ansible/awx#12782]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After editing node in workflow editor on saving workflow getting an error

```
There was an error saving the workflow.

Details
PUT api/v2/workflow_job_template_nodes/33/ 400
This field may not be blank.
```

### AWX version

21.5.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

try to edit a node in WF editor and after saving wf. will receive this error

### Expected results

WF must be saved with new values (in my case I'm changing limit field)

### Actual results

getting an error

```
There was an error saving the workflow.

Details
PUT api/v2/workflow_job_template_nodes/33/ 400
This field may not be blank.
```

### Additional information

At least provide more deatils to the error message, because right now I even don't know what field it's complaining about

**Comment by mabashian** [comment]
Steps to reproduce:

1. Create a JT that prompts for limit
2. Create a new workflow
3. Add a node that references the JT from step 1, provide a value for limit when prompted
4. Save the workflow
5. Edit the workflow
6. Edit the node from step 3
7. Change the limit
8. Save the workflow

<img width="578" alt="Screen Shot 2022-08-31 at 11 28 51 AM" src="https://user-images.githubusercontent.com/9889020/187718678-17d848a0-dbd9-46fc-abc9-aec19203f152.png">
<img width="1278" alt="Screen Shot 2022-08-31 at 11 28 46 AM" src="https://user-images.githubusercontent.com/9889020/187718681-14a6ff96-e198-4272-bf5b-9e6ec88a8f5b.png">

The issue is that `identifier` is being sent in the payload as an empty string.

**Comment by Mrmel94** [comment]
Same issue here, a workaround is not edit the job in the wf but delete it and re-create it

**Comment by AlekseiSaff** [comment]
I'm just changing directly in DB

**Comment by AlekseiSaff** [comment]
21.6.0 still the same

**Comment by AlekseiSaff** [comment]
21.7.0 - resolved

**Comment by nicolaibaralmueller** [comment]
> 21.7.0 - resolved

I can confirm. Issue resolved.
