### ISSUE TITLE
Issues found- New Mesh Viz

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#12903]
In checking the feature-mesh-scaling branch, I found some issues to report:

- [ ] RBAC: For adding an instance, an unauthorized user can access the add form and the edit form by manipulating the url
- [ ] If a normal user logs into a Kubernetes instance, they should not be able to see the instances tab at all. Currently, they can see it in the left side menu and when the UI loads, it shows the user a 403 error.
- [ ] When a user runs a health check on a node, there is nothing in the UI that shows the user the result of that health check-whether it's healthy or not

**Comment by AlexSCorey** [comment]
I think the first item in the task list is sort of addressed [here ](https://github.com/ansible/awx/issues/7565) and since this issue is not isolated to instances or any mesh work I do not think it is a priority for 4.3

For the third item:
We no longer recognize a `Healthy` state on a node, but instead specify different states like those found [here](https://github.com/ansible/awx/blob/devel/awx/ui/src/components/StatusIcon/StatusIcon.js#L25).  However, if a user does a health check on a node, we do update the time stamp on the list item (in expanded view) and give them the reload bar to inform them that things are happening.
![Screen Shot 2022-09-26 at 5 18 43 PM](https://user-images.githubusercontent.com/39280967/192383453-59519ecc-1d8e-43bf-96a0-f403d3525da9.png)
![Screen Shot 2022-09-26 at 5 19 31 PM](https://user-images.githubusercontent.com/39280967/192383449-231f8698-f078-4ec5-9436-f8d9177ee431.png)
