### ISSUE TITLE
webhook notification cannot use the variables from the result

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/awx#12990]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

we are trying to open a gitlab issue every time a job fails so we created a webhook with the following format: https://gitlab.com/api/v4/projects/33425632/issues?title=Issues%20automation%20testing&labels=type::bug&description=${job_friendly_name}

we cannot seem to be able to get any of the variables described here https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html#webhook-payloads into the webhook url

### AWX version

21.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

create a web hook with the provided pattern

### Expected results

the gitlab issue is created and the description contains the job_friendly_url content

### Actual results

the gitlab issue is created and the description contains the 'job_friendly_url' as the text

### Additional information

thank you very much for the project AWX and for looking at this issue.

**Comment by djyasin** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by akus062381** [comment]
Hi @mihai-satmarean,
Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
