### ISSUE TITLE
Cached files allowing an inventory sync when the project sync failed

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#13015]
When a user creates an inventory sync using a project taken from a repo that has somehow cached the inventory files in that repo, BUT the project sync had subsequently failed, the inventory sync is still allowed to be created against that project. The inventory sync, of course, fails because the project was not synced successfully, and the failure will cause user confusion if this occurs.

This one is pretty tough to recreate. Discussions with UI devs resulted in two conclusions:
1. This is likely an issue on the API end and needs to be looked into further.
2. UI can bandaid this issue by preventing a user from being able to sync an inventory source off of a project that has a failed sync as its most recent sync.

For reference- in this screenshot, where '2hosts' appears, this is only appearing here because the files were cached. An unsuccessful project sync would only show /project_root in this field.
![image](https://user-images.githubusercontent.com/63685497/194575292-5aceff22-4d6f-4122-9a66-32b2ab79adfb.png)

**Comment by relrod** [comment]
> The inventory sync, of course, fails because the project was not synced successfully

This behavior seems to depend on whether or not the Project has "Update revision on launch" set or not.

Here is what I think is happening after spending some time tracing bits and pieces of this code. I'm hoping maybe @AlanCoding can clear up anything I get wrong here.

If "Update revision on launch" is set on the project, when we trigger an inventory source update, we are actually launching _two_ `ProjectUpdate`s. We launch one (a 'check' job) because it gets added as a dependency job of the `InventoryUpdate`. I believe that in this case, when the PU dependency fails, the IU also bails out since the dependency wasn't "met". This is why in this case we see an IU failure. If the dependency *is* met, then we continue on, and we end up launching a second PU. I'll come back to that in a second.

When "Update revision on launch" is NOT set. We only launch the "second" PU mentioned above. There's no dependency added, so the IU won't fail due to an unmet dependency task.

That "second" `ProjectUpdate` is interesting. It's a 'run' job (as opposed to the dependency job which is a 'check' job, as mentioned above).

In `RunProjectUpdate#build_extra_vars_file`, we have this:

```python
        scm_branch = project_update.scm_branch
        if project_update.job_type == 'run' and (not project_update.branch_override):
            if project_update.project.scm_revision:
                scm_branch = project_update.project.scm_revision  # <--------
            elif not scm_branch:
                raise RuntimeError('Could not determine a revision to run from project.')
```

This line (the one I've pointed to in a comment in the above code block) is setting the `scm_branch` parameter (ultimately given to the project update playbook) to the `scm_revision` of the `Project` (which I think will only get updated on a successful project sync).

So this causes the IU to "reset" the repo back to the last known working commit, and then do its normal `ansible-inventory` work.

This is why if you look at the actual repository clone on disk -- do something that fails project validation and update the project, you will see the project still has the "new" (broken/failing) commit in it. But then as soon as you do an _inventory_ update, it reverts back to the last working commit.

All of this to say, I think the "cached" files are that we're reverting the project to the last known good commit.

## Questions

So I think my questions after all of that digging are:

- In the "Update revision on launch" case - what is the check job that gets spawned? Why are we launching two PUs in this case? (This one is just for my sanity and understanding)
- What is the actual intended behavior here? Is it intentional that we kind of "fall back" to the last known working revision based on the `Project`'s `scm_revision`? If so, then we should probably also do that in the "Update revision on launch" case. Alternatively, and probably my preference (but we might break some workflows), we just completely disallow IUs if the project they are sourced from is in a failed state.

I am going to stop digging on this for right now until I know more, because my brain is :exploding_head: at this point. :)
