### ISSUE TITLE
AWX 21.4.0 - Job stays stuck in pending with no other jobs running

### ISSUE THREAD

**Issue by creativemind-pluto** [ansible/awx#13013]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

21.4.0

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs
- [X] Collection
- [X] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 18.04.6 LTS

### Web browser

Chrome

### Steps to reproduce

Run jobs & it shows in pending state.

### Expected results

runnings Jobs, add new jobs to the queue

### Actual results

successfully finished jobs

**Comment by akus062381** [comment]
Hi @creativemind-pluto,

This should have been fixed in our latest release. Please try updating to see if it has been fixed.

**Comment by mabashian** [comment]
@creativemind-pluto 

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
