### ISSUE TITLE
Option to clear Variables on inventory level

### ISSUE THREAD

**Issue by Tobias-Pe** [ansible/awx#13045]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Referring the in #5682 described behavior:

When i have Vars in my "all group" which i decide to later on delete, they will stay in the inventory on AWX.
A new checkbox in the sync for the inventory with the option to clear also the inventory level vars would make this easier.
Many people only manage their variables through their repositories which get synced and if deleted variables stay in the inventory in awx after a sync, then it'll lead to long debug times to fix this (as seen in the experiences in the issues #5682 & #10200).

I get that this is not a Bug, but an intended behaviour because you can add variables manually. So i would see the checkbox to automatically clear all variables on sync as an opt-in (like the overwrite options in sync)

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

1. Add a variable to your synced repository under group_vars all.yml
2. Sync that inventory into awx
3. Delete variable in the synced repository
4. If the new opt-in Option will be checked --> Clear all variables in the inventory on awx and after that sync the inventory into awx

### Current results

After deleting the variable and a sync, it will still be in the awx inventory, because Vars at the toplevel inventory are not automatically cleared, as they can also be set manually outside of any one (or multiple) inventory sources.

### Sugested feature result

Opt-In Checkbox in Inventory or Sync, to clear all Vars before a sync.

**Comment by AlanCoding** [comment]
This sounds like the same thing articulated in this comment of a prior issue:

https://github.com/ansible/awx/issues/11623#issuecomment-1256616629

> At the very least a toggle would be nice, (perhaps per-inventory source) to allow for group_vars/all vars to be fully reloaded or something.

My hesitation is that _both_ behaviors (checkbox checked or not checked) are wrong, and it should be fixed properly.

My suggestion is that we track "all" variables on inventory source by adding a new field like `InventorySource.variables`. This should get combined with inventory variables when used in a job. This _necessarily requires_ presenting those variables in the UI so that the user can follow what's happening. Indeed, the UI changes are the hard part IMO.

To re-state, I would rather _not_ add a work-around check box, and just fix the issue, but I will ping @ffirg in case he wants to add anything. It's true that the checkbox would be much easier to implement (but would still involve UI changes). You could even argue that the variables _shouldn't be editable_ if the checkbox dictates that inventory updates should overwrite them... because whatever the user puts in would get overwritten. I think it's easier to do it correctly.

**Comment by AlanCoding** [comment]
Closing in favor of the other approach.
