### ISSUE TITLE
Pin to specific receptor version

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#13060]
there are 2 components to receptor -- receptor (on quay) and receptorctl (on pypi)

Currently awx-ee uses the devel version of receptor
AWX uses the 1.2.3 version of receptorctl

I'd rather see these 2 components in lock step

**Comment by AlanCoding** [comment]
Could we just un-pin this? Because the receptor image points to the quay devel tag. At least devel / devel will get eventual consistency, even if there would be some churn near a release.

https://github.com/ansible/awx/blob/721e19e1c84c9e870fbaf09462dd0fd964c833b0/requirements/requirements.in#L49

Also, I see this in "Needs Review" but can't find any patches linked.

**Comment by fosterseth** [comment]
There are advantages to awx-ee using devel receptor, so I'd like to keep it that way for now.

We could always just unpin receptorctl.

So far this hasn't really been a pain point, so we can close this for now.
