### ISSUE TITLE
RFE: Modify ansible-vault files from within the UI

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#1317]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- API/UI

##### SUMMARY
Would like to be able to modify vaulted files from within the UI so this is possible from a Windows machine.

##### ENVIRONMENT
* Operating System: Windows

##### ADDITIONAL INFORMATION
This would be useful in the event of any security constraints preventing someone from using a Linux box or guest VMs.

**Comment by wenottingham** [comment]
We are not planning to connect Tower directly to source control with write access, which is what this implies.

**Comment by wenottingham** [comment]
More specifically: the place vault files live is in the project repo - we are not going to be writing a full SCM integration (which would need done with users, passwords, keys, etc.), and having something that only works for manual projects is not worth the effort.

If we support vaulted individual variables in host/group vars, we may allow for editing those. But not vaulted files in projects.

**Comment by AlanCoding** [comment]
> If we support vaulted individual variables in host/group vars, we may allow for editing those.

I'm asking around, and it sounds like Ansible core supports this, but AWX makes an inventory script that dumps as JSON which makes this impossible. Simple solution - just switch to YAML, and they hypothetically there's a syntax that the user can copy+paste into hostvars to make it vaulted data, and the JT vault credentials could decrypt it. (I have yet to fully identify this syntax, asking around Ansible core right now)

EDIT: turns out that won't work
