### ISSUE TITLE
Upgraded from 21.2 to 21.6 - getting following error in one of the management jobs

### ISSUE THREAD

**Issue by SigntriggerLabs** [ansible/awx#13230]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Don't know whether a bug or some simple issue to look at: but I upgraded our AWX from 21.2.0 to 21.6.0 version. 
Now most of the things are okay, except I'm seeing below type error sometimes (it's persistent when trying to open 'cleanup session' management job). 
Similar error is visible sometimes when trying to look for job outputs etc. 
I'm running it on AKS v1.23.8. 

### AWX version

21.6.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Navigate to management jobs and click on 'cleanup expired sessions' followed by clicking on schedule

### Expected results

It should be showing the schedule to edit like other mgmt jobs

### Actual results

shows error

### Additional information

![image](https://user-images.githubusercontent.com/79655350/203815254-93b034cb-d81c-4df0-806b-a6c4591a9a4c.png)

**Comment by shanemcd** [comment]
Does this still happen on the latest version (21.9.0)?

**Comment by akus062381** [comment]
Hi @deep7861,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!

**Comment by SigntriggerLabs** [comment]
Hi, 
My apologies, I missed to update here. 
For the question asked, No, I haven't tested upgrading to 21.9 yet. Jumping from 21.2 to 21.6 itself was not ideal for us since we generally do one minor release upgrade at a time but I jumped couple releases since we were running behind. 
Would there be a way to see why it's happening?
