### ISSUE TITLE
Permit `Thycotic Secret Server` as a selectable credential on a Template

### ISSUE THREAD

**Issue by timothydilbert** [ansible/awx#13354]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

There is an increasing need to be able to pull secrets from a secret store like Thycotic/Delinea Privilege Vault and use them within your playbooks. Currently that is partially covered with the following `lookup` plugin:

https://docs.ansible.com/ansible/latest/collections/community/general/tss_lookup.html

The problem with this approach is that it requires you to either put the Privilege Vault credentials on the INI file on the Ansible server, or pass them in as parameters of the task. 

If we were able to select a `Thycotic Secret Server` credential type and set it on a Template, Ansible would automatically set it as an environment variable, and we would not need to set the same credential in an INI file on the TSS client. This would also be a better UX since the Thycotic Secret Server credential is stored under `Credentials` anyways if you're using it to retrieve secrets for Machine credentials.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

1. Create a new credential of type `Thycotic Secret Server`.
2. Create a new Template in AWX.
3. Within AWX on the `Credentials` field, try to select the credential created in Step 1. It's not possible.

### Current results

Currently, the only available credential types are Amazon Web Services, Google Compute Engine, Microsoft Azure Resource Manager, OpenStack, Red Hat Ansible Automation Platform, Red Hat Satellite 6, Red Hat Virtualisation, VMware vCenter, OpenShift, Network, Machine, and Vault.

### Suggested feature result

Thycotic Secret Server should be one of the options available. Then, lookups should not require us to provide the username/password to authenticate with Thycotic Privilege Vault. Instead, those credentials should automatically be pulled from the credential we passed in via the AWX Template.

**Comment by AlanCoding** [comment]
The "Thycotic Secret Server" credential type, if you view in the API at `/api/v2/credential_types/<N>/`, has a `kind` field of "external". Credentials of the credential type, of this credential kind, can only be used for external secrets lookups. If you want a credential to be used in a job to provide env vars and stuff like that, that would be "cloud" `kind`. You can create a custom credential type to do this:

https://docs.ansible.com/automation-controller/latest/html/userguide/credential_types.html

For technical reasons and separation-of-responsibilities, we do not want to allow credentials to be used in multiple types of contexts. That could get confusing, for one, because a credential could use another credential of the same type to look up a field value, or worse, it could go recursive.

So the solution is to make a new credential type, even if it has the same inputs as the built-in TSS type. Hopefully you can do this with a new custom credential type.

**Comment by timothydilbert** [comment]
Thank you for the response. I haven't tested your solution but it does make sense.

**Comment by Torrent007** [comment]
Hi guys,

My team and I still have a question about the default “Thycotic Secret Server” credential type.
Since it can’t be used directly in a Template, what’s the actual use case for this credential type?

_Just a heads‑up: we’ve only been discovering AWX/AAP for a few weeks now, so we might be missing something obvious ^^_

Thanks!
