### ISSUE TITLE
Error thrown in UI when user clears and edits time field in Schedule form

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#13457]
If a user is creating a schedule with a specific end date, and the user performs a selectAll and clear on the time field, and then manually types the time in, and then tries to save, they get the following error:
![image](https://user-images.githubusercontent.com/63685497/213804836-32ed6ef6-9619-4262-995a-7aea8c54a70a.png)

Note: this problem happens in any date field, not just the end date field.

To reproduce:

- Access an existing job template, and navigate to the Schedules tab of that template
- Click Add
- Enter a name for the schedule
- Leave start date/time as whatever it defaulted to
- Select a frequency for the schedule (I used minute)
- Select end 'on date'
- Leave the defaulted date value alone. In the time box, select all text and hit the backspace button. Now type a manual time in that is some number of minutes after the start time of the schedule.
- Click save. You will see the error.

**Comment by mabashian** [comment]
I did take a look at this and the workaround is pretty straightforward.  A user would need to select one of the dropdown options and modify it rather than wiping the entire string out.  Definitely buggy behavior that should be fixed but not one that renders the form unusable.

**Comment by mabashian** [comment]
I looked a little more into what's going on here and it seems like the problem lies here: https://github.com/ansible/awx/blob/devel/awx/ui/src/components/Schedule/shared/buildRuleObj.js#L121.  The time string that gets passed to this function does not include `AM` or `PM` but I think the function being called expects it to be there.  AM/PM are shown in the interface but I wonder if that's something that Patternfly is doing.  We may be running into some kind of race condition with onChange.

**Comment by mabashian** [comment]
OK I think this actually an issue with the PF component we're using here.  I'm not sure that there's a great way for us to get around it but I'll outline what I think is happening.  If we go and look at an isolated example of the time picker component (outside of AWX): https://www.patternfly.org/v4/components/time-picker/react/basic-12-hour/ the `onChange` function of this component console's out a bunch of values.  If you do something like type in `12:34` (without AM/PM) and hit enter, the component fills in AM/PM for you but the `onChange` function never fires.  From our perspective, the value of that field is still `12:34` but the function that we call to build the date object needs the AM/PM context.  My expectation would be that if the underlying component updates the string that `onChange` is fired so that we can update our internal state.  Maybe someone smarter than me can figure out a workaround here but this smells like buggy behavior in the upstream component to me.

**Comment by akus062381** [comment]
filed bug: https://github.com/patternfly/patternfly-react/issues/8712

**Comment by akus062381** [comment]
patternfly bug was fixed. closing
