### ISSUE TITLE
AWX 21.11.0 error : winrm or requests is not installed: No module named 'winrm'

### ISSUE THREAD

**Issue by clementbey** [ansible/awx#13511]
##### ISSUE TYPE

 - Bug

##### COMPONENT NAME

 - Collection
 - Other

##### SUMMARY

```json
{
  "msg": "winrm or requests is not installed: No module named 'winrm'",
  "_ansible_no_log": false
}
```

##### ENVIRONMENT
* AWX version: 21.11.0
* AWX install method: operator 1.1.4
* AWX deployment target: minikube
* Operating System: Debian 11

##### STEPS TO REPRODUCE
Hello there,
Strange issue.... yesturday (01-02-2023 - 04AM00 Europe/Paris) I used AWX to run playbook on Windows inventory and works, but today (02-02-2023 - 04AM00 Europe/Paris) same playbook failed. No reboot, no config changed, no update/upgrade.
Trying to run playbook on Windows Inventory return : winrm or requests is not installed: No module named 'winrm'

Trying to solve issue :

1. Downgrade to AWX 21.10.2

Trying to downgrade to 21.10.2 
Result : **Always Fail**, same message. Return to 21.11.0

2. Install pywinrm module

On AWX-EE, if I list pip modules, no "pywinrm" are found
```bash
 bash-5.1$  pip list

pytz                               2022.7.1
pyvmomi                            7.0.3
PyYAML                             6.0
requests                           2.27.1
 ```
Trying to install module with `pip install "pywinrm>=0.2.2"` [redhat.com/solutions](https://access.redhat.com/solutions/3356681)
```bash
 bash-5.1$  pip list
pyvmomi                            7.0.3
pywinrm                            0.4.3
PyYAML                             6.0
```
Result : **Always Fail**, same message.

3. Install collection ansible.windows

Trying to install `collection ansible.windows` [https://github.com/ansible-collections/ansible.windows](https://github.com/ansible-collections/ansible.windows)
On AWX-EE : `ansible-galaxy collection install ansible.windows`
Result : **Always Fail**, same message.

More informations :
Inventory Windows "variables" are :
```yml
---

ansible_port : 5986
ansible_connection : winrm
ansible_winrm_server_cert_validation : ignore
ansible_winrm_transport: credssp
```
##### ACTUAL RESULTS

```json
{
  "msg": "winrm or requests is not installed: No module named 'winrm'",
  "_ansible_no_log": false
}
```

With verbosity set to `5 Debug WinRM` :
```json
task path: /runner/project/ping.yml:2
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
fatal: [172.16.19.249]: FAILED! => {
    "msg": "winrm or requests is not installed: No module named 'winrm'"
}
```

##### ADDITIONAL INFORMATION

Trying to follow : 
- https://access.redhat.com/solutions/3356681
- https://github.com/ansible-collections/ansible.windows
- https://github.com/ansible/awx/issues/10109

**Comment by kurokobo** [comment]
@clementbey 
As a workaround, use `quay.io/ansible/awx-ee:21.11.0` as EE instead of `latest` tag.
In these days `awx-ee;latest` has been updated and there are some missing modules/packages:

Related issues:
- https://github.com/ansible/awx-operator/issues/1214
- https://github.com/ansible/awx-ee/issues/161
- https://github.com/ansible/awx-ee/issues/163

**Comment by leetcarey** [comment]
Same Issue here, can no longer manage Window estate AWX 21.5.0

**Comment by clementbey** [comment]
Thanks for reply @kurokobo 
With awx-operator where I can change tag `lastest` value for `quay.io/ansible/awx-ee:21.11.0` ?

**Comment by kurokobo** [comment]
@clementbey 
EE can be changed via AWX UI instead of AWX Operator. Move on to the `Execution Environment` > `AWX EE (latest)` > `Edit` and modify `Image` field.
![image](https://user-images.githubusercontent.com/2920259/216377637-8ced6cd8-4e1a-401b-8012-4989631a0ee6.png)

**Comment by clementbey** [comment]
Very helpfull ! Thanks ! 🥇

**Comment by leetcarey** [comment]
Additional Dependency missing
kerberos: the python kerberos library is not installed

**Comment by shanemcd** [comment]
Tracking that here https://github.com/ansible/awx-ee/issues/166

**Comment by vijayreddiar** [comment]
> @clementbey EE can be changed via AWX UI instead of AWX Operator. Move on to the `Execution Environment` > `AWX EE (latest)` > `Edit` and modify `Image` field. ![image](https://user-images.githubusercontent.com/2920259/216377637-8ced6cd8-4e1a-401b-8012-4989631a0ee6.png)

@kurokobo 
We updated it multiple times, but after a while, this change is automatically rolled back by system. 
How to make this change permanent?

**Comment by kurokobo** [comment]
@vijayreddiar 
In the first place, this issue has been solved in the `latest` image, so I think you can safely use `latest` tag again.

As far as I know there is no such feature to roll the change for EE back, but reconciliation by AWX Operator causes rolling this back. So I guess your AWX Operator frequently tries to reconcile AWX by some reason, such as failure of reconciliation or restart of the pod. You should gather Operator's log and ensure reconciliation loop has been completed (I mean ensure the log ends with `PLAY RECAP` and no further activity).

**Comment by vijayreddiar** [comment]
@kurokobo 

> In the first place, this issue has been solved in the `latest` image, so I think you can safely use `latest` tag again.
> 

I tried using the `latest` and now it results into below error when using _**win_ping**_ module. When I changed it back to `21.11.0`, it works fine.

```
{
  "unreachable": true,
  "msg": "ntlm: unsupported hash type md4",
  "changed": false
}

```
> As far as I know there is no such feature to roll the change for EE back, but reconciliation by AWX Operator causes rolling this back. So I guess your AWX Operator frequently tries to reconcile AWX by some reason, such as failure of reconciliation or restart of the pod. You should gather Operator's log and ensure reconciliation loop has been completed (I mean ensure the log ends with `PLAY RECAP` and no further activity).


I will check this.

**Comment by kurokobo** [comment]
@vijayreddiar 

> ntlm: unsupported hash type md4

There is an open issue for this. See this comment for the workaround that change `ansible_connection` to `psrp`: https://github.com/ansible/awx/issues/13519#issuecomment-1416309784

> I will check this.

If it's difficult to change `ansible_connection` or investigate Operator's log, as a quick workaround, you can add new EE by `Add` button on `Execution Environment` page with tag `quay.io/ansible/awx-ee:21.11.0`, and modify your job to use new EE.

**Comment by vijayreddiar** [comment]
Thanks @kurokobo
The tag `latest` along with `ansible_connection: psrp` solved the problem.

Regarding the reconciliation by AWX Operator, I checked the logs and couldn't find anything suspicious. I used below command to check the logs, hope its the right approach.

`kubectl logs -f -n awx awx-operator-controller-manager-7758c4f45c-d8gvk -c awx-manager`

These are the last lines

```
-------------------------------------------------------------------------------
{"level":"info","ts":1675838305.8406897,"logger":"runner","msg":"Ansible-runner exited successfully","job":"6311528651458026476","name":"awx","namespace":"awx"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=65   changed=0    unreachable=0    failed=0    skipped=43   rescued=0    ignored=0

```

We had to rule out the option of adding new EE because there are ~100 resources covering _job templates_ / _projects_ / _inventory sources_ mapped to **AWX EE (latest)** and updating all of them with new temporary EE will be a cumbersome job.

**Comment by kurokobo** [comment]
@vijayreddiar 

> ```
> {"level":"info","ts":1675838305.8406897,"logger":"runner","msg":"Ansible-runner exited successfully","job":"6311528651458026476","name":"awx","namespace":"awx"}
> ```

Don't worry you've made right approach👍 

The `"ts":1675838305.8406897` indicates that the last reconciliation had been occured at only few hours ago `2023-02-08 06:38:25 (UTC)` (simply `ts` is in Unix Time) and your modification for `AWX EE (latest)` had been rolled back at that time.
If this is unintended behavior for you, this is a bit out-of-scope of this issue, but you shoud make further investigation to understand _how often_ and _why_ those reconciliation happened. 

You can quickly get the history of succeeded reconciliation by Operator by following command. If there are frequently reconciliations, I believe they are not AWX issue but your environment-specific issue.

```bash
kubectl -n awx logs deployments/awx-operator-controller-manager -c awx-manager | grep "Ansible-runner exited successfully" | grep '"name":"awx"'
```

Reconciliation is also triggered by Operator restarts and AWX Pod deletions, so it is good to know the number of Pod restarts.

In any case, anything further would be outside the scope of this issue, so I would recommend asking questions on the mailing list or IRC rather than here: https://github.com/ansible/awx#get-involved

**Comment by vijayreddiar** [comment]
> The "ts":1675838305.8406897 indicates that the last reconciliation had been occured at only few hours ago 2023-02-08 06:38:25 (UTC) (simply ts is in Unix Time) and your modification for AWX EE (latest) had been rolled back at that time.

Between _06:34:32_ and _06:38:09_, I manually made changes in UI, but system didn't perform a rollback for any of this. Actually, system is not rolling back immediately. Sometimes it rolls back after 6 hours, sometimes in 30 minutes and sometimes after a day. There is no definitive pattern.

> Reconciliation is also triggered by Operator restarts and AWX Pod deletions, so it is good to know the number of Pod restarts.

This might be true because **awx-manager** container shows more than double the number of Restart Count compared to all other containers (occurs due to server reboots). However, my change was not rolled back when **awx-manager** was terminated at _2023-02-08 06:36:28 (UTC)_. So, this is still remaining an unknown factor.

> In any case, anything further would be outside the scope of this issue, so I would recommend asking questions on the mailing list or IRC rather than here: https://github.com/ansible/awx#get-involved

Sure, I will take help through other channels.
