### ISSUE TITLE
Workflow Identifier editable in visualizer

### ISSUE THREAD

**Issue by Budd59** [ansible/awx#13571]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Hello,

It is possible to give an identifier different from the unified job template name when using awx.awx.workflow_job_template_node.

It should be possible to write it in the visualiser too.

Best Regards

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Create a template name "test"
Create a workflow and add a node

### Current results

You can select the template test, but you can't choose the identifier name.

### Sugested feature result

After selecting the template, a survey should be proposed to give an identifier name.

**Comment by mabashian** [comment]
In the UI you can add an alias to the node in a field below the list of resources in the first step of adding/editing a node:

<img width="1433" alt="Screen Shot 2023-02-15 at 11 04 45 AM" src="https://user-images.githubusercontent.com/9889020/219083689-6a24cd05-1c5d-434c-8f8c-f51b48b5bd0f.png">

That alias will be shown on the node instead of the resource name when set.

I can't speak to the awx cli though.

**Comment by fosterseth** [comment]
in collection you can also set the identifier field
https://docs.ansible.com/ansible/latest/collections/awx/awx/workflow_job_template_node_module.html#parameter-identifier

**Comment by Budd59** [comment]
Oh ok ! It was hidden on my page ! I haven't seen that it was possible to scroll.
Thank you !
