### ISSUE TITLE
[constructed-inventory] fact caching for constructed inventory hosts

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#13601]
for normal inventory when a playbook is run against the host we give the ability to cache "ansible facts" gather during the playbook execution 

for host in constructed inventory we will still allow this behavior 

context:
- host in constructed inventory can belong to multiple "input inventory" 
- we need to provide linkage between host in constructed inventory to the "source inventory" that the host came from (to store facts)

initial proposal is to use a hostvar in the constructed inventory host to denote the linkage

**Comment by AlanCoding** [comment]
I'm going to try to write a use story in painful detail so that I can give a specific work list after that.

User goes to create a constructed inventory, and in doing so, puts in multiple input inventories. The old "smart" inventory allowed filtering on ansible_facts efficiently. Constructed inventory _should_ also allow the same thing, but doesn't yet, and this is an inarguable goal of this. So with the constructed inventory created, it updates the related auto-created constructed inventory source, and in doing so, it writes all input inventories to disk. **First point** we need to serialize the input inventory facts as we serialize the input inventory scripts in preparation for the constructed inventory update. This needs corresponding examples to demonstrate parity with old smart inventories.

From there, we have a constructed inventory with groups / hosts populated. Now we associate that constructed inventory with a job template. Run that job template, that will happen in another EE (for the job), but before that _the constructed inventory_ is serialized for use by `ansible-playbook` and at that time, the facts also need to be serialized along-side of the inventory script (for the constructed inventory). This is complicated by the problem you mention, so we will mark this as **second point** because we need to obtain facts from the source inventory (for reasons that will become clear later).

Now the job finishes and we _save updated facts_ and that needs to apply to the same hosts we got the facts from - the source host. This is fairly well identifiable as the **third point** which is that we need to save gathered facts from jobs to the source inventory. Why? Continue user stories.

Now another unrelated JT runs against a single one of the _input inventories_. In the third point, we must assume that the facts changed, and that everything operating on source hosts need these updates. This part of the user story is justification for _why_ we need to get facts from source hosts & save facts to source hosts - unless someone else has any other bright ideas for this.

So re-summarize

 - ~[ ] serialize facts for constructed inventory update~ --> separate issue
 - [ ] adjust how facts are serialized for job runs, if that job run is against a constructed inventory, so that it (presumably, implementation detail) gets facts from the source host
 - [ ] adjust how facts are updated (on Host model) at the end of a job when that job is a constructed inventory, again presumably following the same logic of deferring back to the source host

The first point is easy and should be accomplished quickly and easily. This will tie-into documented usage examples. The second and third points are technically complicated because of performance when large inventories are involved.

**Comment by AlanCoding** [comment]
Breaking out first point into another issue at https://github.com/ansible/awx/issues/13673

**Comment by AlanCoding** [comment]
The change at https://github.com/ansible/awx/pull/13718 is intended to addressed the 2 un-checked boxes described in my prior comment.
