### ISSUE TITLE
Task output is cut when the output is too long

### ISSUE THREAD

**Issue by balpert89** [ansible/awx#139]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

When a failed task is sufficiently long it is cut out from the ansible task output pane. This way it is hard to determine the error as seen here:

![image](https://user-images.githubusercontent.com/28100685/30338178-fe17e214-97ea-11e7-8dbe-b69ad826b94a.png)

##### STEPS TO REPRODUCE

Create a task that - if it fails - has a very verbose output. The output will be cut.

##### EXPECTED RESULTS

The full output of a failed task.

##### ACTUAL RESULTS

A cut output of a failed task.

##### ADDITIONAL INFORMATION

On a side note, is it possible to look at the ansible logs? On my local ansible machine I enabled logs, but overriding the original ansible.cfg or supplying one in my git repository does not activate the ansible logs.

**Comment by jlmitch5** [comment]
@balpert89 thanks for filing this issue!

Standard out output is capped by the API for storage and performance reasons.  We probably won't change the fact that lines are capped at a certain number of characters because of these reasons.

That being said, you bring up a valid point that line 36 of your output is not useful in and of itself.  If you click the line of output you _should_ be able to gather context about the error from the modal that pops up.  Please let me know if that doesn't work/the modal isn't useful either.  Screenshots are very helpful.

**Comment by matburt** [comment]
Dramatic improvements are also planned for our next major Tower release, so you'll see those changes in awx first. I'm going to close this one given @jlmitch5's comment and that this is going to be an active area of development.
