### ISSUE TITLE
[hop node] prevent instance from peering to self

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#13908]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

we should disallow instance from peering to itself.

e.g. on instance "hop" can add `peers: ["hop"]` through api.

We can prevent this by adding validation to django InstanceLink model or the instance `peers` serializer

### AWX version

22.0.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

on instance `hop` peer to `hop`

### Expected results

validation error

### Actual results

no validation error

**Comment by tanganellilore** [comment]
Hi @fosterseth ,

as you can see in my [PR](https://github.com/ansible/awx/pull/13907), this was included on InstanceLink model.

Please reach me and @TheRealHaoLiu on matrix, we can discuss this PR because I added also the UI part with new API for peer.
I also merged the feature-hope_node in my PR to be aligned

**Comment by fosterseth** [comment]
solved with https://github.com/ansible/awx/pull/13916
