### ISSUE TITLE
Link to docs in UI's Help Button needs to go to the AWX docs

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#14699]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The Help button link on the AWX UI currently goes to the controller docs. It needs to be re-addressed to the new AWX docs URL instead: https://ansible.readthedocs.io/projects/awx/en/latest/userguide/index.html

### AWX version

latest

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

MacOS

### Web browser

Chrome

### Steps to reproduce

1. Run an instance of AWX and log in with your credentials.
2. At the top of the screen, click (?) drop-down menu and select **Help**.
3. The controller docs open.

### Expected results

Help needs to go to: https://ansible.readthedocs.io/projects/awx/en/latest/userguide/index.html

### Actual results

Help goes to: https://docs.ansible.com/automation-controller/latest/html/userguide/index.html

### Additional information

Location of the Help button:
![image](https://github.com/ansible/awx/assets/7514801/d13227dc-68e0-4c75-a3ee-85878cdf4a89)

**Comment by airtonbjunior** [comment]
Hi, @tvo318! I would like to add some details about the issue

The AWX documentation page does not have a version selector, it always redirects to the latest version (and to the english version). It's important that it also works when the documentation page is versioned in the future, similar to the ansible doc.

![image](https://github.com/ansible/awx/assets/2206414/73c2e18f-cb1b-4e9b-adb6-418acf88209f)

![image](https://github.com/ansible/awx/assets/2206414/c3035653-c37d-4fc5-8b05-f7a2ac3b981f)

The funcion `getDocsBaseUrl` in `getDocsBaseUrl.js` return the base url to the documentation page. Specifically about the help button, the function is used in the file `PageHeaderToolbar.js`, line 113: 

`href={${getDocsBaseUrl(config)}/html/userguide/index.html}`

One possible solution is create a new function (or change the `getDocsBaseUrl`**¹**) to return the new baseUrl and keep the conditional, returning 
`https://ansible.readthedocs.io/projects/awx/en/${version}` 
instead of 
`https://docs.ansible.com/automation-controller/${version}`

It might be interesting to also create another variable to control the documentation language for future updates, returning something like 
`https://ansible.readthedocs.io/projects/awx/${language}/${version}`



**¹**It is important to consider that this function is called on 32 different files to provide links to the ansible documentation.

**Comment by tvo318** [comment]
@airtonbjunior, we decided to only support latest. Let's move your suggestion to the [Forum](https://forum.ansible.com/tag/documentation) and see whether we can get some discussion going and feedback on this topic.

**Comment by kurokobo** [comment]
@tvo318 
Hi, I found the HELP button on the API page is not working as well. 
Currently this is the link for `https://docs.ansible.com/ansible-tower/23.8.1/html/towerapi/index.html` which is 404.

![image](https://github.com/ansible/awx/assets/2920259/afd02c1f-d99e-4e62-8e28-8b51e9ed4869)

**Comment by kurokobo** [comment]
This is completely out-of-topic but the copyright at the bottom of the page above is still in `2021`, should it be released year of the version?
