### ISSUE TITLE
Credentials removed when workflow node when edge type changed

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#1481]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
`/api/v2/workflow_job_template_nodes/:id/credentials` gets reverted back to an empty array when the user changes the node from failure->success.  I suspect that this happens no matter what you change the edge type to but I haven't tested all the cases.

##### ENVIRONMENT
* AWX version: 1.0.4.64

##### STEPS TO REPRODUCE

1) Create a Job Template and select PROMPT ON LAUNCH for credentials
2) Create a Workflow
3) Add a root node (the details of this node are not important)
4) Add a on failure child node extending from the root using the template created in step 1 and select some additional credentials when creating the node.  (this will cause `/api/v2/workflow_job_template_nodes/:id/credentials` to be populated)

The workflow should look like:

<img width="1355" alt="screen shot 2018-03-08 at 3 29 23 pm" src="https://user-images.githubusercontent.com/9889020/37174758-86fd00d4-22e5-11e8-98f7-0abc7629447e.png">

5) Change the edge type of the child node from On Failure to On Success -> this is where the credentials seem to get wiped.

In the UI, the following requests are made:

1) POST - `/api/v2/workflow_job_template_nodes/:id/failure_nodes/` with the payload `{id: 2, disassociate: true}`
2) PUT - `/api/v2/workflow_job_template_nodes/:id/` with whatever the node overrides are (this step is only necessary if the user has _changed_ something in the prompt modal but we make the request every time)
3) POST - `/api/v2/workflow_job_template_nodes/:id/success_nodes/` with the payload `{id: 2}`

##### EXPECTED RESULTS

Expected contents of `/api/v2/workflow_job_template_nodes/:id/credentials` to remain the same while POSTing to the different node buckets.

##### ACTUAL RESULTS

`/api/v2/workflow_job_template_nodes/:id/credentials` returns empty array after POSTing to the different node buckets.

The UI for this workflow node prompting is currently in a local branch but I expect to have a PR up in the next 24 hours or so than can be used for testing.  This could be reproduced through the API browser though with enough effort.

**Comment by AlanCoding** [comment]
I believe I've reproduced. It's because of the PUT, and the code for managing the deprecated `credential` field. It looks like it's removing the related credential even when you give a pk value for it inside of the PUT.

> Add a on failure child node extending from the root using the template created in step 1 and select some additional credentials when creating the node. 

Could you tell me what type of credentials you attached? I think I see where the breakdown is happening.

The prior behavior of the `credential` field was that it only accepted SSH credentials. So that's still true now. However, I neglected to validate the type of it when adding it. You can add a cloud credential with that field, but when you PUT/PATCH with a null credential, it removes all the SSH credentials.

This would be fundamentally incompatible with the use of multiple SSH credentials, but this shouldn't be possible yet anyway.

Could you also inspect the data when doing the PUT? If you only attached cloud credentials, then it should be null. Right now I can't quite find a problem with that in my own testing. If I PATCH with a null credential field, the related cloud credentials remain. But there are probably more details of your particular case that I'm not including.
