### ISSUE TITLE
Upstream `uwsgi` does not respond

### ISSUE THREAD

**Issue by soumikgh** [ansible/awx#1488]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Upstream `uwsgi` does not respond. The web interface intermittently gives 502 errors and awx_web says `no live upstreams while connecting to upstream, client: X.X.X.X, server: _, request: "GET /", upstream: "uwsgi://uwsgi`. This is on a fresh install using docker-compose.

##### ENVIRONMENT
* AWX version: 1.0.4.62
* AWX install method: Docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu 16.04
* Web Browser: Mozilla Firefox 58.0.2

##### STEPS TO REPRODUCE

Standard install using docker compose.

##### EXPECTED RESULTS

Pages and the API loading properly.

##### ACTUAL RESULTS

UI gives errors like - `Invalid search term entered. GET returned: 502`
Or just times out with 502 Bad Gateway.

##### ADDITIONAL INFORMATION

Sample log from awx_web -
```[pid: 30|app: 0|req: 62/130] 192.168.2.6 () {26 vars in 261 bytes} [Thu Mar  8 22:03:45 2018] GET / => generated 0 bytes in 38 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
192.168.2.6 - - [08/Mar/2018:22:03:46 +0000] "GET /" 502 173 "-" "-"
2018/03/08 22:03:50 [error] 25#0: *329 no live upstreams while connecting to upstream, client: 192.168.2.6, server: _, request: "GET /", upstream: "uwsgi://uwsgi"
192.168.2.6 - - [08/Mar/2018:22:03:50 +0000] "GET /" 502 173 "-" "-"
2018/03/08 22:03:55 [error] 25#0: *330 no live upstreams while connecting to upstream, client: 192.168.2.6, server: _, request: "GET /", upstream: "uwsgi://uwsgi"
192.168.2.6 - - [08/Mar/2018:22:03:55 +0000] "GET /" 502 173 "-" "-"
2018-03-08 22:04:00,898 ERROR    django.security.DisallowedHost Invalid HTTP_HOST header: u'_:8052'. The domain name provided is not valid according to RFC 1034/1035.
2018-03-08 22:04:00,906 ERROR    django.request Internal Server Error: /
```

**Comment by matburt** [comment]
I'm trying to figure out what this is about:

```
django.security.DisallowedHost Invalid HTTP_HOST header: u'_:8052'. The domain name provided is not valid according to RFC 1034/1035.
```

Do you have an upstream proxy or load balancer that's setting something wonky? Have you made any changes to the nginx configuration?

**Comment by soumikgh** [comment]
Everything is behind a F5 load balancer, but even without that, when accessed from within the internal network, it still gives 502s.

No changes in nginx config, I've done fresh pulls and `--force-recreate` multiple times.

**Comment by matburt** [comment]
Not sure what's up then, and I can't reproduce that. We'd need more information on how `HTTP_HOST` is getting set to something that doesn't look like a remote address.

**Comment by soumikgh** [comment]
From what I can fathom, the nginx catch-all server name is _, and it's binding to port 8052, and somehow this is getting passed as the HTTP_HOST. I did a tcpdump and nothing seems out of the ordinary.

**Comment by soumikgh** [comment]
I fixed this by hardcoding the server_name to the hostname.

**Comment by bain2236** [comment]
which server name to which hostname?

**Comment by omgjlk** [comment]
I just ran into this myself when attempting to put AWX behind a load balancer. The load balancer was not sending a `Host` header with the health check request which was causing a fall through to the [hard coded server_name](https://github.com/ansible/awx/blob/devel/tools/docker-compose/nginx.vh.default.conf#L20) (also [here](https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/nginx.conf.j2#L60). I believe it's these configs that cause Django to get a host header of `_` which leads to the error:

`ERROR    django.security.DisallowedHost Invalid HTTP_HOST header: '_:8052'. The domain name provided is not valid according to RFC 1034/1035.`

I've since set my load balancer to include a `Host` header when it performs the health check so I no longer get these errors, but it would be good if the hard coded configs do not leave this pitfall in place.
