### ISSUE TITLE
Drive job and list updates via websockets, not REST calls

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1611]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Many places in the UI we trigger UI updates via websockets... that are done by making REST calls back to the API.

Examples:
- dashboard
- templates list
- jobs list

This is due to not having sufficient information in the socket message itself to do the UI update.

We should fix that. 

(Imagine the case where you have 100 jobs start in quick succession, 5 people with AWX tabs open, and now you get 500+ API queries.)

##### ENVIRONMENT
* AWX version: any

**Comment by mabashian** [comment]
Attempt at an exhaustive list of places where the UI leverages sockets to update a view:

1) Jobs List
2) Templates Jobs List
3) My View Jobs
4) Inventory Jobs List
5) Dashboard Jobs List
6) Instance Groups Jobs List
7) Templates List
8) Project Templates List
9) Dashboard Templates List
10) Org Templates List
11) Inventories List
12) Inventory Sources List
13) Job Results
14) Workflow Results
15) Project List
16) Org Project List

In almost all cases the UI subscribes to jobs -> status_changed and uses messages from that channel to trigger GET requests to re-fetch the list data.  The job results page is slightly more complicated since it gets output messages directly via sockets.  I don't see this work having a major impact on the job output page but will definitely impact the above lists in a significant way.

**Comment by mabashian** [comment]
Note that making these changes will most likely allow us to remove the `working...` spinner from these lists (since we won't need GET requests anymore).  The e2e tests rely on these spinners in some places so we might have to spend some time cleaning up a few tests as a result of these changes.

**Comment by unlikelyzero** [comment]
@mabashian was this addressed in our rewrite?
