### ISSUE TITLE
When using workflows if a template has extra vars set for prompt on launch then should be able to pre-specify as part of workflow creation

### ISSUE THREAD

**Issue by itewk** [ansible/awx#1686]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When using workflows if a template has extra vars set for prompt on launch then should be able to pre-specify as part of workflow creation

##### ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
1. create a template and mark the extra vars as "prompt on launch"
2. create a workflow template
3. add the template with the "prompt on launch" extra vars to the workflow

##### EXPECTED RESULTS
Should be able to specify the extra vars for the template when adding it to the workflow.

##### ACTUAL RESULTS
No way to specify the extra vars when adding the template to the workflow.

##### ADDITIONAL INFORMATION
If you mark the inventory or credential as "prompt on launch" then when adding the template to the workflow you can pre-select the correct inventory and credential, the same should hold true for the extra vars.

**Comment by mabashian** [comment]
@itewk this functionality was added with https://github.com/ansible/awx/pull/1489.  There have been some bugs fixed/reported since that initial feature landed but we're working to get all that cleaned up.  The original issue is https://github.com/ansible/awx/issues/169.  I'm going to close this as a duplicate.
