### ISSUE TITLE
Previously completed SCM Update jobs show blank standard output

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#1692]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

The Standard Out section for a completed job isn't displaying any logs.

##### ENVIRONMENT
* AWX version: 1.0.4.130
* AWX install method: kubernetes
* Ansible version:  2.4.0.0
* Operating System: Oracle Enterprise Linux 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Go to Jobs -> click on a completed job of SCM Update type

##### EXPECTED RESULTS

The Standard Out section should display the logs of the run.

##### ACTUAL RESULTS

The Standard Out section is blank.

##### ADDITIONAL INFORMATION

This works in AWX 1.0.4.109. So probably some recent changes broke this feature. For some job types such as Playbook Run, the Standard Out is fine.

**Comment by OsirisS13** [comment]
Hi @shen3lu4 is your output on SCM update similar to this, with placeholders been shown under results instead of any actual information, and does your SCM update job fail?:

![image](https://user-images.githubusercontent.com/2848618/38023276-be719f18-3279-11e8-8be9-2dd2c47d1b08.png)

If so the exact same thing is happening to me, I've just installed AWX for the first time yesterday and have been ripping my hair out trying to get SCM working....

ENVIRONMENT
AWX install method: docker
Operating System: Centos 7.4
Web Browser: Chrome

**Comment by shen3lu4** [comment]
No, mine was not like yours. First of all the SCM update was successful.
For a currently running job everything looked fine. It only had issue for a
previous job that the Standard Out section was blank. The Results section
was ok (no placeholders).

Suggest you try an older image like 1.0.4.109 and see what happens. Based
on my experience, newer images are error prone.

**Comment by jakemcdermott** [comment]
Hello @shen3lu4, 

Thanks for reaching out. This seems to be the same issue described here: https://github.com/ansible/awx/issues/1687 and here: https://github.com/ansible/awx/issues/1700 so I am closing. 

You should see that this is resolved in the latest 1.0.5 container image
