### ISSUE TITLE
AWX Admin Application doesn't have permission to launch template from REST API

### ISSUE THREAD

**Issue by raghavs1108** [ansible/awx#1716]
ISSUE TYPE: Bug
COMPONENT NAME: API

SUMMARY: 
POST request to http://<server-ip>/api/v2/job_templates/<template_id>/launch/
responds with
{
    "detail": "You do not have permission to perform this action."
}, but
GET request to http://<server-ip>/api/v2/job_templates/<template_id>/launch/
Succeeds, and responds back with the template details.

ENVIRONMENT
* AWX version: 1.0.5.19
* AWX install method: docker for linux
* Ansible version:  2.5.0
* Operating System: Centos 7
* Web Browser: POSTMAN Request

STEPS TO REPRODUCE
1. Create Application in AWX
2. Follow https://github.com/ansible/awx/blob/ac70945071bec9bb1cfdfed328c13c3b2d1fbd39/docs/auth/oauth.md to create a new Auth Token, and bind it to the application.
3. Ensure that the token has write permissions
4. Fire a GET request to http://<server-ip>/api/v2/job_templates/<template_id>/launch/, to confirm that the access has been granted.
5. Fire a POST request to http://<server-ip>/api/v2/job_templates/<template_id>/launch/

EXPECTED RESULTS
Job gets invoked.
ACTUAL RESULTS
403 Forbidden: 
{
    "detail": "You do not have permission to perform this action."
}

**Comment by scottlackey** [comment]
@raghavs1108 You might just be using a read token instead of a write token, which you will need in order to call those templates.
If you create an application with "password" grant type in the API console, and
If you generate a token on that application that has "password" grant type with something like:

`curl -sX POST -d "grant_type=password&username=admin&password=<password>&scope=write" -u "<someclientid>:<someclientsecret>" http://mydomain.com/api/o/token/ -i | grep token`
you should be able to
`curl -H "Authorization: Bearer <token>" -X POST http://mydomain/api/v2/job_templates/<template_id>/launch/`

**Comment by rooftopcellist** [comment]
@raghavs1108 Did that fix your issue?  I can run jobs with a write scoped application token on my machine.  I am going to close this for now, but if you are still experiencing this issue I can reopen.

**Comment by m4rphel** [comment]
I´m facing the same issue as @raghavs1108 

>You might just be using a read token instead of a write token

On creating my token I chose "Write" for the scope value. Is this not sufficient?

Or are the tokens, which are created in the User Area of AWX UI, not valid to do such api calls?
