### ISSUE TITLE
Backing up and restoring AWX

### ISSUE THREAD

**Issue by vab2048** [ansible/awx#1745]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY
Currently the [documentation](http://docs.ansible.com/ansible-tower/latest/html/administration/backup_restore.html) for tower's backup and restore feature says to use a script `setup.sh` but it is not clear where that script when using AWX.

Please can documentation be provided for backing up and restoring an AWX instance.

**Comment by ryanpetrello** [comment]
@vab2048 the documentation you're referencing is specific to Tower, which is not currently container based like awx; the `setup.sh` script referenced in the documentation does not exist in the awx source because it just plain _doesn't work_ with awx due to differences in deployment strategy.

A new feature recently landed in https://github.com/ansible/tower-cli which might interest you.  It allows you to export and import resources from Tower/awx installs via the awx API:

https://github.com/ansible/tower-cli/pull/479/files#diff-ee3cb42ee3fe998d33ffb7884ad48765R71

**Comment by pkaramol** [comment]
So currently the only way for taking a backup for `awx` is via `tower-cli` and the resources export / import functionality?

Running a `pg_dumpall` against the `postgres` container and restoring by importing this dump should work or not?

**Comment by matburt** [comment]
the cli-based backup/restore is meant to aid updgrades and migrations to new versions. Normal backup/restore for same-version will work fine.

**Comment by pkaramol** [comment]
@matburt thanks!

However in the [documentation](https://tower-cli.readthedocs.io/en/latest/) there is no mention of a complete system backup/restore process.

Is the only way around this to do this one resource at a time? (i.e. exporting all templates and then importing them and so on?)

**Comment by decentral1se** [comment]
For anyone looking for a DIY upgrade path solution, it seems the two best reads are:

  * https://github.com/ansible/tower-cli/pull/479
  * https://groups.google.com/forum/#!topic/awx-project/is60aeikbVs
