### ISSUE TITLE
/var/lib/awx/job_status - not present ?

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1785]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

 - Installer

##### SUMMARY
/var/lib/awx/job_status - not created ? Has there been some change as to where job_status info goes ?

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: rhel 7.4
* Web Browser: chrome

##### STEPS TO REPRODUCE
in awx_task container -

ls -la
total 52
drwxrwxr-x  6 root root   199 Apr 19 13:58 .
drwxr-xr-x 16 root root   202 Mar 28 08:21 ..
drwx------  3 root root    17 Apr 19 13:58 .ansible
-rw-r--r--  1 root root 16384 Apr 19 14:09 beat.db
-rw-r--r--  1 root root    40 Mar 28 08:44 .configsha
-rw-r--r--  1 root root 15086 Mar 27 10:39 favicon.ico
drwxr-xr-x  3 root root    53 Apr 19 14:04 projects
drwxrwxr-x  3 root root    20 Mar 28 08:06 public
-rw-r--r--  1 root root  1263 Mar 28 08:43 supervisord.log
-rw-r--r--  1 root root     4 Mar 28 08:43 supervisord.pid
-rw-r--r--  1 root root     9 Mar 28 08:34 .tower_version
drwxr-xr-x  4 root root    32 Mar 28 08:24 venv
-rw-r--r--  1 root root   200 Mar 27 10:39 wsgi.py

##### EXPECTED RESULTS

job_status dir listed as well

##### ACTUAL RESULTS

see summary

##### ADDITIONAL INFORMATION

was present in 1.0.1 - done a search but can't find anything obvious to it being removed / changed.

**Comment by ryanpetrello** [comment]
@akcrisp this is a result of a notable change in job stdout generation and storage in newer versions of awx that resolves a variety of bugs and performance issues.

`/var/lib/awx/job_status/` _no longer_ stores persistent copies of stdout for jobs due to the changes in https://github.com/ansible/awx/pull/833/

Older versions of awx would actually write stdout to the file system, but in clustered environments, the file wasn't present on _all_ file systems across the cluster (only on the file system where the job actually _ran_), resulting in the issues described in https://github.com/ansible/awx/issues/200

Now when you download stdout for a job (e.g., in the Job Detail UI), it's generated _on the fly_ from event data that lives in the database.  You can fetch the stdout for any job via the API:

```
curl -O https://user:pass@tower.example.org/api/v2/jobs/N/stdout/?format=txt_download
```

**Comment by akcrisp** [comment]
great stuff thanks for the info
