### ISSUE TITLE
Prompt password on launch doesn't work

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#181]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Prompt password on launch doesn't work

##### STEPS TO REPRODUCE

1-Configure a simple project, like this:
```
---
 - hosts: all

   tasks:
   - ping:
```
2-Configure a credential, using credential tipe "Machine" and "Prompt on launch" selected.

3-Configure a simple repository with a machine

4-Configure a template job using all that you've created before

5-Run your job template

##### EXPECTED RESULTS

When I run a template job, the UI ask my password

##### ACTUAL RESULTS

UI simple freezy on "working..."

##### ADDITIONAL INFORMATION

```
"Firefox console output is above:"
19:04:10.859 "Error: data.passwords_needed_to_start.includes is not a function
exports.default</$scope.init/<@http://10.128.0.15/static/js/app.d44f2b2bc431d0b4cea3.js:404:909963
$http/promise.success/<@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:85081
processQueue@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:117543
scheduleProcessQueue/<@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:117810
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:130726
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:128522
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:131153
done@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:85804
completeRequest@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:89746
createHttpBackend/</xhr.onload@http://10.128.0.15/static/js/vendor.d44f2b2bc431d0b4cea3.js:438:90678
"1 vendor.d44f2b2bc431d0b4cea3.js:438:104482
consoleLog/<() vendor.d44f2b2bc431d0b4cea3.js:438
$ExceptionHandlerProvider/this.$get</<() vendor.d44f2b2bc431d0b4cea3.js:438
processQueue() vendor.d44f2b2bc431d0b4cea3.js:438
scheduleProcessQueue/<() vendor.d44f2b2bc431d0b4cea3.js:438
$RootScopeProvider/this.$get</Scope.prototype.$eval() vendor.d44f2b2bc431d0b4cea3.js:438
$RootScopeProvider/this.$get</Scope.prototype.$digest() vendor.d44f2b2bc431d0b4cea3.js:438
$RootScopeProvider/this.$get</Scope.prototype.$apply() vendor.d44f2b2bc431d0b4cea3.js:438
done() vendor.d44f2b2bc431d0b4cea3.js:438
completeRequest() vendor.d44f2b2bc431d0b4cea3.js:438
createHttpBackend/</xhr.onload() vendor.d44f2b2bc431d0b4cea3.js:438
```

**Comment by gconsidine** [comment]
Thanks for filing this issue, @Zokormazo. Since `includes` is valid (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) but not fully adopted across browsers, I want to add a polyfill at the build level as a fix.

What version of Firefox are you using? The MDN link above indicates `includes` is supported in Firefox versions >= 43.

**Comment by Zokormazo** [comment]
Oh, then my PR has no sense, better going with the polyfill

**Comment by gconsidine** [comment]
The release date of Firefox 42 (the version just before `includes` was implemented) was 2015-11-03, so definitely recent enough for it to be an issue.

If you're looking to try it out sooner, it could be as simple as adding [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) as a dev dependency and including it as the first require in the [vendor entry file](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/vendor.js). Otherwise, I should be able to get a fix in for this Monday sometime.

Thanks again the info and for being proactive with your earlier PR.

**Comment by Zokormazo** [comment]
I tried your suggestion

```
diff --git a/awx/ui/client/src/vendor.js b/awx/ui/client/src/vendor.js
index 8f616f8b7..a1eabd7ad 100644
--- a/awx/ui/client/src/vendor.js
+++ b/awx/ui/client/src/vendor.js
@@ -1,3 +1,4 @@
+require('babel-polyfill');
 require('@assets/custom-theme/jquery-ui-1.10.3.custom.min.css');
 require('@assets/ansible-bootstrap.min.css');
 require('@assets/fontcustom/fontcustom.css');
diff --git a/awx/ui/package.json b/awx/ui/package.json
index 8744e3abe..fb8667391 100644
--- a/awx/ui/package.json
+++ b/awx/ui/package.json
@@ -105,6 +105,7 @@
     "angular-scheduler": "git+https://git@github.com/ansible/angular-scheduler#0.1.1",
     "angular-tz-extensions": "git+https://git@github.com/ansible/angular-tz-extensions#0.3.13",
     "angular-ui-router": "1.0.0-beta.3",
+    "babel-polyfill": "^6.26.0",
     "bootstrap": "^3.3.7",
     "bootstrap-datepicker": "^1.7.1",
     "codemirror": "^5.17.0",
```

but it didn't work:

![console](https://user-images.githubusercontent.com/1447328/30519721-8566a56a-9b9d-11e7-862a-a4533ec40f67.png)

I moved babel-polyfill to dependency instead of dev dependency as suggested in https://babeljs.io/docs/usage/polyfill/ and moved babel-polyfill to last entry on vendor.js to not interfere with other requirements and now it works.

I need some testing with oldie browsers. https://github.com/Zokormazo/awx/commit/d2c48c2e92907e9ce64ec34bce71a5afe4dd692b

**Comment by gconsidine** [comment]
Nicely done, @Zokormazo! I'll check this out tomorrow morning.

**Comment by gconsidine** [comment]
Looks like it's not going to be as straightforward as I'd hoped. babel-polyfill uses a function called `define` which conflicts with the build setting `define` to false to avoid modules from being imported AMD style. I'll spend some more time on this today.

**Comment by Zokormazo** [comment]
For just includes() we could maintain own polyfill function file, but it will be a nightmare if we have to support more polyfills

**Comment by gconsidine** [comment]
Hey @Zokormazo, it's looking like we might only target what [browserlist](https://github.com/ai/browserslist) refers to as the 'last 2 versions'.  `babel-preset-env`'s options in Webpack will add the necessary polyfills for us. I'm making some tweaks to the Webpack configuration now.

**Comment by lucaslan** [comment]
Hello, Only for documentation:

I tested on firefox 39.0.3, google chrome 60.0.3112.113 and IE 11.0.9600.18763 running on windows 8 and I had this issue in all of them.

**Comment by gconsidine** [comment]
Cool, thanks for relaying that info @lucaslan. I'll link to a PR I'm about to open that includes support for the "last 2 versions" I mentioned in an earlier comment. IE 10 and Chrome should be all good afterward, but Firefox 39 will probably stay wonky.

**Comment by gconsidine** [comment]
Polyfills added to support the last 2 releases of browsers in #212. Thanks for the help @lucaslan and @Zokormazo!
