### ISSUE TITLE
RFE: Make the JSON output for the stdout endpoint easier to digest

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#1863]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
When pulling the JSON output from the /api/v2/jobs/<ID>/stdout endpoint, it appears in a large text blob contained inside a content with what looks like HTML as well. It would nice if this was formatted more cleanly so its easier to parse for facts.

##### ADDITIONAL INFORMATION
Example of current output:
```
{"content":"<span class=\"ansi31\"> [ERROR]:</span>\r\n<span class=\"ansi31\"></span>\r\n\r\nPLAY [Hello World Sample] ******************************************************\r\n\r\nTASK [Gathering Facts] *********************************************************\r\n<span class=\"ansi32\">ok: [localhost]</span>\r\n\r\nTASK [Hello Message] ***********************************************************\r\n<span class=\"ansi32\">ok: [localhost] =&gt; {</span>\r\n<span class=\"ansi32\">    \"msg\": \"Hello World!\"</span>\r\n<span class=\"ansi32\">}</span>\r\n\r\nPLAY RECAP *********************************************************************\r\n<span class=\"ansi32\">localhost</span>                  : <span class=\"ansi32\">ok=2   </span> changed=0    unreachable=0    failed=0   \r\n\r\n","range":{"start":0,"end":17,"absolute_end":17}}
```
Example of desired output:
```
{content: {
  machine1: {
    task1: {
      metadata: {some_metadata},
      output: {actual_task_output}},
    task2: {
      metadata: {some_metadata},
      output: {actual_task_output}}
  },
  machine2: {
    task1: {
      metadata: {some_metadata},
      output: {actual_task_output}},
    task2: {
      metadata: {some_metadata},
      output: {actual_task_output}}
}}
```

**Comment by wenottingham** [comment]
What version is this?

**Comment by wenottingham** [comment]
We would not change to the 'desired output'... if you want something like that, parse the events yourself.

But there shouldn't be HTML in the output - that's a bug.

**Comment by jpaulovic** [comment]
version: Ansible Tower 3.2.2

wrt the "desired output", that's more of an RFE than a bug. The currently provided output doesn't provide any added value (considering it also contains the HTML bug) in comparison with using a call to <tower_url>/api/v2/jobs/123/stdout?format=txt_download
as the json is _technically_ valid, but virtually unusable (and harder to parse than the raw text output).

**Comment by ryanpetrello** [comment]
@jpaulovic I'll echo what @wenottingham said; the embedded HTML _is_ a bug we intend to fix in the near future, but we're not likely to do much here beyond that.

The JSON format _does_ return line start and ending numbers in addition to the `content`, but you're right in saying that there's not additional event metadata that's returned in the JSON format - it's _mostly_ just the same stdout you get with `?format=txt`.  We likely _won't_ expand on that for this endpoint, because:

- it's hard to say for sure what format people will actually want, what type of data they'll care about, so we'll have to add formatting customization, etc...
- awx _already has_ an API that returns metadata in JSON format about the events that ansible emits through its callback plugin interface:

`/api/v2/jobs/N/job_events/`

This API can be used to fetch event details and build exactly the data structure _you_ care about.

**Comment by ryanpetrello** [comment]
Closing via https://github.com/ansible/awx/commit/53ef9ed28895d04e9cc96fb801001ef335ef94fe
