### ISSUE TITLE
Improve local logging from AWX

### ISSUE THREAD

**Issue by ewortzman** [ansible/awx#1874]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

All

##### SUMMARY

Improve local logging.

##### ADDITIONAL INFORMATION

Currently, AWX doesn't seem to produce any useful local log files.  There are a number of options for log aggregators, but all (obviously) require setting up an external system to gather the logs.  It would be nice if AWX produced local log files that can be viewed without the need to set up a log aggregator.

According to the official Ansible Tower documentation, logs are written to `/var/log/tower`.  However, That directory inside all of the docker containers created by the awx installer is empty.

I've also executed `docker logs -f awx_task`, as instructed by the installer to monitor database migrations.  There is a log file produced, but the information contained in it is not particularly useful for debugging issues.  For example, I am attempting to run a playbook, which ends up starting, but never producing any output, and I'm unable to terminate it.  The log produced by `docker logs` doesn't appear to contain any information to help me determine what is wrong.

**Comment by AlanCoding** [comment]
There are a couple of topics here, so let me triage a little:

> It would be nice if AWX produced local log files that can be viewed without the need to set up a log aggregator.

Yes, I have intention to do just this! We are making several changes to the external logger setup, and as a part of this, we hope to have more clear customization of the handler setup. One thing I want to get out of this is to allow users to define their own custom handler inside of their file settings. With that, it will become trivial to add the built-in python file handler, and of course add it as an option to the setting.

See issue https://github.com/ansible/awx/issues/170

A concrete sub-goal of that issue is to allow custom formatters for the external logger, and (with possibly some limitations) custom handlers.

> According to the official Ansible Tower documentation, logs are written to /var/log/tower. However, That directory inside all of the docker containers created by the awx installer is empty.

That documentation does not apply to the installer you're using, and like you noted, it is redirected to the console which is handled by your container management.

> For example, I am attempting to run a playbook, which ends up starting, but never producing any output, and I'm unable to terminate it.

As a distributed system, it is genuinely hard to produce a good log trail for this sort of thing, but I would expect that for the given job ID you ran, there should logs corresponding to the times it was last seen. There should be a log for when it is submitted to the queue (waiting), and when it finishes running, with an event count. If there is a non-zero event count, then the subprocess running Ansible necessarily did _something_. In your case, it may have never got there. If it is perpetually running and un-cancelable (and there are not other active jobs at the time), then I suspect it may be stuck in a state before the Ansible subprocess has begun, and it may be stuck waiting on the project lock file. We are working on several other issues, and my analysis here remains speculative until we find the real root cause.

**Comment by 6sossomons** [comment]
Has there been any forward movement on this?  Part of my issue currently is that I need to beef up the logs just to debug why I can't see my run logs being written to /tmp/ansible_run.log when defined in the settings.py nor when defined as an extra_var in the job runs.
