### ISSUE TITLE
Consider to not store postgres data in /tmp by default

### ISSUE THREAD

**Issue by fungiboletus** [ansible/awx#1890]
By default, the postgres data is stored in a temporary folder (`postgres_data_dir=/tmp/pgdocker` [here](https://github.com/ansible/awx/blob/devel/installer/inventory#L35)).

This is a bit confusing when you expect a default configuration to work (see #311). Maybe it could be made more explicit that the postgres_data_dir should be changed.

**Comment by freehck** [comment]
I wanna add that I've just also run into this problem. I was very surprised, because my /tmp was NOT on tmpfs. But after some time I found that the problem really is in the fact, that our production distro (it's ubuntu 16.04) has systemd onboard. And the default systemd configuration is to clean /tmp every reboot. I don't know why some developers think it's sane, but we have to take into account these defaults.

I think that many users don't know this specific systemd's "feature", so it would be sane to move the default of postgres_data_dir f.e. to /opt/pgdocker.

**Comment by erismaster** [comment]
Seconding this. Wondered why I couldn't login, found out the DB was wiped. 

Running Ubuntu 18.04

**Comment by jakemcdermott** [comment]
>  I don't know why some developers think it's sane,

It's suitable for the purposes of development, testing, and iteration. `postgres_data_dir` (and other) variables are specifically identified in the installation guide for AWX, which recommends that you change these configuration variables for your particular use case. If you intend to use AWX for production you should really be using an external database, at which point you'd still need to update the installer's default configuration.
