### ISSUE TITLE
Job hangs when running a playbook with a pause task with no timeout

### ISSUE THREAD

**Issue by samdoran** [ansible/awx#1897]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When running a Job Template containing a `pause` task without a timeout, the job will hang indefinitely. The `pause` module has code to prevent this from happening when the playbook is run in a non-interactive manner, but the execution environment within Ansible Tower doesn't match the logic in the module and therefore the `pause` module causes the job to hang.

##### ENVIRONMENT
* AWX version: 3.2.5
* AWX install method: manual
* Ansible version:  2.5.2
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Safari 11.1

##### STEPS TO REPRODUCE

1. Create a playbook with a `pause` task with no parameters.
1. Create a Job Template using that playbook
1. Run the Job Template

##### EXPECTED RESULTS

The `pause` task will be skipped and display the following warning message:
>  [WARNING]: Not waiting for response to prompt as stdin is not interactive
##### ACTUAL RESULTS

Job Template hangs indefinitely and must be canceled.

##### ADDITIONAL INFORMATION

From talking to some folks on the Core team, this feature of the `pause` module — to continue the play if no TTY is detected and no timeout is provided — was put in specifically for `cron` and Tower jobs. I have never personally seen this work, but allegedly it used to work in 2.x versions of Tower.

It does work as intended in `cron` jobs, just not in Tower.

I also tested with Ansible 2.3.2 and Tower 3.2.1.21 and got the same behavior.

**Comment by YakobovLior** [comment]
I'm experiencing the same behavior, but I'm looking for another solution.
Instead of making AWX realize that "stdin is not interactive" and disable pause module,
is there a possibility to run templates from AWX interactively?
We have many playbooks which uses this module and without the ability to use it through AWX we won't be able to migrate to AWX.

**Comment by wenottingham** [comment]
No, interactive stdin for playbooks will not be supported.

**Comment by samdoran** [comment]
@YakobovLior The way to make jobs interactive in AWX is by creating a [survey](http://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html#surveys). Surveys in AWX replace interactive `pause` and/or `vars_prompt`.

**Comment by ryanpetrello** [comment]
@samdoran,

> Create a playbook with a pause task with no parameters.

```yaml
# Pause for 5 minutes to build app cache.
- pause:
    minutes: 5
```

_Shouldn't_ it hang in that scenario?  If you specified a `prompt`, I could see _that_ complaining about a non-interactive environment.

**Comment by ryanpetrello** [comment]
Ah, you're referring to something like:

```yaml
# Pause until you can verify updates to an application were successful.
- pause:
```

**Comment by ryanpetrello** [comment]
It looks like Ansible uses `os.isatty` to determine if it should wait on prompts:

https://github.com/ansible/ansible/blob/73b98926052ee62b7df2c91916b6961e77ff74dc/lib/ansible/plugins/action/pause.py#L185

awx uses the `pexpect` library, which interacts w/ the spawned ansible process via a pseudoterminal.  So the real issue here is that awx doesn't really know what it should be doing in this scenario.  We also can't just catch the special `Press enter to continue` string and send `\r`, because it could occur _anywhere_ in other stdout, not to mention the prompt itself is actually customizable.

**Comment by ryanpetrello** [comment]
Outside of some sort of behavior signaling (maybe via an Ansible config option that awx could set to tell Ansible to always prevent usage of the `pause` module), I don't see much of a way around this.  Even that isn't ideal, because it means that playbooks will behave _differently_ in awx than if you ran them outside of awx.  I'd say this is just unsupported/a known issue.

**Comment by samdoran** [comment]
Thanks @ryanpetrello for looking in to this!

**Comment by YakobovLior** [comment]
@samdoran 
Thank you for the quick reply. I will try to implement survey and update if it fits for this scenario.

**Comment by YakobovLior** [comment]
@samdoran 
Hey samdoran, I've tested the survey usage but it doesn't fit my needs.
The survey works like another extra_variables but it cannot give me the option to press ENTER to continue playbook execution at the pause point.

@wenottingham 
Is there another way to accomplish the behavior I'm looking for?

Thanks

**Comment by ryanpetrello** [comment]
@YakobovLior nope, awx doesn't currently support arbitrary interactive input the way a real tty would (and we don't plan to add support for it: https://github.com/ansible/awx/issues/1897#issuecomment-391378110)
