### ISSUE TITLE
Install isolated nodes with playbook

### ISSUE THREAD

**Issue by Mikey032** [ansible/awx#1944]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

I'm currently having issues installing isolated nodes by doing manual steps. Is there documentation available to do it manually?
It would also be great to install isolated nodes on another host with the Ansible playbook.

**Comment by ryanpetrello** [comment]
zBurrito,

What version of awx are you using?  Please fill out the New Issue template with all of the requested details so we can help you troubleshoot:

https://github.com/ansible/awx/blob/devel/.github/ISSUE_TEMPLATE.md

**Comment by Mikey032** [comment]
Hello

We currently don't have any awx running. Because there currently isn't a possibility to install awx with isolated nodes with the playbook, we need to use the devel branch of the awx project.

When trying to setup awx with isolated nodes. We used the Contributing guide to get started and the following readme: https://github.com/ansible/awx/blob/devel/tools/docker-isolated/README.md to build the docker images.

**Comment by ryanpetrello** [comment]
zBurrito,

At this point in time, the awx openshift installer doesn't really _support_ isolated nodes - there's a lot of implementation details that have yet to be written, such as:

- support for building an image that deploys the minimal "playbook runner" tooling that runs on isolated nodes
- calling various `awx-manage` commands to register isolated nodes and their controllers as pods come online
- baking SSH `authorized_keys` into the image building process for isolated nodes so that controlling awx nodes can SSH into them for isolated playbook execution

There's also a possibility that we may - in the longer term - employ a different model for isolated nodes in containerized environments.  While it's _possible_ that with some experimentation you could get isolated nodes working, we just haven't fully fleshed this out in an official way for containerized awx installs.

As we make progress on this issue in the future, I expect that we'll probably track our planning and progress at https://github.com/ansible/awx/issues/1207 and https://github.com/ansible/awx/issues/1485.
