### ISSUE TITLE
custom ansible.cfg ?

### ISSUE THREAD

**Issue by idgdmg** [ansible/awx#1948]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
Need to use my own custom ansible.cfg in AWX. Where is the "original file" located so I can modify the install?

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: kuberentes with custom repo
* Ansible version: 2.5.1

**Comment by ryanpetrello** [comment]
@idgdmg take a peek at https://docs.ansible.com/ansible-tower/2.4.0/html/administration/troubleshooting.html#locate-and-configure-the-configuration-file

For awx installs, you'll want to make sure you place the `ansible.cfg` on the `awx_task` container file system.

**Comment by sammybenjamin** [comment]
The solution turns out to be not accurate as jobs run on AWX command line behave differently as opposed the same playbook run from AWX console which proves it is NOT using the ansible.cfg as in the project being used. 

For example, I added a change to the ansible.cfg so messages will be presented as Text as opposed to JSON format. The same playbook runs correctly from AWX command line producing text, but it still produces JSON format output when run from AWX console. BUG??? Different Solution?

**Comment by AlanCoding** [comment]
> For example, I added a change to the ansible.cfg so messages will be presented as Text as opposed to JSON format.

Could you give some specifics of the config syntax you're using? It's very important to us to support custom config files, but there are a certain subset of settings that will interfere with how AWX (via the ansible-runner lib) processes events and displays them to the user in the API and UI, and the server may squash user settings by using environment variables that have higher precedence.

**Comment by dberardo-com** [comment]
> For awx installs, you'll want to make sure you place the `ansible.cfg` on the `awx_task` container file system.

Could you please be more explicit? should we override the /etc/ansible/ansible.cfg file or just create a new one under the home folder of the aws user (which i believe being the /var/lib/awx folder?

---

update: i am using AWX 17
