### ISSUE TITLE
Revise capacity units to be in terms of more things (CPU + RAM)

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#196]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Our current capacity units and recommendations are based solely on RAM - 4GB of RAM per 100 forks.

However, actual capacity is far more complex. Examples of theoretical capacity bits:

- RAM: 4GB RAM per 100 forks
- CPU: N CPU cores per 100 forks (dunno what N would be)
- Disk space: not relevant for AWX capacity units, only for recommendations

##### ADDITIONAL INFORMATION

Would need to also verify existing RAM recommendations.

**Comment by AlanCoding** [comment]
> Would need to also verify existing RAM recommendations.

A big shortcoming of what we're doing is that we use _total_ system RAM available from the `free -m` command, and then subtracting what we estimate a typical job would use. However, that command also returns the currently consumed RAM. The quality of data from _actual_ resource use will always be lightyears better than any guesstimate we could attach to a job.

Maybe we could leverage this, in order to account for different jobs with radically different memory consumptions, in addition to other (unanticipated) services running on the box. Just wanted to throw that idea out there.

**Comment by matburt** [comment]
This was implemented with the clustering merges.

**Comment by AlanCoding** [comment]
link https://github.com/ansible/awx/pull/1058
