### ISSUE TITLE
Empty groups ignored when sourcing from projects

### ISSUE THREAD

**Issue by ffrank** [ansible/awx#1966]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When sourcing an inventory from an SCM project, empty groups are ignored and not added to the AWX inventory.

##### ENVIRONMENT
* AWX version: 1.0.6.3
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create the following Inventory file:
```
[loadbalancers]

[workers]
localhost
```

Use it as an inventory source.

##### EXPECTED RESULTS

The AWX Inventory should comprise the groups `workers` and `loadbalancers`.

##### ACTUAL RESULTS

The `workers` group exists, but `loadbalancers` does not. Templates that expect `groups.loadbalancers` to be at least an empty list produce errors.

##### ADDITIONAL INFORMATION

`ansible-inventory` does seem to include empty groups in `--list` output:
```
{
    "_meta": {
        "hostvars": {
            "localhost": {}
        }
    },
    "all": {
        "children": [
            "loadbalancers",
            "ungrouped",
            "workers"
        ]
    },
    "loadbalancers": {},
    "ungrouped": {},
    "workers": {
        "hosts": [
            "localhost"
        ]
    }
}
```

**Comment by AlanCoding** [comment]
This was originally reported in https://github.com/ansible/awx/issues/1192, but that was conflated with the group_vars issue, and when the group_vars issue was fixed the user in that case had no further interest in the empty groups issue.

The issue was previously filed in Ansible core at https://github.com/ansible/ansible/issues/36177

We could re-open 36177 I guess, although I would not predict an enthusiastic response.

**Comment by ffrank** [comment]
Are you certain that this duplicates ansible/ansible#36177?
The scenario in that one would *not* include the empty group in the `ansible-inventory` output. In the above report, it does appear there.

It seems to me that here, Ansible is doing the right thing. It would appear that the group is indeed dropped in between `ansible-inventory` and AWX.

**Comment by AlanCoding** [comment]
Oh, I see, you're right. I will have to dig into these case further.

**Comment by ryanpetrello** [comment]
@ffrank this looks to me like a long-standing (https://github.com/ansible/awx/commit/1283a78e09552e620c254d63f27e2daa61615c2d) default awx behavior that's _configurable_ per source type (the default behavior is to exclude empty groups on all inventory import sources):

```
~/dev/tower ack EXCLUDE_EMPTY_GROUPS
awx/main/tasks.py
2067:        if getattr(settings, '%s_EXCLUDE_EMPTY_GROUPS' % src.upper()):

awx/settings/defaults.py
754:EC2_EXCLUDE_EMPTY_GROUPS = True
774:VMWARE_EXCLUDE_EMPTY_GROUPS = True
827:GCE_EXCLUDE_EMPTY_GROUPS = True
869:AZURE_RM_EXCLUDE_EMPTY_GROUPS = True
878:OPENSTACK_EXCLUDE_EMPTY_GROUPS = True
888:RHV_EXCLUDE_EMPTY_GROUPS = True
898:TOWER_EXCLUDE_EMPTY_GROUPS = True
908:SATELLITE6_EXCLUDE_EMPTY_GROUPS = True
919:CLOUDFORMS_EXCLUDE_EMPTY_GROUPS = True
929:CUSTOM_EXCLUDE_EMPTY_GROUPS = True
939:SCM_EXCLUDE_EMPTY_GROUPS = True
```

By setting `SCM_EXCLUDE_EMPTY_GROUPS = False` in `/etc/tower/settings.py`, you should get the behavior you're looking for.

https://github.com/ansible/awx/blob/3ab7f06f952b3effb21d3000ae29f09b2e106477/awx/main/management/commands/inventory_import.py#L244-L246

https://github.com/ansible/awx/blob/3ab7f06f952b3effb21d3000ae29f09b2e106477/awx/main/utils/mem_inventory.py#L173

@cchurch you have any historical context to add here?

**Comment by wenottingham** [comment]
1) these settings being only in settings.py is mildly dumb (also that they apply to all instances of a source equally)
2) I don't know why these default to `True`

**Comment by ryanpetrello** [comment]
@wenottingham I can't argue with you re: `1.`, and I don't have a better answer for `2.` other than "that was the default that was chosen years ago" 😄

**Comment by ffrank** [comment]
Can confirm that the `SCM_EXCLUDE_EMPTY_GROUPS = False` in the `ansible/awx_task` container fixes this problem.

Do I understand correctly that it would be desirable to expose these settings to the API?

**Comment by AlanCoding** [comment]
The problem with exposing this in the API is that there is a different setting for each type of inventory source, so there are a large number of similar settings, which doesn't jive well with how we manage the distributed database settings. In addition to the empty groups setting, there are even more configurables for each source type, so this would be an enormous number of rarely-used settings to present in the UI. For something like that, I think an entirely different method of organizations these settings would be necessary.

**Comment by ryanpetrello** [comment]
I agree with @AlanCoding - I'd like to come up with a way to make this more easily configurable, but given the scope of the settings and the history involved in Tower/awx setting configuration, that's probably a much larger undertaking.

**Comment by joshuaclausen** [comment]
As a note, both for future searchers and hopefully to help inform future efforts - I found if I added a var to the group in my SCM-based inventory file, it would no longer be "empty", so it would not be auto-removed.  I named mine "filled_by_dynamic_inventory: true" - yay for overdescriptive variable names.

I was mashing up dynamic inventories and static project-sourced inventory files, where my project-sourced inventory files referenced dynamic inventory groups/items, but since the project-sourced inventory file didn't have any knowledge of any hosts in those groups, AWX would remove them on import.  I wanted to use the AWX official containers without modification, so I needed a way to cleanly do this, and adding placeholder vars was just the ticket (instead of manually changing that setting in the settings.py file mentioned above).

It seemed if I could add an environment variable to the SCM-based inventory source that allowed me to override the SCM_EXCLUDE_EMPTY_GROUPS value, that would be a great solution.  After all, it *is* just another python script getting run.

**Comment by MrBones757** [comment]
Apologies for reviving a closed thread,
I came across this issue using Ansible Tower and modifying these settings did not appear to affect from a Tower (AWX) Inventory source.
The context of this is that we have a 'Windows' group that contains the requisite winrm connection details. When no hosts are populated in this group; the variables do not propagate when adding a host using the add_host module. I have modified the 3 variables which may have affected this (TOWER, SCM and CUSTOM) to no avail. Does anyone have any other tips.
I was unable to find documentation about this feature anywhere else.

**Comment by joshuaclausen** [comment]
Have you tried manually adding a never-used var to the ‘Windows’ group?  That seems to keep the group around no matter what.  In my case, I had to enable the verbose logging in the inventory refresh job and then step through where AWX decided to clobber the group (because there were no hosts in it).  However, if I had a manually-specified inventory file that was sourced from my SCM project, it does not remove the group even when there are no hosts.

It’s not quite clear to me if this is the same issue, but figured I’d chime in.  Hope it’s useful somehow.



Joshua Clausen | Tech Director
505 Games
Note my new email: jclausen@505games.com

**Comment by ffrank** [comment]
@MrBones757 I believe this warrants a new Issue report.
