### ISSUE TITLE
[UI][Vault] Error save inventory with vault variables

### ISSUE THREAD

**Issue by w1n32** [ansible/awx#2011]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
 - UI

##### SUMMARY
In host inventory, in "Variables" text area i put variable "password" with vault encrypted string. After i clicked Save button i got error

> Cannot parse as JSON (error: No JSON object could be decoded) or YAML (error: could not determine a constructor for the tag '!vault' in "<unicode string>", line 1, column 16: cell_password: !vault | ^).

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Google Chrome 67.0.3396.87

##### STEPS TO REPRODUCE
Go to INVENTORIES -> HOST -> <Any host>
Insert in to VARIABLES text area this:
`password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          00000000000000000000000000000000000000000000000000000000000000000000000000000000
          00000000000000000000000000000000000000000000000000000000000000000000000000000000
          00000000000000000000000000000000000000000000000000000000000000000000000000000000
          00000000000000000000000000000000000000000000000000000000000000000000000000000000
          0000`

##### EXPECTED RESULTS
Normal save
##### ACTUAL RESULTS
Error
##### ADDITIONAL INFORMATION

**Comment by AlanCoding** [comment]
I'm going to close as a component of https://github.com/ansible/awx/issues/1954

The use of vault variables is still relatively new, and you may want to look around related issues like https://github.com/ansible/awx/issues/223 in order to reformat your variables in a way that is compatible with the newly supported usage. The YAML usage is not yet supported, but may be if 1954 were to go forward.
