### ISSUE TITLE
Trusted CA support for OpenShift deployments in install.yml

### ISSUE THREAD

**Issue by xdfil** [ansible/awx#2012]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY
CA  trusts for situations like this:
Openstack inventory using custom CACERT #1273 

##### ENVIRONMENT
* AWX install method: openshift

##### ADDITIONAL INFORMATION
#1273 was marked closed but the referenced solution only works in a non-kubernetes deployment.

To fix the issue manually will require updating the CA Trust inside the container, and also iirc set an environment variable for python CA path.

Can you folks provide the few additional ansible tasks to the installer that will add these things to the images?

**Comment by matburt** [comment]
I'm totally happy to take a PR on it if you want to build it out.

**Comment by stclark-incomm** [comment]
I have a working solution for this on k8s.  Once I flush out the changes and documentation I'd be willing to submit a PR for this.  I'm not using OpenShift, but I believe the same solution is likely to work.

My solution involves:
- Store ca-certs in a tls secret
- Mount secret to an init container (instead of using a bind mount to the host)
- Run update-ca-trust in the init container
- Copy the /etc/pki/ca-trust/extracted directory to a mounted emptyDir volume
- Mount the emptyDir volume to the web and celery containers at /etc/pki/ca-trust/extracted

This is working for me to use LDAPS authentication with an internal CA certificate.  It probably works for other cases that rely on CA certificates, but I haven't tested other scenarios.

**Comment by matburt** [comment]
That sounds pretty complex. I wonder if it wouldn't be easier to add as a secret or configmap, bind that to the container at startup and just add a trust call over to that if the mount point exists?

**Comment by stclark-incomm** [comment]
The update-ca-trust command needs root privilege to run, the awx containers start with user 1000.  The command could be run in the ENTRYPOINT script, if it was running as root.  A Kubernetes init container isn't adding too much complexity, and keeps the main container running as non-root, so I think it's reasonable.  I'll try and get my change up to github next week.

**Comment by dperez-sct** [comment]
@stclark-incomm do you have progress with this?

**Comment by stclark-incomm** [comment]
@dperez-sct I apologize I missed adding my change to this. Now that AWX is using an operator to install it is something I will have to revisit to see if this problem is still relevant.

**Comment by shanemcd** [comment]
The old Kubernetes installer mentioned here has been removed. If this functionality does not exist in the AWX Operator, please open an issue at https://github.com/ansible/awx-operator/issues
