### ISSUE TITLE
Allow search on `extra_vars`

### ISSUE THREAD

**Issue by mponton** [ansible/awx#2024]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

API forbids search on `extra_vars` with this error:
```json
{
"detail": "Filtering on extra_vars is not allowed."
}
```
I am not sure why this is expressly restricted in the code like this:
```python
    extra_vars = prevent_search(models.TextField(
        blank=True,
        default='',
    ))
```
The `extra_vars` are visible to any users that has access to the jobs. So I am not sure why search should be prevented.

##### ENVIRONMENT
* AWX version: 3.2.3
* AWX install method: Official RH Tower distribution
* Ansible version:  2.4.2
* Operating System: RHEL v7.3
* Web Browser: Chrome

##### STEPS TO REPRODUCE

```
https://your-tower-host/api/v2/jobs/?extra_vars=foo
```

##### EXPECTED RESULTS

Would expect to be able to search on this field.

##### ACTUAL RESULTS

```
HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: your-tower-host
X-API-Time: 0.094s


{
    "detail": "Filtering on extra_vars is not allowed."
}
```

##### ADDITIONAL INFORMATION

We have a particularly good use case for this. We have jobs that run on a specific set of hosts to "pre-stage" servers (e.g. into Active Directory) before these servers are provisioned. `extra_vars` contains the different values including the name of the server to pre-stage. When looking at a bunch of jobs in Tower, we see the same job name, limit, etc... The only field differentiating jobs is `extra_vars`. Not being able to search on it makes the UI (and API) quite limited.

**Comment by wenottingham** [comment]
Extra vars includes security-sensitive credential data.

**Comment by mponton** [comment]
@wenottingham Is this content stripped when displayed in the Tower UI? If it is, could the same process not be used during a search (albeit possibly less than optimal)? If it is not, what is the point of preventing the search if this security-sensitive credential data is visible in the UI by the same persons who could search on this field?

**Comment by wenottingham** [comment]
It's stored encrypted and never displayed in the UI, but filtering on it in the API allows you to filter on the encrypted value, which with enough filtering can lead to determination of some/parts of the encrypted value.

**Comment by mponton** [comment]
@wenottingham OK, I appreciate the explanation. I am pushing my luck a bit here (I know your time is precious and I don't want to waste it, just trying to better understand the actual issue), I am assuming your are talking about credentials passed as extra vars as defined in Tower, right?

We have a set of these credentials (e.g. for API calls to our CMDB), and after my previous comment I looked into it and confirmed what you told me: I cannot see these credential vars in the UI nor in the API output when listing jobs.

So if the API already strips then from the output, wouldn't it be doable to search on the resulting string instead? Or is the search implementation limited to queries on the "raw" value only? If there was a "safe" way of doing this, would you guys consider integrating it?

Thanks for your time and all the work you put in this project.

**Comment by AlanCoding** [comment]
> So if the API already strips then from the output, wouldn't it be doable to search on the resulting string instead?

I think I get what you're speculating.

For illustration, let's say that the implementation was that in the models plaintext password values were saved inside of `extra_vars` in the Job model. Then the values are replaced with the string "$encrypted$" when the API produces its response. Couldn't we filter on the sanitized `extra_vars` instead of the raw `extra_vars`? No.

Servers are expected to have a great many jobs in the system, say a million. Our maximum page size is 200. It is reasonable to sanitize `extra_vars` for 200 records, even if they all contain a dozen passwords, it's not a significant performance consideration. However, if we were to sanitize _a million_ `extra_vars` entries, then it would take longer than any request is allowed. There is no way to do things like ordering or comparisons without leaning on postgres indexing.

However, we do not store the values in plaintext in the database. It goes through an encryption algorithm and cannot be decrypted without the key (stored separately). If we allowed filtering / ordering of `extra_vars` as things stand, then through laborious scripting, it would allow someone to obtain the encrypted version of the password `extra_vars` values for jobs they have read access to. I do see how this is a relatively minor security leak, but it is nonetheless a security leak, and that's why it is still blocked.

**Comment by mponton** [comment]
@AlanCoding I see. You are quite right. I oversimplified this and did not take into account a search in such large environments. I guess I was a bit too centered on my issue to see the larger picture. I really appreciate the detailed explanation. Thanks for the follow up and all the work you put in this project!
