### ISSUE TITLE
"First Name" and "Last Name" fields are limited to 30 characters

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#2075]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently "First Name" and "Last Name" fields are limited to max 30 characters. Its possible to have "first_name" and "last_name" > 30 chars. It should be either increased or at least be configurable to change the max size.

##### ENVIRONMENT
* AWX version: latest

**Comment by wenottingham** [comment]
This is a django limitation.

**Comment by matburt** [comment]
We'll probably pick this up when we upgrade django at a later time.

**Comment by wenottingham** [comment]
assigning as part of planned django 2.2 update

**Comment by ryanpetrello** [comment]
cc @jbradberry

**Comment by jbradberry** [comment]
Yep, ok, making a note of it.

**Comment by ryanpetrello** [comment]
It looks like in recent Djangos, `first_name` is still limited to 30 characters, but `last_name` got a bump to 150:

https://github.com/django/django/commit/d5b573d872bbe0d5825efaee2d41cb3cdc75417b

**Comment by jbradberry** [comment]
@wenottingham Just wanted to check back about this, do we still want to customize the user model for only the `first_name` field?  Bring it up also to 150 characters, perhaps?

I ask because it is a fairly risky process involving some database fiddling: https://www.caktusgroup.com/blog/2019/04/26/how-switch-custom-django-user-model-mid-project/

**Comment by wenottingham** [comment]
No, the idea is to upgrade the limits to whatever django supports.

**Comment by jbradberry** [comment]
@wenottingham In that case, as @ryanpetrello notes above, Django 2.0 has automatically increased the size of the `last_name` field to 150 characters: https://docs.djangoproject.com/en/2.2/releases/2.0/#abstractuser-last-name-max-length-increased-to-150

Examination of my development database confirms that this is the case:
```
                                     Table "public.auth_user"
    Column    |           Type           |                       Modifiers      
                  
--------------+--------------------------+--------------------------------------
------------------
 ...
 username     | character varying(150)   | not null
 first_name   | character varying(30)    | not null
 last_name    | character varying(150)   | not null
 ...
```

If that is all we want, then this ticket should probably be closed with no further action taken.

**Comment by wenottingham** [comment]
Has the upgrade landed?

**Comment by jbradberry** [comment]
> Has the upgrade landed?

It's in #4070 , which is ready for review and will with luck pass all of the tests tonight.

**Comment by ryanpetrello** [comment]
Yep, I expect once #4070 lands, we can just close this ticket.  I don't think Django in its current state will allow us to make the length configurable (unless we want to introduce a custom user model, which I'd prefer not to do), but 150 is a nice improvement for the last name.

**Comment by ryanpetrello** [comment]
@jbradberry @wenottingham I'm going to ~close~ mark as `needs_test` since we're back in parity with what upstream Django does, and it *is* an improvement:

https://github.com/ansible/awx/issues/2075#issuecomment-511020914

I'm not particularly interested in carrying a custom `User` subclass for the purposes of making the `first_name` longer than 30 chars, but `last_name` now supports 150.

Let me know if you disagree.

**Comment by Spredzy** [comment]
Tested and verifeid. last_name has properly be bumped to a 150 limit
