### ISSUE TITLE
survey password written on disk for vmware_guest

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2186]
- Feature Idea

 - UI

I don't know if this is a security bug, so I open it as feature request. I have a playbook which create a vm from template in vmware and I use the module vmware_guest. I created a project with my playbook which take username and password from awx. In awx there is a survey which ask for username, password for access to vcenter and other informations for create the vm. When I run the job I see a temporary file is created with the contents of script python and all vars, and in these vars there is also the password don't encrypted for access to vcenter. Could you find another solution and don't write the password on disk?
This is my playbook

    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        folder: /
        name: testvm_2
        state: poweredon
        template: template_el7
        disk:
        - size_gb: 10
          type: thin
          datastore: datastore
        networks:
        - name: VM Network
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy

**Comment by wenottingham** [comment]
This is intentional, it's in a temporary directory that lives only for the lifecycle of the ansible-playbook process, isolated from other jobs via both unix permissions and bubblewrap. Any user with sufficient permissions to read the temporary file has sufficient permissions to cause more serious damage by interfering with the AWX process itself.

The alternative is passing them via the commandline, which makes them readable by any process on the system.
