### ISSUE TITLE
Add a playbook editor

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2206]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Add a playbook editor to the UI that would allow adjusting Ansible playbook content from inside the UI session

**Comment by ghost** [comment]
+1 This will be very useful feature

**Comment by wenottingham** [comment]
This is not planned.

There's multiple issues at play here:

1. Technical - The only way to do this with *good* feedback is to a) import ansible code under the hood b) shell out a lot. a) is a licensing issue (ansible is GPL, AWX is Apache), and b) is really ugly.

2. Complexity - Given the sheer number of fringe options for both plays/tasks and modules, populating the UI with all of them brings completeness at the expense of complexity that's exposed directly
to the user.  That may make it harder to guide the flow of *when* they should use particular options. Our current most succesful flow is that customers get comfortable writing Ansible automation (usually via the commandline), and then bring in Tower/AWX when they need that control
and centralization. Trying to frontload playbook development in AWX first for users who are new to Ansible entirely runs the risk of making the UI much more complex and actually scaring them off.

3.  Context inside of AWX - The biggest #1 best practice we have around playbook development is to use source control and collaborate on playbook development. Building a playbook editor inside the application Tower means you either ignore source control entirely (limiting its usefuleness in a large production environment), or you're on the hook for building a very large piece of infrastructure that
has to handle commits, pushes, merges, conflicts, and all the other "fun" bits of source control. We're not equipped at this time to reimplement the GitHub UI, nor would we be the right people to do so.

So that gives you some idea of what our product thinking is around this area; hope that helps.

We recommend using Ansible support in existing editors/IDEs (https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible, https://atom.io/packages/language-ansible), and combining that with source control (github, gitlab, etc). If you're looking to interactively debug playbooks, https://github.com/ansible/ansible-jupyter-kernel may be of use.

**Comment by ghost** [comment]
@wenottingham

I think you are overcomplicating this. We re simply asking about giving an editor option in Tower UI to view and edit files. That way users are not needed to go in CLI and edit/save files.  That's all. Why is this so much complex?

**Comment by wenottingham** [comment]
It's an idea that as described is fundamentally a toy that doesn't scale in use and actively works against best practices. It's not overcomplicating things -- it's building tools that make sense both in small and large usage.

**Comment by ghost** [comment]
@wenottingham: You are saying "it's building tools that make sense both in small and large usage." you know this request is coming from large organization who has huge customer base to satisfy. 

What I am simply asking is a way to manage ansible playbooks via Ansible Tower. Ansible Tower is supposed to be a GUI version of Ansible. I am not asking you implement it my way. Just fix it the way you think is best.  Not doing anything about it is not helping the community or your big customers.

**Comment by wenottingham** [comment]
I said large and small *usage*.  This is true regardless of company size.

No usage of AWX (or its downstream) at scale involves using an UI to enter and edit playbooks, or syncing manual repositories, etc. It's using SCM, pull requests, testing, and so one. Oftentimes it means using the API and not worrying about the UI at all except for a few operators. That's why these are best practices - we know what works.

Given that, we choose to focus on building things that make sense both in small cases and in these large usage cases... that means expanding things like workflows, working on scaling via containter strategies, and so on. Being a content repository/editor doesn't fit there, so we work on the things that do make sense.

**Comment by Marauder1568** [comment]
Install Webmin and use the web editor that's available there. I ended up here searching and thinking the same thing that it would be nice, but came to the same conclusion that it was intentionally designed this way for a reason.

**Comment by ohobby** [comment]
+1

**Comment by jacobjohnanda** [comment]
+1

**Comment by Trackhe** [comment]
+1

**Comment by danielo515** [comment]
Maybe you don't want to add an editor, I don't agree with I understand it. But what about adding at least a viewer with syntax highlight? It is a simple addition of a Javascript library
