### ISSUE TITLE
could not handle archive. Command \"unzip\" not found

### ISSUE THREAD

**Issue by mouliveera** [ansible/awx#2227]
##### ISSUE TYPE
"msg": "Failed to find handler for \"/tmp/ansible_mLT185/consul_1.0.6_linux_amd64.zip\". Make sure the required command to extract the file is installed. Command \"/bin/tar\" could not handle archive. Command \"unzip\" not found."

**Comment by ryanpetrello** [comment]
@mouliveera you'll need to provide some additional details about the problem you're encountering.  This includes:

* What you're attempting to do, and how you expect it to work.
* What's _actually_ happening (the problem you're encountering).
* Details about your AWX installation environment.

Please take a look at the template we provide for new issues: https://github.com/ansible/awx/issues/new?template=bug_report.md

We ask for these details for a _reason_ (so that we can understand the problem and help people effectively debug).

**Comment by mouliveera** [comment]
@ryanpetrello Issue [#2228](https://github.com/ansible/awx/issues/2228)
