### ISSUE TITLE
When split jobs are created, I want to be able to search for them specifically.

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#2333]
##### Summary
When split jobs are created, I want to be able to search for them.

##### Acceptance Criteria:
1. A search filter can be applied to job lists to show only split jobs
2. A search filter can be applied to job lists to show only parent workflow jobs of split jobs
3. ~A search filter can be applied to job lists to show only split jobs workflow jobs.~  (edit: crossed out as this is just duplicating 1 and 2*)
4. Job Templates lists can be filtered to only show job templates that produce split jobs.

##### ADDITIONAL INFORMATION
Link #2174
Link #1283

**Comment by AlanCoding** [comment]
Just a quick driveby of this, I'm fairly confident that these work in the current branch, but the field names will soon change anyway:

> 1. A search filter can be applied to job lists to show only split jobs

Note that for this, as with most cases, you can filter either on the type (jobs here) or unified_jobs generally

`/api/v2/jobs/?not__internal_limit=`

This is still undocumented, as I was discussing with @kialam, and I'm struggling with what the right thing to do is, because I don't want more fields in the jobs API, but that might be the best option.

> 2. A search filter can be applied to job lists to show only parent workflow jobs of split jobs

`/api/v2/workflow_jobs/?job_template__isnull=false`

This field will change `job_template` -> `slice_job_template`. Maybe.

> 3. A search filter can be applied to job lists to show only split jobs + workflow jobs.

I'm not 100% sure what this means, and it probably involves using the `or__` syntax in our filtering system to combine the two prior filters.

> 4. Job Templates lists can be filtered to only show job templates that produce split jobs.

`/api/v2/job_templates/?job_slice_count__gt=1`

**Comment by jakemcdermott** [comment]
🏈 punting for now
