### ISSUE TITLE
Category( or folder) for templates/project/inventory

### ISSUE THREAD

**Issue by xding2020** [ansible/awx#2350]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

With too many templates/projects/inventory entries in the Tower, category or folder would help user organzie their work. So user would see the category first when they go to templates/projects/inventory page. Then they could click the category, maybe like a drop-down menu, or jump to another page, only the templates/projects/inventory belonging to the category will be visible.
The idea comes from that I personaly feel quite frustarted about that I have to find the template again after I save changes to the template (it will always go back to the first page).

**Comment by benapetr** [comment]
We have infrastructure with 10 000 servers, 20+ inventories and 30+ organizations (we use organizations for teams, because organizations are only isolated groups of users with own inventories, projects and templates).

It's already extremely hard to navigate through jobs or templates as there is no hierarchy.

**Comment by UnknownGnome** [comment]
In AWX 4.0.0 the addition of the Launch button to the template screen is great. I'll jump on board here to say that some folders or drop-downs would be great for templates. I found this issue when I was going to create one of my own for the same thing.

**Comment by ciinema** [comment]
+1

**Comment by RyanW19** [comment]
Any update on this feature? I've seen it's been open for exactly a year now and just wondering if it's on the todo or if theirs an ETA?

**Comment by RyanW19** [comment]
Is their any update on this yet? would be great to get this implemented

**Comment by cs-laurentiuvasiescu** [comment]
Any update? Looks like a popular request :)

**Comment by chris93111** [comment]
+1

**Comment by chirogocki** [comment]
+1

**Comment by Mordecaine** [comment]
+1

**Comment by nwerker** [comment]
+1

**Comment by rmeichsner** [comment]
+1

**Comment by lucasafonsokremer** [comment]
+1

**Comment by benapetr** [comment]
Just a hint for developers - I've seen another project solved this in a very elegant way that didn't require so much coding, they simply allowed slash to be part of item name, so internally all items were all stored in one place, but UI was grouping them according to their prefix. So that in database you would have items called

folder1/task
folder1/b
folder2/c
test

And UI would build the hierarchy itself. That's one approach you can take that requires almost no modifications on database level (no schema changes)

**Comment by nwerker** [comment]
+1

**Comment by athomsonitrs** [comment]
+1

**Comment by shelkro** [comment]
+1 please add this feature.

**Comment by darrinseats** [comment]
+1

**Comment by tristan-evans-od** [comment]
Sorry if this is obnoxious, but "+1". Would love to see this added as a feature.

**Comment by rbreekveldt** [comment]
+1

**Comment by ffirg** [comment]
This would mean a fundamental design across the stack from the IU, API and down into the database. This is not something we're looking at doing at this time. There are labels and advanced searching under Job Templates just for this purpose. With sensible, standard naming conventions, that should suffice.
