### ISSUE TITLE
Two suggested UX updates...

### ISSUE THREAD

**Issue by rpural** [ansible/awx#2360]
##### ISSUE TYPE
 - Feature Idea for a better user experience

##### COMPONENT NAME

 - UI

##### SUMMARY
For the Tower interface (actually two):

 

First, on the Template editing screen, add a launch button within the editor, rather than having to go down in the list and find it again. This would save a huge amount of time while debugging and editing, with little to no cost in space on screen or code.

 

Second, and similar in justification to the first, when I set search criteria, keep the search criteria; don’t go back to the full list just because I edited a template or looked at a job. Again, this would save huge amounts of time and frustration, while keeping the focus on the task at hand. Once I want to go back to the full list, I can just click on the tag to remove it from the search, but having to re-enter the tags each time the screen changes really drags down productivity.

 

Just my rambling complaints for today.

**Comment by AlanCoding** [comment]
> First, on the Template editing screen, add a launch button within the editor, rather than having to go down in the list and find it again.

That is on the agenda, see card https://github.com/ansible/awx/issues/1991

Persisting list filters was also mentioned there, but that would be a separate issue. I think that at some point, someone looked into persisting search filters and other view-related settings, but I can't find anything right now. @jlmitch5 do you know of any such issue?

**Comment by jlmitch5** [comment]
+1 on your first point.  I agree, it is a UX improvement with very little involved.  You can track progress in 1991.

Persisting searches on lists is roped into this issue https://github.com/ansible/awx/issues/278.  The way we've thought about it before is by persisting the user's preferences to the backend, as well as having an interface where there can be different saved searches, with an interface to select them and set one to be default.  That's a pretty major feature with both front end and back end work necessary and is currently not very specifically scoped, nor is it prioritized, so it won't be happening in the short term.

Since we persist the searches in the query params, it is feasible that we could take you back to the route in some cases with those populated (and thus the search tags would be present).  I could see this being a more reasonable short term solution, though I'm not sure of the specifics of when you'd want search tags and when you wouldn't.

**Comment by AlanCoding** [comment]
Right, a design of saved search filters hasn't been completed, but that is exactly what I was looking for.

Since the material from this issue is covered in those 2 other issues, @rpural I will go ahead and close this, but we do take this feedback into account. Thanks for your suggestions.
