### ISSUE TITLE
VERSION 2.0.1 for awx_web docker image is incorrect

### ISSUE THREAD

**Issue by z1odeypnd** [ansible/awx#2404]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Instalation fails with error: 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image ansible/awx_web:2.0.1 - 404 Client Error: Not Found (\"{\"message\":\"manifest for ansible/awx_web:2.0.1 not found\"}\")"}`
Because VERSION file contains version 2.0.1, but docker image awx_web (https://hub.docker.com/r/ansible/awx_web/tags/) not have awx_web image with tag 2.0.1 at this moment.

**Comment by AdrianDutu** [comment]
I am also getting this error.

**Comment by z1odeypnd** [comment]
> I am also getting this error.
@Darkhan90 , you can edit VERSION file and rewrite version to 2.0.0 or latest

**Comment by AdrianDutu** [comment]
@z1odeypnd I did that already. But that didn't bring the bug fixes in 2.0.1, it just installed the outdated version again. I was doing the upgrade because of the [workflow UI bug](https://github.com/ansible/awx/pull/2348#issue-219194846) which has been fixed in 2.0.1, but i still have the bug, so i need the new 2.0.1 images.

**Comment by AdrianDutu** [comment]
@z1odeypnd the 2.0.1 image is there now.

**Comment by z1odeypnd** [comment]
@Darkhan90 , ok, I close issue. =)
