### ISSUE TITLE
If a WFJT contains a SJT, the SJT detail view cannot be opened from the context of the WFJT view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2465]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
If a WFJT contains a SJT, the SJT detail view cannot be opened from the context of the WFJT view

##### ENVIRONMENT
* AWX version: 2.0.1
* Operating System: MacOS
* Web Browser: Firefox 62.0.3

##### STEPS TO REPRODUCE

1. Create a SJT with multiple slices
2. Create a WFJT which contains the SJT from step 1
3. Run the WFJT and attempt to click on the SJT Detail view link

##### EXPECTED RESULTS

Able to view the SJT Detail

##### ACTUAL RESULTS

Error 404 Modal

##### ADDITIONAL INFORMATION

![wfjt-sjt](https://user-images.githubusercontent.com/12446869/47057567-4e5c4b00-d18f-11e8-8f9d-cd58187cfae2.gif)

**Comment by AlanCoding** [comment]
This is a hard overlap between job slicing and https://github.com/ansible/awx/issues/2252

Presumably it will be resolve once the two branches are merged together in the main development branch.

Practically, workflows-in-workflows is probably expected to land first, in which case a rebase of job slicing will resolve this.

**Comment by kialam** [comment]
~~This should be "fixed" in #2352.~~
While it is true that #2352 is supposed to link up the possibility of Workflows within Workflows, and that these [changes](https://github.com/ansible/awx/pull/2352/files#diff-2f3a9c22ab39ef8f4beeb12e004431c3R1088) should correctly link the `DETAILS` anchor to a workflow details page for a sliced job, I dug a little further with @marshmalien and discovered that the API is returning a `unified_job_type` of `job` for sliced jobs.

Here's what I think is happening:
1) The WF Details page makes a call to the API to the `/workflow_jobs/34/workflow_nodes/?order_by=id` endpoint to get all the nodes of a particular workflow.
2) The response within `summary_fields` contains the `unified_job_template.unified_job_type` attribute, what is what the [UI uses](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js#L906) to link to either job, inventory, or project detail pages.
3) The `unified_job_type` being returned for split jobs is `job` and therefore the UI will link to a job detail page instead of a workflow detail page.
<img width="952" alt="screen shot 2018-11-01 at 12 53 22 pm" src="https://user-images.githubusercontent.com/2293210/47866455-2bf43f80-ddd5-11e8-903f-71efddadf599.png">

**Comment by AlanCoding** [comment]
Great analysis, thanks!

I'm not liking this field `summary_fields.unified_job_template.unified_job_type ` one little bit. I wish we could get rid of it, the concept becomes degenerate with the introduction of this feature.

https://github.com/ansible/awx/blob/a1fe60da78445c7970eaa823e88ce21860053785/awx/api/serializers.py#L398

proposal:

 - add field `summary_fields.job.type`
 - replace the UI's use of the UJT with this instead

https://github.com/ansible/awx/blob/a1fe60da78445c7970eaa823e88ce21860053785/awx/api/serializers.py#L107

**Comment by AlanCoding** [comment]
Pushed commit to workflows-in-workflows branch

ff5d84f61fdfb365ebaf72a55b2c1c4936c390c8

Manually tested that this works in UI.

**Comment by kialam** [comment]
A quick grep of the `summary_fields.unified_job_template.unified_job_type` field attribute shows that it's being used in various places throughout our app, specifically in `workflows` and the `scheduler`. I don't think we can get rid of the field altogether, which I don't think is what you're suggesting. I _do_ like using the new `type` field in `summary_fields.job` however and think if we isolate the changes to that one particular section in the code, as you've done, it would be fine. I'm going to run e2e and unit tests on that branch to make sure the changes look good.

<img width="461" alt="screen shot 2018-11-02 at 11 30 30 am" src="https://user-images.githubusercontent.com/2293210/47926591-560e3600-de97-11e8-9fc4-4f2de4abe85b.png">

**Comment by AlanCoding** [comment]
I agree with you that all those uses of the field are suspect, even though the field has not been removed.

I was floating some proposals for a change to avoid misleading clients, like:

```json
                "unified_job_template": {
                    "id": 1132,
                    "name": "JobTemplate - TermSpray昉",
                    "description": "InternetCopyConcernDutyAmountGardenExampleStorageIronStep捬",
                    "unified_job_type": "job,workflow_job"
                }
```

but I don't envision something like this getting traction.

**Comment by kialam** [comment]
It would also be slightly different for the UI to parse out that string but not impossible. Tests look good on that change by the way. 👍

**Comment by unlikelyzero** [comment]
blocked by https://github.com/ansible/awx/issues/2606

**Comment by dsesami** [comment]
This works normally now in devel for SJTs in workflows in chrome and firefox.
