### ISSUE TITLE
Running Inventory Source sync, doesn't update connected Project

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#248]
##### ISSUE TYPE

 - Bug?

##### COMPONENT NAME

 - UI

##### SUMMARY

I have the Project set to update

![screenshot from 2017-09-21 16-34-19](https://user-images.githubusercontent.com/1614425/30723238-c10a7650-9eea-11e7-91cb-8f49c9598a99.png)

And the Inventory Source is set to refresh it's inventory from the selected Project

![screenshot from 2017-09-21 16-35-25](https://user-images.githubusercontent.com/1614425/30723261-e6fa1c8a-9eea-11e7-808d-c916ed259f2b.png)

But it when running an inventory sync it isn't updating the Project first. It's using the same commit when the Project was last manually updated to

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by AlanCoding** [comment]
"Update on Project Change" will automatically update the inventory source as a side effect of updating the project. However, this isn't triggered by updating the inventory, the update needs to start with the project.

**Comment by matburt** [comment]
working as designed

**Comment by naisanza** [comment]
@AlanCoding @matburt in that case, the Inventory Source isn't updated when the Project is updated. 

I just tried updating the Project several times, and the Inventory Source never updates.

After manually syncing the inventory Source, the hosts list updates.

**Comment by matburt** [comment]
In the above image you'll need to make sure `Update on Project Change" is checked. Was that the case? Otherwise it will not update immediately when the project is updated.

**Comment by AlanCoding** [comment]
"Update on Project Change" also only runs the inventory update if the project revision has changed, so if you're updating the project when no new commits have landed, the inventory will not update. This is designed for static content that you want to remain synced to the project's revision.

**Comment by L1ghtman2k** [comment]
I have the same issue, 
When I click on 'UPDATE ON PROJECT CHANGE', it throws me this error:

```
update_on_launch: Cannot update SCM-based inventory source on launch if set 
to update on project update. Instead, configure the corresponding source 
project to update on launch.
```
The workaround:
First update the project, then sync the inventory, then launch the template

**Comment by jscheible** [comment]
Another work-around is to have the playbooks and inventories in the same repo (in different directories), and thus in the same project.  Set the Job Template to update the project on launch, and the inventory will be updated at the same time.  (Of course, set the inventory to Sync on Project Update.) 

Ugly, but it does work.

**Comment by IPvSean** [comment]
this is still an issue as of 

```Ansible Automation Platform Controller 4.1.1 ```

for the inventory I have this->
![image](https://user-images.githubusercontent.com/6537680/152255215-dc16564d-cdcb-4b21-b230-efd52c644f1d.png)

specifically you can see that `Update on launch` is checked.

The corresponding Github project also has this set->
![image](https://user-images.githubusercontent.com/6537680/152255425-98e1aafb-df59-46a7-ad66-71b96a4fd2b5.png)

As you can see in the screenshot, I have `Update Revision on Launch` checked.

However... it will not actually sync.... I have tested this about 5-10 times now.... 

it "seems" to do what you think would happen->
![image](https://user-images.githubusercontent.com/6537680/152255631-a444a8f9-4532-4c1e-afe1-eeb25a9178af.png)

step1->  sync github git repo (project)
step2->  sync inventory from that
step3->  run job template

BUT IF YOU CLICK AWAY FROM JOBS TO ANOTHER TAB, THEN BACK THE **SOURCE CONTROL** UPDATE DISAPPEARS?? (sorry for all caps, I am just tired and think I am going crazy)

![image](https://user-images.githubusercontent.com/6537680/152255759-32d19316-8914-4db4-8a27-45acf82608eb.png)

so if I go into one of those github project updates before they disappear, I can see this->

```
{
  "changed": false,
  "before": "d4fb92a363e292adf1738076b4ba4fd092e3c809",
  "remote_url_changed": false,
  "after": "d4fb92a363e292adf1738076b4ba4fd092e3c809",
  "invocation": {
    "module_args": {
      "dest": "/var/lib/awx/projects/_19__sample_vlans",
      "repo": "https://github.com/IPvSean/sample_vlans",
      "version": "d4fb92a363e292adf1738076b4ba4fd092e3c809",
      "force": false,
      "track_submodules": false,
      "remote": "origin",
      "clone": true,
      "update": true,
      "verify_commit": false,
      "gpg_whitelist": [],
      "accept_hostkey": false,
      "accept_newhostkey": false,
      "bare": false,
      "recursive": true,
      "single_branch": false,
      "refspec": null,
      "reference": null,
      "depth": null,
      "key_file": null,
      "ssh_opts": null,
      "executable": null,
      "umask": null,
      "archive": null,
      "archive_prefix": null,
      "separate_git_dir": null
    }
  },
  "_ansible_no_log": false
}
```

it says it is NOT changing... so something is up... because if I do a manual one...

![image](https://user-images.githubusercontent.com/6537680/152256088-cbf90754-3e84-4526-a31f-58f2462563c8.png)


**changed**

weird huh?

**Comment by AlanCoding** [comment]
@IPvSean in your case, do the inventory and the job template use the same project?

If they do, then https://github.com/ansible/awx/issues/11336 would fairly directly articulate what your use case is.

If not, then that would require expanding the scope of what's being talked about there.
