### ISSUE TITLE
API denied when creating new virtualenvs

### ISSUE THREAD

**Issue by ybizeul** [ansible/awx#2500]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Trying to follow https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md, I cannot make the PATCH request to create a new environment.

##### ENVIRONMENT
* AWX version: 1.0.6.23
* AWX install method: docker on linux
* Ansible version:  2.5.5
* Operating System: CentOS 7
* Web Browser: Safari / Postman

##### STEPS TO REPRODUCE

- Followed the aforementioned documentation in a shell into the awx_task container
- Istalled gcc and python-devel along the way to satisfy dependencies
- Installed `pyvmomi` and `netapp-lib` with pip

On the credential part, I created a new application "API Access"

![image](https://user-images.githubusercontent.com/182035/47264321-d71f1200-d514-11e8-99ef-69b1304090ec.png)

as well as a new token for `admin`

![image](https://user-images.githubusercontent.com/182035/47264326-fb7aee80-d514-11e8-9a06-cb365d14bd90.png)

I can now query the configuration :

![image](https://user-images.githubusercontent.com/182035/47264333-1f3e3480-d515-11e8-8875-ee95795f1522.png)

but I cannot `PATCH` the new environment :

![image](https://user-images.githubusercontent.com/182035/47264359-b4d9c400-d515-11e8-96c0-2a63806275ac.png)

```
Oct 21 09:44:41 ansible journal: 2018-10-21 07:44:41,314 DEBUG    awx.api.authentication User admin performed a PATCH to /api/v2/organizations/1/ through the API using OAuth token 1.
Oct 21 09:44:41 ansible journal: 2018-10-21 07:44:41,319 WARNING  awx.api.generics status 403 received by user admin attempting to access /api/v2/organizations/1/ from 10.0.1.122
```

##### EXPECTED RESULTS

I should be granted permission

##### ACTUAL RESULTS

I got permission denied

**Comment by ryanpetrello** [comment]
@ybizeul can you give this a shot with a newer version of awx?  We've fixed several notable issues related to custom virtualenvs since then.  When I try to reproduce with your steps in the Docker on Linux environment, it works fine for me:

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/214912/47295187-0dc05f80-d5dd-11e8-862f-d5cb31bf832c.png">

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/214912/47295214-19ac2180-d5dd-11e8-9b07-522f78019149.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/214912/47295326-62fc7100-d5dd-11e8-8918-cd000171b241.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/214912/47295266-3fd1c180-d5dd-11e8-9adb-d4f941b0556a.png">

```
~ curl -kiX PATCH -d '{"custom_virtualenv": "/venv/ryan"}' -H "Authorization: Bearer I9gc5MhKq7zUTC05VBgnKsGfZdASeQ" https://tower.local:8043/api/v2/organizations/2/ -H "Content-Type: application/json"
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Mon, 22 Oct 2018 13:36:05 GMT
...
```

**Comment by ybizeul** [comment]
That's what I feared... I tried an upgrade but it broke django's deployment, or something else.
I need some time to figure out how to do an upgrade without losing secrets, etc...

Will keep you posted

**Comment by ybizeul** [comment]
Thanks after upgrading AWX it works indeed
