### ISSUE TITLE
Clicking WF node as a user with read-only access changes text to DELETED, doesn't show node details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2521]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
As a read-only user of a workflow I would expect to be able to click on a workflow node and at a minimum be presented with a read-only view of the template/project/inv source that was selected _and_ any prompt configuration on that node.  Currently, none of that is shown and the text on the node is changed to DELETED when clicked:

![read_only](https://user-images.githubusercontent.com/9889020/47455518-0c8b6000-d7a0-11e8-9623-167a7da8b826.gif)

**Note that the node/template are not actually deleted but this could be extremely alarming to a user.**

##### STEPS TO REPRODUCE
1. Create an org called org 1
2. Create a workflow within org 1 using all resources from org 1
3. Create an org called org 2
4. Create a user that belongs only to org 2
5. Give the user in org 2 read-only permissions on the workflow created in step 2
6. Log in as the user from org 2
7. Navigate to the shared workflow
8. Click on one of the nodes

##### EXPECTED RESULTS
The left-hand panel will show information about the node in a read-only fashion

##### ACTUAL RESULTS
No information about the node is shown, node text changed to DELETED

**Comment by mabashian** [comment]
This should be addressed when the workflow convergence branch is merged

**Comment by ryanpetrello** [comment]
We ready to close this one?

**Comment by unlikelyzero** [comment]
Since workflow Viz was one of the few components which was migrated to ui_next is likely using the same codebase, let's retest this in the new UI

**Comment by unlikelyzero** [comment]
We need to verify that the WFViz supports Read Only Mode

**Comment by akus062381** [comment]
I just tested this, at first it worked,  but then I started getting the following error when logged in as the read-only user (see below for further description of why this error is popping up and how it might be adjusted to provide more helpful information to the user):

![image](https://user-images.githubusercontent.com/63685497/112369928-27d16100-8cb3-11eb-8492-60528678c8fc.png)

Putting back into needs_devel.

**Comment by akus062381** [comment]
Observations: 
1) This has been fixed and implemented in the new UI.
2) If a WF Vizualizer has multiple nodes in it, a read-only user must be given read-only access to each different type of node in order to view the information about that node. For example- in the above screenshot, the read-only user was given read-only access to abash-workflow, and when they click the "i", they see the information about that workflow. However, they cannot see the info for the nodes attached to that one.

Thoughts: This error message may not be helpful to the user? Perhaps consider a message that lets the user know that they need to contact the admin in order to obtain access to the nodes they need to view?

@ryanpetrello I'll address this toward you since Mike is out on paternity leave.

**Comment by ryanpetrello** [comment]
@jakemcdermott any thoughts on this one?

**Comment by mabashian** [comment]
I think this is working as designed.  If we want to improve the UX in the future we can but closing this for now.
