### ISSUE TITLE
pyvim ssl error

### ISSUE THREAD

**Issue by dmj24** [ansible/awx#2579]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Template

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: Kubernetes
* Ansible version:  2.7.1
* Operating System: Centos7 (containerised)
* Web Browser: Chrome 70

##### STEPS TO REPRODUCE

Edit Dockerfile.j2 and add: "pip install pyvmomi"
build and deploy image. 
The following simple vmware clone script will work manually on the command line inside the awx-web container but will error inside awx

- name: Clone a virtual machine from Template and customize
  vmware_guest:
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ data_center }}"
    cluster: "{{ cluster_name }}"
    folder: "{{vcenter_folder_name }}"
    name: "{{ vm_hostname }}"
    template: "{{ vm_template_name }}"

##### EXPECTED RESULTS

The command should complete as it does using ansible-playbook

##### ACTUAL RESULTS

TASK [../roles/vmware : Clone a virtual machine from Template and customize] ***
task path: /var/lib/awx/projects/_6__main_ansible_repository/roles/vmware/tasks/main.yml:5
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_guest_payload_71zFeM/ansible_vmware_guest_payload.zip/ansible/module_utils/vmware.py", line 505, in connect_to_api
    service_instance = connect.SmartConnect(**connect_args)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", ssl…

**Comment by jakemcdermott** [comment]
Hello - thanks for creating this issue.

We aren't setup to support installations made with modified container image builds - when you modify these images you may break some expected behavior.

Having said that, you should look into our [custom virtualenv feature](https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md) as it allows you to run your job template / playbook using a virtualenv with non-default python packages installed to it.

If you need additional support, please reach out to our community mailing list or stop by our irc channel (`#ansible-awx` on freenode).
