### ISSUE TITLE
The SJT context does not appear on the Host's 'Completed Jobs' view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2589]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
SJTs do not appear on the Hosts Completed Jobs view

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Create a SJT which can run on at least two hosts.
2. Create a WFJT which runs the same playbook as above
3. Run SJT to completion
4. Navigate to the Inventory/ Host / Completed Jobs view
Note: Workflows and JTs are listed, but SJTs are not.

##### EXPECTED RESULTS

The WFJT and SJT playbook runs should be displayed together on the Hosts Completed Jobs view

##### ACTUAL RESULTS

Playbook runs without a sourced parent.

**Comment by unlikelyzero** [comment]
@marshmalien @kialam not sure about this one. I don't know which feature this would fall under

**Comment by mabashian** [comment]
This is the endpoint that the UI is hitting on that page: `/api/v2/unified_jobs/?page_size=20&job__hosts=*host_id_goes_here*&order_by=-id`

**Comment by kialam** [comment]
@unlikelyzero I _am_ seeing sliced playbook jobs under the Host Completed Jobs view:
<img width="1298" alt="screen shot 2018-11-05 at 9 07 01 am" src="https://user-images.githubusercontent.com/2293210/48002716-5d715180-e0da-11e8-89ea-95ee5a512be0.png">

And while I don't see the parent Workflow of the sliced job playbook, this appears to be the default behavior for all Hosts Completed Jobs view; e.g. the completed jobs list does not contain Workflows, sliced or otherwise.
