### ISSUE TITLE
Save button on credentials form should be hidden to auditor user

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#260]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Talked with @trahman73 and the way that all the other forms behave is to hide the SAVE/CANCEL buttons when a user cannot edit a form and instead show a CLOSE button.  The credentials form shows a disabled SAVE button and an enabled CANCEL button.  I discovered this while working on https://github.com/ansible/awx/pull/257.

##### STEPS TO REPRODUCE

1) Create auditor user
2) Create credential
3) Log in as auditor user
4) Navigate to the credential created in step 2

##### EXPECTED RESULTS

Close button, no save button

##### ACTUAL RESULTS

Cancel button, disabled save button

##### ADDITIONAL INFORMATION

<img width="1438" alt="screen shot 2017-09-22 at 4 13 30 pm" src="https://user-images.githubusercontent.com/9889020/30762696-03802bf8-9fb1-11e7-8d16-aeb3e2e9fb69.png">

**Comment by Zokormazo** [comment]
There are some ui errors, but there is an api error too.

rbacUiControlService asks for options on given path to set canAdd value if POST option exists
https://github.com/ansible/awx/blob/b9f2aa3437c6f49186373f74c7c593f013aca3b8/awx/ui/client/src/shared/rbacUiControl.js#L23

Using an auditor user, OPTIONS on projects for example just return GET action, but on credentials returns both GET & POST.

All button activation/disabling boolean statements end with a `|| canAdd` and since canAdd is true for auditor, the button show/hide is not working properly.

From the other hand, on the crendential-list.js the Add button is hardcoded to true when it should be canAdd, althrought since canAdd is broken it will continue appearing with just fixing that.

**Comment by jlmitch5** [comment]
interesting find @Zokormazo

cc @AlanCoding for API thoughts.  It does seem strange to me that POST is returned in the options for a system auditor for the cred endpoint.

**Comment by AlanCoding** [comment]
If you create a user with no other permission, that user has the ability to create a credential. System Auditor is a privilege, and granting it does not revoke any other privileges the user already had, including privileges that all users have.

**Comment by jlmitch5** [comment]
ah yeah, that makes sense (though I could see how it would be advisable to keep the auditor role completely read-only from a usage perspective).

So yeah, implementation here seems like it'd be straightforward and mimic the pattern from other forms...only thing weird here might be that those all use the form json config and the cred form uses our new, componentized pattern of dealing with forms & inputs.

**Comment by Zokormazo** [comment]
Actually the credentials list is not using canAdd from POST like the rest of the section, it has a ngShow: true hardcoded to make the add button visible always. I haven't go further since I was waiting an answer around the API thing

**Comment by ryanpetrello** [comment]
Closing due to age.
