### ISSUE TITLE
Support become plugins

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2630]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Ansible is implementing become plugins here: https://github.com/ansible/ansible/pull/38861

AWX should be able to support this. (We should probably drop the hardcoded list).

**Comment by AlanCoding** [comment]
Looks like Ansible PR moved to ~https://github.com/ansible/ansible/pull/50421~

Still not merged.

EDIT: it moved again, keep reading.

**Comment by matburt** [comment]
Generate list of become plugins from ansible command (cached) and use that to present what is available (if ansible 2.8)

**Comment by mabashian** [comment]
Proposed UI changes for this feature:

The Privilege Escalation Method field is exposed when the user is adding/editing a machine credential.  This field is currently a dropdown with a number of hard-coded options that the user can choose from.  With this feature we'll be opening this field up to support more than just our hard-coded list of options.

Option 1:
Make Privilege Escalation Method a text input field and allow the user to type in whatever they'd like.

Option 2:
Make Privilege Escalation Method a combination of type ahead and input using something like Select2.  [See this Select2 example](https://select2.org/tagging).  In the example the user is able to select from a preexisting list or select what they've typed in the input so far.  In order to support this, the api would need to provide the list of default values in the OPTIONS response.

cc @trahman73 @wenottingham on which option you'd prefer here

**Comment by trahman73** [comment]
@mabashian The Select2 example in Option 2 seems fine to me. Option 1 can be a backup if needed.

**Comment by wenottingham** [comment]
I'd agree with option 2.

**Comment by ryanpetrello** [comment]
@mabashian @wenottingham I'm fine with Option 2 as long as it's understood that the API _won't_ be doing any automatic discovery (e.g., we won't be able to know that you've got a special become plugin in SCM called `please.py`)  We can present a list of common values support by Ansible core, but it should only be a list of _type-ahead suggestions_ - what your installed Ansible supports in practice may vary.

**Comment by wenottingham** [comment]
Yes. (We could dump the current system ansible set, but that's about it.)

**Comment by ryanpetrello** [comment]
cc @mabashian https://github.com/ansible/awx/blob/devel/awx/main/constants.py#L16 for a list of values for the type-ahead widget portion of this.

**Comment by AlanCoding** [comment]
Moved again, @ryanpetrello tipped me off in other places, but I want a link here

currently active PR as of this comment:

https://github.com/ansible/ansible/pull/50991

**Comment by AlanCoding** [comment]
@jbradberry @mabashian the Ansible core PR for become plugins just merged, so this should be un-blocked for final completion / testing. What's it's current status?

**Comment by jbradberry** [comment]
@AlanCoding The backend PR (#3093) is already merged.  The frontend PR (#3165) is still open but I think was more or less there?

**Comment by mabashian** [comment]
@AlanCoding yep, just waiting for #3165 to be tested then we'll get it merged in

**Comment by mabashian** [comment]
Everything's been merged in - closing

**Comment by unlikelyzero** [comment]
I believe that this one may have been merged prematurely
