### ISSUE TITLE
Feature idea: denote invalid items

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#276]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

C.f. https://github.com/ansible/awx/issues/275

Imagine deleting an inventory, project, or credential. Any job templates (and scheduled jobs) that reference these are now invalid, and will fail to run.

We should figure out a good way to denote these invalid items / raise them to be fixed.

**Comment by mabashian** [comment]
Just had a meeting about this enhancement so I wanted to relay that information here.  We discussed two potential paths forward:

1) The UI could glean from related fields that something required has been deleted rendering the JT invalid.
2) The API could provide a flag denoting that a JT/Schedule is invalid that the UI can key off of.

We decided that option 2 would the best path moving forward.  On the templates/schedules for templates lists the UI will denote invalid items with some text/icon (tbd).  This will alert the user that that template will need to be edited and the missing resource replaced with a valid one before the template can be launched/schedule executed.

**Comment by matburt** [comment]
@mabashian does this take care of that for the UI? 

https://github.com/ansible/ansible-tower/pull/4691

**Comment by matburt** [comment]
Some of my notes from the Oct 30th meeting:

We decided that this wouldn't account for credentials at all. The api side will check what it has access to this can be:

* No project (this means that the project has been deleted)
* No inventory - and no prompt-for-inventory selected

Schedule can also check these properties

**Comment by ryanpetrello** [comment]
@mabashian

> The API could provide a flag denoting that a JT/Schedule is invalid that the UI can key off of.

Given that we're not factoring in credentials (because in 3.3, it's perfectly valid to have zero credentials) do we _need_ a new key in the API response to determine this validity?  For a JT, you could detect this stale state if either the `inventory` or `project` were `null` (both of which are present on the JT list _and_ detail `GET` request).

The same is true of Schedules - they have an `inventory` primary key for overrides, and there's a `related` key to the associated `unified_job_template`.  What if we added `['related']['inventory']` and `['related']['project']` helpers to the schedules endpoint to facilitate detection?

**Comment by matburt** [comment]
api side done, moving to UI

**Comment by mabashian** [comment]
@marshmalien does #1441 wrap up all the work for this feature?  I was going to close it but wanted to double check with you before doing so.

**Comment by marshmalien** [comment]
@mabashian Yes. That wraps it up!
