### ISSUE TITLE
Ability to 'show' entered passphrase is lost when editing credential

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2834]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
1. Create a credential
2. You can click 'SHOW' on the passphrase button to show what you're typing in.
3. Go to edit that credential
4. Hit 'replace' so you can enter a new/correct passphrase
5. You can no longer 'SHOW' it; the button is just 'REVERT' to cancel changes

##### ENVIRONMENT
* AWX version: 2.1 (and probably older)

**Comment by ghost** [comment]
@wenottingham I am currently thinking of two possible approaches that we can take:

1. We have both the **SHOW** and **REVERT** buttons, like this

![screenshot from 2019-03-05 18-26-19](https://user-images.githubusercontent.com/15652962/53844642-5f59fd00-3f74-11e9-905c-72bf09906e17.png)

Although, this will have complications - like changing the partial HTML template, because the current version [only supports single button](https://github.com/ansible/awx/blob/devel/awx/ui/client/lib/components/input/secret.partial.html#L7-L15). So we'd either dynamically insert a button, or add a condition to its show/hide.

2. Second approach would be, remove the **REVERT** button and replace it with **SHOW** button as shown below

![screenshot from 2019-03-05 18-27-07](https://user-images.githubusercontent.com/15652962/53844780-dbecdb80-3f74-11e9-99d7-b8bfa30b8950.png)

Now, this approach is a bit simpler than the previous one, as we only have to deal with single button, so that won't require any UI changes in template. Plus, I think we do have a cancel option while editing, so a user wishing to revert can always cancel if they don't want to save the password. So, I think having only SHOW/HIDE makes more sense.

I think we can discuss what might be a better way out here.

**Comment by jakemcdermott** [comment]
We're making some substantial changes to this view and this field over on https://github.com/ansible/awx/pull/3098/

@vismay-golwala This is not a good issue to work on at the moment. If it's not too much trouble, would you please grab another issue from the backlog?

**Comment by ghost** [comment]
@jakemcdermott no problem, thanks for the heads up!

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/issues/2834
