### ISSUE TITLE
there should be an easy setup for  development django environment for Ubuntu  to contribute without docker and vm 

### ISSUE THREAD

**Issue by saurabhchandrapatel** [ansible/awx#2886]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Development envirment 

##### SUMMARY 

there should be an easy setup for  development django environment for Ubuntu  to contribute without docker and vm 

currently, a few blogs which you can find for Ubuntu setup

**Comment by wenottingham** [comment]
Non-container development environment is not currently planned. Adjustments to the current container-based one for easier use on Ubuntu may be accepted as PRs, but we're not currently looking at it.

**Comment by rharmonson** [comment]
They don't care.

Folks have been asking for non-docker installation instructions since its release. I know for I have been monitor and originally I figured it was just a matter of time so I would check back once a month. Silly me assumed no open source project would require the adoption of docker to participate unless it was "Docker" but it is clear they just don't care that they are excluding a bulk of their potential audience.

See this thread.
https://github.com/ansible/awx/issues/989

Imagine how many people come interested in AWX and simply move on to other things for they have no interest in Docker.

Move on to another project that will hear your request and give it due consideration.
