### ISSUE TITLE
Eu-West-3 unavailable for Amazon inventories

### ISSUE THREAD

**Issue by ellagan** [ansible/awx#2934]
Amazon inventories don't support new AWS region.
Could you please add EU West 3 region ((EU) Paris) in available fields when defining a inventory source ?

**Comment by wenottingham** [comment]
We use boto2, there has not been a boto2 release that includes this region as of yet.

**Comment by ellagan** [comment]
Ok, but using "use_endpoint_heuristics" in boto config or using "BOTO_USE_HEURISTICS" environment variable allows guessing endpoint which are not built-in.
We currently use Ansible with boto2 and it works like a charm for manually executed playbooks. I can deploy Ansible and set the BOTO_USE_HEURISTICS in the docker envs, but I can't display eu-west-3 in the available regions.

**Comment by wenottingham** [comment]
Unless I'm misunderstanding, `BOTO_USE_HEURISTICS` allows you to use unknown regions you specify... it doesn't help for the case of discovering those new regions (which is what would be needed for the dropdown).

**Comment by ellagan** [comment]
You are right. That's the method we use because eu-west-3 is not (and maybe won't be) available in the endpoints.json file for boto2

**Comment by syvanen** [comment]
Is there any plans to start using boto3 instead of boto2?
AWS refers to boto3 as the Python SDK and also Boto2's Github page refers to boto3 as way forward.

There are several PR's on boto2 to update the endpoints.json which are not accepted. And seeing how the endpoints.json is now 2 years old I doubt there will be any updates coming. That release 2 years ago added this `BOTO_USE_ENDPOINT_HEURISTICS` -variable to be able to support unknown regions. But it's disabled by default as it can potentially break other things.

So for AWX to be able to support the growing AWS regions we need to either change to boto3 or set the `BOTO_USE_ENDPOINT_HEURISTICS` to AWX's settings.

**Comment by syvanen** [comment]
Also there's no point trying to set `BOTO_USE_ENDPOINT_HEURISTICS` as Tower has hardcoded list of regions and gives error if you try to use something like "eu-north-1" or "eu-west-3".
See: https://github.com/ansible/awx/blob/5cdab1b57a373ef3ecc30fc38347b761b48d8f58/awx/settings/defaults.py#L701

**Comment by wenottingham** [comment]
https://github.com/ansible/awx/issues/171 needs handled first, then we can discuss completely moving off of boto2.

**Comment by AlanCoding** [comment]
Closing because we will track this in https://github.com/ansible/awx/issues/2115

**Comment by sentient** [comment]
Is this still an issue in August-2020 with AWX 14.0.0  
I am trying to get the inventory for us-gov-east but I cannot figure out any work-around to get this working
Running the docker-compose runtime

I did see Tower had issues https://access.redhat.com/discussions/4854041
but where do we change this for awx?
