### ISSUE TITLE
Allow for per-JT disabling of bubblewrap

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#302]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Right now, bubblewrap is a global toggle. There are occasionally cases where a playbook could conceivably require it to be disabled; there should be a way to do that without compromising the security of the entire system.

This should be a job template-level setting that is *only modifiable by the superuser*.

**Comment by AlanCoding** [comment]
This is no longer possible with the introduction of execution environments. We _have_ to run inside a container.

There was an idea thrown around to run without container isolation _per-instance_, under the idea that someone might spin up containers and have them join the mesh (so they are already isolated). So that's another weird route to what container groups do today. But this is all very new and no one is asking for it.

@chrismeyersfsu correct me if I'm wrong closing this.
