### ISSUE TITLE
RFE: Workflow convergence based on status of all the previous jobs

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#3054]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Currently, if you have two jobs in a Workflow converging in one with RUN condition "On success", Tower runs the job if one of the previous one finishes successfully and not if both finish successfully. It would be great if you could set a RUN condition like "Run this convergent job just if these previous jobs finish successfully".

##### ADDITIONAL INFORMATION

Workflow example: 
![wfjt](https://user-images.githubusercontent.com/33290633/51599678-85fe3000-1f00-11e9-93a4-9432a6b38bf5.png)

In the example provided, "Job Template 1" and "Job Template 2" are set  with RUN condition "On success", but Tower runs "Job Tempate 3" if one of the previous jobs finishes successfully and not if both finish successfully.

**Comment by matburt** [comment]
The way to expand on this would be to add a conditional on the convergence point to decide on whether a condition should be applied based on the state of previous jobs leading to the converged node.

**Comment by kdelee** [comment]
* Want way to support OR as we as AND logic
  * Current behavior is OR (e.g. any parent that WOULD trigger causes convergence node to trigger)
    - [ ] migrate any current WFJT that are convergence nodes (have multiple parents), to be set to have "OR" behavior
       * may have some challenge finding these nodes
   - [ ] New default should be “AND” instead of “OR”
* How to present this to users in UI?
    * Just an API property “converged_behavior: ANY/ALL”
    * Need to decide “OR”/”AND” vs. “ANY”/”ALL”
        * @tvo318  + @trahman need to decide
* Want to ensure performance concerns are maintained
    * How heavy are checks for AND/OR logic on front/backend for large workflows?
    * Check for effects on "Do Not Run" logic 
    * Ensure still wait for all parents to finish

DEPENDENCY/ORDER OF OPERATION:
Need to happen AFTER “pause”/”Approval” node https://github.com/ansible/awx/issues/1206
^ Also referred to sometimes as "logic node"

NO WE WILL NOT DO:
* Percentage logic
* ⅔ of parents successful logic, etc

API SCHEMA:
- [ ] Parameter on the WFJT node / WFJ node `"convergence_behavior"` with two choices XOR boolean with different name. Need to discuss more with @tvo318 and @trahman73 for name

UI:
* undecided when node "becomes" convergence node. Perhaps all nodes will have "converged_behavior" attribute, but when will we expose option to users? After node has multiple parents?

**Comment by chrismeyersfsu** [comment]
@Dagon- @piroux I've written a blog post on how to, effectively, get AND behavior out of a workflow as a stop gap https://www.ansible.com/blog/tower-workflow-convergence Let me know if that meets your needs.

**Comment by manderson-it** [comment]
It would be great to have this as a standard product feature. To only have logical OR convergence is insufficient.

**Comment by yeago** [comment]
i think currently in conjunction with the "on success" run option the OR is a pretty unexpected result, as when the user arrived at the convergence step they would have chosen that option already differently to handle the failed states. only giving my 2c because i think surfacing an API to the user to handle partial failure behavior any/all takes on less importance.

**Comment by kdelee** [comment]
@rebeccahhh have you synced up w/ @appuk lately on this?

**Comment by rebeccahhh** [comment]
@kdelee yep, we've been chatting

**Comment by adpavlov** [comment]
I would actually call it a bug instead of feature idea:)
if 2 blocks lead to one, that usually means that last one depends on both previous steps.

**Comment by appuk** [comment]
Tests PR merged, hence closing the issue

**Comment by adpavlov** [comment]
Please add link to commit/merge

**Comment by ryanpetrello** [comment]
@adpavlov this feature is available in awx 9.2.0, which was just published.

Here's the PR:
https://github.com/ansible/awx/pull/5621

**Comment by adpavlov** [comment]
> @adpavlov this feature is available in awx 9.2.0, which was just published.
> 
> Here's the PR:
> #5621

Thanks!
