### ISSUE TITLE
[RFE] Restore deleted assets by admins in Tower

### ISSUE THREAD

**Issue by pravindmali** [ansible/awx#3062]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Customer are using Ansible Tower in multi-tenant env. Different teams are using tower and teams are doing some time mistakes and deleting some stuff which they don't want to.  They are reaching out to admins to see if they can restore those items. Is there a way to provide some kinds of recycle bin which is managed by admins only.  Anyone who deletes any kind of asset goes to recycle bin but can be restored by admins on demand.  There can be limits on number of days or items which can be stored in recycle bin.  But having this feature is a good management feature in multi-tenant env.

**Comment by matburt** [comment]
Make sure you implement proper privilege separation and only give users the proper permissions. DELETE is delete, it's gone.

**Comment by ghost** [comment]
We need to provide following development access to different teams.

1.  Create new project within particular org
2. Create new inventory within particular org
3. Create new credential within particular org
4. Create new Job Template within particular org
5. Create new Workflow Template
6. These people can look stuff created by other people in same org

What is the minimum  privileged level for a person to do the above ? This question is related to my previous question. Please provide answer to this.

**Comment by ghost** [comment]
@matburt, What kind of proper permissions are you talking about? Minimum permission level which is needed for somebody to develop code in tower is Project Admin, Inventory Admin, Credentials Admin, Job Template Admin, Workflow Admin.  Almost admin of everything except org admin. That means all my users(100+) in multi tenant env can delete any asset they like. There is no control provided by Tower on that, no matter whatever permission we assign. 

Biggest problem in being project/job/workflow admin is they can delete stuff created by other users in same org. Because all users are at same level. They should be limited to their assets.

Provide restore functionality will atleast give org admin chance to restore stuff as all users are at same level.
