### ISSUE TITLE
force connection to AD/ldap server is required

### ISSUE THREAD

**Issue by daswars** [ansible/awx#313]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I am trying to connect awx to our Microsoft Active Directory and encounter the following problem

awx only tries to establish a connection to the ad/ldap server if i write the user name : domain\username

This fails: Filter: sAMAccountName=domain\username
the request should look like this: sAMAccountName=username

If I only try to log in with the username, no connection to the ldap server will be established.
(i can see this with tcpdump)
How can I force awx that everyone tries to go against the ldap server

**Comment by daswars** [comment]
i fixed it self thanks

**Comment by matburt** [comment]
How did you fix it @daswars ?

**Comment by tculp** [comment]
I'm encountering this same issue.

Edit for those coming here from the future:
It turns out that sometime in my LDAP settings tinkering, I had successfully logged in far enough with my LDAP user (but not enough to see the login page) for an account to have been created in the users tab using the same username. I assume this was not considered to be an LDAP account, hence AWX not falling back to LDAP auth. After deleting the existing account, AWX resumed authenticating with LDAP and I was able to log in.
