### ISSUE TITLE
Artifacts are not always returned from completed job runs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3193]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
If a job (with artifacts) completes and an API query is made soon after completion, the artifacts are not always returned in the API response. Additionally, the empty response in the artifacts field is the same as if there were no artifacts available _or artifacts at all._

##### ENVIRONMENT
* AWX version: 3.0.0

##### STEPS TO REPRODUCE

1. Run a job which produces artifacts
1. Observe in the network tab that the final query to the finished job after it has successfully ran has an empty response for the artifacts object
1. Note that (more often than note) artifacts is empty

##### EXPECTED RESULTS

1. A job with artifacts should return artifacts once complete
OR
1. A job with artifacts which are being processed should return a more correct state (i.e. processing, incomplete, etc)

##### ACTUAL RESULTS

1. A job will eventual return the correct artifacts _after some time_ in the API response.
1. If the artifacts are not yet processed, the API response is the same as if there were no artifacts available for that job at all.

**Comment by wenottingham** [comment]
> If a job (with artifacts) completes

What specific 'completes' marker is this referring to? The command finishing, or event processing finishing?

**Comment by chrismeyersfsu** [comment]
In the AWX code path, processing facts happens after the ansible process finishes, and after we update the job status. This is problematic because we have already informed the user that "hey your job is done" because the status is now success. Further, the processing of facts can happen any time during the job event processing phase.

**Comment by chrismeyersfsu** [comment]
In the AWX code path, processing facts and artifacts happens after the ansible process finishes, and after we update the job status. This is problematic because we have already informed the user that "hey your job is done" because the status is now success. Further, the processing of facts can happen any time during the job event processing phase.

Thus, a consumer of the API (i.e. the UI) has no way to know when the fact or artifact data is done being processed.

**Comment by kialam** [comment]
Parent ticket: #447

**Comment by unlikelyzero** [comment]
![inconsistentartifacts](https://user-images.githubusercontent.com/12446869/52601338-72bdf080-2e2c-11e9-9bfc-47529bb484f6.gif)

The artifacts are only displayed on refresh in this gif, but the artifacts codemirror is displayed if the api call to the completed job is at the precise time. Otherwise, no artifacts are displayed

**Comment by ryanpetrello** [comment]
I think this is _actually_ a UI issue, not an API one.  Or at least, it's my opinion that the API currently provides everything necessary over the websocket interface to drive the expected behavior.  There are *two* important events we want to listen for, represented by:

A.  The dispatcher actually being _done_ with a job.  This *includes* the work necessary to persist facts/stats.  This is realized through a web socket message announcing the `status=success/failed/error` at the **very** end of our task execution code:

https://github.com/ansible/awx/blob/f61b6f96159452416569f24c1b7750a3b0142681/awx/main/tasks.py#L1081-L1089

B.  The "final event" (`EOF`) - which represents the _actual_ file EOF for the `ansible-playbook` we fork - being received:

https://github.com/ansible/awx/blob/f61b6f96159452416569f24c1b7750a3b0142681/awx/main/dispatch/worker/callback.py#L71-L82

Right now, the UI only appears to refetch the details from `/api/v2/jobs/N/` in response to event `B`, but we should really be doing so in response to _either_ of these events.  In scenarios where `B` happens *before* `A` happens (e.g., fact/stat saving takes awhile, and/or you're running a playbook with _very_ few events), you see the error described by @unlikelyzero where the UI is _not_ updated appropriately once artifacts are saved.

**Comment by unlikelyzero** [comment]
Tested that 10 successive JT+Artifacts complete with rendered `Artifacts` field on Job Results detail page.
@kialam @ryanpetrello do you want to close it?
