### ISSUE TITLE
inventory sync link "click to view log" is broken

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3288]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When I want to click to cloud icon it always take me directly to home page, see where the link is pointing to on screenshot:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1560121/53238280-321a6e80-3699-11e9-967f-4cab043c5d86.png">

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker
* Operating System: MacOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Click the cloud icon in list of inventory sources

##### EXPECTED RESULTS
Take me to job

##### ACTUAL RESULTS
Takes me to home page

**Comment by wenottingham** [comment]
Can you get a browser console of what it's trying to request/do?

**Comment by benapetr** [comment]
I am not sure what you mean, that cloud icon is directly pointing to root page of AWX instead of page that displays sync progress as it is advertising.

Where exactly in browser console would I see this, I wouldn't expect this to be connected to any JS.

**Comment by benapetr** [comment]
but this should be very easy to reproduce in 3.0.1

**Comment by mabashian** [comment]
@benapetr I'm not able to reproduce this issue.  If you hover over the sync status icon you will not see a direct link out to the details view because that list does not have access to the ID of the job and must perform a GET request to know where to route you.  As such, clicking on that icon fires off a Javascript function rather than behaving like a typical `<a href="">` link.  It's possible that an error is being thrown to your browsers console.  If you're using Chrome/Firefox can you take a look at the Developer Tools -> Console for us and report any errors that may be presented when you click on that icon.

This is what I see when I try to reproduce:

![test_sync](https://user-images.githubusercontent.com/9889020/53811244-e8e2de00-3f26-11e9-8bb7-a49f6b1bcbf8.gif)

**Comment by benapetr** [comment]
I am just getting this in console when I click the icon, nothing else
![image](https://user-images.githubusercontent.com/1560121/53884773-9edc2400-401c-11e9-82f8-38fbea604cbd.png)

But now it doesn't do anything, it no longer takes me to home page of AWX, it just does nothing (working... appears for a short time and then disappears and that's it)

**Comment by benapetr** [comment]
I resolved problem with certificate and now there is nothing in console, bug still persist

**Comment by benapetr** [comment]
![screen](https://user-images.githubusercontent.com/1560121/53889718-2dee3980-4027-11e9-9ff6-3261af3a591d.gif)

**Comment by nixocio** [comment]
Reopen if we still see this one on the new UI.
