### ISSUE TITLE
If an Extra Variable YAML/JSON toggle is selected, the Launch button is disabled

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3303]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If an Extra Variable YAML/JSON toggle is selected, the Launch button is disabled

##### ENVIRONMENT
* AWX version: 3.0.1

##### STEPS TO REPRODUCE
1. Edit a JT
2. Toggle the Extra Variable field from YAML to JSON
Note: Launch button is disabled

##### EXPECTED RESULTS
Launch button not disabled because nothing was modified

##### ACTUAL RESULTS
Launch button disabled as if it was a JT Edit
![editjt](https://user-images.githubusercontent.com/12446869/53277683-2186ea00-36d3-11e9-9535-78ea3de4d06e.gif)

**Comment by unlikelyzero** [comment]
Note: this is a symptom caused by the fact that the Extra_var JSON/YAML toggle sets the `isDirty` flag on all forms. For that reason, I'm going to keep this open as a symptom of a design decision which will mean that if further action is needed, this ticket will remain open and closed independent of any other impacts of that design decision.

**Comment by jlmitch5** [comment]
Since the value is "dirty" in terms of it being a different value passed to the api, a workaround would be something like

update launch disable from being "form.$dirty" to being "form.$dirty and not (codemirror field $dirty and justToggleChanged)"
where justToggleChanged is set by callback for parse type change
we would also need to check to see if the value is $dirty in the $watch statement, which would set justToggleChanged to false if it had.

And a note--because of the nature of the issue allows the form to be submitted before saving a change to the api, the users choice of yaml/json would not persist (I think)

**Comment by unlikelyzero** [comment]
Not applicable in the new UI
