### ISSUE TITLE
Display Host description along with its name

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#3348]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
In all views regarding selecting/displaying Hosts, the description field is not shown.
To be honest, I added all my hosts by IP, so the UI always displays only the IP when selecting hosts for example.

I put the hostname in the description field.

I dont have DNS entries for all hostname, thats the reason why I use IPs. I dont want to update my hosts file everytime I add a host.

Is this a good idea or a bad practice of mine?

**Comment by AlexSCorey** [comment]
Host descriptions will be added in future releases.

**Comment by lijok** [comment]
Ran into this yesterday as I was dealing with the same issue
What you can do is set the hostname as whatever, and add a variable "ansible_host" with the actual ip/hostname of the host

**Comment by dsesami** [comment]
@mabashian question for you -- when I move the inventories/demo inventory/HOSTS page to half-width, the description vanishes. Is this intentional? Seems odd that the field vanishes when the page is at half width.

**Half width:**
![Screenshot from 2019-07-24 13-56-08](https://user-images.githubusercontent.com/19942822/61816694-e708b100-ae1a-11e9-8983-f3ef8c5f1fd2.png)

**Full width of same page:**
![Screenshot from 2019-07-24 13-56-24](https://user-images.githubusercontent.com/19942822/61816711-ec65fb80-ae1a-11e9-9cd4-e284e851dd1d.png)

(note that the description field vanishes with no way to see it)

**Comment by dsesami** [comment]
followed up w/ @mabashian , this design is intentional. closing :+1: host description appears with names.

**Comment by Commifreak** [comment]
Since my upgrade to 17.0.1 this is gone again:

![grafik](https://user-images.githubusercontent.com/87267/108367360-ac831800-71f9-11eb-96f2-f59d4b891933.png)

Any config option here?

**Comment by Commifreak** [comment]
@mabashian @dsesami Can you confirm, that this issue is back since AWX 17? Thanks in advance!

**Comment by AlexSCorey** [comment]
This is an issue in the new UI.  Reopening

**Comment by VladoPortos** [comment]
Can confirm its gone :-/

**Comment by Commifreak** [comment]
@mabashian or others: Any update on this?

**Comment by InnocentK** [comment]
Related to the work in https://github.com/ansible/awx/issues/9363

**Comment by InnocentK** [comment]
Resolved
