### ISSUE TITLE
UI should display reason for inherited privileges

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3438]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Right now when you open permission tab, you often see mysterious users with some privileges and you have hard times understanding why they have them - it would be epic if UI told you the reason, like some ? icon which if you hovered on, displayed something like "User is admin because they are admin of organization XX this item belongs to".

I am currently running into some weird privilege conditions which are probably bugs, and I am unable to determine why users have admin privileges on items they definitely shouldn't have. This would help.

**Comment by wenottingham** [comment]
I assume this is for non-revokable privleges?

**Comment by benapetr** [comment]
> I assume this is for non-revokable privleges?

Of course, explicitly granted privileges are not inherited from anything I suppose

**Comment by AlanCoding** [comment]
I'm going to close this in favor of the other issue https://github.com/ansible/awx/issues/3600

Basically, we are at an impasse, in that to allow more types of permissions to be assigned, we need to fully express how permissions are inherited in the UI, which is what this issue is saying. As a matter of housekeeping we are trying to consolidate activity related to old issues like these.
