### ISSUE TITLE
RFE enable vmware inventory plugin for ansible 2.9+

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3508]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Usage of vmware inventory plugin was not enabled with https://github.com/ansible/awx/pull/3266

We should work on getting this enabled in the future.

##### ADDITIONAL INFORMATION

We need to do more research about what differences there may be between script and plugin and get any fixes into ansible core before we can do this.

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/ansible/issues/46727

It's going to be hard to update the script for issues when core is no longer maintaining it.

**Comment by AlanCoding** [comment]
Firstly, this is blocked by the need to convert to collections, because ansible/ansible is no longer accepting patches, particularly not for 2.10, and even if we did a 2.9 backport, it needs to go in the collection first.

https://github.com/ansible/awx/pull/6283

Secondly, this is blocked by actually getting this patch in:

https://github.com/ansible-collections/vmware/pull/58

More patches may be needed, but this passes our first-level of smoke tests.

**Comment by AlanCoding** [comment]
Assuming those blockers are addressed, here is the branch for enablement:

https://github.com/ansible/awx/compare/devel...AlanCoding:vmware_plugin?expand=1

Other stuff needs to merge first before we can seriously consider this.

**Comment by AlanCoding** [comment]
Component issue: https://github.com/ansible/awx/issues/6727

Ongoing work in: https://github.com/ansible-collections/vmware/pull/80

In-progress work for this issue is lumped into: https://github.com/ansible/awx/pull/6283

**Comment by kdelee** [comment]
We are now using the plugin and our regression tests are running and passing -- calling this verified. Any follow up issues for options or small bugs will be tracked in new issues.

**Comment by thekoma** [comment]
The plugin works but I cannot get the tags to work. Also would be useful to group bt folder but the documentation is missing a lot of examples..

**Comment by s-jaiganesh** [comment]
I cannot get the vmware tags in AWX.
