### ISSUE TITLE
Update GCP credentials to JSON format

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#351]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Currently, our GCP credentials are:
- service account email
- project name
- key

However, current GCP best practice is to use the JSON format of their credentials (which is what GCP gives you by default). This JSON file contains all the above data (and more).

We should move to just supporting the JSON format, rather than requiring people to cut and paste values out of the JSON.

**Comment by chrismeyersfsu** [comment]
@wenottingham The current Credential fields lends itself to the p12 auth. p12 is still a thing (I tested it). The new hotness is JSON auth. Should we continue to easily support the p12 flow?

**Comment by wenottingham** [comment]
I believe the P12 format is deprecated.

**Comment by wenottingham** [comment]
Also, discovered in passing that Ansible 2.4 warns that the way we currently pass credentials (as opposed to using the JSON format) is deprecated and may be removed in Ansible 2.5.

**Comment by chrismeyersfsu** [comment]
#### P12 format
It is deprecated. However, you can still run the google recommended command to convert the P12 to PEM:
`cat key.p12 | openssl pkcs12 -nodes -nocerts -passin pass:notasecret | openssl rsa > key.pem`
This PEM file can then be put in a JSON file under `{ "private_key": ...}` OR the PEM file can be passed directly to Ansible gce modules as `credentials_file: /path/to/key.pem`. Similarly with GCE dynamic inventory.

#### Ansible GCE Dynamic Inventory
The inventory ini file has no notion of accepting the `.json` file as `libcloud_secrets` OR you can pass the `.pem` file.

https://github.com/ansible/ansible/blob/v2.4.0.0-1/contrib/inventory/gce.ini

```
[gce]
# GCE Service Account configuration information can be stored in the
# libcloud 'secrets.py' file.  Ideally, the 'secrets.py' file will already
# exist in your PYTHONPATH and be picked up automatically with an import
# statement in the inventory script.  However, you can specify an absolute
# path to the secrets.py file with 'libcloud_secrets' parameter.
# This option will be deprecated in a future release.
libcloud_secrets =

# If you are not going to use a 'secrets.py' file, you can set the necessary
# authorization parameters here.
gce_service_account_email_address =
gce_service_account_pem_file_path =
gce_project_id =
gce_zone =
```

#### Ansible GCE Modules
auths NOT OK, even though the project and service account is contained in the json.
```
Ansible 2.3.2.0
ansible localhost -m gce -a "credentials_file=~/Downloads/gce_cred_full.json.txt
```

auths OK.
```
Ansible 2.3.2.0
ansible localhost -m gce -a "credentials_file=~/Downloads/gce_cred_full.json.txt service_account_email=xxxcompute@developer.gserviceaccount.com project_id="xxx-yyy-zzz"`
```

In summary. Ansible doesn't directly use the parameters expressed in the `.JSON` file, with the exception of the `private_key`.

#### Ideas
Our credential can make available the google generated `.json` file via an ENV variable.
1. For GCE module usage; playbook users can open the `.json` file and consume the other needed params: `project_id`, `client_email` and inject them into the module invocations.
2. For GCE dynamic inventory scripts, our `CredentialType` set of features can't express the generation of the `.ini` file from only the `.json` file without special business logic.
3. Let the UI massage the uploaded JSON into the needed fields.

For 2. we can either
2a. Have special business logic to pull out of the `.json` the values of `project_id` and `client_email` to build the `.ini` file.
2b. Have the API (or UI) extract the `project_id` and `client_email` from the `.json` and auto-fill the two fields values as defaults to help the user, while still allowing them to override.

 For 1. If you choose 2b. we make the users life easier by giving them direct access to `project_id` and `client_email` from an ENV var. Choosing 2a. the user still has to do 1. "manually" in their playbooks.

Implementation wise for 2b; the API will support a json "blob" for `ssh_key_data` as well as the already supported `.pem` file contents. If it's JSON and `username` and/or `project` is not explicitly specified, then extract and fill in: `json.client_email` -> `username` and `json.project_id` -> `project` and store the full contents of the json file in `ssh_key_data`

3. Looks like a good solution too but would require the UI to deviate from it's auto-generated fields pattern to handle this special case. The API could add something in the OPTIONS response that helps with this.

**Note:** We should also update AWX to use the newest env variable, `GCE_CREDENTIALS_FILE_PATH` instead of `GCE_PEM_FILE_PATH`. This resolves deprecation warnings.
**Note:** This will require special business logic in AWX but not at the `CredentialType` level, more so at the view level, which I like.

**Comment by jakemcdermott** [comment]
> 3. Looks like a good solution too but would require the UI to deviate from it's auto-generated fields pattern to handle this special case. The API could add something in the OPTIONS response that helps with this.

👋 Hey guys - This issue should be resolved by: https://github.com/ansible/awx/pull/712. Let me know if you have any questions.

**Comment by voidspace** [comment]
Works great for me.
