### ISSUE TITLE
AWX - HA - Instance Group

### ISSUE THREAD

**Issue by sujiar37** [ansible/awx#3627]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
AWX HA - Docker Compose Stand-alone Installation

##### ADDITIONAL INFORMATION

I have been following this project since from the version `1.X` to the current latest one which is `4.0`. I have huge respect towards this community and the contributors for their efforts. I am checking the possibility of contribution towards enabling HA [ Instance Group ] for Docker Standalone. I wish to contribute towards HA and I have a working model which could be found in [my repository](https://github.com/sujiar37/AWX-HA-InstanceGroup).

**Comment by ryanpetrello** [comment]
Hey @sujiar37,

Neat!  At the moment, I'd be a little hesitant to merge in _official_ support for HA/Swarm in Docker deployments - not because it's a bad idea, but because we already _have_ an official supported deployment mechanism for scaling out clustered instance groups in awx (using kubernetes), and we're already spread pretty thin on people to maintain *another* official supported install method for awx (we very recently - in 4.0.0 - decided to *stop* maintaining one because we didn't have the bandwidth to keep it going).

Like any open source project, we constantly have to weigh the cost of _officially_ supporting and maintaining new things like this - what amounts to a new supported _platform_ for awx in our eyes - just like any feature we'd agree to add.  awx is a fairly fast moving project, and adding official support for this means that any time we want to change architectural details of awx (like how jobs are distributed across a cluster, for instance), we have to spend time making sure it works on _all_ platforms (or we risk leaving users in the dust).

I'm going to close this issue because we generally use these to track planned enhancements and bugs, but feel free to continue the discussion here or potentially in IRC (`#ansible-devel`).

**Comment by zdriic** [comment]
Hello @ryanpetrello 
Could you give me the procedure to install AWX in a cluster mode with Kubernetes ? 
I can't install it with the official doc (https://github.com/ansible/awx/blob/devel/INSTALL.md#kubernetes).
Should I configure Kubectl config file before run install.yml with my personnalized inventory file ?


I have these errors :

TASK [kubernetes : Get Namespace Detail] ******************************************************************************************************************
task path: /root/Kub-awx-install.9.0.1/awx/installer/roles/kubernetes/tasks/kubernetes.yml:2
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl get namespace awx", "delta": "0:00:00.313356", "end": "2019-11-06 08:30:31.489015", "msg": "non-zero return code", "rc": 1, "start": "2019-11-06 08:30:31.175659", "stderr": "error: the server doesn't have a resource type \"namespace\"", "stderr_lines": ["error: the server doesn't have a resource type \"namespace\""], "stdout": "", "stdout_lines": []}
...ignoring

TASK [kubernetes : Create AWX Kubernetes Project] *********************************************************************************************************
task path: /root/Kub-awx-install.9.0.1/awx/installer/roles/kubernetes/tasks/kubernetes.yml:7
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl create namespace awx", "delta": "0:00:00.152700", "end": "2019-11-06 08:30:31.863581", "msg": "non-zero return code", "rc": 1, "start": "2019-11-06 08:30:31.710881", "stderr": "error: no matches for kind \"Namespace\" in version \"v1\"", "stderr_lines": ["error: no matches for kind \"Namespace\" in version \"v1\""], "stdout": "", "stdout_lines": []}


Thanks for your answer

**Comment by matburt** [comment]
>  the server doesn't have a resource type "namespace"

You've got bigger problems. What version of kubernetes is this?
