### ISSUE TITLE
When did you plan to merge runnerpy3 branch ?

### ISSUE THREAD

**Issue by jbrt** [ansible/awx#3688]
##### ISSUE TYPE
 - Even with AWX 4.0.0, playbook execution based on fully python3 modules still fail
 - We need a runner fully compatible with Python 3

##### SUMMARY
I've tried an AWX installation with runnerpy3 branch and execution of 100% python3 module works perfectly. So, I'm wondering when did you plan to merge this branch into the core project ?

Regards,

**Comment by ryanpetrello** [comment]
@jbrt,

> playbook execution based on fully python3 modules still fail

Can you elaborate on what failures you're seeing?  The `runnerpy3` branch is old, `level` has our latest code.

**Comment by jbrt** [comment]
@ryanpetrello 

Sure: I made a couple of custom modules written in full Python3. With the stable release of AWX the main runner is only compatible with Python2 code (Python 3 specific syntax throwed a syntax error). 
By using the code present on runnerpy3, this issue doesn't appear anymore. 
So, I'm wondering when the main runner of AWX will can handle Python3 natively (or maybe I missed a tricks for doing that).

**Comment by jbrt** [comment]
Here is an example of AWX traceback (as you can see I used a custom virtualenv):

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 67, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 17, in <module>
    from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 16, in <module>
    from yaml import load as yaml_load
  File "/var/lib/awx/venv/walle/lib/python3.6/site-packages/yaml/__init__.py", line 374
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

**Comment by ryanpetrello** [comment]
@jbrt the problem is that you're running your playbooks using a Python 2.7 virtualenv.  AWX itself runs under python3, but when it executes playbooks, it forks a process that uses a _separate_ py2.7 virtualenv by default (we made this decision because a lot of Ansible community content isn't quite _ready_ for py3 yet).

Have you set up a custom virtualenv with Python3 as described here?

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

What you'll want to do is make a custom `python3` virtualenv and install ansible and any dependencies you need into it.

**Comment by jbrt** [comment]
My bad ! My installation of psutil was not done successfully.
Sorry for this inconvenient.

Regards,
