### ISSUE TITLE
Allow cross organization inventories

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#3774]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Customer request: 

We have a customer who would like to have a single Satellite inventory in one organization. They would like to be able to assign inventory admin privileges to that org, to allow them to be able to create a smart inventory using hosts from that org in a separate org. Allowing this will prevent extra syncs and load against the Satellite server.

**Comment by AlanCoding** [comment]
> They would like to be able to assign inventory admin privileges to that org, to allow them to be able to create a smart inventory using hosts from that org in a separate org.

Smart inventories are restricted to pulling hosts from within a single organization for permissions reasons. In this proposal, how would the user grant Org2 admins access to create a smart inventory that sources from Org1?

Have you tried adding the admins from Org2 to the `inventory_admin_role` of Org1? You can also make a team for the purpose of giving this permission.

**Comment by rvdlinden** [comment]
It is possible to grant full admin rights from an Org1 maintained satellite sync'ed inventory to Org2.
The users in Org2 would be able to see and manage all content of that inventory.

The issue starts when that same inventory (which shows hosts, facts, etc) is used in Org2 within a Smart Inventory. Now the hosts and facts are suddenly not available anymore due to the fact the Smart Inventory and Satellite Inventory belong to different Orgs.

What also works is that if Org1 creates a Smart Inventory from the Satellite inventory and assigns admin rights to it for Org2. Now Org2 would be able to use the Smart Inventory.

In either case, it's always Org1 that needs to initiate the creation of the (Smart)Inventory and allow than others to make use of it. I would however like to take out the responsibility of Org1 and allow each Org to manage their own Smart Inventories BUT based on central the collection of the Satellite hosts and facts. Org1 should only need to allow permissions to new Organizations once and after that each Org should be able to manage their own Smart Inventories as they like.

The main reasons or doing this are:

- Customers tend to add hosts by fqdn, shortname, ip-address and/or cname. Each entry takes up a licenses while in fact it's only one host. If they would always add hosts based on fqdn, at least the license count doesn't go up, but in reality this is not true

- Decomm'ed hosts might not be cleaned and keep lingering in the system. Using Satellite as source + Smart Inventories allows unknown hosts to be removed and will keep the system nice and tidy.

**Comment by TheRealHaoLiu** [comment]
Smart inventories has been deprecated in favor of constructed inventory

Please check out https://github.com/ansible/awx/pull/13303
