### ISSUE TITLE
Upgrade to PostgreSQL 10 or 11

### ISSUE THREAD

**Issue by matburt** [ansible/awx#3778]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

On the AWX application side nothing will really need to change here but:

* Compose definitions need to be updated
* K8s/Openshift startup playbook needs to be updated to point at the new system
* Dev environment and tools we install into the containers need to be updated

For container based deployments, I *think* postgres startup will upgrade the database but we should check this.

**Comment by joseorpa** [comment]
I would be glad to help with this issue. Can you assign it to me?

**Comment by matburt** [comment]
I'd say if you can get something up within the next week or two go for it. This is in the critical path for AWX so we'll end up assigning a comitter to look at it, but if you get a PR up then that'll make things a *whole* lot easier.

**Comment by joseorpa** [comment]
Pull request created #3805
I'm working on Openshift stuff

**Comment by jean-christophe-manciot** [comment]
@rooftopcellist @matburt @joseorpa 
Sorry for being late to this party, but can't we skip the 10 step and go directly to 11?
Postgresql 10 has already been **obsoleted** by several Linux distributions, including:
```
- Debian: since buster (10.0)
- Ubuntu: since disco (19.04)
```

**Comment by rooftopcellist** [comment]
@jean-christophe-manciot We want to keep the postgresql version the same across all of the platforms that we support and some still require we use postgresql 10.x for now.

**Comment by jean-christophe-manciot** [comment]
I believe your policy is **unsustainable** and leads to 2 major issues since it makes at least 2 major distributions stuck with unsupported packages:
- the bugs are no longer patched
- it a also a security issue since the security patches are no longer applied either

By letting AWX dragged by the lowest common denominator, this policy:
- disadvantages the most up-to-date distributions which have made some bold moves and favors innovations & security
- forces everybody to live in the past

AWX can strongly discourage such distributions to remain skittish by dropping its support and **move on**.
