### ISSUE TITLE
Restrict REST API Access based on source IP/Hostname

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#3793]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Is it possible for API access to be restricted from source IP/Hostname?

**Comment by ryanpetrello** [comment]
@ryan012880 this would be pretty difficult to pull off because the UI _itself_ is just a client for the REST API, so you'd need to whitelist the source IP of any browser user.  If you wanted to do something like this, it would probably make the most sense to edit the nginx configuration directly and add directives like:

```
location /api {
    allow yoursubnet/16;
    deny all;
}
```
