### ISSUE TITLE
Will AWX support MySQL Database with the existing code?

### ISSUE THREAD

**Issue by NTDBANNU** [ansible/awx#398]
Trying to migrate from Postgres database to MySQL database with the existing code. we replaced the variables and the connections from postgres sql to mysql in ansible configurations, Dockerfile.j2 under templates and in settings.py. Able to run awx_web container but facing issue with awx_task container. Please find the below screenshots of awx_task container log and AWX login page

<img width="941" alt="awx_task_log" src="https://user-images.githubusercontent.com/24846966/31422766-bc45bae8-ae04-11e7-9279-b062d0aca6b6.png">

<img width="818" alt="awx_ui" src="https://user-images.githubusercontent.com/24846966/31422927-0219978c-ae06-11e7-93fd-6a1f74a1d84f.png">

**Comment by matburt** [comment]
We have no current plan to and this isn't supported in the installer.

**Comment by hardys** [comment]
FWIW I think this could be an interesting feature request to consider, for example in the OpenStack case, frequently OpenStack is deployed with mysql and enabling awx to integrate with the existing DB (and memcached and rabbitmq) would be pretty nice from a deployment perspective.

**Comment by ryanpetrello** [comment]
@hardys having spent a good deal of time (5-6 years) working upstream in OpenStack myself, my experience was that the multi-database support in OpenStack really ended up being:

1.  It works with MySQL.
2. On a service-by-service basis, probably Postgres works for free because we're using SQLAlchemy, but if there's an issue I guess file a bug and somebody will address it?   ¯\_(ツ)_/¯

I've sat in on countless public sessions w/ the OpenStack infra team at dev summits as they wondered when they could _finally_ stop running CI for Postgres 😄.  Supporting both simultaneously _is_ totally possible to do (especially with awesome ORM tools like SQLAlchemy or Django's ORM), but it's also a very notable QE, CI, and maintenance burden - so much so that a community as large as OpenStack has had trouble keeping up.  By comparison, awx is a much smaller, less mature open source project than OpenStack.

> enabling awx to integrate with the existing DB (and memcached and rabbitmq) would be pretty nice from a deployment perspective.

For what it's worth, this is something that we _explicitly_ ask people _not_ to do when deploying awx.  awx has a sophisticated process for determining available capacity for distributing playbook runs across awx nodes - co-locating and sharing services (especially with a service like OpenStack, which can generate a _huge_ amount of traffic over RabbitMQ) causes this process to be unreliable.

As @matburt said, I _really_ don't see us pursuing this.

@NTDBANNU there is a _very_ notable amount of Postgres-specific ORM code in awx, as well as usage of postgres-specific features (such as advisory locks) that simply won't work with MySQL due to implementation discrepancies between the two.  The error you're seeing in your screenshot is one such discrepancy.

**Comment by hardys** [comment]
@ryanpetrello: thanks for the feedback, I do understand maintaining test coverage for multiple DB backends is hard, and I can't argue with your assertions re OpenStack.

My point was more that given that typical OpenStack deployments already have memcached, rabbitmq and a DB, it's kind of a shame when considering AWX integration that it's all duplicated.

Not a blocker by any means, but when I started looking at using AWX with OpenStack recently the first thing I looked for was ways to integrate with our deployment toolchain (TripleO which is based around Ansible and Containers, but expects a common DB, Memcached and RabbitMq at present), and that kind of doesn't fit well due to the opinionated nature of the AWX installer and DB.

Sounds like it's probably a lot of work, but FWIW I'm looking for ways to help so the information/context provided is appreciated :)

**Comment by ryanpetrello** [comment]
Yep - the ask in this issue is valuable feedback - I just figured it warranted a thorough answer on _why_ we're so opinionated about the "no" answer:  it's a _lot_ of work, and awx really runs best when not sharing its services (especially the message bus).
