### ISSUE TITLE
Group Based Mapping When Using Azure AD Authentication Method In Ansible Tower

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#3989]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently we can only use email(with regular expression) to map AD user with Org and Team when using Azure AD authentication method in Ansible Tower. The purpose of this RFE is to map AD user  using AD groups with Org and Team when using Azure AD method.

**Comment by wenottingham** [comment]
To do this, use SAML (which Azure AD also supports) and use the attribute-based mapping there.

OAuth doesn't provide the necessary attributes/bits to do this.

**Comment by lknite** [comment]
@wenottingham Is this SAML direction still the way to go or has support for Azure/oidc improved since 2019?  Might you be so generous as to provide an example of how to set this up so that AWX can use groups claims?

This one seems close, https://groups.google.com/g/awx-project/c/wwtPiL21d4Q/m/HtHG8BFuBQAJ, I'm trying to enter that example via the AWX gui, not quite sure what goes where.  What I'd really like to do though is provide the values to the awx operator in kubernetes so that when awx comes up it is already configured with Azure.

![image](https://github.com/ansible/awx/assets/92187614/d4147486-6a9c-4132-9296-f0fe26c8b48b)
