### ISSUE TITLE
Job Event parent not linked in related

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4127]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

While verifying that job event children were properly linked to when https://github.com/ansible/awx/issues/3798 was fixed, I noticed that the parent was then not referenced by the children.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run the playbook:

https://github.com/ansible/test-playbooks/blob/master/debug.yml

and set `ansible_connection: local`

Do this on an inventory with 500 hosts (roughly).

##### EXPECTED RESULTS

The event:

> Task Started (debug)

is a parent of many other events.

Navigate to /api/v2/job_events/<id of debug event>/children

EXPECT that 
Children have link to parent in their `related` fields

##### ACTUAL RESULTS
No link to parent in `related` fields

##### ADDITIONAL INFORMATION

@AlanCoding I only noticed this because of a comment in a test you wrote...

**Comment by AlanCoding** [comment]
If providing the link incurs a lookup, then providing the link wouldn't be worth the cost, otherwise you would undermine the previous decision to stop linking them. IIRC, we don't have any kind of named URL for job events. I see two options:

 - give some filtered link like `/api/v2/job_events/uuid=xxxx`, where xxxx comes from the parent_uuid field of the current event
 - add some new kind of named-url kind lookup ability like `/api/v2/job_events/xxxx`, where xxxx is the UUID, and get that from the parent_uuid

The 2nd option is more intellectually honest, but the first option would allow me to be lazier.

**Comment by ryanpetrello** [comment]
Did we break something or regress here?  Is there something the UI needs?  If not, I'd probably say "meh" and move on.

**Comment by AlanCoding** [comment]
> Did we break something or regress here? Is there something the UI needs?

no and no.

**Comment by kdelee** [comment]
Ah ok, thanks for clearing that up
