### ISSUE TITLE
Host variables from Microsoft Azure Resource Manager missing

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#4132]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Centos7

##### STEPS TO REPRODUCE

I don't know how to reproduce this issue since I don't know the root cause.

##### EXPECTED RESULTS

Host variables normally show:

> powerstate: 
resource_group: 
image:
public_ip: 
public_ip_name: 
ansible_connection:
public_ip_id: >-
id: 
os_disk:
security_group_id: 
virtual_machine_size:
windows_auto_updates_enabled: 
mac_address: 
type:
location: 
tags:
public_ip_alloc_method: 
provisioning_state: 
plan:
computer_name: 
windows_timezone: 
ansible_host: 
name: 
windows_rm: null
fqdn: 
network_interface_id: 
private_ip_alloc_method: 
security_group: 
network_interface: 
private_ip: 
private_ipv4_addresses:
public_dns_hostnames:
public_ipv4_addresses:
resource_type: 
vmid: 
vmss: 

##### ACTUAL RESULTS

I have a host which only shows the following variables:

> ansible_host: 
computer_name: 
id: 
image: 
location: 
mac_address: 
name: 
network_interface: 
network_interface_id: 
os_disk:
plan: 
powerstate: 
private_ip: 
private_ipv4_addresses:
provisioning_state: 
public_dns_hostnames:
public_ip: 
public_ip_id: 
public_ip_name: 
public_ipv4_addresses:
resource_group: 
resource_type: 
security_group: 
security_group_id: 
tags:
type: 
virtual_machine_size: 
vmid: 
vmss: 

So for example public_ip_alloc_method and private_ip_alloc_method is missing. 

##### ADDITIONAL INFORMATION

I've tried to delete the inventory and start again but same result. Other hosts show all variables. 
We had no issue before version 4.0.0 with this host.

**Comment by awithrow9** [comment]
@AlanCoding @kdelee Can you take a look at this one?

**Comment by AlanCoding** [comment]
The variables `fqdn`, `public_ip_alloc_method`, and `private_ip_alloc_method` were established to be missing from the inventory plugin, and left out knowingly. There is some discussion here:

https://github.com/ansible/ansible/pull/53046

If you have a specific use case that needs these variables, the details of that that would be important information for us to have.

In addition to those, your data shows 

 - 'windows_auto_updates_enabled'
 - 'ansible_connection'
 - 'windows_rm: null'
 - 'windows_timezone'

to be missing. The `ansible_connection` looks like it has been resolved on the core side in https://github.com/ansible/ansible/issues/34689, which may require an upgrade of Ansible for your case.

That leaves 3 more variables without any other background, all which start with `windows_`. It's possible that we may not have known about that because we had a testing gap. We did not see these missing with other instance types. I'm guessing these were Windows boxes? Ping @kdelee

**Comment by nicolaibaralmueller** [comment]
> The variables `fqdn`, `public_ip_alloc_method`, and `private_ip_alloc_method` were established to be missing from the inventory plugin, and left out knowingly. There is some discussion here:
> 
> [ansible/ansible#53046](https://github.com/ansible/ansible/pull/53046)
> 
> If you have a specific use case that needs these variables, the details of that that would be important information for us to have.
> 
> In addition to those, your data shows
> 
> * 'windows_auto_updates_enabled'
> * 'ansible_connection'
> * 'windows_rm: null'
> * 'windows_timezone'
> 
> to be missing. The `ansible_connection` looks like it has been resolved on the core side in [ansible/ansible#34689](https://github.com/ansible/ansible/issues/34689), which may require an upgrade of Ansible for your case.
> 
> That leaves 3 more variables without any other background, all which start with `windows_`. It's possible that we may not have known about that because we had a testing gap. We did not see these missing with other instance types. I'm guessing these were Windows boxes? Ping @kdelee

Hi @AlanCoding 

I'm using ansible 2.8.1. Yes the VM's are windows boxes.

Should I downgrade to ansible 2.8.0?

**Comment by AlanCoding** [comment]
It would be consistent that this block of code is not entered for whatever reason in your particular case:

https://github.com/ansible/ansible/blob/77de663879bcf2f6ab82d5009b8a0b799814750b/contrib/inventory/azure_rm.py#L725-L731

We could see about testing if these are added for a generic Windows box in Azure.

**Comment by ryanpetrello** [comment]
@AlanCoding It sounds like this is a problem specific to Windows machines (in terms of remaining issues we know about)?

**Comment by nicolaibaralmueller** [comment]
depricated
