### ISSUE TITLE
Error on Playbook syntax

### ISSUE THREAD

**Issue by AndreMTrindade** [ansible/awx#4166]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Good morning. You have a problem on playbook syntax. 

##### ENVIRONMENT
* AWX version: Recent Version

##### ACTUAL RESULTS

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/xubuntu/Downloads/awx/installer/roles/local_docker/tasks/compose.yml': line 25, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Start the containers
  ^ here

**Comment by AndreMTrindade** [comment]
Ansible version: 2.5.1

**Comment by AndreMTrindade** [comment]
I changed "docker_compose" to  "docker_service" on "/home/xubuntu/Downloads/awx/installer/roles/local_docker/tasks/compose.yml"

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/pull/4164

**Comment by aubrel** [comment]
This has probably already been recognized but just to make it explicit, I believe this is due to the Ansible version used here being below 2.8 (version mentioned here is 2.5.1). `docker_service` did not become known as `docker_compose` until v.2.8: https://docs.ansible.com/ansible/latest/modules/docker_compose_module.html#synopsis

**Comment by dandoetech** [comment]
just wanted to try out awx shortly in a dev env. Does anyone know why I should need ansible to start a docker container? Seems like someone is really loving ansible a lot ..

**Comment by MrAmbiG** [comment]
For those who want to have a quick running awx on your kubernetes, just use the awx operator which will do the job but unfortunately it won't allow us to install a specific version of awx.
It is so unfortunate that @redhat @ibm  has made it so unnecessarily difficult for those who want try their flagship devops/automation product. There are a lot of helm charts which install much complicated systems on k8s with configurable values.yaml. It is in the redhat's best interest to serve their product as everybody else is doing so that one need to spend hours to learn their proprietary method of installation, dependencies, bugs, problems etc.,
