### ISSUE TITLE
Make machine credentials available in the playbook

### ISSUE THREAD

**Issue by fvzwieten** [ansible/awx#4169]
##### ISSUE TYPE
I would like to see that the machine credential is NOT an exception and also provide it's data to the playbook, for example using environment variables.

##### SUMMARY
Example use-case: Create a VM on a public cloud, ie Azure. Part of the VM creation is to specify a credential to be able to log-in into freshly created VM. It would be great if one could use the machine credential data for it, either the username/password or the prov esc user/pass or the ssh key info, depending on how the VM is created on the target cloud. After that, the same machine credential can then be used to run playbooks in this VM.

**Comment by ryanpetrello** [comment]
We're unlikely to do this for machine credentials as they exist today because it's a pretty notable change to our security model for SSH auth - machine credentials are *intended* to be used for authentication between the Tower host and the managed host(s) where a playbook runs.

cc @matburt @wenottingham

**Comment by wenottingham** [comment]
Yeah, I don't think we'd do this in a general way.
