### ISSUE TITLE
Job Results - Output Header

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4221]
## Job Results - Header

Mockup: https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs-output/

The data necessary to populate the header will come from `/api/v2/jobs/:id`.  Note that some of this data will not be available until the job finishes running.  We should display `...` for Plays, Tasks, and Hosts while the job is running.  We should display `00:00:00` for Elapsed Time while the job is running.

#### Job Results Header Tasks
* Display Job Name
* Display Job Status
* Display Plays count
* Display Tasks count
* Display Hosts count
* Display Elapsed Time
* Delete button is out of scope for this issue and will be handled by https://github.com/ansible/awx-pf/issues/221
* Mark strings for translation
* Make sure header is responsive
#### Not in Scope for MVP
* Download icon
* Relaunch icon
* Schedule icon
* Full screen expand/collapse icon
* Host status bar
* Search

**Comment by jakemcdermott** [comment]
<img width="1439" alt="Screen Shot 2019-06-15 at 8 56 51 AM" src="https://user-images.githubusercontent.com/9753817/59551699-b2682680-8f4b-11e9-8b21-b59b80d48b81.png">

**Comment by mabashian** [comment]
Adding a few things to this (I think most if not all of these things apply to the area above the output):

- add Failed badge count to the header area when count is greater than 0
- add Unreachable badge count to the header area when count is greater than 0
- add dropdown to filter output by status
- add dropdown to filter output by verbosity level (this one will require further discussion)

**Comment by marshmalien** [comment]
>add dropdown to filter output by status
>add dropdown to filter output by verbosity level (this one will require further discussion)

Tracking output filters in: https://github.com/ansible/awx/issues/5906

**Comment by dsesami** [comment]
Few things:

Plays, Tasks, and Hosts labels do not appear when the playbook is launched. I expected a "..." status. Is this intentional?
![Screenshot from 2020-02-18 10-22-43](https://user-images.githubusercontent.com/19942822/74749811-bb2a9e00-5238-11ea-9b81-6d86d64972b4.png)

The sparkline box is animating when the job is in progress, but it is still missing the above-mentioned fields.
![Screenshot from 2020-02-18 10-25-09](https://user-images.githubusercontent.com/19942822/74750009-03e25700-5239-11ea-9094-3fce87e58c38.png)

Complete jobs display normally. Failed and unreachable counts display correctly as well.

**Comment by dsesami** [comment]
Confirmed with @marshmalien that the above behavior is intentional. This may change with the websockets work, so it's something that should be followed up on. Once automation stubs are fleshed out for this item, I'll close it out.
