### ISSUE TITLE
Usage of  start_line and end_line query parameter with txt_download of job output in REST API

### ISSUE THREAD

**Issue by gsakkar** [ansible/awx#4329]
##### ISSUE TYPE
 Usage of  start_line and end_line query parameter with txt_download of job output in REST API incase job out put is more than 1 MB

##### SUMMARY
/api/v2/jobs/{id}/stdout/
Retrieve Job Stdout
the start_line and end_line query string parameters can be used to specify a range of line numbers to retrieve.

I will poll the job stdout in periodic interval using start_line and end_line so that i will avoid duplicate output to be parsed in to script. But if the job output content is larger than 1MB then i will go with query_string ?txt_download but i cannot use the start_line and end_line along with txt_download query string

Expected:
/api/v2/jobs/{id}/stdout/?txt_download=txt&start_line=N&M

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker
* Ansible version:  2.7.6
* Operating System: Linux
* Web Browser:

##### EXPECTED RESULTS

Expected:
/api/v2/jobs/{id}/stdout/?txt_download=txt&start_line=N&M

##### ACTUAL RESULTS
Unable to poll the job output incase more than 1 MB

**Comment by ryanpetrello** [comment]
@gsakkar,

For performance reasons, we limit the size of output on the `stdout` endpoint.  In order to accomplish the start/end line calculation you've referenced, you've actually got to load the data into memory, and that can get expensive for larger stdout content.

If you want to work around this, you can always raise the setting that affects this:

```python
>>> 1024 * 1024 * 5
5242880
```

```json
HTTP PATCH /api/v2/settings/job/
{"STDOUT_MAX_BYTES_DISPLAY": 5242880}
