### ISSUE TITLE
unable sync projet from git repository

### ISSUE THREAD

**Issue by wilfried79** [ansible/awx#4342]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I just make a fresh install of awx on rhel 7.6.
I create credential to connect to my gitlab server
I create a project to sync playbook from gitlab
job failed with the following error
fatal: Authentication failed for 'http://$encrypted$:$encrypted$@gitlab/ansible/galera-cluster.git

credentials are ok
sync is ok on my awx 3.0.0 server; same credentials, same settings, same network

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: RHEL 7.6
* Web Browser: firefox 68

##### STEPS TO REPRODUCE

create credentials to connect to gitlab server.
create projects and run it

##### EXPECTED RESULTS

job succed

##### ACTUAL RESULTS

authentication failed despite credentials are ok

##### ADDITIONAL INFORMATION

before make a fresh install to reproduce the issue, I try to upgrade my awx server (3.0.0).
same result

**Comment by AlanCoding** [comment]
I have attempted to reproduce this by creating a private repo on gitlab.com.

Project:
 - scm_url: https://gitlab.com/ansible-engineering/test-playbooks.git
 - credential: SCM cred w/ username & password for gitlab

This works without any problem. I find that the SCM url passed into the git module in the project_update.yml playbook is `https://$encrypted$:$encrypted$@gitlab.com/ansible-engineering/test-playbooks.git`

Right now, the difference in my and your steps looks like http vs. https, so that's my best guess as to your error.

I do want to point out that I used the clone link from gitlab

![Screen Shot 2019-07-18 at 8 09 47 AM](https://user-images.githubusercontent.com/1385596/61456539-5b7fb380-a934-11e9-97d2-3b505f50ed96.png)

and I did find that using the SSH option did not work, but that might be because I don't know how.

If you would share the format of the URL and any other non-secret parameters you used I can revisit this.

**Comment by wilfried79** [comment]
My host has a proxy configured to access to internet.
on release 6.0.0, contener has the same settings has the host.
The solution to my issue is to add an exception on environment variable to exclude proxy for gitlab server
_export no_proxy=<gitlab host>_

rebuild contener and test
