### ISSUE TITLE
Schedules should be in template details, not template list

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#446]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Schedules live in the list view. That's weird compared to everything else. We should move them.

![schedule](https://user-images.githubusercontent.com/5208768/31626389-7da5183e-b277-11e7-91ba-5f6f9768cf53.png)

##### ENVIRONMENT
* AWX version: 1.0.x

**Comment by mabashian** [comment]
I took a quick look at what this would take this morning since #829 is currently outstanding.  Theres some non-trivial work needed here.  I was hoping that we could just add schedules to the related object in the form config and let the boilerplate state generator logic kick in but its going to need more massaging than that.  I think we've got a couple of options here - 1) Add some custom logic to the state generator to handle schedules list/add/edit (sort of like permissions) or 2) De-couple all the state trees that need this schedule tab from the state generator and manually define all of the necessary states.  Option 1 is certainly faster but option 2 is probably the direction we want to go long-term.

**Comment by jaredevantabor** [comment]
this is fixed in devel now

**Comment by gamuniz** [comment]
@jaredevantabor I'm trying to test this but don't know exactly what I'm testing. Are we supposed to see a schedules tab and also the schedules link on the jobs page?

**Comment by jaredevantabor** [comment]
@gamuniz, yes, there should be a schedules tab now in the edit view of the resource. Additionally, the schedule icon should direct the user to that schedules tab.
