### ISSUE TITLE
Unable to convert a notification to webhook type

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4521]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to convert a notification to webhook type. Note: this may affect more than just webhooks

##### ENVIRONMENT
* AWX version: 6.0.0 (regression from older versions of AWX)

##### STEPS TO REPRODUCE

1. Create a notification (i.e. grafana notification).
2. Save
3. Edit notification type to webhook.
4. Save

##### EXPECTED RESULTS

Save without error

##### ACTUAL RESULTS

Error on save

##### ADDITIONAL INFORMATION
![Screen Shot 2019-08-20 at 9 02 42 AM](https://user-images.githubusercontent.com/12446869/63349981-86419b00-c32a-11e9-9eca-6429000d3d11.png)

**Comment by jladdjr** [comment]
Adding some context. I ran into this as well after following the steps given in the description. In my case, the UI was attempting to PUT:

![image](https://user-images.githubusercontent.com/4440360/63408255-71551e00-c3a3-11e9-86d9-51c8a4ea292e.png)

I suspect that some of the old config is being carried over into the payload for the new NT config, which can lead to mismatched fields. I suspect that moving from one type of NT to another has been a problem for a little while, but haven't confirmed.

**Comment by unlikelyzero** [comment]
note this is a regression when updating to the latest AWX

**Comment by jladdjr** [comment]
@unlikelyzero - Did some digging and found that if a user created a NT of type X, then changed the type to Y, we weren't validating the notification configuration. [This change](https://github.com/ansible/awx/compare/2eaf62a62d9efa4a5c69acba3a369db4f15f130a...jladdjr:extend_nt_validation) ensures that we do.

@keithjgrant - when I run awx with the new validation in place ^, I see that the UI is posting configuration fields that aren't used by the API. For example, when I create a webhook NT, the API responds with:

![image](https://user-images.githubusercontent.com/4440360/63690865-9641fa80-c7c2-11e9-9890-72d27c195e30.png)

The dev console shows those fields being included in the payload:
![image](https://user-images.githubusercontent.com/4440360/63691005-f20c8380-c7c2-11e9-8465-51e3b695d4e4.png)

@keithjgrant - can you tell where the UI is adding in those extra fields?

When I looked at Grafana, I also saw some unrecognized config fields creeping into the payload:
![image](https://user-images.githubusercontent.com/4440360/63691102-2ed87a80-c7c3-11e9-825b-63ccfb11b424.png)

I haven't checked the other NT types, but suspect several of these may be affected.

Final thought, getting back to the original issue here - @keithjgrant, do you know if the UI is reposting the old config for a NT if the NT type gets changed? I'm wondering if that's actually contributing to the issue @unlikelyzero spotted here.

It seems like whenever a user switches to a different notification type, the UI should purge any configuration fields not relevant to the current type. It may even been reasonable to simply clear _all_ notification config data if the type changes (def seems like it'd be an easier approach if the UX was considered acceptable). So, for example, even though both email and webhook have a username field, may be reasonable for the UI to not persist that field if the user changes NT types (currently it does if I switch between the two types).

**Comment by jladdjr** [comment]
> note this is a regression when updating to the latest AWX

@unlikelyzero - are you saying this currently affects the devel branch? If the issue is not introduced by the notification templates feature, I would vote to handle this outside of that feature. The fix involved changing the validation for NT's, which could easily have side-effects. What do you think about handling this after custom NTs merges?

**Comment by unlikelyzero** [comment]
@jladdjr woof. Took me a while to understand what I wrote. 
This is a regression introduced in devel (3.6.0) and not the notification template PR, itself.

**Comment by jladdjr** [comment]
> This is a regression introduced in devel (3.6.0) and not the notification template PR, itself.

@unlikelyzero - okay, perfect, thanks for clarifying. yeah, when I looked at our NT validation, I didn't see anything in the validation section that was [changed by my PR](https://github.com/jladdjr/awx/blame/templated_messages/awx/api/serializers.py#L4257), so makes sense that this predates notification templates.

**Comment by keithjgrant** [comment]
> Final thought, getting back to the original issue here - @keithjgrant, do you know if the UI is reposting the old config for a NT if the NT type gets changed? I'm wondering if that's actually contributing to the issue @unlikelyzero spotted here.

In the example given initially (changing from Grafana to Webhook), the UI posts with a notification_configuration.username of `null` (unless one is added by the user—in which the save is successful). When a new Webhook NT is created, this field is omitted entirely. Since this is an optional field, it should either a) not post the value b) post it with an empty string or c) the API should interpret the null as an empty string.

> It seems like whenever a user switches to a different notification type, the UI should purge any configuration fields not relevant to the current type. It may even been reasonable to simply clear _all_ notification config data if the type changes (def seems like it'd be an easier approach if the UX was considered acceptable). So, for example, even though both email and webhook have a username field, may be reasonable for the UI to not persist that field if the user changes NT types (currently it does if I switch between the two types).

I think this generally makes sense — though there is a _long_ list of fields to clean up among all the various NT types, and I don't want to have to write something handling each and every one if it can be avoided. I'm looking into how feasible it is to keep only the name, description, organization, and custom messages, while clearing all other fields...

**Comment by jladdjr** [comment]
> I think this generally makes sense — though there is a long list of fields to clean up among all the various NT types

@keithjgrant - I'm a js n00b, so ignore if this thought is garbage.. is there a way no create a namespace in js (put the config in some kind of dict?) so that you would only need to clear the namespace / dict and not go through a laundry list of variables that need to be cleared?

I realize that would involve a refactor, but sounds like that might help keep the config tidy in general? 🤷‍♂

**Comment by keithjgrant** [comment]
Okay, I found a piece of code already in place to deal with the null value for `username`, but it was only applied to email notifications, not Webhook ones (both use that field). That turned out to be a pretty simple fix...

Before I make the PR, have we seen any other errors stemming from changing types? or was switching to Webhook the only real issue here?

**Comment by elyezer** [comment]
@keithjgrant have you tried converting from email to webhook? I remember running into something similar when trying to do that.

**Comment by keithjgrant** [comment]
Just checked: Email to Webhook works now. I also changed to each of the other types, filling in any required fields, and saw no errors when saving.
