### ISSUE TITLE
A JT with multiple notifications attached (for same event type - e.g. started), only uses one NT to generate all notifications

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4533]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A JT with multiple notifications attached (for same event type - e.g. started), only uses one NT to generate all notifications

##### STEPS TO REPRODUCE
1. Create three Slack Notification, each with a different custom message
2. Create a JT with all 3 Slack Notifications configured on start
3. Launch JT

##### EXPECTED RESULTS
Each custom message should be delivered

##### ACTUAL RESULTS
One custom message is delivered three times

**Comment by jladdjr** [comment]
The issue is here:
https://github.com/jladdjr/awx/blob/7f035cb2918d0e2fbe10fdcbeb3e14ee32f8b4e6/awx/main/models/notifications.py#L481-L490

This was introduced in 3.6 ([here](https://github.com/ansible/awx/pull/3982/files#diff-3cbeaef3dc5e8f2a7f463efcd3edddc1))

* If you build a function inside of a for loop
* .. and ~that function references the iteration variable~ (UPDATE: I was wrong about this part, see next comment)
* .. then all functions will be given _the same variable reference_
* .. and the function with effectively act on the final value the iteration variable took

![image](https://user-images.githubusercontent.com/4440360/63391979-8d3bce00-c369-11e9-8421-f7dde8e03bbb.png)

**Comment by jladdjr** [comment]
Turns out my diagnosis wasn't quite right. It's not so much that the variable stored inside our function is getting re-written each iteration, it's that the method itself isn't fetching the variable's definition until the last possible moment (late-binding). A better description of the issue is given [here](https://stackoverflow.com/a/3431699/10669572).

![Screenshot 2019-08-20 20 42 23](https://user-images.githubusercontent.com/4440360/63401097-0bf53300-c38b-11e9-9c30-37832e323657.png)

Issue is fixed by https://github.com/jladdjr/awx/commit/24a9efa56

(cc @beeankha re: Python trickiness ^)

**Comment by jladdjr** [comment]
Updated description / steps to reproduce. Issue wasn't isolated to WFJT, could be reproduced using any UJT.

**Comment by unlikelyzero** [comment]
Verified with latest
