### ISSUE TITLE
use new / improved pf react component for multiple typeahead select input

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4613]
##### ISSUE TYPE
 - Bughancement

##### SUMMARY
Here are some enhancements we'd like to see in our existing multiselect input component:
- tab should close the menu if it is open.
- arrow keys should cycle through the available selections (like it does for a regular multi select widget)
- if using keyboard to make a selection, enter key should add a tag for the  _currently selected item_, which is not necessarily the same as the _current text input_.

This functionality is _already_ in place with the existing pf-react multiple typeahead select input: https://patternfly-react.surge.sh/patternfly-4/components/select/. It is my understanding that this component was updated recently to use simple chips, which addresses the reason why we weren't using it before.

This issue is for swapping our existing `MultiSelect` component (in use for JT labels and a few other places) for the pf-react component.

**Comment by jakemcdermott** [comment]
this blocks https://github.com/ansible/awx/issues/4618 and https://github.com/ansible/awx/issues/4504. Please remove `state:blocked` label from https://github.com/ansible/awx/issues/4618 and https://github.com/ansible/awx/issues/4504 when this is resolved.

**Comment by jakemcdermott** [comment]
this is blocked by https://github.com/ansible/awx/issues/4431 because we want to hold off on any significant changes to the template add/edit views until that lands.

**Comment by AlexSCorey** [comment]
The other issue that I came across with PF Multiselect is that not only did they not have simply chips, but I was also unable to style the chips that component generates to match our existing chips.

**Comment by keithjgrant** [comment]
After wrestling with this for a while, I think this needs to wait for the PF `<Select>` to mature more. Here are some of the problems I ran into.

Our current version of patternfly-react:
* crashes if empty array of options is provided (can be worked around a bit)
* pressing Enter to select an option submits the whole form

After upgrading to latest patternfly-react:
* produces warning `<form> cannot appear as a descendant of <form>` [https://github.com/patternfly/patternfly-react/issues/3157]
* pressing Enter to select option still submits the whole form
* crashes attempting to render selected chips — this can be fixed with more data restructuring, but after encountering the other issues here, I'm not sure it's worth our time just yet

**Comment by keithjgrant** [comment]
The "latest patternfly-react" mentioned above refers to:

```
    "@patternfly/patternfly": "^2.36.0",
    "@patternfly/react-core": "^3.112.3",
    "@patternfly/react-icons": "^3.14.12",
    "@patternfly/react-tokens": "^2.6.31",
```

**Comment by keithjgrant** [comment]
Patternfly has closed their issue. This might be unblocked now; we should test it out.
