### ISSUE TITLE
google Hangout chat using webhook results in error

### ISSUE THREAD

**Issue by nakacya** [ansible/awx#4665]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Sending notifications to google Hangout chat using webhook results in error

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: CentOS 7.6,Amazon Linux 2
* Web Browser: Chrome

##### ACTUAL RESULTS

```
2019-09-05 08:01:30,801 ERROR    awx.main.notifications.webhook_backend Error sending notification webhook: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"body\" at 'message': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message",
            "description": "Invalid JSON payload received. Unknown name \"body\" at 'message': Cannot find field."
          }
        ]
      }
    ]
  }
}
```

**Comment by ryanpetrello** [comment]
@nakacya,

This isn't really a bug in AWX; it's an HTTP response from Google's API telling you it doesn't know what to do with the JSON payload that's being sent (because it would be impossible for AWX to send a _default_ JSON structure that _every_ HTTP service out there understood).

If you want to craft a JSON body in your notification body that adheres to Google's Hangout API, you'll need to set up a notification with a custom body (this is a new feature in AWX 7.0.0, which was just released yesterday) that matches whatever Google Hangouts expects.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/214912/64342500-9dce8400-cfb8-11e9-882c-c72d82f8b013.png">
<img width="301" alt="image" src="https://user-images.githubusercontent.com/214912/64342510-a1faa180-cfb8-11e9-89ca-290c10347405.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/214912/64342512-a9ba4600-cfb8-11e9-9077-e3548693a591.png">

**Comment by nakacya** [comment]
I understand.
If you wrote the following contents in Customize Messages, you can confirm that you can output the same as slack notification

`` `
{"text": "{{job_friendly_name}} # {{job.id}} '{{job.name}}' {{job.status}}: {{url}}"}
`` `

**Comment by tobsome** [comment]
@nakacya, did you get it working? Figuring out the same issue. Tried it for some hours now to get the notifications via Google Chat webhook working without any results..

**Comment by gerbz** [comment]
@nakacya @tobufckr same here, any luck?

**Comment by tobsome** [comment]
@gerbz, nope, unfortunately not.

**Comment by kurokobo** [comment]
For the recent Google Chat, this is the working example configuration.

![image](https://github.com/ansible/awx/assets/2920259/489bcb84-15f6-45a2-b0a6-bb4087ba02d2)

**Comment by Tas-sos** [comment]
Yes exactly! If you want to use Webhook to send notifications to **Google Chat** or **Slack** you have to click to `Customize messages..` and then add the `text` keyword and then you message, for example: `{"text": "Something"}`.

### Examples

![Screenshot 2023-10-06 at 14-52-10 Ansible Automation Platform Tas-sos Webhook tests for dist-git](https://github.com/ansible/awx/assets/9154286/cbe9e8ce-d07c-40e7-a96f-31deede43270)

![Screenshot 2023-10-06 at 14-52-58 Ansible Automation Platform Tas-sos Webhook tests for dist-git](https://github.com/ansible/awx/assets/9154286/c7b8c9ea-d572-4215-a4fe-98c8f91678ac)

![Screenshot 2023-10-06 at 14-53-19 Ansible Automation Platform Tas-sos Webhook tests for dist-git](https://github.com/ansible/awx/assets/9154286/5d8c5615-fbef-47d8-ad92-2973ecde1338)



:warning: Note: The `Test` functionality never works because by default Webhooks add the message to `body` section/field of sending data. So no worries about that, just test your Webhook directly by enabling it for a Job Template/Workflow.
