### ISSUE TITLE
Replace pluralization util with Lingui pluralization

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#4705]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some pluralization is done with a util function based on English rules. These should be update to use Lingui pluralization for proper internationalization: https://lingui.js.org/tutorials/react.html#plurals

**Comment by AlexSCorey** [comment]
Looked at the docs for https://lingui.js.org/tutorials/react.html#plurals and it seems that their `<Plural>` isn't the right tool for the job.  It requires that we know which word we might want to pluralize ahead of time and then hard code the message with the singular and plural form of the word.  Because so often the words we want to pluralize are variables it's hard to know how to pluralize it. 
So, the recommendation @keithjgrant  and I have is to modify our `pluralize()` to take a # of items, and then the word to be pluralized in both singular and plural form.  ie. `pluralize(numOrgs, 'organization', 'organizations')`
