### ISSUE TITLE
dashboard and job list are very slow with larger UnifiedJob counts

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#4708]
```sql
awx-dev=> SELECT COUNT(*) FROM main_unifiedjob;
 count
--------
 606596
(1 row)
```

(on a poorly provisioned laptop with all services running in Docker containers)

Logged in as an org admin and clicked back and forth between the dashboard and jobs list tabs:

Before:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/214912/64664243-8cec9b00-d41c-11e9-82ac-080315a8063c.png">

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/pull/4706

**Comment by kdelee** [comment]
is https://github.com/ansible/awx/pull/4717 meant to also go in for this issue? or you wanting to punt on that for now and just test this as is?

**Comment by ryanpetrello** [comment]
@kdelee nope, #4717 isn't going in in the near future.

**Comment by elyezer** [comment]
I am now at:

```
awx-dev=> SELECT COUNT(*) FROM main_unifiedjob;
 count  
--------
 495371
(1 row)
```

And the page has been consistently being loaded in about 2.5~3 seconds. Since when the system had just a few jobs run. I will keep getting jobs run to check closer to the number mentioned in the issue description `606596` to check if we have loss of performance. I am running AWX on docker containers which is the same scenario as described by this issue.

![Screenshot from 2019-10-08 09-18-11](https://user-images.githubusercontent.com/48132/66398904-9978fa80-e9ac-11e9-8447-5cb16ba73efd.png)


Update:

Now with more jobs:

```
awx-dev=> SELECT COUNT(*) FROM main_unifiedjob;
 count  
--------
 717160
(1 row)
```

The page still loading in about 2.5~3 seconds:

![Screenshot from 2019-10-08 13-35-17](https://user-images.githubusercontent.com/48132/66418674-95f76a80-e9d0-11e9-8a2b-7007a2d5ad99.png)

With that we can consider this as being verified.
