### ISSUE TITLE
RFE: Allow `'` Character in Usernames

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#4728]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Allow the `'` character in usernames inside of Tower. This is currently a limitation in the underlying django library: 

https://docs.djangoproject.com/en/1.11/ref/contrib/auth/

**Comment by wenottingham** [comment]
Because this is a limitation of the underlying library (and the underlying OS, for usernames on the box itself), this is unlikely to change before upstream changes.

If these usernames are coming from a third-party source (such as SAML), we suggest using a different value for `attr_username` in the SAML config, e.g.: `"attr_username": "email"`.

**Comment by jbradberry** [comment]
Neither Django 3.2 LTS nor the latest 4.1 support this.  This seems extremely unlikely to change, so closing this.
