### ISSUE TITLE
CLI: Sometimes characters in monitoring stdout get transformed in incorrect ways

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4771]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In certain environments using `monitor` for watching sdtout of adhoc commands leads to characters getting transformed.

##### STEPS TO REPRODUCE

Still unclear on this, have one environment in particular that reproduces it (but not sure how it is different than my local setup)

##### EXPECTED RESULTS

When comparing stdout from `api/v2/ad_hoc_commands/ID/` to local stdout, they should be the same

##### ACTUAL RESULTS

Small aberrations like:
`prepare_env()\x1b[0m` getting transformed to `prepare_en…\x1b[0m` (notice the `v()` in `prepare_env()` has been transformed to `…`

##### ADDITIONAL INFORMATION

This happened in a python3 install

**Comment by jbradberry** [comment]
So it turns out that `AdHocCommandEventSerializer` (as well as `JobEventSerializer`) has logic that truncates the `stdout` fields down to `settings.EVENT_STDOUT_MAX_BYTES_DISPLAY` when accessing the event list endpoint, which is what the cli accesses.  The events detail endpoint as well as the special `stdout` endpoint are unaffected.

We almost certainly don't want the results coming from the cli to be mangled, and it seems like the most straightforward way of dealing with this is to add a parameter to the events list endpoints telling it to provide un-truncated output.

**Comment by kdelee** [comment]
this is still showing up for me in python3 environments :/

**Comment by kdelee** [comment]
There is an upstream fix that is working for me, so taking out of `needs_test` for now...now just waiting on backport

**Comment by ryanpetrello** [comment]
@kdelee the fix for this is present in `devel` now: https://github.com/ansible/awx/pull/5140

**Comment by ryanpetrello** [comment]
I'm going to close this one @kdelee; let me know if that's wrong.
