### ISSUE TITLE
when format of extra variables will switch to YAML all the time

### ISSUE THREAD

**Issue by AlexanderStohr** [ansible/awx#4833]
when in templates editor view i am editing "EXTRA VARIABLES" in JSON format and saving it i will always end up in anything being displayed in YAML format.

side note:
JSON was selected because i am trying to use ansible vault.
as found out from other bug reports ansible vault syntax will not work with YAML formatted items.
and further (to my understanding) it got told that there is no 100% exact forward-backward conversion between the two formats due to a special keyword in YAML. on the other side i am unsure at the moment if all valid JSON codes will see an exact conversion towards YAML.

i would have expected my selected input format for this window to persist. am i right?

**Comment by AlanCoding** [comment]
> and further (to my understanding) it got told that there is no 100% exact forward-backward conversion between the two formats due to a special keyword in YAML.

I'm confused by that takeaway. In principle, Ansible has developed a standard for representing their custom types (unsafe, vault) in a way which is convertible between YAML and JSON. That has not been fully adopted in AWX. Adoption involves customization of both python (backend) and frontend libraries.

But the issue here seems mostly unrelated and I believe is UI.

**Comment by AlexanderStohr** [comment]
i feel like it has to go here because it was observed (and rooted?) in the web GUI.

**Comment by AlexSCorey** [comment]
This issue is no longer valid n the new UI.
