### ISSUE TITLE
Add a toggle to turn off/on https://galaxy.ansible.com/ as a fallback server

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4954]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the current implementation of https://github.com/ansible/awx/pull/4589, you can change the "fallback" server in the file settings. But this isn't very accessible.

This issue is to add a toggle like "Use Galaxy Fallback", and it's it's checked, it will use the public galaxy in the server list at lower precedence than what's defined in the settings. If it is unchecked, it will _only_ use the server defined in the CTiT settings.

**Comment by elyezer** [comment]
The toggle is now present on the UI:

![Screenshot from 2019-10-22 14-52-54](https://user-images.githubusercontent.com/48132/67320047-b26cca00-f4db-11e9-970d-37124059af69.png)

To validate it was working was done the following:

1) Created a project to sync https://github.com/ansible/test-playbooks/tree/with_requirements
2) Created a job template to run the `use_debug_role.yml` playbook
3) Ran the job template with the access to the public galaxy enable and it worked as expected
4) Ran the job template with the access to the public galaxy disabled and it failed as expected. It tried to fetch from the primary galaxy server and since one was not configured it failed.

With all that we can consider this as verified.
