### ISSUE TITLE
Job notification sent before all data available

### ISSUE THREAD

**Issue by Menduist** [ansible/awx#500]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - Notifications

##### SUMMARY
I have a template with 50 hosts. When the job completions notification are sent (I use a webhook callback), they only contain data for ~16 hosts. If I immediately use the API to retrieve "job_host_summaries", I get only ~30 hosts. After a few secs, all the hosts are retrievable using the API.

##### ENVIRONMENT
* AWX version: 1.0.0.588
* AWX install method: docker on linux
* Ansible version:  2.4.0.0

##### STEPS TO REPRODUCE
Since this is a timing problem, I don't know how to replicate it exactly, but with my setup (50 hosts and AWX hosted on a powerful server), even with the "Hello World" project, the notifications are sent too early

##### ADDITIONAL INFORMATION
https://github.com/ansible/awx/blob/73ece87e6895377b36cb7f19fb9d2bc414dad6cc/awx/main/models/jobs.py#L633
According to this, this problem is known, but only wait for any host data to be available, but not all of it.

**Comment by jangsutsr** [comment]
The root of this issue is the asynchronous nature of job task run: job host summaries, alone with all job events, are fetched and saved by `run_callback_receiver` process, while anything else of a job run are done in `celeryd` process. There is no guarantee these two processes will finish simultaneously: the event queue `run_callback_receiver` is listening on is probably not done processing when the task in `celeryd` officially finishes, especially when the job produces a large number of callback events.

Possible solutions:
* Document the possible incompleteness of job host summary list in notification body.
* Remove job host summaries from notification body.
* As suggested, wait a solid 5 secs rather than just 'wait for any host data to be available'. (in this way host data loss is less likely, but still possible).
* Figure out a way to detect if `run_callback_receiver` finishes, probably using `playbook_on_stats` event.

Don't have a good answer yet, just want to shed some light on this issue.

**Comment by Menduist** [comment]
I don't think just removing the host summaries is a viable option, since many people will just use the API to retrieve these informations, and have the same problem.

I didn't look deeply at the code yet, but from what you said, couldn't celeryd report the number of hosts of the job, and then in notification_data simply wait for `len(summaries) == target_host_count`?
As a bonus, the number of host would be stored directly in the Job, instead of having to look in job_host_summaries (maybe it's already here but I didn't saw it)

Or the insert of the job summaries could be atomic, this way you can be sure to have either the full set or nothing.

**Comment by matburt** [comment]
I think in this case we just need to wait until we get all information back before emitting the notification.

**Comment by matburt** [comment]
We did this with set_stats we need to do it here

**Comment by ryanpetrello** [comment]
@Menduist I've just merged a fix which _should_ resolve this issue - thanks for reporting it!

https://github.com/ansible/awx/pull/1652
