### ISSUE TITLE
on instance detail, capacity slider broken and used capacity bar out of alignment

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#5022]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The capacity slider is no longer a slider, but rather a round button with no slider. You can adjust it down, and it does apply, but after that it cannot be moved.

Additionally, the used capacity bar is out of alignment and sticking out of the row.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser: chrome

##### STEPS TO REPRODUCE

Go to instance groups page
click on an instance group
go to instances tab
See that capacity slider is not a slider
Grab button and drag left, see that it "works" in lowering number of forks
See that cannot now move it again, it is stuck
Notice that bar is out of alignment.

##### EXPECTED RESULTS

Slider is a slider and can be used over and over
Capacity bar is aligned properly

##### ACTUAL RESULTS

BEFORE:
![Screenshot from 2019-10-16 16-06-07](https://user-images.githubusercontent.com/29239279/66958393-130c8a80-f036-11e9-97ee-ce65549043c8.png)

AFTER:
![Screenshot from 2019-10-16 16-06-20](https://user-images.githubusercontent.com/29239279/66958400-17d13e80-f036-11e9-92ab-5968a5237da9.png)

##### ADDITIONAL INFORMATION

possibly related: 
https://github.com/ansible/awx/issues/1436
https://github.com/ansible/awx/issues/4788#issuecomment-539632382

We believe this came in with container groups merge to devel
@elyezer reproduced this as well

**Comment by elyezer** [comment]
In order to verify this the window was resized to be on different UI responsive breakpoints and then was tried to interact with the slider. The following screenshots demonstrate how the UI was presented, on all of them the slides was working as expected.

![Screenshot from 2019-10-22 15-20-01](https://user-images.githubusercontent.com/48132/67322956-cadee380-f4df-11e9-9a5f-60846e73edcb.png)

![Screenshot from 2019-10-22 15-19-26](https://user-images.githubusercontent.com/48132/67322958-cadee380-f4df-11e9-81a7-4adee2c1987e.png)

![Screenshot from 2019-10-22 15-19-02](https://user-images.githubusercontent.com/48132/67322959-cadee380-f4df-11e9-905c-594496638d34.png)

![Screenshot from 2019-10-22 15-18-50](https://user-images.githubusercontent.com/48132/67322960-cadee380-f4df-11e9-8090-35da76d04ce8.png)

![Screenshot from 2019-10-22 15-18-36](https://user-images.githubusercontent.com/48132/67322962-cb777a00-f4df-11e9-9c1e-657711b989c4.png)

![Screenshot from 2019-10-22 15-18-24](https://user-images.githubusercontent.com/48132/67322964-cb777a00-f4df-11e9-9268-879e990b2aa9.png)

![Screenshot from 2019-10-22 15-18-06](https://user-images.githubusercontent.com/48132/67322965-cb777a00-f4df-11e9-9a19-af8d8f3312c8.png)
