### ISSUE TITLE
Logger enhacement

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#5034]
##### ISSUE TYPE
 - Create new loggers in order to improve output for reporting

##### SUMMARY

**Customer suggestion**

- A new logger (eg: job_status) which send all information for a job summarized in one event with all necessary fields.

Another enhancement, more basic (in my point of view) is to implement useful fields in the job_event logger in the summarized field for all executed job :

- Organization :
  * Id
  * Name

- Job_Template:
  * Name
  * Id
  * Limit (Host)

- Project :
  * Name
  * Id

- Inventory :
  * Name
  * Id

With all these fields, we could cross informations to build proper reports and dashboard related to Ansible Tower Organization and projects which is not possible today.

**Comment by wenottingham** [comment]
This would be logging something which doesn't directly correspond to anything else in Tower, I'm not sure how this would fit off the top of my head.

**Comment by wenottingham** [comment]
This is not something we plan to do, for multiple reasons:
- annotating job events with this data would make processing events even slower, and make providing real-time storage more difficult. It's the most performance-sensitive part of the code, which is why we don't process that data heavily.
- for job_status, we'd look for more specific changes to activity stream, rather than creating a new logger
