### ISSUE TITLE
JOB TAGS and SKIP TAGS not being honored via "prompt on launch"

### ISSUE THREAD

**Issue by mattch3wie** [ansible/awx#5110]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
User entered values for SKIP TAGS and JOB TAGS are not honored.

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: RHEL 7.6
* Web Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Configure a template to have null or populated values in JOB TAGS and SKIP TAGS and activate "prompt on launch" for those 2 fields.
![tags_null](https://user-images.githubusercontent.com/56000662/67570164-bb89b100-f6fe-11e9-8cd9-bc0b31d44edf.png)

On launch, enter the tags one might want to run/skip
![tags_tagged](https://user-images.githubusercontent.com/56000662/67570267-eecc4000-f6fe-11e9-9671-c37445f0c425.png)

Click next to get to the job preview. The preview shows no tags have been assigned to the job though they were in fact entered. On launch of the job, the requested tags will not be honored.
![tags_nothonored](https://user-images.githubusercontent.com/56000662/67570508-934e8200-f6ff-11e9-9d57-3af0801cd660.png)

NOTE: If the template is saved WITH values, and prompt on launch is selected. You may REMOVE those predefined values with no issue. Any new values entered during "prompt to launch" will still go unrecognized.

##### EXPECTED RESULTS

JOB TAGS and SKIP TAGS values are assigned via "prompt on launch" and honored in job execution
![tags_honored](https://user-images.githubusercontent.com/56000662/67570589-cbee5b80-f6ff-11e9-9eb9-d8f34d52e7df.png)

##### ACTUAL RESULTS

Jobs run without honoring the tags entered by the user.

**Comment by AlanCoding** [comment]
I can not reproduce this. I see that you prompt for inventory as well, so I tried all the combinations I could think of, using the default inventory vs. a different one.

![Screen Shot 2019-10-25 at 9 18 13 AM](https://user-images.githubusercontent.com/1385596/67574448-78344000-f708-11e9-865d-d87a78abc40b.png)

The tags & skip tags take effect in the job.

**Comment by mattch3wie** [comment]
Interesting! We have a test instance (Running the same OS and AWX  version but running Ansible version 2.8.6) and we experience the same issue.

Is there any log, debug option, or etc that might expose more information to go on vs just workflow and screenshots?

**Comment by apollo13** [comment]
I am also seeing this and it is a regression in 8.0.0. @AlanCoding which info can we provide? All I can say is that entering the that results in no tag on the run screen.

**Comment by AlanCoding** [comment]
In your screenshots, the tags did not show up in the "preview" window. This suggests that it's a UI bug. It would be helpful to confirm that if you could open up the Right Click->Inspect->network in Chrome, and then confirm that the data submitted to the `/launch/` endpoint as a POST did not contain the tags or skip_tags (probably didn't).

Also check if you see any errors in the UI console. Those will be helpful if you do see any.

**Comment by apollo13** [comment]
@AlanCoding This was the data sent to the server:
```
{"extra_vars":"---\n","job_tags":"","limit":"tcmgmt1dev","job_type":"run","verbosity":0}
```

js console shows no errors.

**Comment by mattch3wie** [comment]
I did a quick check job; here is the submission data for /launch/ as requested @AlanCoding ( I believe I got the correct stage of /launch/ :P)

`{job: 257, ignored_fields: {}, id: 257, type: "job", url: "/api/v2/jobs/257/",…}
allow_simultaneous: false
artifacts: {}
controller_node: ""
created: "2019-10-25T16:48:36.639609Z"
description: "DO NOT USE - STILL IN PLANNING/CONFIG STAGE"
diff_mode: false
elapsed: 0
event_processing_finished: false
execution_node: ""
extra_vars: "{}"
failed: false
finished: null
force_handlers: false
forks: 0
id: 257
ignored_fields: {}
instance_group: null
inventory: 6
job: 257
job_args: ""
job_cwd: ""
job_env: {}
job_explanation: ""
job_slice_count: 1
job_slice_number: 0
job_tags: ""
job_template: 18
job_type: "check"
launch_type: "manual"
limit: ""
modified: "2019-10-25T16:48:36.693744Z"
name: "Linux Patching"
passwords_needed_to_start: []
playbook: "patch.yml"
project: 17
related: {created_by: "/api/v2/users/4/", modified_by: "/api/v2/users/4/", labels: "/api/v2/jobs/257/labels/",…}
result_traceback: ""
scm_branch: ""
scm_revision: ""
skip_tags: ""
start_at_task: ""
started: null
status: "pending"
summary_fields: {,…}
timeout: 0
type: "job"
unified_job_template: 18
url: "/api/v2/jobs/257/"
use_fact_cache: false
verbosity: 1
webhook_credential: null
webhook_guid: ""
webhook_service: ""`

Note that I too saw no error in the UI console.

**Comment by elyezer** [comment]
I was able to verify that this is working now. Did the following:

1) Created a Project to sync https://github.com/ansible/test-playbooks
2) Created a Job Template to run the `test_tags.yml` playbook and prompt on launch for tags and skip tags.
3) Run the job template and had the following as the input:

![Screenshot from 2019-10-30 16-05-04](https://user-images.githubusercontent.com/48132/67895088-3d7b3f00-fb30-11e9-9501-8906e2c5eca8.png)

![Screenshot from 2019-10-30 16-05-14](https://user-images.githubusercontent.com/48132/67895098-44a24d00-fb30-11e9-9444-986c40fd5a70.png)

4) Checked the output and it was like the following:

![Screenshot from 2019-10-30 16-07-39](https://user-images.githubusercontent.com/48132/67895120-4ec44b80-fb30-11e9-8bd0-e63660e6f412.png)

5) Verified that the tasks with the `other_tag` tag were not run and only the tasks with the tag `tag` were. Also verified that the task `task_with_multiple_tags` was not run because it had both the `tag` and `other_tag` tags and therefore it would get skipped.
6) Run the job again and this time haven't filled neither the skip tags and run tags. The run can be seen on the screenshot below and this time all the tasks were run as expected.

![Screenshot from 2019-10-30 16-11-13](https://user-images.githubusercontent.com/48132/67895307-9cd94f00-fb30-11e9-9ee8-77bdc01686c7.png)

**Comment by apollo13** [comment]
@elyezer What's the corresponding commit id in the devel branch?

**Comment by ryanpetrello** [comment]
https://github.com/ansible/awx/commit/841975d72bd61a4b918d9a7becb7d7a04488ac0b

**Comment by apollo13** [comment]
Thank you!
