### ISSUE TITLE
Support inventory plugins that live in a collection

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5149]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Followon of https://github.com/ansible/awx/issues/3776.

Once collections can be exposed in some way (imagine handwaving here), however they are exposed needs to work such that an custom inventory plugin can be sourced from a collection (as opposed to requiring it be in source control only).

**Comment by AlanCoding** [comment]
Same as https://github.com/ansible/awx/issues/4720?

**Comment by wenottingham** [comment]
Maybe, this is more if a user wants to use a custom plugin from a custom collection, not using a custom collection for our stock ones.

**Comment by AlanCoding** [comment]
Since acba5306c69edc2493826b0bfad891702ff3ce53, you can use an inventory plugin from a custom collection if put in the collections requirements.yml. Whatever we do for sourcing collections for jobs should apply the same to inventory updates, yes. A similar statement might be made for ad hoc commands too, which is different from SCM inventory since there's no project involved, but collections-as-top-level object would change that. Or maybe there will be some new-type-other-than-SCM inventory.

**Comment by jladdjr** [comment]
Think I assigned this to myself w/out realizing it was a 3.7 enhancement. I'm following the thread here, but will unassign myself for now. Want to make sure the plugin migration gets in first.

**Comment by AlanCoding** [comment]
If done in any sane way, this would be taken care of along with https://github.com/ansible/awx/issues/5150

If we wire things up to take an arbitrary configuration, this system should also allow arbitrary collections / plugins.

If we provide guard rails for the users, that options system should apply to https://github.com/ansible/awx/issues/3780 equally. Metadata is metadata. The schema for options is already out there.

**Comment by wenottingham** [comment]
Putting in needs_test... once exec envs are live, this should be  a verification-only issue.

**Comment by AlanCoding** [comment]
So then we're limiting the scope to SCM ~collections~ inventory with references to a collection in an execution environment.

@yagomarques is collecting test cases and this is one that I can outline specifically.

**Comment by wenottingham** [comment]
SCM *configuration files* with references to a collection in an exec env, yes.

**Comment by AlanCoding** [comment]
Good catch, I wrote that wrong.

The inventory file is in SCM. The collection is in the execution environment.

**Comment by kdelee** [comment]
@yagomarques @shebangbash assigning you because we should add coverage for this in the execution-environments branch

**Comment by AlanCoding** [comment]
We have already tested using this inventory file in conjunction with a custom EE that contains `community.general` plus the needed dependency:

https://github.com/ansible/test-playbooks/blob/master/inventories/linode_fqcn.linode.yml

There might be other test cases which are desirable, but I would like something more specific for the scope of this issue.

Otherwise close this issue as finished.

**Comment by kdelee** [comment]
I agree this coverage exists, closing
