### ISSUE TITLE
Inventory update fails with Python script source due to missing /usr/bin/python in AWX 9.0.x

### ISSUE THREAD

**Issue by stephenk-gr** [ansible/awx#5242]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a python inventory script within a project attempts to update it fails with the error: 
`([Errno 2] No such file or directory`
It appears that when the script is run the environment expects /usr/bin/python to exist and this is missing in AWX 9.0.0 & 9.0.1
Creating a symlink within the awx_task container allows this to run successfully.
```ln --symbolic /usr/bin/python3 /usr/bin/python; ```

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linuxr
* Ansible version:  2.8.5
* Operating System: Centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add a project which contains an executable python inventory script.
Add an inventory.
Add an inventory source with "Sourced from a Project" type, using the added project and select the python script as the inventory file.
Save & sync the inventory source

##### EXPECTED RESULTS

Sync to complete and hosts to become available in the inventory.

##### ACTUAL RESULTS

Received the following error:
```
[WARNING]:  * Failed to parse
/tmp/awx_11903_lqb82efj/project/inventories/scripts/hosts.py with script
plugin: problem running
/tmp/awx_11903_lqb82efj/project/inventories/scripts/hosts.py --list ([Errno
2] No such file or directory:
'/tmp/awx_11903_lqb82efj/project/inventories/scripts/hosts.py':
'/tmp/awx_11903_lqb82efj/project/inventories/scripts/hosts.py')
```

##### ADDITIONAL INFORMATION

Confirmed that the script file existed in the location during the inventory update.
When repeatedly running the following within the awx_task container when the update job was running the same error occurred 
`find /tmp -name hosts.py -exec () \;`
This lead me to determine that it was an issue with python. 
Running "python" within the awx_task failed as /usr/bin/python does not exist. 
I confirmed this existed in a previous version.
Adding it back in via symlink fixed the issue.

**Comment by mhurron** [comment]
Pretty sure this isn't a bug. The release notes for 9 say they upgraded the containers to be built from CentOS 8, which makes a changes to installing python.

https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/

Red Hat doesn't recommend linking python3 to python, but since this is a single use container you might be able to get away with it. A better solution would be to call python3 instead of python. It looks like all the AWX stuff calls python3.

**Comment by ryanpetrello** [comment]
Yep, what @mhurron said.  CentOS 8 doesn't have a `/usr/bin/python/` because python2 is being retired **very soon**.

```shell
bash-4.4$ cat /etc/centos-release && /usr/bin/python
CentOS Linux release 8.0.1905 (Core)
bash: /usr/bin/python: No such file or directory
```

Under the hood, AWX now runs entirely on python3.  If you have some specific reason for continuing to run inventory scripts under python2, install it.  However, we highly recommend people switch as soon as possible:

http://pythonclock.org

Realistically, if you're saying that a symlink fixes the problem, then it sounds like your script is already valid python3 code (or is close) - just change your shebang to `/usr/bin/python3`.
