### ISSUE TITLE
Job templates not parsing roles inside nested git subrepos

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#5248]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have some playbooks with roles, something like this:

- hosts: all
  remote_user: root
  roles:
    - common-apps
    - users

if i run this playbook from the web interface, the playbook just completes without executing the roles and the job is marked as successfully completed
- it was working fine prior to version 8.0.0

if i run the same playbook from the celery pod, it executes correctly the roles.

Note: Roles and playbook are on a submodule
I've attache 2 screenshots of the same playbook executed from the GUI and from the celery pod.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: kubernetes
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:
![Screenshot at Nov 05 16-31-20](https://user-images.githubusercontent.com/23634711/68221611-f8e91b00-ffe9-11e9-9b36-1b2e2a8e2071.png)
![Screenshot at Nov 05 16-32-46](https://user-images.githubusercontent.com/23634711/68221624-fdadcf00-ffe9-11e9-80c7-b8f21113522a.png)

**Comment by alancivita** [comment]
i was able to reproduce the bug on a docker-compose deployment. Same issue:
roles are not parsed when templates are launched via GUI

**Comment by alancivita** [comment]
i've also moved the playbook and the roles outside the submodule directory and it worked fine, definitely it's a GUI bug with submodules.
I think it's quite important, can . anyone advise on it please?

**Comment by alancivita** [comment]
@ryanpetrello Hi Ryan, any chance to have a look at this? 
Regards

**Comment by AlanCoding** [comment]
Just to get environment parity, could you report what version of Ansible you hit this with?

**Comment by AlanCoding** [comment]
> i've also moved the playbook and the roles outside the submodule directory and it worked fine

Could you give more information about the directory structure you used? For instance, was the submodule a sub-directory inside of the `roles/` folder? Or was the submodule the entire `roles/` folder? Was it somewhere else pointed by to `ansible.cfg`? Was the playbook at the top-level of the project or somewhere else? When you got a success by moving the role folder outside the submodule, what folder was it in at that time?

These details are important to me right now because there could either be a bug related to handling of submodules, or there could be a bug related to managing the config setting for role paths. There are also a lot of different configurations I could guess, and if there's a layout that slipped through the cracks I need to get tests for that case.

**Comment by alancivita** [comment]
Hi Alan,  thanks for getting back to me.
will be back shortly with all the details

**Comment by alancivita** [comment]
a recap:
the issue is NOT present on awx 6.1.0
i can't test on 7 because of this issue
it's present in awx 8.0.0 - 9.0.0 and 9.0.1

the ansible version is the one provided by awx:


Directory structure:
there's a git repo structured in this way:
a main directory called
platform with a subdirectory called test:
inside the test subdirectory there's the ansbile submodule dir with roles inside

└── test
    ├── ansible
    │   ├── README.md
    │   ├── run-once-site.yaml
    │   ├── roles
    │   │   ├── common-apps
    │   │   │   ├── README.md
    │   │   │   ├── defaults
    │   │   │   │   └── main.yaml
    │   │   │   └── tasks
    │   │   │       └── main.yaml

The playbook "run-once-site.yaml" as you can see is inside the submodule dir.
I got success by moving the roles folder and the playbook outside the ansible  submodule 
 directory, in this case under the test directory: 
 
Feel free to ask for any logs or anything else that you think could help.

**Comment by AlanCoding** [comment]
To be sure I'm reading it right, your job template would reference the playbook `platform/test/ansible/run-once-site.yaml`, is that correct? Or is platform just the name of your repo, suggesting `test/ansible/run-once-site.yaml` in the JT?

**Comment by alancivita** [comment]
that's correct
platform/test/ansible/run-once-site.yaml

**Comment by AlanCoding** [comment]
After looking into the details, this came awfully close to what is already in https://github.com/ansible/test-playbooks/pull/85, but to avoid any false positives in the bug, I made the branch https://github.com/ansible/test-playbooks/compare/master...AlanCoding:submodules_roles?expand=1 to be sure that I don't incorrectly use the role from the parent repo (as opposed to the sub-repo). The job template using the playbook `test-playbooks/utf-8-䉪ቒ칸ⱷꯔ噂폄蔆㪗輥.yml` runs correctly. In this case the playbook and the roles are in the subrepo, as in your case.

I wonder if there's some setting used in submodules that I'm just not applying in these cases? Otherwise I'm kind of stumped.

**Comment by alancivita** [comment]
Hi Alan thanks for the effort!
i just realise that the info i provided are not correct 100% sorry:
so our roles are subrepos as well, so each =indivdual role in the ansible submodule, is a submodule repo itself. 
Sorry about that

**Comment by AlanCoding** [comment]
okay, that is a known limitation. I will re-label this issue.

**Comment by alancivita** [comment]
is a fix planned in the short term?

**Comment by alancivita** [comment]
Hi there,
is there any progress on this one?
thanks

**Comment by alancivita** [comment]
Hello,
is there an ETA on this one?
thanks

**Comment by AlanCoding** [comment]
I put up #7367 as a possibility, but it would still need some more work.

**Comment by AlanCoding** [comment]
Believed to be resolved by https://github.com/ansible/awx/pull/12356
