### ISSUE TITLE
400 Bad Request when using curl callback

### ISSUE THREAD

**Issue by darrenjones24** [ansible/awx#5304]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Following an upgrade, I'm having difficulty using provisioning callback receiving a 400 error/

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: kubernetes
* Ansible version:  2.8.5
* Operating System: Coreos
* Web Browser:

##### STEPS TO REPRODUCE
 curl -vv -k -f -H 'Content-Type: application/json' -XPOST -d '{"host_config_key": "6b81525c-6da4-4911-98a6-6eaa025379e2"}'  https://awx.susx.ac.uk:31768/api/v2/job_templates/18/callback/ 
 or
/usr/local/bin/request_tower_configuration.sh -k -s  https://awx.susx.ac.uk:31768 -c 1803bbdf-c7dd-4359-a561-fb43b57bf97b -t 19

##### EXPECTED RESULTS

Callback to initiate ansible

##### ACTUAL RESULTS
curl: (22) The requested URL returned error: 400 Bad Request

2019-11-12 08:12:46,666 WARNING  awx.api.generics status 400 received by user AnonymousUser attempting to access /api/v2/job_templates/18/callback/ from 139.184.228.25
2019-11-12 08:12:46,670 WARNING  django.request Bad Request: /api/v2/job_templates/18/callback/
2019-11-12 08:12:46,670 WARNING  django.request Bad Request: /api/v2/job_templates/18/callback/
[pid: 133|app: 0|req: 190/1050] 139.184.228.25 () {38 vars in 512 bytes} [Tue Nov 12 08:12:46 2019] POST /api/v2/job_templates/18/callback/ => generated 42 bytes in 628 msecs (HTTP/1.1 400) 8 headers in 247 bytes (1 switches on core 0)
139.184.228.25 - - [12/Nov/2019:08:12:46 +0000] "POST /api/v2/job_templates/18/callback/ HTTP/1.1" 400 42 "-" "curl/7.61.1" "-"

##### ADDITIONAL INFORMATION

AWX 'sees' the correct IP address, and I have set: REMOTE_HOST_HEADERS = ['REMOTE_HOST, HTTP_X_FORWARDED_FOR']

**Comment by ryanpetrello** [comment]
Hey @darrenjones24,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by lukepafford** [comment]
Should this issue really be closed? I've spent the entire day on this and I'm receiving the same error as the original poster. This [reddit post](https://www.reddit.com/r/ansible/comments/b0die2/awx_callbacks_failing_that_no_matching_host_could/) also talks about the issue and what he attempted to do to fix it.

If the feature really does work, then the docs are leading quite a few of us into the pit of failure, since it appears to be pretty simple to configure.

I'll keep hacking away at this, and leave an update if i find out what my personal issue was because as of right now, I can't find any solutions online.

**Comment by darrenjones24** [comment]
If it is any help, I found that putting the node IP addresses inthe PROXY_IP_WHITELIST helps:

`kubectl describe  pod  -n namespace |grep IP: | awk '{print $2}'

 curl -v -X PATCH 'https://user:pass@hostname/api/v2/settings/system/'     -d '{"PROXY_IP_WHITELIST":["xxxxxxxx"]}' -H 'Content-Type:application/json'`

**Comment by lukepafford** [comment]
I finally got to the bottom of why so many people likely have these same problems.

## How do callback URLs actually work?
The how isn't really documented. After playing around with various different proxies, and host inventories, it seems to be pretty simple:
1. Your AWX instance *must* be behind a reverse proxy (or I *think* more accurately, whatever value you have set to the `TOWER_URL_BASE` setting)
2. The IP of the client that is initiating the callback URL request must be sent in a value that AWX is configured to read in the `REMOTE_HOST_HEADERS` setting
3. I didn't confirm this, but it makes sense that your `PROXY_IP_WHILTELIST` should be set to all the IPs of your proxy servers.
4. The IP address must be resolvable by a reverse DNS lookup (or you have the actual IP in the inventory)

## My specific issue
I was accessing my AWX instance from my Nginx reverse proxy that is public facing. 
My requests all appeared to be coming from my public external IP, and since this public IP doesn't exist in the inventory, it complained that the host couldn't be found (rightfully so).

To solve this, I setup an internal Nginx service on my AWX server. I set the URL to the Nginx endpoint as the value of the `TOWER_URL_BASE` setting.

Internal clients were now sending internal requests to the instance, and sending their correct IPs.

Once you realize how it's actually working, it just becomes a simple routing/DNS problem.

**Comment by alvaroc20** [comment]
Hello @lukepafford @darrenjones24  
I'm experiencing the same issue. In my case, it's deployed on Kubernetes using the awx-operator. I've tried adding the node's IP to the whitelist and ensuring the correct headers are in place, yet I still can't perform the callback due to a 400 error. I've been troubleshooting this for two days without success. Does anyone have any insights on what the blocker might be in this private network scenario? It's worth mentioning that since it's set up with the awx-operator, my ability to modify the YAML files might be quite limited.
