### ISSUE TITLE
tower_schedule ansible module

### ISSUE THREAD

**Issue by kfox1111** [ansible/awx#5461]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There is no ansible module for declaratively requesting a job schedule be configured. There needs to be one.

**Comment by AlanCoding** [comment]
Prior attempts:

 - https://github.com/ansible/ansible/pull/60040
 - https://github.com/ansible/ansible/pull/43437

I was hesitant to re-file this as it is, because alternatively, we may add some verification that all endpoints have supported modules corresponding to them (and all fields therein). That would capture this as well as all others. We want to generally avoid dealing with these issues on a case-by-case basis, as established by the AWX CLI.

**Comment by AlanCoding** [comment]
Implemented in https://github.com/ansible/awx/pull/6733
