### ISSUE TITLE
API get requests duplicated 

### ISSUE THREAD

**Issue by stinager** [ansible/awx#5486]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I wrote a custom script to build an inventory. The script simply makes a GET request to an API to retrieve a list of machines with the status "ON".

When this script is launched on AWX, I saw multiple GET requests to the API (actually one per host) instead of only one. I don't know where the problem can come from.
`#!/usr/bin/env python3
import requests
import json
headers = {
    'Content-Type': 'application/json',
    "Authorization": "xxx"
}
url = 'https://xxx.com/api/ppd/machineson'
r = requests.get(url, verify=False, headers=headers)
data = json.loads(r.text)
print({"XPC_PPD": {'hosts': data["objects"]}})`

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker
* Ansible version:  2.8.0
* Operating System:
* Web Browser: Chrome

##### EXPECTED RESULTS
When I run this script locally on my machine it takes less than a second because only one API request is needed.

##### ACTUAL RESULTS
Script runs in 11.0s because 20 API requests have been launched instead of one.
![Capture](https://user-images.githubusercontent.com/18574470/70615769-4ff79680-1c0d-11ea-8111-a9be970cea1f.PNG)

**Comment by AlanCoding** [comment]
To compare the local behavior you need to run `ansible-inventory -i <script>` or `ansible-playbook -i <script>`. It is a published feature of Ansible inventory scripts that it will re-call the script once for every host if it does not provide the `hostvars` dict nested under the `_meta` dict. Yours looks like it doesn't do this, so it is extremely likely that's what's happening. It's also likely that it nests the entire inventory contents under hostvars for every one of your hosts, because the contract it is assuming is that passing the `--host` option to your script will tell the script to give variables for that host.

https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-script-conventions
