### ISSUE TITLE
Make main_jobevents More Efficient

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#5590]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

If running an environment with a large record count under `main_jobevents`, performing maintenance tasks to this table can be delayed due to long running auto-vacuum to the table.

This feature request would like to address one of the following:
- A better tuned postgres configuration that handles this table more efficiently
- An alternative solution to make dealing with jobevents more efficient

**Comment by ryanpetrello** [comment]
I've done quite a bit of work on investigating this over the past several weeks, and I've come to the conclusion that *long term*, we may need to reconsider how we store and query this type of event data when we're talking about scaling beyond, say, a billion rows.  Here are some notes and observations that have come from spinning up single node installs with 1B+ rows.

The bottom line is that when you get this many rows in a postgres table, even simple index scans have trouble keeping up.  Here's an _approximation_ of a query made by a popular request the UI uses to fetch stdout for the job detail view:

```
awx=> EXPLAIN ANALYZE SELECT counter, start_line, end_line FROM main_jobevent WHERE job_id=1000005 ORDER BY start_line DESC LIMIT 10;
                                                                            QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=4.60..4.60 rows=1 width=12) (actual time=1518.164..1518.168 rows=10 loops=1)
   ->  Sort  (cost=4.60..4.60 rows=1 width=12) (actual time=1518.163..1518.164 rows=10 loops=1)
         Sort Key: start_line DESC
         Sort Method: top-N heapsort  Memory: 25kB
         ->  Index Scan using main_jobevent_job_id_571587e8 on main_jobevent  (cost=0.57..4.59 rows=1 width=12) (actual time=0.019..1232.186 rows=2080000 loops=1)
               Index Cond: (job_id = 1000005)
 Planning time: 0.413 ms
 Execution time: 1518.188 ms
(8 rows)
Time: 1519.106 ms (00:01.519)
```

Note that this is event data I inserted basically sequentially on a system at rest over a period of an hour, and that the system has had *very* little actual database activity beyond this.  Additionally, when I generated this data, I:

- Dropped all table indexes
- Inserted all the data
- Recreated the index

...so I don't expect vacuuming or reindexing to make a very tangible difference here.  

This query represents fetching a limit of 10 rows from 2M event rows (for one job) against a total table size of ~1B events.  This is an `m5.4xlarge` with a large disk with a decent amount of free space, and with high (tens of thousands) IOPS.

Notice that’s almost 1.2 seconds spent on an index scan.  `b-tree` indexes are great, but at worst, they're `n log(n)`, which is *fast*, until you start talking **really** big values of `n`.

In my opinion, if we care about fast access times for _our types of usage patterns_, we're starting to hit the limits of row-based relational storage systems, especially as we have users that are increasing pushing the boundaries of a billion events - even potentially beyond 10B as time goes on.

There *are* ways we can improve this today with postgres.  One good option is starting to talk about partitioning this data (potentially by date ranges, i.e., a partitioned event table by month or week).   Something like that might buy us some time and scale.  That said, managing partitions involves more software, and a more sophisticated setup that we'd have to support across **all** of our supported platforms, and it vastly complicates things like data migration and reporting.  Newer versions of postgres and things like https://github.com/pgpartman/pg_partman make this _easier_ to manage, but it's definitely not as simple as one global table.  Additionally, any sort of solution like this locks us further into a postgres-specific implementation long-term, which complicates other initiatives we've considered, like multi-DB support through Django's ORM.

Other options down the road (and this is where I cc @matburt, because he and I have discussed this at length) are investigating alternative (potentially non-relational) storage options for this type of data.

**Comment by ryanpetrello** [comment]
In terms of *tangible* things we can accomplish in the near future, here are some ideas I've got:

1.  Investigate moving the primary key of these tables to a `bigint` so that customers with large amounts of events aren't overflowing the primary key (see: https://github.com/ansible/awx/issues/6010)

2. Profile and tune our cleanup job for performance for large-scale datasets.  If the advice we're giving users for now is "run this cleanup job periodically, and don't store billions of rows long-term if you care about fast random read access", then that cleanup process needs to be *very* fast, and *very* memory-efficient.  I know that this is a problem that @fosterseth is actively working on as we speak.

3.  Given the current architecture, there's basically no way that `/api/v2/job_events/` will *ever* be useful at the type of scale we're discussing here; I **almost** think we should just get rid of it because at high event volume, it's kind of a loaded gun for someone without the context of _this issue_.  That said, I think we need to come up with ways to assure that *individual job detail views* _are_ as performant as possible.  One thought is to investigate ways for the UI to make stdout requests that yield _more refined_ queries - potentially ones that take advantage of additional indexes.  One of the issues we have right now is that for jobs with hundreds of thousands of rows, or millions of rows, some of these queries the stdout view makes end up having to sort millions of rows.  We should brainstorm and see if there's any creative ways we could come up with to _refine_ requests made beyond just `job_id=X` cc @jakemcdermott

**Comment by gamuniz** [comment]
@ryanpetrello @matburt @wenottingham 
In my opinion our customers are getting bigger and are targeting more devices than in the past. While I would like to say that data management is helping(it does somewhat) it really doesn't fix our issue. We have customers doing thousands of jobs a day and at that scale they're only able to keep a weeks worth of data. That to me is bad user experience when you also consider the fact that our solution for them was to keep no data in PG and ship it to loggers(which are another can of worms).

**Comment by ryanpetrello** [comment]
@matburt @wenottingham I think we should use this ticket to track "the 1B+ event problem", as discussed above.

**Comment by ryanpetrello** [comment]
Even though I'm not ready to call this issue "solved" (because if we're talking about 1B+ event scale, there's a larger architectural conversation to have), I *do* think it's worth mentioning that I think this PR:

https://github.com/ansible/awx/pull/6032

...will introduce some drastic improvements for job event stdout views at large scale.

Specifically, see this comment of mine for details:

https://github.com/ansible/awx/pull/6032/files#r383911506

**Comment by ryanpetrello** [comment]
I'm going to close this, and replace it with this better description of the problem, and our intended solution:

https://github.com/ansible/awx/issues/9039
