### ISSUE TITLE
System Auditor cannot read a  job if associated objects are deleted.

### ISSUE THREAD

**Issue by vi-patel** [ansible/awx#563]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
related to issue: https://github.com/ansible/awx/issues/458
When a job has associated objects removed from it (projects, inventory, credentials, and template), a system auditor can no longer access the job id, but the admin can.  Not sure why there is any case, where the system wide auditor cannot read a job.

from the UI:
Insufficient Permissions: You do not have permission to view this job.
using the cli (as a system auditor): tower_cli.exceptions.Forbidden: You don't have permission to do that.

##### ENVIRONMENT
* AWX version: AWX 1.0.0.588
* AWX install method:  docker
* Ansible version:  Ansible 2.4.0.0 
* Operating System: RHEL 7.4
* Web Browser: FF ESR 52.3

##### STEPS TO REPRODUCE

run a job as a normal user under any organization.
After the job is run, delete the template, inventory, project, and credentials associated with the job.

Query the job that was run using a user that is a system auditor for the AWX instance.

##### EXPECTED RESULTS

Able to query the job to get stdout and status.

##### ACTUAL RESULTS

auditor is unable to query the job

**Comment by AlanCoding** [comment]
Can you confirm that the system admin can see this particular job?

**Comment by vi-patel** [comment]
The system admin does have access to the job and its stdout.

**Comment by vi-patel** [comment]
Also, from the UI, the auditor can see the job, but trying to select it to see its details, gives the user permission error.

**Comment by AlanCoding** [comment]
Right, good catch. The flaw in logic is apparent in the method here. It doesn't account for system auditors.

https://github.com/ansible/awx/blob/8666512d994bf9d81061d8df4955604cb66db57e/awx/main/access.py#L1360-L1364

A recent change was that we consistently returned the full queryset for auditors (instead of sometimes inconsistent implementation before), and that can cause the situation you describe where the list shows the object, but the detail view (`/api/v2/jobs/N/`) says you can't see it.

Simply deleting that `can_read` method will allow the logic to defer to `get_queryset`, and this will give the right answer.

**Comment by AlanCoding** [comment]
Note for QE purposes: I believe this bug has existed since the system auditor role was originally introduced, but it would have been rather hard to find.
