### ISSUE TITLE
[RFE] Allow Inventory Sourced from Project to sync with branch specified in initiating job template launch

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#5698]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, when you specify an scm branch for a job template launch, the template will launch with the correct code, but if the inventory is sourced from a project, it will always sync with the branch specified in the project itself. If the inventory between the two branches is different, this can cause issues with the job launch by pulling the correct branch for the project itself, but the incorrect branch for the inventory.

**Comment by tutoGav** [comment]
Thanks for create this RFE, @msilmser 

This was originated by a technical support case.

As he said, the problem is when you create a project and use an inventory whose source is tracked with the project itself, by using a SCM tool.

When you create a template job and you set it up to prompt for SCM branch on launch as the inventory source, I expect both do it pulling from the branch setted at launch time, otherwise, the project and the inventory could not be in sync, and that is currently a problem becouse it interferes with our branching strategy or anyone who implements GitFlow

**Comment by wenottingham** [comment]
-> #5692

**Comment by tutoGav** [comment]
@wenottingham, you closed both issues, please keep this open

**Comment by wenottingham** [comment]
? #5692 remains open.

**Comment by tutoGav** [comment]
Excuse me, my bad
