### ISSUE TITLE
Playbook field not shown in Job Template form for user with execute permissions

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5771]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The playbook field is missing from the Job Template form when viewed by a user with only execute permissions on the JT.

<img width="1486" alt="Screen Shot 2020-01-27 at 9 22 36 AM" src="https://user-images.githubusercontent.com/9889020/73182228-a437d680-40e6-11ea-909b-2163d4512ccb.png">

The playbook field is available through the API though so I believe it should be shown in this scenario.

##### STEPS TO REPRODUCE
Grant execute permissions to a user without any existing permissions on at JT, view the JT with said user.

##### EXPECTED RESULTS
Read-only playbook field shown

##### ACTUAL RESULTS
Playbook field hidden

**Comment by elyezer** [comment]
The playbook field is now visible as expected:

![Screenshot from 2020-03-17 11-24-24](https://user-images.githubusercontent.com/48132/76871863-fc1ad000-6841-11ea-8141-722421ec19f5.png)

In order to take the above screenshot I did the following:

1) Created a Job Template
2) Created a normal user
3) Set the `execute` permission for the Job Template created on 1 to the user created on 2.
4) Logged as the user created on 2 and navigated to the Job Template view.

With that we can consider this issue as verified
