### ISSUE TITLE
LDAP Auth Does not Pick Up System Trust Store

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#5790]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: All
* OS version: RHEL

##### STEPS TO REPRODUCE

1. Configure LDAPS in AWX LDAP auth configuration
2. On the server, add all cacerts and intermediaries in `/etc/pki/ca-trust/source/anchors`
3. Update the trust store with: `update-ca-trust`
4. Attempt to authenticate into AWX/Tower

##### EXPECTED RESULTS

LDAPS authentication is successful

##### ACTUAL RESULTS

```
(Can't contact LDAP server", 'info': 'error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate)'},))
```

##### ADDITIONAL INFORMATION

Workaround
Add the django-ldap opt configuration to the AWX/Tower API with a PATCH to `/api/v2/settings/ldap/`
```
{
    "AUTH_LDAP_1_CONNECTION_OPTIONS": {
        "OPT_X_TLS_REQUIRE_CERT": true,
        "OPT_X_TLS_CACERTFILE": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem",
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    }
}
```
*NOTE: For `OPT_X_TLS_CACERTFILE`, you can set a path to any other cacert bundle. This file needs to be readable by the awx user.

**Comment by supaflyster** [comment]
Hey, are you running update-ca-trust with `extract` option (i.e. update-ca-trust extract)?  We use same setup and it works fine.

**Comment by ghjm** [comment]
Assuming this issue is on RHEL 7, this appears to be a platform issue, not an issue in the AWX code.  The default install of OpenLDAP on RHEL 7 includes, in `/etc/openldap/ldap.conf`, the config entry:
```
TLS_CACERTDIR  /etc/openldap/certs
```
This points to a cert store specific to OpenLDAP, distinct from the system trust.  In Fedora this [has been changed](https://src.fedoraproject.org/rpms/openldap/c/bdec46fdafce949b88f36cb2055e1ec3f2c721f4?branch=master) to point to the system trust.  (In RHEL 8 the platform supported LDAP server is now 389-ds rather than OpenLDAP.)

The workaround given in the bug report fixes this by overriding the config setting in the Tower process.  Another way of fixing this is to edit ldap.conf as follows:
```
# TLS_CACERTDIR    /etc/openldap/certs
TLS_CACERT    /etc/pki/tls/cert.pem
```
This will result in OpenLDAP client using the system trust store for TLS certificate verification, for Tower and any other LDAP-using applications on the host.

**Comment by ryanpetrello** [comment]
Spoke to @gamuniz, he said close it.
