### ISSUE TITLE
roles/requirements.yml not being honored (possible regression?)

### ISSUE THREAD

**Issue by n2aws** [ansible/awx#5826]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running a job that uses roles/requirements.yml, it never appears to download the roles, but also doesn't show as "Skipped" in the logs.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: kubernetes
* Ansible version:  2.8.5
* Operating System: N/A, official docker containers for kubernetes
* Web Browser: N/A, fails even for scheduled jobs.

##### STEPS TO REPRODUCE
Create a valid roles/requirements.yml in a Project. (confirmed with the yamllint python script installed via pip)
Create a job that uses the project.
Run the job in check mode. (I've not confirmed if this happens when not using check mode, as that is against our local policies)

The SCM update will run, it will display that is was successful, but in the logs (debug enabled) it shows:
```
PLAY [Install content with ansible-galaxy command if necessary] ****************
META: ran handlers
META: ran handlers
META: ran handlers
```

The above step takes less than a second, even though it's downloading more than 1gb of data from several remote git repositories. (I've tested it with and without "DELETE ON UPDATE" enabled in the project options.)

##### EXPECTED RESULTS

"PLAY [Install content with ansible-galaxy command if necessary] ****************"
Should return a valid result, see that it's required, and download the associated roles.

##### ACTUAL RESULTS

```
PLAY [Install content with ansible-galaxy command if necessary] ****************
META: ran handlers
META: ran handlers
META: ran handlers
```
This step does not appear to download the roles.

##### ADDITIONAL INFORMATION

I've been unable to attempt this without "check" mode, so I cannot report if the results are the same, or different. However, this appears to be a regression of (or similar to)  #3177

**Comment by n2aws** [comment]
Update:  Tested without check mode, and observed the same behavior.  I also have manually run the "Project" manually,  and the SCM Update" behaves exactly the same. As such, I don't necessarily think that the "check mode" is related.

**Comment by egmar** [comment]
We see this bug too, in fact I believe it appeared after support for collections was added. What we figured out is following:

- When running only project update, then roles/collections are not installed.
- When running a job template it triggers project update (project doesn't have this option enabled) and then the project update job is running in Run mode and respectively roles/collections are installed **in the job folder**

I think the issue is in following code:
https://github.com/ansible/awx/blob/6395d646810f3f81e1482e9b57d9fb489e5bcf97/awx/main/tasks.py#L2100-L2102

With this in mind, the issue itself is slight bigger since roles/collections are downloaded on each job executions because instead of being downloaded/installed in the project location (as it was before collections), it is installed in temporary folder where job env is.

**Comment by wenottingham** [comment]
As @egmar noted, we do this on the job template-triggered update that checks out the repository to use - are you looking at that update, or only at the update that updates the SCM revision?

**Comment by egmar** [comment]
@wenottingham for us, main concern is downloading roles/collections on each job execution. It may cause unnecessary load on Galaxy or other locations (Github, Automation Hub). Moreover, it might lead to increased costs if Galaxy is using S3 as storage for collections, since they charge per request as well.

**Comment by n2aws** [comment]
@wenottingham In our case, it was the failing job templates that made us start looking into it.  So, it fails in the job template, and in the project scm update.

As @egmar noted, we too prefer not to have it to a role/collection update on each job execution.  In our case, some of our projects pull in large amounts of roles.. and doing that for each run would be prohibitively slow and costly.

For some of our job templates, pulling them on a "per job execution" basis, is acceptable.  For others, it's not and thus we use a project "schedule" execution to update the roles from git on the occasional (and defined) basis.

I hope that answers your question, if not, post back and I'll try to clarify.

**Comment by egmar** [comment]
I've change the code to install roles/collections in project folder and only when they are not installed. They get synced (part I'm not fully sure about, but it works) into folder where job env is setup. From few tests I've ran it works correctly, though I've yet to test in isolated instance or container groups. 
Now it's a question if AWX team wants to pursue this scenario, or perhaps there are other reasons behind decision of running roles/collections installation on job execution.

**Comment by n2aws** [comment]
@egmar  You made mention of code changes regarding this issue.  Do you happen to have a commit hash, or a link so I can see the changes, and maybe test them in my environment to see if this issue is resolved?  I see that 9.2.0 was tagged, but nothing in the Changelog about this issue, so I'm assuming your code changes did not make it into that newly tagged version.

**Comment by egmar** [comment]
@n2aws see this commit https://github.com/egmar/awx/commit/6cc3b1ee458e32dab889579e21afef6ddfb33b84 it works in our setup, but i'm sure I missed some use cases.

**Comment by wenottingham** [comment]
This will eventually be covered as part of https://github.com/ansible/awx/issues/5518. As the SCM branch/tag/etc for a job is now promptable, we cannot save roles in the project directory itself.
