### ISSUE TITLE
Address upcoming GitHub API deprecations

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#5970]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
GitHub is deprecating certain types of API authentication:  https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

> GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.

##### ENVIRONMENT
* AWX version: all
* AWX install method: all
* Ansible version:  all

##### STEPS TO REPRODUCE

At the very least, we'll need to update to the latest social auth for GitHub SSO logins to continue to work.  See:

https://github.com/python-social-auth/social-core/issues/430
https://github.com/python-social-auth/social-core/pull/428

@jbradberry will this have any side effects for your recent addition of GitHub webhook support?

**Comment by jbradberry** [comment]
@ryanpetrello I _think_, if I'm reading this right, that it is not an issue for the webhook support.  We are using Basic Authentication with a personal access token.

**Comment by kdelee** [comment]
@appuk assigned you since you have experience w/ the social auth testing w/ Github.

I know that @ryanpetrello and @elyezer did some testing before merge. Might want to check with them about that.

**Comment by appuk** [comment]
Working as expected, hence closing the issue:
<img width="569" alt="Screen Shot 2020-03-30 at 12 01 31 PM" src="https://user-images.githubusercontent.com/11617351/77934530-36429380-727e-11ea-9cdf-414e474bbc01.png">
<img width="670" alt="Screen Shot 2020-03-30 at 11 41 27 AM" src="https://user-images.githubusercontent.com/11617351/77934416-0eebc680-727e-11ea-8398-0d95e8aa30ab.png">
<img width="573" alt="Screen Shot 2020-03-30 at 11 54 54 AM" src="https://user-images.githubusercontent.com/11617351/77934423-10b58a00-727e-11ea-93f3-8ffb4827bf0a.png">

**Comment by ryanpetrello** [comment]
@appuk can we also verify that the other SSO integrations still work (to make sure our upgraded library version doesn't affect them)?

**Comment by appuk** [comment]
will do 👍

**Comment by appuk** [comment]
Google OAuth:
<img width="620" alt="Screen Shot 2020-03-30 at 3 31 08 PM" src="https://user-images.githubusercontent.com/11617351/77966017-41aeb280-72b0-11ea-9a21-b552aa884a8e.png">
<img width="478" alt="Screen Shot 2020-03-30 at 6 01 04 PM" src="https://user-images.githubusercontent.com/11617351/77966184-80446d00-72b0-11ea-9ba7-4db4bbc5ce1c.png">

<img width="228" alt="Screen Shot 2020-03-30 at 6 05 03 PM" src="https://user-images.githubusercontent.com/11617351/77966464-15dffc80-72b1-11ea-83fe-154d5dfea02b.png">



LDAP:
<img width="498" alt="Screen Shot 2020-03-30 at 5 58 41 PM" src="https://user-images.githubusercontent.com/11617351/77966012-3e1b2b80-72b0-11ea-9092-dfb43f694abb.png">

Couldn't verify the Azure auth since we do not have the shared account anymore

**Comment by ryanpetrello** [comment]
Awesome, thank you @appuk 🙏!

**Comment by jomach** [comment]
How can I login to awx having a app token ? Like the token that comes from: POSTs https://api.github.com/app/installations/<installation_id>/access_tokens
