### ISSUE TITLE
[RFE] Allow use of vault encrypted variables in job template/workflow extra_vars

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#6030]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently, there is not an option to pass vault encrypted vars to a job template/workflow  API as extra_vars. Encrypted vars will get interpreted as-is in the job. Placing these vars in the host/group vars of the inventory or within the project/playbook works as expected.

`Use Case Need`: Passing encrypted vars from Jenkins to the Job Template/Workflow launch API as extra_vars. 

![Screen Shot 2020-02-21 at 10 54 29](https://user-images.githubusercontent.com/31855206/75049636-903e8500-5498-11ea-82c0-550a295df5f5.png)

![Screen Shot 2020-02-21 at 10 44 48](https://user-images.githubusercontent.com/31855206/75049574-70a75c80-5498-11ea-8fc2-b8ad1e05df71.png)

##### RELATED
[#1992](https://github.com/ansible/awx/issues/1992)
[#2297](https://github.com/ansible/awx/pull/2297)

**Comment by tom0010** [comment]
Any update on this?

With AWX 14.1 I can create a `password` variable in a survey, which is perfect. But, I'd like to do this within the API.

**Comment by wenottingham** [comment]
Password variables aren't sent encrypted, they're just *stored* encrypted and not retrievable later.

**Comment by MalfuncEddie** [comment]
It would be nice to have the option to set a random password in an application without needing to first create a credential.
CLI you can do this by creating a file and encrypting it. It would be nice if you can just use that variable in a survey or in the extra vars.

So basically I have the same issue as OP

**Comment by jessechoward** [comment]
I don't think ansible-vault is the correct encryption for on-the-fly encryption like this. ansible-vault is meant for storing secrets/sensitive vars/files at rest in a repo, not in-flight vars. That's what asymmetric encryption/keys are for.

In theory for something like this your user (or small app wrapper in front of the AWX API) would use a public key to encrypt the value of known vars into a base64 string before setting in extra-vars. Your role/playbook would have the private key encrypted with ansible-vault for tasks to use to decrypt the known var(s) if present early on.

Maybe I am missing something in the described use case, but AWX itself provides the layers for RBAC in terms of AD/LDAP mappings etc. The templates should have all the credentials they need. I am skeptical of using vault in this manner mostly because the encryption is symmetrical, so the calling party has to have the encrypted string already and the secret to make it encrypted. If just sharing the pre-encrypted string, why not just put it in the repo to begin with? Like I said, maybe I am missing something in the use-case.

**Comment by ffirg** [comment]
We are not going to be implementing this as is. Longer term we'd like to do some runtime vars plugin capability along these lines.

**Comment by prumand** [comment]
I know this is was closed on Feb, but I just wanted to add, why I would like that too:

1. it works when you run it via cli `ansible-playbook -e 'extra-vars-with-yml-or-json'`. I thought awx should work the same way.
2. We deploy applications with awx and some secrets seems to be fitting into the application repo, not the inventory repo. That's why we pass those secrets via jenkins to the awx-job.
