### ISSUE TITLE
Remove fallback behavior when an IG is defined on JT or inventory

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#6134]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

- Instance groups are required to be assigned to the node pool to delegate the ability to assign to other organization objects
- Due to how instance groups fallback for capacity from job template -> inventory -> organizations, any nodes which are out of capacity at any of these levels will inherit all nodes in the organization pool
- If you only add the instance groups to the organization for allowing users to assign to objects, its a counter-intuitive user experience when an instance group becomes unavailable and another is picked up for fallback from the org pool.
- If an instance group has restrictions, such as managing separate external environments, you wouldn't want other instance groups inheriting the jobs as fallback which could cause unnecessary job failures.

Please add a new role or change the current to allow instance group assignment without adding the node to the execution pool.

**Comment by wenottingham** [comment]
see also #5711 , #4292

**Comment by lucab85** [comment]
+1

**Comment by AlanCoding** [comment]
@jbradberry what would you think of this implementation:

Introduce a new instance group reserved name, and create it at the same time that we create the `default` and `controlplane` instance groups in the installer. Spit-balling the name, call it `termination_group`. Since the related `instance_groups` relation is ordered...

https://github.com/ansible/awx/blob/c7049e1a0e6a786c4d5526e19354d58f1239273e/awx/main/models/unified_jobs.py#L178

You could put it at the end of your JT's IG list.

The backend implementation is relatively easy to think through here. Task manager makes use of the `preferred_instance_groups` method. It returns a list. With a fairly trivial wrapper, we could look for the "terminator" group, and cut the list off before that entry.

There would be a lot of validation we'd need to add to handle its special status (prevent users from adding instances to it, stuff like that). That would be fairly mundane work.

**Comment by jbradberry** [comment]
@AlanCoding I'm afraid I'm not a fan of relying on special naming of objects to get different behavior.

My off-the-cuff proposal would be to add a boolean field to `InstanceGroup` called something like `reserved` or `restricted`.  Such groups would then only be used if they are explicitly assigned to a `JobTemplate` or `Inventory`.

It does, however, sound like we have the reverse problem as well, of jobs needing special IGs not being able to prevent ordinary IGs from being used as a fallback.  I'd probably go for adding a new boolean to JTs, then.  `no_fallback`?

**Comment by AlanCoding** [comment]
I don't think your first proposal would solve the problem here. My problem with a new JT field is that this isn't just about JTs.

Talking more about it, I see the point of the original post here. You need to assign IGs to an org to delegate usage, but that changes the behavior so they become fallbacks.

Adding roles to IGs would be consistent with current patterns and would solve the problem here. It looks like the RFE https://github.com/ansible/awx/issues/4292 covers that.

**Comment by jbradberry** [comment]
@AlanCoding I don't see how adding the new role described in that RFE helps with either of the problems enumerated in this issue, though I do like having finer-grained roles in general:

- We need to allow the user to prevent fallback into the general pool for JTs that require special IGs.  Having the proposed Instance Group Admin role does not help with that.
- We need to allow the user to prevent special IGs from being part of the general pool.  The proposed Instance Group Admin role doesn't seem to help with this either, since (presumably) it'll work like other derivative roles and still require ownership by the Org, thus conflating Org ownership with being part of the fallback pool.

**Comment by AlanCoding** [comment]
Right now, people associate instance groups to their organization in order to allow organization admins to access them. If instance groups had an `admin_role`, then they would just delegate that role to the users (or teams) who need to use them. This would solve the problem, and is a potential solution called out in the original issue filing here. It flew over my head at first, but I get it now.

> We need to allow the user to prevent special IGs from being part of the general pool.

I don't strictly agree. There are no special instance groups in the user stories here, they're just frustrated by the fact that permission delegation is conflated with fallback groups.

**Comment by jbradberry** [comment]
> If an instance group has restrictions, such as managing separate external environments, you wouldn't want other instance groups inheriting the jobs as fallback which could cause unnecessary job failures.

It's what I understood this point in the parent comment to mean.

**Comment by jbradberry** [comment]
> Right now, people associate instance groups to their organization in order to allow organization admins to access them. If instance groups had an admin_role, then they would just delegate that role to the users (or teams) who need to use them.

That wasn't how I understood #4292, though admittedly Bill's comment on that issue leans that way.  The way the title and parent comment are worded leads me to believe that the proposed role would parallel something like the Org Project Admin role.  Even if we go for a `InstanceGroup.admin_role`, though, I still don't see how it helps with preventing fallback to inappropriate IGs for templates that have special requirements.

**Comment by JoelKle** [comment]
Hello together,
we are a customer of AAP and opened the RH case #03190216 addressing this problem. So if you need first hand customer feedback what we need, feel free to ask :)

> Right now, people associate instance groups to their organization in order to allow organization admins to access them. If instance groups had an admin_role, then they would just delegate that role to the users (or teams) who need to use them. 
> they're just frustrated by the fact that permission delegation is conflated with fallback groups.

Exactly @AlanCoding!

Adding roles to IGs would be a good starting point, but now that I think about it, that only partially solves the problem.

I try to describe the use case we have:
We have three network zones which are restricted. We deployed in each zone multible Execution Nodes.

- Network Zone: HSZ
  - Instance Group = default & controlplane & SE1-HSZ 
  - postgres database is also in this zone
- Network Zone: DMZ
  - Instance Group = SE1-DMZ
  - using automation mesh execution nodes
- Network Zone: DRZ
  - Instance Group = SE1-DRZ
  - using automation mesh execution nodes

Currently we need to add the IG SE1-HSZ, SE1-DMZ, SE1-DRZ to the organizations that the orga-admin users can use the IG in their special JT which should run on a restricted instance.
That is the only way we know how to give non system-admin users the posibility to assign other IG to a JT or Inventory.

If we would add a `InstanceGroup.admin_role` we could give any team, user, ...the permission to use a "special restricted IG" WITHOUT adding the IG on the orga level. Great!

But what happens when a user assigns a restricted IG to a JT and that IG is out of capacity?
It would still fallback to the defaults from the Inventory and Orga. That's not what we expext. When the JT starts on the "default" IG, it will always fail because the nodes in our HSZ zone have no access to the other network zones...
If we select a restricted IG for a JT or Inventory, it should be "encapsulated" to IG / execution nodes in that restricted network zone.
The Job should be placed in the "waiting queue" until capacities are free on execution nodes in that restricted zone.

So I think we need a separate fallback mechanism for each restricted network zone.
Some sort of "pools" for IG where I can create a "pool" for each restricted network zone and add multiple IG to that pool.


> Introduce a new instance group reserved name ..... call it `termination_group`

I would call this a nice "workaround" but not a final solution.

Regards Joel

**Comment by JoelKle** [comment]
I found a really ugly workaround.

We have a organization called "sit-linux". Users in that orga should be able to run jobs on the IG SE1-HSZ and SE1-DRZ.

To achieve a separate fallback mechanins per restricted network zone, we created two organizations.
Reason: each organization has it's own fallback mechansim.

1. Orga "sit-linux SE1-HSZ"
   - select IG SE1-HSZ on orga level

2. For Orga "sit-linux SE1-HSZ" create:
   - Project "projectname SE1-HSZ"
   - Inventory "inventoryname SE1-HSZ"

3. Orga "sit-linux SE1-DRZ"
   - select IG SE1-DRZ on orga level

4. For Orga "sit-linux SE1-DRZ" create:
   - Project "projectname SE1-DRZ"
   - Inventory "inventoryname SE1-DRZ"

= We have created two completely independent orgas per restricted network area (aka IG).

5. assing the users the "orga admin" permission for both orgas


If a user creates a JT:
  If he want that this JT runs on IG SE1-HSZ:
    He has to use Project "projectname SE1-HSZ" and "inventoryname SE1-HSZ"
  OR if he want that this JT runs on IG SE1-DRZ:
    He has to use Project "projectname SE1-DRZ" and "inventoryname SE1-DRZ"
 

Now if e.g. the IG SE1-DRZ runs out of capacity, jobs will be put in the pending queue until there's capacity left.
There no fallback to any other IG except the one selected on Orga level!

**Comment by jbradberry** [comment]
@JoelKle thanks for all of this context, this seems useful.

**Comment by john-westcott-iv** [comment]
https://github.com/ansible/awx/pull/12728
