### ISSUE TITLE
 Ansible Tower to support Windows Edge Browser

### ISSUE THREAD

**Issue by LohitashwaIBM** [ansible/awx#6177]
- Feature Idea
Support for Ansbile Tower with Windows Edge Browser.

##### SUMMARY
Several of our customers are using Windows Edge Browser and want support of Ansbile Tower with Windows Edge Browser. This feature request is for supporting Windows edge browser with Ansible Tower.

**Comment by wenottingham** [comment]
This will be addressed in the new UI, where we will follow our upstream UI guidelines:
`PatternFly 4 supports the latest two versions of Edge, Safari, Firefox and Chrome.`

**Comment by unlikelyzero** [comment]
@LohitashwaIBM which version of Windows Edge

**Comment by LohitashwaIBM** [comment]
I would say versions for all supported Edge browsers  or at the least n to n-2

**Comment by unlikelyzero** [comment]
@LohitashwaIBM I need more details as Windows support is nuanced. Do you have a list of customers or users who you are targeting? Maybe Pendo or Google Analytics data?

I ask because there are two versions of MS Edge in the wild: Classic and Chromium. Classic has been used up until recently in enterprise environments and has no upgrade path to Chromium for enterprise users.

Chromium support is easy and will has 3 versions available for test.

Our UI (along with many others) do not work well with Edge Classic: https://github.com/ansible/awx/issues/6048

**Comment by LohitashwaIBM** [comment]
Clarification: Is this getting delivered as part of any release ?

**Comment by wenottingham** [comment]
If you are asking about the Ansible Tower roadmap, you should discuss with your support representative.

**Comment by LohitashwaIBM** [comment]
No, i was looking at this particular feature.. I saw some status changing on Apr 3 and a statement indicating Successfully merging a pull request may close this issue. Hence the ask on when will the support for windows edge browser will be available

**Comment by unlikelyzero** [comment]
@LohitashwaIBM please check out awx 16.0.0 with edge chromium
