### ISSUE TITLE
(WFJT | maybe others) tab switching reloads entire panel

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6191]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We're not loading / unloading the correct set of components when switching between tabs on some of our views. Best illustrated by comparison - see gifs below.

Regular JT:
![template_tab_load](https://user-images.githubusercontent.com/9753817/76010005-27b3c700-5ee0-11ea-90fc-339b0cd2e6bd.gif)

WFJT:
![wfjt_tab_load](https://user-images.githubusercontent.com/9753817/76009412-2766fc00-5edf-11ea-9111-86ca57e98597.gif)

**Comment by dsesami** [comment]
I think I'm catching the same issue in the Hosts view. Click from the sidebar, choose hosts and pick one, try to switch tabs. The entire page seems to reload. Since this bug includes "(maybe others)", let's include it with this ticket.

WFJT view and all other views (credentials, JTs, etc.) work fine now, it seems.

**Comment by dsesami** [comment]
The Hosts page is only loading tabs, and not doing a full reload. All other pages also appear to be displaying correct behavior now. :+1:
