### ISSUE TITLE
Incorrect form action button placement

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6210]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1451" alt="Screen Shot 2020-03-06 at 10 42 35 AM" src="https://user-images.githubusercontent.com/9889020/76098528-a1f35280-5f97-11ea-9791-eb4ab003300a.png">

Form buttons should be aligned left and on their own line like this:

<img width="1443" alt="Screen Shot 2020-03-06 at 10 46 54 AM" src="https://user-images.githubusercontent.com/9889020/76098643-d404b480-5f97-11ea-8c1a-992cb98700ad.png">

It looks like a number of forms are impacted by this (maybe all of them).

**Comment by dsesami** [comment]
One place where I still see this issue is editing users and teams (shrink your screen a bit to see it happen on teams, as it's not apparent when the screen is wide enough):

![Screenshot from 2020-03-09 14-25-40](https://user-images.githubusercontent.com/19942822/76245249-eab64000-6211-11ea-846b-774b113bd26d.png)

**Comment by marshmalien** [comment]
@dsesami approved and said feel free to close this issue. Closing!
