### ISSUE TITLE
awx Collection: Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible/awx#6227]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/awx.awx/blob against https://github.com/ansible/awx/tree/devel/awx_collection

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by AlanCoding** [comment]
> As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

We need to carefully check to see if any further commits when into _ansible/ansible devel_ since this repo started hosting the collection?

Yes, some did, because some people merged stuff before I had the opportunity to close their PRs. Otherwise, we monitored the `tower` label and closed stuff.

https://github.com/ansible/ansible/pulls?q=is%3Apr+is%3Aopen+label%3Atower

Looking at the specific git history:

 - https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ansible_tower.py ✅ 
 - https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/tower.py ✅ 
 - https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/tower.py ✅ 
 - https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/web_infrastructure/ansible_tower ✅ , the last commit was cherry picked in 9a9d53d17a614efe4d72642229a325534364bcfe

> During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

Didn't really see anything related.

There were some test changes to keep the tests on that side functional temporarily, but those issues didn't affect our testing.

**Comment by AlanCoding** [comment]
closing as resolved
