### ISSUE TITLE
tower_role ansible module should support Workflow

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#6279]
##### ISSUE TYPE
 - Tower_role(https://docs.ansible.com/ansible/latest/modules/tower_role_module.html) module does not support `workflows` it does support other objects like job_template, credentials, inventory, projects etc. I would

##### SUMMARY
If we add `workflow` support to this module it will be complete (at least in my perspective) to support setting permissions of all the objects one would care for.

**Comment by wenottingham** [comment]
Would this be fixed with the conversion off of tower-cli?

**Comment by AlanCoding** [comment]
The tower-cli role command works with workflows. This is an issue because the module parameters, DOCUMENTATION, and code had to be updated after tower-cli was updated, and updating the modules was very hard, because the act of merging was hard.

This isolated request is very trivial. Converting the modules is not trivial.

**Comment by squidboylan** [comment]
I'm closing this because we added an integration test in https://github.com/ansible/awx/pull/6304
