### ISSUE TITLE
Support all unified job template actions (update, approve, etc.)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#6367]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now with the AWX collection, you can:

 - launch jobs
 - launch workflows

It should also be possible to take the corresponding action for all the other types:

 - update inventory sources
 - update projects
 - approve approval templates
 - launch system job templates (module does not exist)

Prior attempted implementation was https://github.com/ansible/awx/pull/5856 for inventory sources.

**Comment by john-westcott-iv** [comment]
We already have some pattern established for this with job templates. We have tower_job_template to manage a JT and then tower_job_[launch|wait|cancel]. If we need to maintain that pattern for backwards compatibility should that just be our pattern?

So for projects it would be something like: tower_project (to manage a project) and then tower_project_update_[launch|wait]. 

I like the ideas of separating the "CRUD" from "the actions". It feels like that would better mimic how the API works (i.e. a job template is a different thing that a job) and I think having more modules might be clearer to users rather than having only a couple with a ton of different states. (like: 'updated', 'launched', 'canceled', 'present', 'absent', etc). From an auto-generation perspective having a CRUD and "action" templates may also be easier than more complex modules with multiple states. 

If we truly do want to go for less modules (and are ok with breaking the existing pattern) I think I would still prefer tower_job_template and tower_job and let _job_template take the standard absent, present and let job take states: launched, canceled, waited (not sure I like 'waited' but stated are past test).

**Comment by AlanCoding** [comment]
There are a _lot_ of "action" endpoints, although it depends on how you count association.

CRUD modules work with the language of Ansible, and I don't see that for "action" modules, which sound like an anti-pattern. Ideally, if something is truly an action, then it shouldn't be supported in the collection. Association is an action, but can be put into the language of desired state by the client.

I want to ask these questions, debate proposed patterns, and hopefully get it right. If we deprecate something, then fine, we should.

> I think I would still prefer tower_job_template and tower_job and let _job_template take the standard absent, present and let job take states: launched, canceled, waited 

I would like to know more about how this would look. I don't quite get it.

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/awx/pull/7873

**Comment by AlanCoding** [comment]
out of date after feature completeness testing, and the sub-issues have new issues opened for them

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/awx/issues/8009
