### ISSUE TITLE
add (all) credentials to unified job template list endpoint summary fields

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#641]
Mockup:

<img width="501" alt="mockup" src="https://user-images.githubusercontent.com/1342624/32793088-f8cf8e8c-c932-11e7-9bf2-0c0c7d9873ed.png">

Currently, we do not have the information present in the list endpoint to make displaying the "credentials" row as a group of tags as the mockup shows.

**Comment by matburt** [comment]
:O We can't really do this, it will destroy performance of the job template list view.

**Comment by ryanpetrello** [comment]
@jlmitch5 as we discussed, providing this data on the list view has the potential to create notable performance problems for that endpoint.

**Comment by cchurch** [comment]
Would it add something beyond just an additional `prefetch_related` query?

**Comment by AlanCoding** [comment]
prefetch-ability was proven in #665

@cchurch that would have been impossible with a many-to-many on JobTemplate, like what we had with `extra_credentials`, but knowing this... the `credentials` relationship was added on UnifiedJobTemplate for exactly this reason. Now it is possible, because that was done.
