### ISSUE TITLE
instance group ordering 

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#6428]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Regression on https://github.com/ansible/awx/issues/3840

##### ENVIRONMENT
* AWX version: devel
* AWX install method: openshift
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

* Make 3 instance groups
* Go to an org and associate each, one by one

##### EXPECTED RESULTS

* For them to be returned in the order in which you added them

##### ACTUAL RESULTS

* 1st is 2nd
* 2nd is last
* 3rd is first

**Comment by ryanpetrello** [comment]
🤔 

I'm having trouble reproducing this:

http://ryanpetrello.com/instance-group-order.mp4

**Comment by fosterseth** [comment]
I also was not able to reproduce the ordering issue on local cluster. any reason to think it could be specific to openshift install?

**Comment by fosterseth** [comment]
https://github.com/ansible/tower-qa/pull/4894

that test fails for me on devel local cluster, so I've been able to replicate the issue that way

I think the `OrderedManyToManyField` might not be working correctly in this case

One thing I've noticed is this particular line in `_update_m2m_position`, which is a method called each time we add an instance group.

https://github.com/ansible/awx/blob/943543354a53ac8754be45f1372318d01c875bd1/awx/main/fields.py#L1042-L1044

unexpectedly, it does not use the modified `get_queryset` from `OrderedManyToManyDescriptor`, which will order the results based on the `position` column before returning.

I believe it needs to return the previous order (based on `position`) -- because it's about to rewrite the `position` starting with 0.

Instead, those lines above use the default manager and default `get_queryset`, which can return items in an arbitrary order.

```bash
inspect.getsourcefile(sender.objects.get_queryset)
'/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py'
```
compare to this

```bash
org = Organization.objects.first()
inspect.getsourcefile(org.instance_groups.get_queryset)
'/awx_devel/awx/main/fields.py'
```

Note:
sender is our `through` model, `awx.main.models.ha.OrganizationInstanceGroupMembership`

**Comment by ryanpetrello** [comment]
Spoke w/ @fosterseth, it sounds like this was just a bug in the associated test cc @kdelee

**Comment by kdelee** [comment]
Going to call this verified, thanks for the bug fix!

**Comment by kdelee** [comment]
need to backport this to 3.6.x
