### ISSUE TITLE
Extend WF Node View modal details

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6530]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Part of: https://github.com/ansible/awx/issues/5997

The Node Modal Detail should show a mini details page with prompt values _overlayed_. Initial work has been done in https://github.com/ansible/awx/pull/6490. Project Sync details are done, but we need to add Job Template, Workflow Job Template, and Inventory Source details.

Prompt values won't show up until support for workflow node prompting lands #5913. 

- [x] Project Sync
- [x] Job Template
- [x] Inventory Source
- [x] Workflow Job Template

<img width="800" alt="Screen Shot 2020-04-01 at 4 31 33 PM" src="https://user-images.githubusercontent.com/15881645/78183982-c3c8e380-7436-11ea-926d-c2102452e6e3.png">

**Comment by marshmalien** [comment]
Mockup with Prompted Values
![image](https://user-images.githubusercontent.com/15881645/78908023-80323300-7a4f-11ea-8617-876730692e0e.png)

**Comment by dsesami** [comment]
Current adjustments we've agreed upon:

- Approval nodes need to not show date created/modified fields before initial save, otherwise they are null
- Job Template itself when viewing node details should be hyperlinked like the other fields so one can get to the page for the JT (if they want to edit it, for example)
- Missing fields, like projects that were deleted, should indicate that they are missing, similar to:

<img width="448" alt="Screen Shot 2020-04-22 at 1 35 30 PM" src="https://user-images.githubusercontent.com/19942822/80104861-c6a28a00-8545-11ea-8f96-77329f01a842.png">

**Comment by dsesami** [comment]
Adjustments listed above were done, this looks great. closing it out.
