### ISSUE TITLE
Add Ansible Role ansible-role-tower-config to awx collection

### ISSUE THREAD

**Issue by keilr** [ansible/awx#6558]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add Ansible Role [ansible-role-tower-config](https://github.com/victorock/ansible-role-tower-config) to awx collection.

This role is very extensive and well structured. It would be great to see this role integrated into the awx collection. It is maintained by @victorock (Red Hat). The role has already several contributors (see PRs) and is actively used.

cc @dbv-rl @spookiej @coreywan

**Comment by keilr** [comment]
@AlanCoding what do you think of this idea?

**Comment by AlanCoding** [comment]
I'm not totally against it, but it would need work.

Tricky part is maintaining the parameters. It's a burden to keep a schema of all the fields in code, because they have to be updated if something changes. We have been moving [towards a code generator](https://github.com/ansible/awx/blob/devel/awx_collection/tools/generate.yml) to produce the DOCUMENTATION string in the modules themselves, so that we can try to auto-discover new fields and functionality.

https://github.com/victorock/ansible-role-tower-config/blob/master/tasks/config/organization/user.yml#L8

Instead of passing the `tower_user` `username`, if we could just arbitrarily pass the user's data into the module, that would be something I'd feel better about maintaining. I also realize there are tradeoffs with increased obfuscation.

----
You are probably aware of the `tower_send` and `tower_receive` modules.

We have an effort underway right now to replace these tower-cli things with something more maintainable, see https://github.com/ansible/awx/pull/6125. These would get support via the AWX collection's modules. A really basic sketch of what that would look like is https://github.com/jbradberry/awx/pull/3

The data files for that will look different from the data files you had in ansible-role-tower-config. It's not completely crazy to me to have data files with properties that align with the individual module parameters. But it depends on how well the use cases are satisfied with existing tooling in the works. Ping @jbradberry

**Comment by keilr** [comment]
That sounds promising! Maintaining the role is indeed a lot of work and totally unnecessary because `tower_import` module will do the same thing - just better.

**Comment by keilr** [comment]
@AlanCoding I just had a look at the code generator. Ansible automates itself :) Nice work! I'm looking forward to see the new tower modules.
