### ISSUE TITLE
Modify the current license counting behavior

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#6782]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
"To Clarify. This is a feature request.

We need to count....
example vs Example vs example.com

as 1 host and not 3 hosts.

This artificially inflates the number of hosts in the inventory, and impacts our licensing negatively."

**Comment by wenottingham** [comment]
Well, AWX doesn't count licenses.

In any case, this is not planned at the level suggested. We do not have the context at the application level to know whether `example` and `example.com` are different hosts, and attempting to introspect something like host variables to compare things like `ansible_host` are not tenable from a performance standpoint.

Using dynamic inventory sources tied to a CMDB (cloud provider, or otherwise) avoids these issues.
