### ISSUE TITLE
Delete Only Items On Screen

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6853]
##### ISSUE TYPE
-Enhancement
##### SUMMARY
Currently when we selectAll and then delete items it is unclear as to what is exactly being deleted.  This feature needs to be improved upon so that only the items that are rendered on the screen are deleted. Things to consider:
-Deleting all items on page
-Deleting filter, sorted, searched items
-Navigation after deleting bulk delete.  See #6734 
This solution should also fix the bug described in #6734 
-In the case where a user select n number of items to be deleted, and then filters the list, all selected items should be unselected and the user will have to recheck the items they want to delete.
##### ENVIRONMENT
* AWX version: 11.1
* AWX install method: docker for ma
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

 See #6734

**Comment by AlexSCorey** [comment]
see the work done https://github.com/ansible/awx/pull/6784 that might be helpful

**Comment by mabashian** [comment]
@AlexSCorey  As I understand it, clicking the Select All checkbox selects all the rows currently listed on the page and throws them into state.  If you then filter the list down to a subset and click delete, we'll still delete all of the originally selected rows (?).  Is that the problem we're trying to solve here?  If so, we may want to make the title a bit more specific.

As far as #6734 goes, I'm not sure that the delete action should be handling whether or not a previous page of contents still exists.  In order to do that, we'd have to make a request to see if the previous page has rows _before_ we redirect.  I feel like it'd be much better to have the list itself redirect to page 1 when a user attempts to access a page that does not exist.

**Comment by akus062381** [comment]
@keithjgrant this looks great!

**Comment by akus062381** [comment]
this is resolved.
