### ISSUE TITLE
How to get current session user inside credential_plugin backend

### ISSUE THREAD

**Issue by prbinu** [ansible/awx#6905]
##### ISSUE TYPE
 - Feature Idea (need help!)

##### SUMMARY
I'm currently working on a feature extension that requires current/request session user available in credential_plugin backend. I have tried the following, but didn't work (returns None):
 
credential_plugin backend:
https://github.com/ansible/awx/blob/f7a8e30d3e5cb3c677618b9306262c6aa927586f/awx/main/credential_plugins/hashivault.py#L92

```
    from crum import get_current_user
    from crum import get_current_request
    
    print(get_current_user())
    print(get_current_request())
 ```
But both are returning NULL. Is there any way to determine the current session user id? 
If not, how can pass this info to this backend?

My experience with Django is limited, so I probably would have overlooked.

**Comment by ryanpetrello** [comment]
Credential plugin code is invoked in the context of a background process that runs an Ansible playbook via https://github.com/ansible/ansible-runner (**not** inside HTTP requests), so the notion of "the current user/session" when a credential plugin is invoked doesn't really exist/make sense.

The credential plugin system doesn't really have access to any sort of context necessary to introspect HTTP sessions of API users (and that's really an intentional design decision).  What are you trying to accomplish?

**Comment by prbinu** [comment]
Thanks Ryan.
> What are you trying to accomplish?

Problem:
To run playbooks through AWX, currently we need to fetch the token from Vault and paste it to Vault Signed SSH credential plugin (AWX UI https://docs.ansible.com/ansible-tower/3.5.0/html/administration/credential_plugins.html#hashicorp-vault-signed-ssh). Though this works, the user has to frequently update this token on AWX UI by running vault command (on terminal). IMO, this is not a good user experience, and is painful to the users.

Proposed solution:
We would like to use the Azure AD (SSO) issued `id_token` (OIDC/JWT token) to connect and fetch SSH certificates from Vault and run Ansible playbooks. (ref: https://www.vaultproject.io/api/auth/jwt). In this model, AWX Vault Signed SSH credential_plugin use requesting user's `id_token` received as part of SSO to fetch SSH certificates to run playbooks. When the `id_token` expires, AWX SSO re-login automatically refreshes `id_token`. From a security perspective, this method is better than storing some long-lived credentials/keys in AWX, and more streamlined that token-paste model. 

The same mechanism can be extended for AWS as well (`AssumeRoleWithWebIdentity`) and in fact 
 this can be used with any service that supports OIDC auth.

I've kind of made progress with caching the id_token, but now stuck with this issue.

Appreciate your response, and hope we can find some ways to address this.

**Comment by wenottingham** [comment]
As noted, playbooks are run completely outside of the user context. When using things like clustered AWX, or container groups, they're run on entirely different pods or K8S clusters. Not to mention scheduled jobs which are run without being done by a user's session at all.

Trying to use AWX login credentials of any sort with  playbooks isn't going to work.

**Comment by prbinu** [comment]
Thank you for explaining the current limitation to support this use case. The only thing we need is to get the identity (say user-id) of the user initiated the task/playbook. No credential info is needed.

Would it be possible to inject the user-id as a env variable or something similar to the credential plugin backend? I'm persistent on this because I believe there is certainly a (security) value in doing so, and I hope you can help us on this. 

If you can recommend a better way than this proposed integrated solution, I'm happy to adopt it. The last thing I would prefer is to store users and/or shared long-lived keys with excessive privileges on AWX servers.

@ryanpetrello  @wenottingham

**Comment by ryanpetrello** [comment]
Hey @prbinu,

The current interface for credential plugins:

https://github.com/ansible/awx-custom-credential-plugin-example

...doesn't really include any information or metadata *beyond* the fields defined on the credential type itself (i.e., URL and authentication details for connecting to the third party system), and that's sort of by design - the purpose of this interface is *just* to take raw credential fields and perform a lookup in some third-party system.

Additionally, this code isn't really invoked from a context where the type of metadata you're looking for (like the user that launched the playbook) is set in the environment.

That's not to say we couldn't *add* some functionality for this, but doing so would involve changing the interface (which would likely break existing plugins that people have already written).

It *sounds like* you're trying to implement some type of RBAC mapping of AWX users to users in an external credentialing system?  It's worth noting that even if we *did* provide this type of metadata to plugins, the context of "the user that launched the playbook" isn't always accurate or what you'd expect, and that makes for ambiguities from an RBAC perspective.

- What if it's a scheduled job where technically **no** user launched it - do we use the user who created the schedule?
- What if _that_ user is removed from the system at some point in the future, and then the schedule runs again?
- What about workflows that are commonly used to combine multiple playbook resources that are potentially set up by disparate users?

**Comment by prbinu** [comment]
Hi @ryanpetrello,

My knowledge about AWX is limited, so I would rely on the AWX team. The way I see this is similar to a CICD system where the jobs are initiated by - (a) users (CLI or WebUI), (b) triggered by a Git commit, (c) by a cron job etc. This also includes job pipelines. All I'm saying is there should be a way to propagate who initiated the job, and it doesn't have to a user. The ability to pass some context data between jobs (playbooks) is desired for pipelines/workflows.  

The proposed flow can coexist with other flows, and is applicable only to user initiated jobs (and fallback to other methods for other cases). For a user to setup this flow, he/she needs to create a credential plugin that is only accessible by that user (set the permission only to self), and configure AWX jobs to use this credentials plugin.

**Comment by prbinu** [comment]
Does it help to keep this as a feature request?
