### ISSUE TITLE
install awx ok without npm/node package

### ISSUE THREAD

**Issue by abennani31** [ansible/awx#6918]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I installed AWX on my centos 7 vm bu following the awx official project. I saw after that i forgot npm and node Prerequisites. However, i got no erros on the installation and i can access to awx server on the UI.

why npm and node are presents in Prerequisites if the are not used/mandatory?

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Centos 7.8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Following the official awx projet. Don't install npm/node Prerequisites.

**Comment by ryanpetrello** [comment]
Perhaps our docs are unclear?

If you're just using our official builds, you don't need npm/node on your host machine.

It sounds like you got everything installed and working?

**Comment by abennani31** [comment]
Hello,
Yes every thinks is working. I saw later that npm/node are marked in https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites

Perhaps, you have to remove it from prerequisites?

Regards,

**Comment by jakemcdermott** [comment]
@abennani31 We will not be removing node and npm from the prereqs for installing because they're still required under some circumstances. Instead, I've added a note next to these items explaining that the requirement is conditional based on how you've configured the installer:

![Screenshot from 2020-05-13 08-44-10](https://user-images.githubusercontent.com/9753817/81814051-3f1dba80-94f6-11ea-8835-c12effedfcee.png)
