### ISSUE TITLE
Replace bubblewrap-based task execution in AWX with container-based execution

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#7060]
This is a subtask of a larger enhancement/initiative surrounding execution environments: https://github.com/ansible/awx/issues/5157

AWX's current execution system is limited to executing jobs under [bubblewrap](https://github.com/containers/bubblewrap) for process isolation. For OpenShift and Kubernetes based deployments, this requires any container running jobs to run in privileged mode.

In a future release of AWX, we'd like to replace this execution mechanism with execution based strictly on containers, likely via Docker and/or podman.

This is a multi-stepped change that will require:

1.  Changes to the https://github.com/ansible/ansible-runner project itself to support container-based execution.
2. Modification to AWX's task execution to interface with runner to properly mount certain volume data (such as the appropriate project/SCM data that contains playbooks)
3.  Changes to the way that AWX executes and manages the JSON artifact data of inventory imports (today, inventory imports in AWX rely on a specific `awx-manage` process that is necessary to save inventory/group/host artifacts into the database).
4.  Certain types of "jobs" will continue to follow the model of local execution (meaning, they won't run in a container), in particular system jobs.

Other considerations include:

- How will this affect existing users that have grown accustomed to the "bwrap whitelist" mechanism, by which certain file paths can be "exposed" to the ansible-playbook runtime?  Should we continue to support this type of functionality?  How will that affect "Job Isolation"-specific settings that exist today.
- This new model will require AWX installations to either include to interact with a container registry.  What should be the default behavior for new installs (are users required to bring their own, or will all AWX installations provide a default container registry via the galaxy-ng project (https://github.com/ansible/galaxy_ng)?

**Comment by Vacant0mens** [comment]
@ryanpetrello if container-based execution is what you're going for, within Kubernetes (if you're running un-privileged) the runner wouldn't be able to create containers on the Kubernetes cluster that AWX/ansible is running on. You would need an extra pod/container that runs Docker or some other container engine within the container that you would communicate to via an Api, or have the engine included in the runner's container or pod in order to call it locally.
If you're going to be calling a container runtime engine locally, it'd probably be easier to just run the tasks locally (within the container) as sub-processes or as a separate process. Isn't that what BubbleWrap is for though?

As far as unprivileged Kubernetes instances, I think it would be the same either way, and either way you'd lose system-level tasks (which I don't know why you'd want that in a Kubernetes environment anyway). You'd probably want to hit remote Kubernetes instances so that your workload isn't running on the same cluster as your ansible/AWX instance.

**Comment by Vacant0mens** [comment]
@ryanpetrello  replying to your comment [here](https://github.com/ansible/awx/issues/7916) So what's the problem with having some kind of BubbleWrap service running in a pod/container alongside AWX? That could potentially save a rewrite of the entire task management structure.
Containers in the same pod can share information potentially even down to system-level process calls. But couldn't BubbleWrap run as a thread/process within the same container anyway? 
I can understand wanting to have container-based task management/isolation, but it seems like a lot of work to rip out the current rather than including it and making it work within the current container environment.

If by "system jobs" in your 4th point, you mean you'd want to control docker or the kubernetes cluster that AWX is running on, that may not be the best option, and definitely won't work in unprivileged containers.

**Comment by ryanpetrello** [comment]
> So what's the problem with having some kind of BubbleWrap service running in a pod/container alongside AWX? 

The main problem is that in the near future, we're planning to reimplement how all of this works (and get rid of bubblewrap entirely), so I'm not interested in building and supporting an interim solution.

(if it's not clear, our intention in rewriting all of this isn't **just** to get rid of bubblewrap: https://github.com/ansible/awx/issues/5157)

**Comment by Vacant0mens** [comment]
Okay, well I guess the only question then is, How will container-based execution be implemented in an unprivileged environment? or will the assumption be that it will always be privileged and everything will be coded/documented around that assumption?

**Comment by shanemcd** [comment]
@Vacant0mens There are some pretty big changes coming in this area over the next couple months. We'll be announcing it in a more formal manner, probably via the mailing list, as things start to materialize in the near future. But the high-level answer is: we'll be rearchitecting how AWX runs on top of Kubernetes and utilizing [Receptor](https://github.com/project-receptor/receptor) as a backplane for running jobs inside of ephemeral pods. Receptor itself will have the ability to take a unit of work, spin up a pod, and get the data back into AWX. The AWX k8s deployment will turn into a decoupled control plane used for receiving and processing job events, and ultimately persisting them in the database. If it helps to see it more visually, I have been using this diagram to explain the overall concepts:

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/773186/91184606-d29c8500-e6ba-11ea-8c06-34e095ef5296.png">


I hope this gives you a better idea of the general direction we're heading.

**Comment by TimoStramann** [comment]
This topic needs more attention in my opinion. Podman is default in modern rhel/centos distros for some time already.

**Comment by aelbarkani** [comment]
is this evolution still active ?

**Comment by AlanCoding** [comment]
Yes, covered by https://github.com/ansible/awx/pull/8030

**Comment by kdelee** [comment]
Verified by extensive use of this feature. 
Thanks @yagomarques and @shebangbash and @elyezer for all their work on this along with the developers
