### ISSUE TITLE
Error due to session time out

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7210]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
An error is raised due to a session time out.

![error_time_out](https://user-images.githubusercontent.com/9053044/83453277-33a01e00-a428-11ea-979d-2ed07d232dfa.png)

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker on linux
* Web Browser: firefox-76.0.1-7.fc32.x86_64

##### STEPS TO REPRODUCE
1 - Login
2 - Let the session time out
3 - Go to your previous URL

##### EXPECTED RESULTS
Perhaps, redirect the user to the login page.

##### ADDITIONAL INFORMATION
This issue is a known issue. Possibly related to https://github.com/ansible/awx/issues/4205

**Comment by jakemcdermott** [comment]
accidentally fixed w/ https://github.com/ansible/awx/pull/7186

**Comment by jakemcdermott** [comment]
The `ContentError` redirects on `401` errors: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/ContentError/ContentError.jsx#L34

This problem is unique to the api request for configuration data in the `App` component. This is because we don't use a `ContentError` component there on failed data load.

**Comment by jakemcdermott** [comment]
I accidentally fixed this bug during code cleanup w/ https://github.com/ansible/awx/pull/7186

**Comment by dsesami** [comment]
Looks like it boots you to the login page. Nice 👍
