### ISSUE TITLE
Applications List

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#7233]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add support for Applications List

**Comment by dsesami** [comment]
as with #7234 , I'm going to wait for #7235 to do those together.

**Comment by dsesami** [comment]
This looks great, but there's something to tweak in a future issue to deviate from the old UI's functionality.

It's weird to me that you can search by description, but description isn't visible in the list. Maybe we can consider making an issue about making the description visible in the list via toggle (simple/expanded view).

Also, we should enable searching by org name, since that's provided in the list fields. We should also add "Last Modified" to the sort (not search) options, in a similar vein.

**Comment by dsesami** [comment]
closed out with the merge of #7341
