### ISSUE TITLE
Ephemeral Inventory

### ISSUE THREAD

**Issue by rads18** [ansible/awx#7288]
##### ISSUE TYPE
 - Feature Idea
Ability to create ephemeral inventory during play run.
Also be able to use that as a job template in a workflow to provide as inventory source for the following templates.

##### SUMMARY

I have been using meta: refresh_inventory which allowed me to create ephemeral inventory during the play run. Based on recent response from from Bill https://github.com/ansible/awx/issues/7276, I have been told this is no longer supported.

The feature of meta: refresh_inventory has proved to be very useful for me and I am sure others as well. 

Scenario:
All teams in the org just use a local inventory with localhost  for their template and during playbook run create dynamic inventory via the meta: refresh_inventory . This is done by a role which creates a custom python script which is then called by refresh_inventory to create a dynamic ephemeral inventory host data/meta data available to the rest of that play.  This way there are not 100's of inventory per project.

In a very active automation environment with thousands of users /job runs, this feature of meta refresh has given end users teams and team that maintain the ansible infrastructure to not have to worry about maintaining multiple inventory lifecycle.

**Comment by wenottingham** [comment]
Due to how inventory is passed to templates, runner, and the ansible process, this is not really practical in how things currently work.

It is simpler in the short and medium term to utilize the awx.awx collection and essentially 'poke' the inventory into the API for a later run.

If you insist on passing data from template to template, and want to use that as an inventory, you'd use set_stats to set it in one template, and unparse that in a subsequent step to use as inventory.
