### ISSUE TITLE
import/export modules

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#7329]
##### ISSUE TYPE
 - Feature Idea

Add to the tower collection modules that perform import/export type things.

## Open Questions:
- currently CLI always updates --- that's not the ansible way, what do we want to do to fix this?
  - check if object of same name exists and not update unless `force: true`
  - OR....more granular check if sub items have changed, this would be more work

needs more fleshing out

related to https://github.com/ansible/awx/issues/5146

**Comment by AlanCoding** [comment]
@john-westcott-iv already has some material for this.

**Comment by john-westcott-iv** [comment]
We are writing import/export modules here https://github.com/ansible/awx/pull/6125
But they use the CLI libraries which, as you mention, currently always report changed.

**Comment by ryanpetrello** [comment]
@john-westcott-iv is there a branch or PR for this work somewhere?

**Comment by AlanCoding** [comment]
https://github.com/jbradberry/awx/pull/3

https://github.com/ansible/awx/compare/b1d83dd35d8ddf91d7c816575bd89bb1fe4af57f...john-westcott-iv:import-export-collection

That is relative to @jbradberry's import/export branch, which has changed in the meantime. Rebasing it may or may not work, squashing and cherry-picking might be better, and even that would introduce a lot of conflicts.

The original work started with refactoring some of the base class, and other lighter parallel refactoring has happened elsewhere. We do need to swap out the logic for making requests, login, and logout. However, we still need to share the code for processing the authentication parameter processing. Even with awxkit, IIRC, you still initialize your own client/connection/session/whatever it is. This was the non-obvious thing that took me a while to accept.

**Comment by john-westcott-iv** [comment]
@ryanpetrello The modules are stuck in some PR gridlock:

We need #7286 (lookup plugins) to go in.
Once that is done we need to refactor and merge #6615 which splits the modules utils out into tower_api and tower_connector.
After that we can refactor #6125 on to awx/devel and finish up the tests.

**Comment by AlanCoding** [comment]
Maybe some updated version of #6615, my concerns about that refactor are specifically due to this awxkit integration. The `TowerConnector` class got all of the config processing logic in that split. That might sound logical, because it's not what happens in practice, because awxkit doesn't do any work for us in terms of processing module parameters or config files.

The logic that awxkit will re-implement will be specifically login/logout/make_request, but even that seems like too much. Will these modules create a new token if given username/password? That's not something the AWX CLI does.

There is a lot of logic around handling error codes, and that may be left to awxkit to raise exceptions. I'm curious what other people envision for this.

The collection will be primed for refactoring after we the details hashed out about what responsibilities lie where. awxkit has a completely independent code lineage from the collection, and because of that, it sends us back to basic design questions.

**Comment by ryanpetrello** [comment]
PR: https://github.com/ansible/awx/pull/7799
