### ISSUE TITLE
ansible/awx:12.0.0 image has a corrupted rpm database

### ISSUE THREAD

**Issue by hluaces** [ansible/awx#7365]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The `ansible/awx:12.0.0` image base state has a corrupted rpm database that prevents it from using `dnf`. 

##### ENVIRONMENT

* AWX version: 12.0.0
* AWX install method: Docker version 19.03.11, build 42e35e61f3
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

Simply run the ansible/awx:12.0.0 image with any `dnf` command:

```
hector@red-queen:~$ docker run -it ansible/awx:12.0.0 dnf update
Unable to find image 'ansible/awx:12.0.0' locally
12.0.0: Pulling from ansible/awx
8a29a15cefae: Pull complete 
4bfe2cb83ba8: Pull complete 
1ae37eb5d179: Pull complete 
45dd75deaa3d: Pull complete 
d9b4612c3fcc: Pull complete 
4c013ca1c2a0: Pull complete 
263589746006: Pull complete 
a2f9f347f22b: Pull complete 
574c6464ecbc: Pull complete 
1da8571bac8d: Pull complete 
d3b4c45b1f19: Pull complete 
28dbc615ca4c: Pull complete 
a640b28ecfc2: Pull complete 
a1f083e6af58: Pull complete 
b42c7a3628e2: Pull complete 
80775a4b3733: Pull complete 
b2bb9b1d2771: Pull complete 
Digest: sha256:484bc509c70b40d46950d6271a9b35a4d842470b47e4c6925af78b72e2ae5a99
Status: Downloaded newer image for ansible/awx:12.0.0
error: rpmdb: damaged header #173 retrieved -- skipping.
error: rpmdb: damaged header #173 retrieved -- skipping.
Error: This command has to be run under the root user.
```
Also, any playbook run that tries to install packages on the container itself will fail because `dnf` will be unable to work with the corrupted database.

##### EXPECTED RESULTS

The container should be able to operate with `dnf` normally. 

##### ACTUAL RESULTS

The container can't operate with `dnf` normally: no package installs, updates, etc.

##### ADDITIONAL INFORMATION

I think that this is related due to this:

> Please reconsider this. For CI testing in Nmstate, we use stock base images that setup with  yum/dnf to contain the requirements for the test environment. It seems that using yum/dnf in two  layers corrupts the RPM db (when building the image on docker hub or quay). This then breaks  installing test RPM packages during the CI run. Rebuilding the rpmddb would fix the DB. Ideally, the > DB would not break in the first place but I guess this might be related. I re-opened this issue so  this comment does not get lost.

From: https://bugzilla.redhat.com/show_bug.cgi?id=1680124, found on [here](https://github.com/geerlingguy/docker-centos8-ansible/issues/7#issuecomment-625501886)

Allegedly, the Dockerfile could be tweaked to avoid using `dnf` on several layers to avoid corruption.  [This external commit from an open source project](https://github.com/geerlingguy/docker-centos8-ansible/commit/87f182ab97b8f599dc9226201d32bbfcfb0b511c) was dealing with the same issues and could fix the problems by changing how the Dockerfile deals with package installs.

I also think that issue #6306 is related to this.

**Comment by blomquisg** [comment]
@Spredzy can you look at this one?

**Comment by shanemcd** [comment]
Hi. I dont think this is a corrupted database. When I read this error I see:

```
Error: This command has to be run under the root user.
```

You are seeing this because the containers run under a [non-root uid](https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/Dockerfile.j2#L244) by default, because security. 

Side note: while I was investigating this issue, I found that we do [this](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/templates/docker-compose.yml.j2#L87) in our "local docker" install path, which feels wrong. But it's been that way for over 3 years at this point. This will get fixed in an upcoming release.

So back to your issue: I guess you have a couple options here. If you really want to run your containers as root and accept all security risks that come with that, you could build your own image and forcibly set the container as root:

```
FROM ansible/awx:12.0.0

USER root
```

_or_, more preferably something like this, where you install them into the image itself rather than trying to do it at job runtime:

```
FROM ansible/awx:12.0.0

USER root

dnf install ....

USER 1000
```

At this point, you would push this to your dockerhub account under `<account>/awx` and set this variable to your username: https://github.com/ansible/awx/blob/devel/installer/inventory#L9

**Comment by sjortiz** [comment]
@shanemcd the issue happens even if you are root.

Dockerfile:

```
FROM ansible/awx:12.0.0

USER root
RUN dnf update -y

....
```


Error:

```
Step 1/5 : FROM ansible/awx:12.0.0
 ---> 4793918ad0df
Step 2/5 : USER root
 ---> Using cache
 ---> 9aec78d073e2
Step 3/5 : RUN dnf update -y
 ---> Running in ff7e62cbb7aa
error: rpmdb: damaged header #173 retrieved -- skipping.
error: rpmdbNextIterator: skipping h#     173 blob size(4836): BAD, 8 + 16 * il(70) + dl(3708)
```

**Comment by sjortiz** [comment]
Also this doesn't work either:

docker file:

```
FROM ansible/awx:12.0.0

USER root
RUN rm -f /var/lib/rpm/.*.lock
RUN rpm --rebuilddb
RUN dnf update -y
```

error:

```
Step 4/7 : RUN rpm --rebuilddb
 ---> Running in 59b46490f3f8
error: rpmdbNextIterator: skipping h#     173 blob size(4836): BAD, 8 + 16 * il(70) + dl(3708)
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.1 to recover
The command '/bin/sh -c rpm --rebuilddb' returned a non-zero code: 1
```
