### ISSUE TITLE
LDAP user email attribute is empty

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx#7388]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After the LDAP user logged in first time and the user was created in AWX, the email attribute is empty. The first and the last name are ok.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Ubuntu 18.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login with LDAP user

##### EXPECTED RESULTS

email field will be filled with AD email attribute address

##### ACTUAL RESULTS

email filed is empty

**Comment by ryanpetrello** [comment]
Hey @unbreakabl3,

Are you still encountering this on newer versions of AWX?

**Comment by shanemcd** [comment]
@unbreakabl3 ping - can you try this on a more recent version of AWX?

**Comment by unbreakabl3** [comment]
Sorry for the delay. I don't have an access to this environment anymore, so cannot test. im going to install the latest one soon and will check it.

**Comment by john-westcott-iv** [comment]
Hi!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
