### ISSUE TITLE
Feature: Full podification/dynamic clustering

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#74]
AWX Feature Spec - Podification w/dynamic clustering
====================================================

User Persona
------------
AWX administrator

Usage Cases
-----------
AWX has a container-based deployment system. However, this system does not
currently support joining clusters and instance groups, and there is not an
isolated node container OOTB.

AWX should be able to be spun up as a pod that automatically joins the
proper cluster and groups, usable for scale-out at runtime.

This requires:
- automatic joining of a cluster with minimal or no state encoded in the runtime container
- run-time creation of instance groups without cluster downtime
- isolated node containers that can be deployed wherever
- probably other things

Supported targets:
- OpenShift
- raw Kubernetes
- possibly others as time/patching permits

API Considerations
------------------
Lots

UI/UX Considerations
--------------------
The cluster view in AWX should allow for the dynamic creation and assigning
of instance groups via whatever way the API exposes it.

Docs
----

QA Suggestions
--------------

Notes
-----

Updates/Changelog
2017-09-08: initial version

**Comment by mabashian** [comment]
UI implication notes:

- Implement Instance Group CRUD (add/edit/delete)
    - Anticipating Name, Description and policy (Minimum Instances and Percentage of New Nodes and Static Instances) fields
    - Percentage of New Nodes will be a slider component
    - Minimum Instances which is currently a dropdown component
    - Static list of Instances that always belong to the Instance Group (don't see this in the mockup)
- Implement Instance associate/disassociate with Instance Group from Instances related tab
    - Modal with Instance list (see host/group associate/disassociate) multi-select
- Instances remain read-only

ITEMS THAT NEED CLARIFICATION

- Should clicking on Instance show Instance Groups related tab where user can associate/disassociate the Instance from particular Instance Groups? _Haven't had this request yet_
- Can Instance Groups be associated with other Instance Groups (like groups in inventories)? _Thinking no, but need to follow up_
- In the planning meeting there was mention of a potential button for rebalancing an Instance Group but unclear as to whether that is needed.  If it is needed, where should that button go? List, Instance Group form, etc? _Thinking we don't need this, all rebalancing will happen automatically_
- Instances that get removed from an Instance Group when deleting Instance Group/disassociating Instance from Group will get added back to the base Instance Group.  Do we need special prompt help text to explain this to the user?  Basically can't add/remove an Instance through the UI. _Yes, include a message in the prompt denoting that an instance will get moved back to the base group upon disassociation_
- Static list of instances policy in Instance Group form is currently not in the mockups but should it be?
- Websocket support on these pages unclear.  Could use jobs websocket channel group as a trigger to detect changes in status.  This would require us to make a REST call on each status change.
- Should Minimum Instances policy be a number field instead of dropdown? _If this number is capped at like 10 then dropdown.  If uncapped then number picker (see schedules)._
- Instance Group Instance list - should we denote manually added Instances v. instances added via policy?

**Comment by matburt** [comment]
Some more implementation details:

* RabbitMQ container instance needs to modified to support autoclustering (paired with etcd or consul, likely the former)
* Automatic Provisioning/Deprovisioning of Instances
* Queue/Instance Group Membership should be driven entirely by the UI and not require `inventory`/`installer` involvement at all.
    * Requires POST support for `instance_group/n/instances` and `instances/n/instance_groups` endpoints.

In order to facilitate automatically placing `Instances` in `Instance Groups` for container based deployments we will need some way to automatically assign these transient instances. We'll do this with `Instance Group Policies`.

These Policies allow you to specify a certain percentage, or minimum number of instances that an Instance Group will attempt to keep as members. This will happen automatically as instances are provisioned/deprovisioned.

Instances that are removed from Instance Groups will automatically stay assigned to the `tower` instance group.

**Comment by wenottingham** [comment]
@matburt since the branch landed, should this be closed?

**Comment by matburt** [comment]
Yep, closing with #1058
