### ISSUE TITLE
tower_workflow_job_template module not idempotent when defining survey

### ISSUE THREAD

**Issue by kenchrcum** [ansible/awx#7554]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The module tower_workflow_job_template always returns changed if survey_enabled and survey parameters are defined.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

Execute tower_workflow_job_template module various times:

```- name: Workflow Job Template
  awx.awx.tower_workflow_job_template:
    name: Workflow Job Template
    organization: Default
    inventory: Default
    survey_enabled: yes
    survey:
      name: "Workflow Job Template"
      description: "Workflow Job Template"
      spec:
        - required: true
          min: 0
          default: ''
          max: 1024
          question_description: ''
          choices: ''
          new_question: true
          variable: input
          question_name: input
          type: text
```

##### EXPECTED RESULTS

After first run which creates the Workflow Job Template the following runs should return changed=false.

##### ACTUAL RESULTS

All runs of the task return changed=true. After removing survey_enabled and survey parameters the result is as expected.

**Comment by rozgonik** [comment]
Ran into the same issue. After some investigation i found the culprit:
[The expression `existing_spec = module.get_endpoint(spec_endpoint)`](https://github.com/ansible/awx/blob/8e024c234c6053b6de072d032049ed8cac461f40/awx_collection/plugins/modules/tower_workflow_job_template.py#L274) returns a dictionary similar to this:
`{"json": {"description": "", "name": "", "spec": <... survey spec dict ...>}, "status_code": 200}`
But the `new_spec` dictionary below contains the following:
`{"description": "", "name": "", "spec": <... survey spec dict ...>}`

Of course, these dicts will never be the same, thats why the module reports changed on all runs.

A quick fix would be to prefix the mentioned line with `["json"]` to get the proper dict for comparison.
However as i see, every other interraction with AWX uses a higher level method instead of this lower level-ish `get_endpoint`, so i dont think this is the proper way of dealing with the issue. (But maybe can be used as a hacky workaround until the release of a proper fix.)

**Comment by t-readyroc** [comment]
I'm running into this issue as well, though, at the same time, the survey is not created. First run attempting to create a new workflow template - template is created, survey is not.

**Comment by zjpeterson** [comment]
+1, having this issue as well (`awx.awx` 16.0.0)

**Comment by beeankha** [comment]
Test coverage was added via functional test playbooks, closing issue.
