### ISSUE TITLE
RFE: Write Inventory changes to the database after inventory sync has completed

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#7586]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In order to long running connections to the database during slow inventory syncs, some users may desire an option to write all data to the database after the sync as opposed to during.

**Comment by AlanCoding** [comment]
It is possible that this will be accomplished by https://github.com/ansible/awx/issues/7061

Several forms of inventory refactoring are planned, it's going to be a massive task, and I think @chrismeyersfsu may have started on some of that.

The largest change will be moving `ansible-inventory` calls into a container. Saving to the database will only happen after that has completed. I don't think that saving the inventory has ever been a major bottleneck, and if it had, it was because of overly-verbose logging. Typically, it's the inventory plugin itself that's the thing that takes an eternity.

**Comment by wenottingham** [comment]
While https://github.com/ansible/awx/issues/7061 may change this, we are not planning to deeply change the process of how we import inventory. We've always only ever started saving it after the `ansible-inventory` process exits.

**Comment by chrismeyersfsu** [comment]
Yeah, I'm not exactly sure what is wanted here. As @wenottingham said, we don't update the inventory in the DB until the cloud inventory gathering process has finished. We also tried hard to push the lock that protects competing inventory source updates to the same Inventory down as far as possible. https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L884
