### ISSUE TITLE
catch event for refresh $rootScope

### ISSUE THREAD

**Issue by Pavloid21** [ansible/awx#7610]
##### ISSUE TYPE
 - Local problem

##### SUMMARY

Sometimes an event occurs on the page that clears $rootScope. More precisely, it returns to its initial state. In this case, the event occurs when switching between browser tabs! O_o Here it is worth clarifying that a response from the socket is expected on the page. And weird behavior is observed when we return to the tab after the socket response event.

I have already tried to catch the changes on the locationChangeStart and routeChangeStart, but no results.

**Comment by jakemcdermott** [comment]
Hi @Pavloid21 

Thanks for the bug report. Can you provide a little more detail in terms of the expected vs actual behavior from a user perspective? What are you observing on tab change and how does it differ from what you'd expect?

**Comment by Pavloid21** [comment]
> Hi @Pavloid21
> 
> Thanks for the bug report. Can you provide a little more detail in terms of the expected vs actual behavior from a user perspective? What are you observing on tab change and how does it differ from what you'd expect?

Sure! For example, a page expects a response from a socket. We leave the page to wait for an answer and go about our business to neighboring tabs to work with other resources. We return back where, as expected, the response from the socket about the end of the job will be processed. But, we observe that the answer is skipped, the controller scope are destroyed (root scope too) and recreated. Visually, the controller rolls back to its original state.

**Comment by jakemcdermott** [comment]
@Pavloid21 

I think I'm encountering the bug you're describing on devel.

If I'm in the middle of doing something, say filling out a launch prompt or entering data into the job template form, and then switch to another tab, when I return to my awx tab it seems to trigger a reload which clears the unsaved state on forms, prompts, etc.

I'm not sure this has to do with sockets or job events _specifically_ but we should definitely fix it.

**Comment by Pavloid21** [comment]
@jakemcdermott 
I am already inclined to believe that this behavior is not related to sockets. As a workaround, I've added state-by-key returns to the session store where possible. Of course, in this case, the interface blinks. In the meantime, I'm looking for a more relevant solution.

**Comment by mabashian** [comment]
OK I'm pretty sure I understand what's going on here so I'll outline it as best as I can.  If I'm misunderstanding some aspect of the issue please let me know.

A few years ago, we added this flag UI_LIVE_UPDATES_ENABLED in the settings which allowed users of AWX to toggle websocket messages (and therefor live list updates) on or off.  For some folks were running in to issues with the sheer volume of list refresh requests that were being made if they were running a significant number of jobs at the same time.  We found out that some users would have multiple AWX tabs open at any one given time and if those tabs were set to a page where we used websocket events to trigger updates to a list then that would result in a tremendous number of GET requests back to the server.  For some installations, this would negatively impact API response times and generally make for a poor user experience.  In order to combat that, we added some code that would ignore websocket messages for backgrounded tabs.  You can see the logic here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/socket/socket.service.js#L30-L45 and here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/socket/socket.service.js#L107-L116.

If a tab is backgrounded and we receive a socket message that would trigger an update to a list we flip the `needsRefreshAfterBlur` flag over to true.  When the tab comes into focus again, we reload the entire state.  At the time, this was the most desirable solution mostly due to ease of implementation.

There have been some changes to the way we react to websocket events in the past few months or so which I think would impact this particular situation.  You can see that PR here: https://github.com/ansible/awx/pull/5968.  We no longer make wholesale GET requests to refresh list contents whenever we get a socket message saying something has changed.  Now we can take the data from the socket message and update the list inline, without a GET request (in most cases).  You can read more specifically about the behavior here: https://github.com/ansible/awx/pull/5968#issuecomment-591565513.

Options that I can see moving forward:

1) We could remove this "background tab" logic and just let each tab behave as it normally would.  There are still scenarios where a backgrounded tab could steadily issue GET requests but they'd be time-banded to 1 every 5 seconds.  This is something we'd have to discuss as it could still result in a non-trivial number of requests being made from tabs that are not being actively viewed.
2) We could change this line: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/socket/socket.service.js#L39 to do something like, broadcast a message out to all of the rendered states.  Lists could then listen for that message and trigger a refresh of their data on it.  This would potentially get us around the wholesale refresh of all states but it would require a fair bit of auditing to find all of the lists that may need to listen/update.  Touching that many files makes me a little nervous.
3) We could look at more granular settings that would allow a user to control whether or not backgrounded tabs reacted to socket messages.  I think this would be most likely combined with either 1 or 2.

The other thing to consider is whether this should be evaluated in terms of current AWX or UI Next.

@Pavloid21 a completely untested suggestion as a workaround would be for you to remove these lines: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/socket/socket.service.js#L28-L45 and these lines: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/socket/socket.service.js#L107-L116 from your local installation.  Again, I haven't tested that but on the surface it may do what you're asking for.

**Comment by jakemcdermott** [comment]
On second look, I believe the bug I was describing [here](https://github.com/ansible/awx/issues/7610#issuecomment-659410044) is a different issue entirely. Somehow I got awx into a state where switching to awx from another tab caused a refresh 100% of the time, without socket messages. I think this is probably different from the `UI_LIVE_UPDATES_ENABLED` behavior described above.

If I find a reliable way to reproduce https://github.com/ansible/awx/issues/7610#issuecomment-659410044 I'll open a separate GH issue for it.

**Comment by jakemcdermott** [comment]
> We could remove this "background tab" logic and just let each tab behave as it normally would. There are still scenarios where a backgrounded tab could steadily issue GET requests but they'd be time-banded to 1 every 5 seconds. This is something we'd have to discuss as it could still result in a non-trivial number of requests being made from tabs that are not being actively viewed.

I think I like this option - given the recently-added time banding logic for event-driven list refreshes, we could _probably_ handle a few tabs being open without the `refreshAfterBlur`. 

It's true that it could result in more requests from a given user if they have multiple tabs. Each tab is roughly equivalent to another user idling on awx which _seems_ reasonable enough given the time banding.
