### ISSUE TITLE
Render SECRET_KEY file error on CentOS 7

### ISSUE THREAD

**Issue by AnythingLinux** [ansible/awx#7648]
We are using CentOS 7 Linux
when run: $ ansible-playbook -i inventory install.yml 
from /root/awx/installer 

it shows error:
TASK [local_docker : Render SECRET_KEY file] ***********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'secret_key' is undefined\n\nThe error appears to be in '/tmp/awx/installer/roles/local_docker/tasks/compose.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Render SECRET_KEY file\n  ^ here\n"}

need help

**Comment by AnythingLinux** [comment]
@farcaller @svenstaro @joefiorini @lukesneeringer any one help

**Comment by svenstaro** [comment]
Don't just randomly highlight people.

**Comment by ryanpetrello** [comment]
@UbuntuEvangelist,

The issue is exactly what the error states - your inventory file doesn't have a `secret_key` variable defined.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
