### ISSUE TITLE
System auditor item in access list is missing a name 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7816]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
System auditor entry in access list is missing a value in the name column. The auditor doesn't have a `resource_name` so unless we can show a username/first/last name value, it probably needs a default string like "System Auditor". 

_System Auditor Role_
```
{
  "id": 14,
  "type": "role",
  "url": "/api/v2/roles/14/",
  "related": {
      "users": "/api/v2/roles/14/users/",
      "teams": "/api/v2/roles/14/teams/"
  },
  "summary_fields": {
      "user_capabilities": {
          "unattach": true
      }
  },
  "name": "System Auditor",
  "description": "Can view all aspects of the system"
}
```

##### STEPS TO REPRODUCE
1. Navigate to Users list
2. Select a System Auditor user 
3. Navigate to the user's Access tab
4. List item with `Role: System Auditor` is missing a name value in the first column 

##### EXPECTED RESULTS
Name column has a value for system auditor role

##### ACTUAL RESULTS
Name column has no value for system auditor role

##### ADDITIONAL INFORMATION
_Old UI & New UI_
<img width="1920" alt="Screen Shot 2020-08-04 at 12 22 45 PM" src="https://user-images.githubusercontent.com/15881645/89320156-1d445780-d64f-11ea-9f25-418b61e5598a.png">

_System Auditor with Demo organization project admin access_
<img width="956" alt="Screen Shot 2020-08-04 at 12 27 37 PM" src="https://user-images.githubusercontent.com/15881645/89321340-d9eae880-d650-11ea-8fa5-9cd18d5a9514.png">

**Comment by mabashian** [comment]
At first I was thinking that we should put something like `User Type` in the first column for this particular row but now idk...  Since the role can be removed it would seem odd to label it as `User Type`.  @wenottingham any thoughts on this one?  The first column displays the resources name in link form, the second column shows the resource type.  In the case of the system auditor role we don't have a value for either of those things.  Should we just leave them blank like we did in the old UI or should we attempt to detect this scenario and add some generic text?

**Comment by wenottingham** [comment]
I assume System Admin has the same issue.

If we're describing what the resource they have access to is, options are probably:
- leave it blank
- have a hardcoded 'System' tag there (that isn't a link)

**Comment by mabashian** [comment]
> have a hardcoded 'System' tag there (that isn't a link)

Sounds good to me

**Comment by tiagodread** [comment]
Verified that the user can see System when summary_fields.resource_name is empty and it’s possible search for System.

Added a e2e test in 5822
