### ISSUE TITLE
Not working disabling job isolation

### ISSUE THREAD

**Issue by DySprozin** [ansible/awx#7897]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not working disabling job isolation

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9.11
* Operating System: Ubuntu 16.04
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

set AWX_PROOT_ENABLED to False
set AWX_PROOT_BASE_PATH to "/tmp2" (any non-existent path)

##### EXPECTED RESULTS

job working in the Project dir

##### ACTUAL RESULTS

error "No such file or directory: '/tmp2/awx_108_9j68vbne'"

##### ADDITIONAL INFORMATION

How can I disable copy project to tmp dir and enable working playbooks in the Project dir?

**Comment by DySprozin** [comment]
"Starting in AWX versions above 6.0.0, the project folder will be copied for each job run. "
https://github.com/ansible/awx/blob/fcfd59ebe26d0051a838ea395d05665dba0db15d/docs/process_isolation.md

Is any way to disable it?

**Comment by Jochem22** [comment]
I also would like to disable this. I have local changes in the ansible.cfg for a project in /var/lib/awx/projects. This will be ignored when the project folder will be copied. Looks like the project folder will be copied from the source and not the local "/var/lib/awx/projects" folder?

**Comment by wenottingham** [comment]
No, this is intentional for a few reasons.

- Repeatability/auditability:  For SCM projects, if it's defined to run with a particular revision, it needs to run with that revision, not "that revision plus a local change".
- Parallelism: by each job run having its own checkout, it allows parallel job runs without potential interference with each other
