### ISSUE TITLE
Add Controls to SAML Organization Mapping

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#7901]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add the ability to disable automatic organization creation when a user logs into AWX/Tower and add controls regarding what organizations can be created through SAML authentication.

If an attribute is mistakenly updated to contain a large number of values, the next time a user logs into AWX/Tower, all of those erroneously added organizations will be populated as objects into the application. There should be controls around what organizations are created to prevent this for a better user experience.

**Comment by wenottingham** [comment]
The control to disable automatic organization creation is just not setting the SOCIAL_AUTH_SAML_ORGANIZATION_ATTR fields/maps - it already exists.

What I think may help in this scenario is better test functionality. Even if there were to be guardrails, you'd need a better idea of what will be created to set what the guardrails would be.

(This also isn't unique to SAML - a complex LDAP forest could end up creating *many* orgs and teams).

**Comment by wenottingham** [comment]
Is the idea here to precreate the orgs/teams and prevent creation of new ones? That may be possible, but does seem to be a workaround, and would require manual process any time you'd want to onboard a new group.

**Comment by mpetrive-rh** [comment]
@wenottingham I think most users are ok with somewhat manual, purposeful steps when onboarding new groups.  If you take the way the LDAP integration, which is what most users are using, requires an update every time you want to onboard a new group.  This can of course be streamlined by creating automation to update the LDAP org/team mapping.

**Comment by balonik** [comment]
@wenottingham `SOCIAL_AUTH_SAML_ORGANIZATION_ATTR` is there to add users to Organizations automatically based on data from IdP, creating Organizations it's just a side effect not primary function of that field, right?
In combination with #7902 it creates a dangerous situation where renaming Organization brakes access to AWX items for everyone in that Org.
As @mpetrive-rh mentioned you HAVE to do a manual action already. It's configuring the Org/Team mapping in SAML config page OR granting the user permissions manually. Proposed feature doesn't bring manual action to the table, it's already there.

An option to disable automated Org/Team creation on user login would help not to populate app with garbage AND improve user experience by avoiding that moments when you login and nothings there, because someone renamed your Org or Team.

Another option (which I personally prefer, but is more complex) is to add new immutable attribute like `key` to the Organizations and Teams and use that attribute to map LDAP/SAML stuff instead of using often complex, long and human friendly `name` values.

**Comment by wenottingham** [comment]
This was fixed in https://github.com/ansible/awx/pull/8069
