### ISSUE TITLE
git and manual scm project type integration

### ISSUE THREAD

**Issue by hdjur** [ansible/awx#7926]
When people work, they try to keep their history free from committing mistakes, ie junk versions of code that they know is defective from the start, that is I guess the motivation for using "Manual SCM Type" projects with awx, so that they can test things before they decide to push them to scm repository, such as git, or whatever they use. However, is there a possibility to create the manual directory, populate it via git clone, and do git commit and git push from that directory, all that via awx web console, or do all these things have to be performed manually via separate ssh session on awx host?

**Comment by wenottingham** [comment]
The point of manual projects is that they are entirely manually handled - we don't know (or care) whether it's a local git checkout, a shared filesystem, or something else. 

Since we recommend and want people to use source control natively via source control projects, I don't think we'd ever add features to 'upload' a project in this manner. We want the service to be resilient in case of server failure, with only needing the database to recover. To do this would require storing the uploaded content in the database... and that's not what it's for.
