### ISSUE TITLE
AWX is not pushing logs to datadog

### ISSUE THREAD

**Issue by bwahmed** [ansible/awx#7981]
I have deployed AWX tower and configured log aggregator. When I press test button. It says success but logs are not pushed. I'm not seeing any logs in datadog. 

AWX version I'm using is: 6.1.0.0

![Screenshot_2020-08-19 Ansible AWX SYSTEM](https://user-images.githubusercontent.com/45651587/91083430-ef5b9d00-e667-11ea-99ed-9415e83babd3.png)

**Comment by ryanpetrello** [comment]
Hey @bwahmed,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel.

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

I'd suggest first trying an upgrade to a newer version of AWX - the version you're using is pretty old at this point, and we've since completely reimplemented the external logging aggregation feature:

https://github.com/ansible/awx/issues/5155
