### ISSUE TITLE
Schedule Add form crashes when selecting a run frequency

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8002]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Visit a schedules page. In my example, I went to a Job Template > Schedules Tab > Add
2. Select a run frequency from the dropdown (once, daily, monthly)

#### EXPECTED RESULTS
The page loads normally.

##### ACTUAL RESULTS
The page crashes with the following error:

`TypeError: t.plural is not a function`

**Comment by dsesami** [comment]
This partially blocks https://github.com/ansible/awx/issues/6172

**Comment by dsesami** [comment]
I suspect this is related to running in production mode; see discussion in https://github.com/lingui/js-lingui/issues/437

**Comment by unlikelyzero** [comment]
@dsesami @mabashian before you close this, please do a brief look at the e2e tests to understand how we missed this in our automated coverage

**Comment by mabashian** [comment]
@unlikelyzero @dsesami I _think_ that this would only be triggered by running the command to compile the strings.  It's been a looooong time since we did that and pushed to devel (mostly because we didn't think it would have any impact on the app).  Obviously that's wrong.  We should probably get in the habit of compiling and committing the strings to the repo on some cadence to make sure things like this don't crop up.
