### ISSUE TITLE
Delete button inside kebab doesn’t works when trying delete on or more items 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8017]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Trying to delete some resource like Credentials, Organization etc using "Delete" option inside a kebab nothing happens.
See: https://github.com/ansible/awx/issues/7831

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.11
* Operating System: MacOs
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Credentials or Organizations
2. Select Advanced Search 
3. Select items on the list
3. Click on Kebab 
4. Click on Delete
5. Click on Delete inside modal

##### EXPECTED RESULTS

The resource be successfully  #deleted

##### ACTUAL RESULTS

The resource has not been deleted, no http request is made

![chrome-capture (3)](https://user-images.githubusercontent.com/12464858/91345275-7e2a0000-e7b5-11ea-8b0c-3ad1d527c4fa.gif)

**Comment by mabashian** [comment]
OK so I spent some time looking in to this issue and I think I generally know what's going on.  Rendering the `ToolbarDeleteButton` _inside_ a `Dropdown` component means that the confirmation `Modal` that we show on delete is also being rendered _inside_ the `Dropdown`.  The modal does pop up (as seen in the gif) but when you click on it (anywhere on the screen actually), the modal gets hidden and the dropdown menu gets hidden.  I _believe_ this is because we're clicking on something other than one of the dropdown items.

In order to fix this we either need to a) not render the modal inside the dropdown (which won't work if we want to combine the button and modal in one component) or b) figure out how to abort closing the dropdown on a click within the modal.

**Comment by mabashian** [comment]
I've included a fix for this in https://github.com/ansible/awx/pull/7993

**Comment by tiagodread** [comment]
Everything works well after merge this https://github.com/ansible/awx/pull/7993
