### ISSUE TITLE
Error hidden on Inventory Source Edit page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8045]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Error text is squished on Inventory Source Edit page

##### ENVIRONMENT
* AWX version: 40603c213af13ed40b7268aa6bd7f660fab3c112

##### STEPS TO REPRODUCE
1. Create an Inventory with 'Update on launch' and 'Update on project update' enabled.
2. Save
Note error text is squished

##### EXPECTED RESULTS
Error text to take up entire span of form

##### ACTUAL RESULTS
Error text takes up width of left aligned form fields

##### ADDITIONAL INFORMATION
![Screen Shot 2020-08-28 at 1 39 54 PM](https://user-images.githubusercontent.com/12446869/91608461-99c31100-e943-11ea-81fb-a52121911b07.png)

**Comment by mabashian** [comment]
Repurposing this issue since the ux has changed a bit.  If you follow these exact same instructions you'll get a 400 from the api but no error is shown.  I believe this is because the field `update_on_launch` is a checkbox and we don't have built in logic to display an error under/around a checkbox.

We may need to look at displaying the error generically again.  If that's the case, the text may still be squished and we should fix that.

**Comment by kdelee** [comment]
This will require a visual test

**Comment by akus062381** [comment]
Note: this issue has been fixed. 
this should not have a visual test because the error message is no longer present
will work on functional test

**Comment by akus062381** [comment]
tests have been automated. closing issue.
