### ISSUE TITLE
Keep comment in inventory during import

### ISSUE THREAD

**Issue by lerminou** [ansible/awx#8093]
#### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have in out company some inventories with some variables per host / group.
When our build team comment some variables in inventories, these comments are skipped during the import to AWX,
So it's hard to track some changes about the variables for the exploitation team

Is it possible to keep the comment when the import is performed 
![Capture d’écran du 2020-09-08 11-23-30](https://user-images.githubusercontent.com/3818051/92458499-c4279080-f1c5-11ea-8353-622e1ea85071.png)

**Comment by wenottingham** [comment]
How are you importing?

**Comment by lerminou** [comment]
I have a inventory  with some vars defined per group/host defined in bitbucket
In Awx I just set the inventory source as external with the link to my repository and the checkbox "update when the project updates"
I also tried the checkboxes "override variables"  to perform a full replace but nothing change

**Comment by wenottingham** [comment]
I defer to @AlanCoding, but I believe the ansible-inventory procedure procesess ini/YAML  inventory in a way that comments do not survive; there's not much we can do about it.

Variables in general can be posted as either JSON or YAML, and any saving as JSON will eliminate any comments as well.

**Comment by AlanCoding** [comment]
Maybe you meant that you put variables in `host_vars/` and `group_vars/` folders. That takes simple YAML and so I understand this expectation.

But we use `ansible-inventory` as an intermediary, and get JSON. I don't even know how one might go about passing through comments. Yes, it has a YAML option, but we can't use it because it's not the same data structure and the YAML data structure doesn't work for us. Even if they did give the same output as YAML, we wouldn't just be able to load it and dump it at will. We would have to combine variables, preserving comments.

So that leaves me at https://github.com/yaml/pyyaml/issues/90, changes would have to make their way through _several_ upstreams in order to get us to a design that could reasonably be talked about for use in AWX.

**Comment by wenottingham** [comment]
Closing; we cannot consider this due to the reasons above.
