### ISSUE TITLE
Enabling Fact Caching breaks the ability to use custom module paths

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#815]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
##### SUMMARY

If you've got fact caching enabled AWX will ignore custom library paths.
##### ENVIRONMENT
* AWX version: Latest
* AWX install method: Tower Installer
* Ansible version:  2.4.2
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a custom module and a non default library path /usr/share/ansible
2. set that as library in ansible.cfg library = /usr/share/ansible
3. create a job template using a playbook that calls that module
4. enable fact caching on job template
5. Run job

##### EXPECTED RESULTS

Expect that the module is run without an issue.

##### ACTUAL RESULTS
Receive an error
 ```ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.```

##### ADDITIONAL INFORMATION
Workaround is to add modules to the ANSIBLE_LIBRARY path hard coded inside AWX, disable fact caching option or alter project to house custom modules in library/ adjacent to playbook

**Comment by ryanpetrello** [comment]
We'll have to brainstorm on this a bit; it may be somewhat tricky.  Two ideas I had:

1.  Find out the value of `library` from `ansible.cfg` so we can compose a `:` delimited value ourselves using the "base" value.  Something like this might work:

```shell
ansible-config dump | grep DEFAULT_MODULE_PATH
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible']
```

...but `ansible-config` is only available from 2.4+.  Also, this would incur overhead of an additional `subprocess.call()` every time we run a playbook with fact caching.

2.  Symlink all of the Tower-injected custom modules into `<playbook.yml>/library` so that they're auto discovered and used.  This could get tricky in terms of:

    - overwriting existing `library` files
    - unintentionally leaving scm clones in a modified state

One downside to this is that it may not work if you make use of `import_playbook`.

**Comment by ryanpetrello** [comment]
I think the best solution to this would be to tell users to _not_ use `ansible.cfg`, but instead to do:

```
PATCH https://tower.example.org/api/v2/settings/jobs/
{
    "AWS_TASK_ENV": {"ANSIBLE_LIBRARY": "/usr/share/ansible"}
}
```

...and that if awx sees a value set there, it won't overwrite it - we'll just append the awx-specific modules to the path so that they're used properly.  This is also more amenable to clustering - you don't have to go stick `ansible.cfg` files everywhere to make this work.

@gamuniz @wenottingham how do you feel about this?

**Comment by gamuniz** [comment]
tried your solution before logging the ticket. it's hardcoded in tasks.py or someplace so it can't be appended.

**Comment by ryanpetrello** [comment]
@gamuniz yep, I'll work on a PR to make it work.

**Comment by rmfitzpatrick** [comment]
Verified on 3.2.3.21 with automated tests tbd.  @tvo318 documenting Tower's acceptance of `ANSIBLE_LIBRARY` over a library entry in a project's ansible.cfg seems like it would be helpful: http://docs.ansible.com/ansible/latest/intro_configuration.html#library

**Comment by ryanpetrello** [comment]
Resolved via https://github.com/ansible/awx/commit/2955842c44c69cc4b93811ac8311abdf48ba28bc
