### ISSUE TITLE
Failed to add workflow node.

### ISSUE THREAD

**Issue by gueux** [ansible/awx#818]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Can't create save any Workflow Template in Editor

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: Ubuntu
* Web Browser: Chrome 62.0

##### STEPS TO REPRODUCE

- create new Workflow Template
- go to Workflow Editor
- add new node with some job
- click Save

##### EXPECTED RESULTS

Close Workflow Editor with saved result

##### ACTUAL RESULTS

Modal Window appears with error:

"Failed to add workflow node. POST returned status: 400"

##### ADDITIONAL INFORMATION

I've got next error in awx_web container:

```
2017-12-13 17:45:57,453 WARNING  awx.api.generics status 400 received by user god attempting to access /api/v2/workflow_job_templates/11/workflow_nodes/ from 172.68.11.250
172.68.11.250 - - [13/Dec/2017:17:45:57 +0000] "POST /api/v2/workflow_job_templates/11/workflow_nodes/ HTTP/1.1" 400 60 "http://awx.xxxxxxxx.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "89.185.0.51"
[pid: 25|app: 0|req: 534/1508] 172.68.11.250 () {64 vars in 2682 bytes} [Wed Dec 13 17:45:57 2017] POST /api/v2/workflow_job_templates/11/workflow_nodes/ => generated 60 bytes in 55 msecs (HTTP/1.1 400) 8 headers in 237 bytes (1 switches on core 0)
```

**Comment by AlanCoding** [comment]
I'm pretty sure this is because of the lag in UI feature implementation, but it depends on the actual data being passed.

**Comment by Foxsa** [comment]
AWX version: 1.0.1.325
In my case status 400 returns if node's job has a survey. Without it everything is OK

**Comment by mkempster22** [comment]
AWX 1.0.2.289 also noticing it only fails with nodes that have surveys configured.

(I tried updating to .325 and ran into a whole load of bugs including the workflow editor not opening and JSON output of tasks not showing correctly and not being able to close the output.)

**Comment by AlanCoding** [comment]
I believe some survey-related bugs were fixed by #846 - specifically, surveys with required questions raised 400 errors. That was reversed, because the questions could be answered either by the workflow node, or the workflow variables themselves.

That fix was new as-of 1.0.2-293, so it's probably worth upgrading to get some fixes in.

**Comment by mkempster22** [comment]
Ah right okay, i'll try updating once I can fully test it as I had to recover to a backup this morning due to the upgrade breaking too many things to be usable

**Comment by Erlum** [comment]
Hi.

I'm running 1.0.4.7 and the problem seems to still be present. 

Adding a job to a workflow does not work if that job either uses a survey or requires something on launch. (ex: credentials) 

I've tried disabling the survey and requirements of a job in order to add it to the workflow, then enabling them, then launching the workflow and it doesn't work either : I am not asked to fill the requirements, which makes the job fail.

Is there any plan to fix this in the near future ? 

Thanks !

**Comment by coolcps** [comment]
I can only save workflows that contain nothing more than inventory/project sync.

1.  Trying to add a job with a credential that needs to be selected fails.  It allows me to select the credential and place the node, but when I click save, nothing happens.

2. Trying to add a job without a credential lets me place the node, but when I try to save, I get the error: Failed to add workflow node. POST returned status: 400

**Comment by mabashian** [comment]
This should be fixed by https://github.com/ansible/awx/commit/72f2994cc5f00848dd3e68074c32cef88707f48b
