### ISSUE TITLE
Not setting Container Groups credential crashes UI

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8199]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. go to container groups -> Add
2. Fill in the name, turn on pod spec override but don't set a credential.
3. Try to save. the page will crash:
![Screenshot from 2020-09-22 11-27-55](https://user-images.githubusercontent.com/19942822/93903606-db3aa800-fcc6-11ea-9732-a260070e0c75.png)

assigning @nixocio because he is familiar with this code.

**Comment by dsesami** [comment]
Interestingly, this results in an instance group, instead of a container group, if you hit back. this should be double-checked.

**Comment by nixocio** [comment]
This is somehow related to https://github.com/ansible/awx/issues/8184

**Comment by nixocio** [comment]
The API does not enforce a credential as required field for the `instance_groups` endpoint. And if a credential is not provided the resource type created will be instance groups, if a credential, `OpenShift or Kubernetes API Bearer Token` is provide it will be a container group. But since the UI is not enforcing a required Credential when creating a Container group. This issue was raised. That is why is related to https://github.com/ansible/awx/issues/8184. Once #8184 is fixed, we should revisit this one.

**Comment by nixocio** [comment]
I added a PR for the issue #8184. I will investigate this one now.

**Comment by dsesami** [comment]
It turns out that https://github.com/ansible/awx/pull/8239 fixed this as a side effect. This resolves the issue there. stubs will be included in `instance-groups/container-group-operations.spec`.

**Comment by nixocio** [comment]
Thanks for looking into this issue @dsesami, even though it was already fixed as a side effect of the #8239. I will update the `ContainerGroupDetails` code to be a bit more robust.

**Comment by dsesami** [comment]
this can be reclosed with the merge of #8280
