### ISSUE TITLE
Add metrics dashboard

### ISSUE THREAD

**Issue by swiedernix** [ansible/awx#8366]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Can we include a dashboard which includes all tower metrics to enable better troubleshooting?

I know that one can fetch those metrics from the Tower API, but I think it's worth to provide a builtin
dashboard (batteries included).

I wouldn't mind if AWX engineering would add more metrics, specific to AWX operations, to the API.

The goal is to get a AWX operations dashboard where one can immediately analyze the status of the AWX cluster.

**Comment by ryanpetrello** [comment]
We're unlikely to build some custom dashboard or visualization for this data, because existing tools already exist.  For what it's worth, `/api/v2/metrics/` is consumable out-of-the-box via tooling like https://prometheus.io

See:  https://docs.ansible.com/ansible-tower/latest/html/administration/metrics.html

**Comment by swiedernix** [comment]
sry ...  I know that AWX has an metrics API ... which we are already consuming using prometheus.

But our last encounters with Redhat support showed that support is clueless about the cluster status, which
is frustrating .... 

therefore an dashboard with all vital metrics would enable support to get a real picture of an AWX/Tower cluster.

One could also think of adding some vital metrics  to the tower API, like redis/callback receiver stuff/queue lengths ... you know all these which could be used to determine a serious problem within the current tower architecture.  Like having 200K jobevents/minute for example. I'm sure you've heard of that.

**Comment by ryanpetrello** [comment]
I work with folks in Red Hat support pretty regularly, and I definitely wouldn't classify them as "clueless" - they're working with the tooling they have (which is something that's constantly evolving, even upstream).  In any event, this is the public issue tracker for the open source AWX project, not Red Hat's product, so I'm not interested in airing grievances here, because it's not the place for it.

Much of what you're asking for *is* currently captured in sos reports in newer versions of AWX (or if not, can be added), and I'm not against expanding reporting, but we're unlikely to add a specific metrics dashboard _just_ for supportability.

If we add anything here, it would likely be part of the work categorized at https://github.com/ansible/awx/issues/7704, and it's likely metrics we'd store periodically and expose per-Instance at `/api/v2/metrics` or potentially `/api/v2/instances/` - not some sort of unified dashboard/metric user interface.
