### ISSUE TITLE
tower_inventory_source module in the AWX collection does not have the schedule endpoint implemented

### ISSUE THREAD

**Issue by spisakni** [ansible/awx#8456]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Taking a look at the awx/tower_inventory_source.py file I see no support for the /api/v2/inventory_sources/${id}/schedules/ endpoint that is available in the Tower API reference guide. This feature request is to formally request to have this endpoint added. 

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_inventory_source.py
![image](https://user-images.githubusercontent.com/7788463/97178523-f9843f80-176d-11eb-9dbb-a5c83bcd2327.png)

**Comment by sean-m-sullivan** [comment]
Looking at this, is this not already handled by the tower_schedule module? since inventory sources are part of unified job templates? Doing testing later today to be sure, but believe this to be the case. From the looks of it, we are not doing schedules in workflows/templates and other places, but instead using the tower_schedule module to do this function.

**Comment by beeankha** [comment]
Per @sean-m-sullivan 's comment above, I was able to successfully create a schedule for an inventory source by using `tower_schedule` module. Closing this issue.
