### ISSUE TITLE
Smart inventory issues

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8548]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Opening this bug to address all concerns related to this [issue](https://github.com/ansible/awx/issues/8542)
See: https://github.com/ansible/awx/issues/8542#issuecomment-722519786

- [x] The smart inventory form is missing helps popovers especially for the field `Host Filter`

- [x] The host filter modal contains link to hosts for each item, which can easily move the user to host details (the old UI is a list without link)

- [x] The host filter modal is missing the `Key` button that contains very useful information about how to perform search

**Comment by nixocio** [comment]
I followed up with @mabashian about those topics.

 > The host filter modal contains link to hosts for each item, which can easily move the user to host details (the old UI is a list without link) 

This one is a general change. Since we re-use this component in different places. We should file a different issue for this one, and explore a solution.

> The host filter modal is missing the Key button that contains very useful information about how to perform search

The advanced search in the new ui allows the user to filter those keys. This is a different approach from the current ui.

![image](https://user-images.githubusercontent.com/9053044/99092389-135fb800-259f-11eb-9c9f-8a8bc84630af.png)

**Comment by tiagodread** [comment]
@nixocio Opened the issue https://github.com/ansible/awx/issues/8610 to track the item:

> The host filter modal contains link to hosts for each item, which can easily move the user to host details (the old UI is a list without link)

**Comment by tiagodread** [comment]
All items was addressed, opened a separate issue to evaluate usage of links in modal, we can safely close this.
