### ISSUE TITLE
Evaluate usage of links in modal

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8610]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The host filter modal contains link to hosts for each item, which can easily move the user to host details (the old UI is a list without link)
This issue is a follow up from https://github.com/ansible/awx/issues/8548.
See: https://github.com/ansible/awx/issues/8548#issuecomment-726844266

##### STEPS TO REPRODUCE

1. Navigate to Inventories
2. Create a smart inventory
3. Click on Smart host filter lookup

##### EXPECTED RESULTS

The list items shouldn’t contain links, see the old UI:
![image](https://user-images.githubusercontent.com/12464858/99451670-4ab4c880-2901-11eb-907d-5b5bf09b89ab.png)

##### ACTUAL RESULTS

The host items contain links which the user can easily click on it and go to the host details
![image](https://user-images.githubusercontent.com/12464858/99451740-6b7d1e00-2901-11eb-929a-72e6fd3316c3.png)

**Comment by nixocio** [comment]
I think this is a general issue not just applicable to Smart Inventory modals. Smart inventory is one good example.

**Comment by unlikelyzero** [comment]
@nixocio @mabashian filing this as a ux issue and medium as the feature works as designed but the UX is not obvious. 3x people have used it incorrectly

**Comment by mabashian** [comment]
>3x people have used it incorrectly

I'm assuming the way they think this works is that they need to select hosts by clicking on them instead of creating a filter?

I think we have a few options here with varying degrees of difficulty to implement:

1) We could remove the links for this modal in particular.
2) We could change the way the links work so that they always open in a new tab (this is what I would prefer because I do think having the links is beneficial)
3) We could completely overhaul the UX of the smart inventory host modal and try to make it abundantly clear that you need to enter in a search term to satisfy the field.

**Comment by unlikelyzero** [comment]
@mabashian number 2 should use the popout link

**Comment by mabashian** [comment]
@tiagodread I don't think we have _any_ links in lists in modals anymore.  I checked the host filter modal and this is what it looks like:

<img width="1655" alt="Screen Shot 2021-06-21 at 4 07 57 PM" src="https://user-images.githubusercontent.com/9889020/122821457-df721100-d2aa-11eb-99bb-4eacb3a55746.png">

I feel like we can close this and perhaps open an enhancement to _add_ links that open in a new tab to these places.  What do you think?

**Comment by tiagodread** [comment]
@mabashian we can close this one, I agree.
