### ISSUE TITLE
Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY parameters to the tower_credential module

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8611]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is a request to add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY parameter support for the tower_credential module.

**Comment by wenottingham** [comment]
This is not planned; the existing type-specific fields (such as using "username" and "password" for the access_key and secret_key) are deprecated in favor of using `inputs`.

**Comment by t-readyroc** [comment]
This issue was actually filed on my behalf, but was incorrectly filed. Rather than adding parameter support as listed in the issue above, my request was rather to update [the documentation](https://cloud.redhat.com/ansible/automation-hub/ansible/tower/content/module/tower_credential) to correctly reflect the following paradigm:

- AWS_ACCESS_KEY_ID = the "username" input
- AWS_SECRET_ACCESS_KEY = the "password" input

As the documentation currently stands, the user is left wondering how to set those inputs correctly.
