### ISSUE TITLE
Smart inventory details doesn’t update data after editing 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8635]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After editing an inventory source, the user is redirected to de details tab, but the data changed isn’t updated, the user needs to refresh the page to see everything updated

##### STEPS TO REPRODUCE

1. Create a smart inventory
2. Edit this smart inventory

##### EXPECTED RESULTS

- After editing all new data should be displayed in the details page
- All data present in details tab should be a unique data-ouia identifier in order to interact with this elements.

##### ACTUAL RESULTS

The data was persisted but not displayed in the details tab

##### ADDITIONAL INFORMATION
![smart1](https://user-images.githubusercontent.com/12464858/99675655-3c2bf580-2a56-11eb-8037-defcea5332a7.gif)

**Comment by unlikelyzero** [comment]
@mabashian @wenottingham btw, as we start to get closer to release, I think we should redefine priority as severity. Once we get to "hardening", it'll be easier to sort/filter on severity to then drive priority.

In this case, this is a single page (of dozens) and can be fixed with a simple refresh, so 'low'. 
If this was app-wide, 'medium'. 
If this broke the form entry, 'high'

**Comment by nixocio** [comment]
Closing this one as a duplicate - See: https://github.com/ansible/awx/issues/10407
