### ISSUE TITLE
Bulk delete of tokens doesn't list personal access tokens

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8680]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tokens aren't named so we'll have to get creative here.  It looks like we're currently displaying the application name (if present).  Note that 3 rows are selected but only one listed in this screenshot:

<img width="1435" alt="Screen Shot 2020-11-25 at 10 39 25 AM" src="https://user-images.githubusercontent.com/9889020/100249614-c10d8800-2f0a-11eb-99d9-418573427567.png">

The one thing that's probably going to be unique across these tokens is the expiration time.  We may end up having to use that in combination with some static strings (Personal access token/Application access token) as well as the application name.

**Comment by mabashian** [comment]
This error is also thrown to the console because tokens don't have names:

<img width="1075" alt="Screen Shot 2020-11-25 at 10 48 01 AM" src="https://user-images.githubusercontent.com/9889020/100250517-bf908f80-2f0b-11eb-90b4-a65b0522f9b3.png">

**Comment by nixocio** [comment]
This issue has changed a bit since it was filed. Instead of appending `token` to the application name - to create a token name, right now we are displaying just the name of the application itself. However, when deleting in bulk we do not show the `Personal Access Token` selected to be deleted.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/9053044/127671519-74dd6d60-bb82-403e-a46e-56d98757e200.png">

**Comment by akus062381** [comment]
@nixocio can I please have good locators added here?
Data-OUIA locators are preferred. Data-cy are next best, ID third best.
We are trying to get away from using aria labels wherever possible. Thank you!

The items that need locators added:

- each item listed as selected for deletion
- cancel button
- the elements inside the Alert Modal header
- it would be great to have a data-OUIA for the close button instead of an aria label

**Comment by akus062381** [comment]
issue resolved
