### ISSUE TITLE
[ui_next] Email fields should not exist for Webhook form on Notification Template

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8817]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Email fields should not exist for Webhook form on Notification Template

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Create a notification template for webhooks
Note: email options is a required field. Effectively breaking webhook notification templates

##### EXPECTED RESULTS
1. Only Webhook field options

##### ACTUAL RESULTS
1. Email field options

##### ADDITIONAL INFORMATION
![Screen Shot 2020-12-10 at 12 14 27 PM](https://user-images.githubusercontent.com/12446869/101805876-45523480-3ae1-11eb-8068-40431b1a1262.png)

**Comment by jakemcdermott** [comment]
note: The field should be there, but it is misnamed. The associated fix updates the label so that the field name is correct.

**Comment by unlikelyzero** [comment]
this was attached to the issue and closed without coverage. All high severity regressions will have automated coverage added

**Comment by unlikelyzero** [comment]
No unit tests added to PR

Will need to verify with a functional test

**Comment by tiagodread** [comment]
The only change here was a simple label/text change, it seems to me that was firstly added wrong, but now it's fixed, also, this label text is not something that will regress because isn’t a functional change, we don't need an extra e2e test to cover it, we do have the suite `notification-crud.spec.js` that is testing the webbook option as well.

![image](https://user-images.githubusercontent.com/12464858/109972830-7c964300-7cd6-11eb-9664-cb915d3f1f43.png)

cc @jakemcdermott @unlikelyzero
