### ISSUE TITLE
Standalone AWX

### ISSUE THREAD

**Issue by dylan8911** [ansible/awx#882]
##### ISSUE TYPE

 - Feature Idea
 - Issues

##### COMPONENT NAME

 - Installer

##### SUMMARY

I was able to get AWX out of docker and make it work, depending on the version that's being pulled, on both Centos and Ubuntu. However, I keep on running into small annoying issues. For example: 

 - On version 1.0.3.301, the scm tasks never pull our custom roles.
 - On version 1.0.3.303, we get an internal server error.

Hence, my team and I were wondering... Are there any plans on getting an official docker-less version of AWX, one that could be installed directly on Centos, in the roadmap?

**Comment by apple4ever** [comment]
I'd love that as well. You'd think setting up AWX using Ansible via a playbook would be relatively easy, or they'd provide the playbook for that (since that's the whole point of Ansible & AWX). I'm not a fan of Docker, so hopefully this is added. 

BTW, if you could share your setup, that would be awesome.

**Comment by seniormuffinman** [comment]
You can try this one, not official though.

[AWX RPM ](https://github.com/subuk/awx-rpm)

**Comment by wwitzel3** [comment]
There are currently no plans to do this.

**Comment by MrMEEE** [comment]
Repository and installguide (unofficial):
https://github.com/MrMEEE/awx-build/blob/master/installguide

**Comment by muzzol** [comment]
@wwitzel3 so the only way to officially install AWX is through the playbook install with docker?

**Comment by mkempster22** [comment]
@muzzol Only official ways are listed here: https://github.com/ansible/awx/blob/devel/INSTALL.md
Docker and Openshift

**Comment by dylan8911** [comment]
Sorry for the delay.

I got this fully working outside of docker or openshift. Thanks for the effort tho!

@apple4ever I'm waiting on our management team for the authorization to share my playbook. If I can, i'll get back to you.

**Comment by sadoMasupilami** [comment]
@dylan0911 I would really love to see that too!

**Comment by muzzol** [comment]
@wwitzel3 is there any problem leaving this issue open as a feature request?

I think is obvious there's interest in AWX beyond docker (ex: lxc, openvz, solaris zones), so even if it takes some time for a dev to take over it, I would like to get some centralized (and official) feedback.

**Comment by mgsreddy** [comment]
@dylan0911 , Would you like to share your playbook on this?

**Comment by J-SirL** [comment]
Why do they have only Docker junk!, I  wote that we should create a fork to create a proper version of awx.

**Comment by MrMEEE** [comment]
@J-SirL @mgsreddy @muzzol @dylan0911 You guys are welcome to try my RPM version and join in on the project:

https://github.com/MrMEEE/awx-build/blob/master/installguide.md

**Comment by shanemcd** [comment]
Hi @J-SirL, we only support running AWX in Docker because it's an open source project and we do not have the resources to support multiple OS distributions or versions. The downstream product, Ansible Tower does have the option of installing on Red Hat-based OSs and Ubuntu via their native packaging systems. I'm sorry if this is frustrating but it's really a matter of support / bandwidth, not that we hate you.

**Comment by ryanpetrello** [comment]
It's also worth mentioning that there's nothing _wrong_ with other open source approaches to installing awx, like the one mentioned above (https://github.com/MrMEEE/awx-build/blob/master/installguide.md).  It's just that if you need support for those install method, and you file an issue in this awx issue tracker, the awx maintainers aren't _as_ open to helping troubleshoot (because we didn't write, and we don't maintain https://github.com/MrMEEE/awx-build/blob/master/installguide.md).

**Comment by apple4ever** [comment]
@MrMEEE NICE, thought I wish it was in deb format! I'd actually be willing to help get that going. 

@dylan0911 any update?

**Comment by MrMEEE** [comment]
@apple4ever I actually already have the Source build for Ubuntu running, but haven't had the time to do the Debian build files for the package, and the integration for pushing it to launchpad..

**Comment by dylan8911** [comment]
All, 

I'm sorry for never getting back to this thread. My manager asked me to wait before replying and that they would take a decision on this and let me know if we would make my work public. 9 Months later, I don't think this will ever happen...

In the meantime, with the continuous stream of updates this project has, my team and I ended up reworking the ansible files and docker tasks to make the vanilla "dockerized" project work for us. 

Sorry =/
