### ISSUE TITLE
[ui_next] [UX] When adding role to team multiple times state is erroneously remembered

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8824]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We currently preserve the last known configuration on the Add user workflow. Also

```Dissociating team roles is not really working. I’ve created a role to admin an inventory and then deleted it. Then I dissociated that and the list was clean. Then I tried to add an org role and the inventory one came with it. This seems related to the not resetting the form above.```

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Add a resource type permissions to a user from the team page.
2. Add another resource type permission with the 'Add' button
Note: refilled form. Including Admin rights

##### EXPECTED RESULTS
Some permission state remembered. Not the Admin permission role.

##### ADDITIONAL INFORMATION
![Screen Shot 2020-12-10 at 1 30 22 PM](https://user-images.githubusercontent.com/12446869/101814256-e2b26600-3aeb-11eb-9336-c55f23b11e98.png)

**Comment by unlikelyzero** [comment]
May need to split this up based on:

```Dissociating team roles is not really working. I’ve created a role to admin an inventory and then deleted it. Then I dissociated that and the list was clean. Then I tried to add an org role and the inventory one came with it. This seems related to the not resetting the form above.```

**Comment by mabashian** [comment]
This sounds much more like a bug than an enhancement

**Comment by mabashian** [comment]
@unlikelyzero this definitely sounds like two separate issues.  I'm not able to reproduce the first issue but it does sound concerning.

>Dissociating team roles is not really working. I’ve created a role to admin an inventory and then deleted it. Then I dissociated that and the list was clean. Then I tried to add an org role and the inventory one came with it. This seems related to the not resetting the form above.

This part is a bit confusing to me.  Do you have concrete steps to repro?

**Comment by mabashian** [comment]
Here's my tldr; version:

1) Go to a team's roles list
2) Click add and associate a job template admin role (the job template doesn't matter just make sure it's one that's not already associated)
3) Without refreshing/navigating away click add again
(Note that the state for the previous add is still present - this is not correct, it should be back to it's original form)
4) Attempt to associate a _different_ job template admin role

Duplicate requests will get made.  One request will successfully associate the role, the other will result in a 400.

We should only be making the one request.

Another slightly different situation that is probably the exact same bug:

1) Go to a team's roles list
2) Click add and associate a job template admin role (the job template doesn't matter just make sure it's one that's not already associated)
3) Without refreshing/navigating away click add again
(Note that the state for the previous add is still present - this is not correct, it should be back to it's original form)
4) Attempt to associate a _different_ job template _execute_ role

Note that again, 2 requests are made but this time one is execute and one is for admin on the second job template.  This is incorrect because we only wanted to apply execute to the second job template.

**Comment by mabashian** [comment]
We don't have this problem with the resource role add modal because I think that component is mounted/unmounted when the button is clicked/modal is closed.  In the case of the user/team role add the button is _included_ in the component with the wizard.

**Comment by akus062381** [comment]
@mabashian I am seeing this:
![image](https://user-images.githubusercontent.com/63685497/120538625-c0234a80-c3b4-11eb-93f8-5354eecea08c.png)

**Comment by akus062381** [comment]
resolved.
