### ISSUE TITLE
[ui_next] Can add team permissions to team

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8835]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can add team permissions to team.

This menu is for granting access to a team. Granting a team access to another team is extremely confusing, and there’s no articulable guidance about the nuances and hazards of doing that. It would be best to not present this menu for teams, and assume that granting access ONLY means granting users access to the team.

<img width="629" alt="Screen Shot 2020-12-10 at 5 29 53 PM" src="https://user-images.githubusercontent.com/12446869/101837632-587af980-3b0d-11eb-8307-16a4a1516ee2.png">

##### ENVIRONMENT
* AWX version:12/10

**Comment by unlikelyzero** [comment]
@AlanCoding can you expand on the can of worms

**Comment by AlanCoding** [comment]
We did not allow adding teams to team roles in the old UI. The other immediate issue is exactly what you say for this form itself

> Granting a team access to another team is extremely confusing, and there’s no articulable guidance about the nuances and hazards of doing that.

But there's another problem in that the access list of objects the target team has access to will not give sufficient information for users to understand. By "target team" I mean if you have teams A->B, team A's member role becomes a member of team B, and then B->JT, the B team has execute role for the job template, then users of team A will show up in the access list (I believe `/api/v2/job_templates/42/access_list/`) for the JT, but not with sufficient details. They just abstractly have that permission _somehow_ and UI does not know the permission can or cannot be revoked, or even what revoking that permission would _mean_. That's why I feel that it would be easiest to keep team-to-team permissions out of the new UI as well.

**Comment by tiagodread** [comment]
Ok, this is the result, we are not displaying the `Team` option in Add Roles modal for a team anymore

![image](https://user-images.githubusercontent.com/12464858/116256109-42cb4100-a749-11eb-98cc-3d551d93ae4a.png)
