### ISSUE TITLE
[ui_next] Inventory update Delete hits wrong endpoint

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8838]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory update Delete hits wrong endpoint.

```I try to delete the SCM inventory update from the job page. It fails with an error about the inventory, but it shouldn’t be deleting the inventory, it should only be deleting the update.```

##### ENVIRONMENT
* AWX version: 12/10

##### MORE INFO
Also, that’s not the right number for the inventory, 66 is the ID of the inventory update.
![Screen Shot 2020-12-10 at 3 52 00 PM](https://user-images.githubusercontent.com/12446869/101828548-b30d5900-3aff-11eb-8a7a-d10208387cbd.png)

**Comment by mabashian** [comment]
https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx#L364 should be InventoryUpdatesAPI

**Comment by akus062381** [comment]
I manually tested this by creating a source within an inventory and Syncing it. I clicked Sync a few times to generate multiple jobs. 
When I went to the jobs page and selected multiples of the jobs I had just triggered, and click the delete button, instead of returning the list of remaining jobs, the jobs page showed "No Jobs Found".
When I clicked refresh, then the UI showed all of the remaining jobs.
![image](https://user-images.githubusercontent.com/63685497/114916335-ac1a8e00-9df2-11eb-95d9-306edd3df186.png)
![image](https://user-images.githubusercontent.com/63685497/114916377-b63c8c80-9df2-11eb-98c9-19c31022e132.png)

I am going to put this back into devel to be fixed.

**Comment by mabashian** [comment]
@akus062381 I wasn't able to reproduce this behavior given the description.  Do you mind generating a gif for us or walking through it step by step?

How many jobs did you select to delete?  Was it a whole page?

**Comment by mabashian** [comment]
Also - we may want to consider what you found to be a new bug and open a new issue so that we can close this one out.

**Comment by akus062381** [comment]
closing and opening a new issue- https://github.com/ansible/awx/issues/10272
