### ISSUE TITLE
Unexpected 'inventory deleted' error on template survey launch

### ISSUE THREAD

**Issue by natman** [ansible/awx#8910]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Impossible to launch a template because of deleted inventory.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: centos 7
* Web Browser: firefox

##### STEPS TO REPRODUCE

 launch the survey of a template and fill the vars, atvthe final step of the survey, awx complains that the inventory is deleted. We cannot go further and it is Impossible to launch the template

##### EXPECTED RESULTS

The wanted inventory to be available and the template to launch.

##### ACTUAL RESULTS

Inventory deleted whatever is the inventory.

##### ADDITIONAL INFORMATION

I tried several inventories and several templates.
I previously upgraded from a full functional 15.0.1 awx.

**Comment by mabashian** [comment]
@natman Can you provide us with a little more information about how the job template was configured so that we can reproduce? I'm mostly interested in what fields are being prompted at launch.  Is inventory prompted at launch and/or is there a default inventory set on the job template?

If possible, can you post a screenshot or gif of the error you're seeing?

**Comment by natman** [comment]
![image](https://user-images.githubusercontent.com/1138093/102392659-aa24f780-3fd7-11eb-81a4-dea85a2bd3b0.png)
![Sélection_012](https://user-images.githubusercontent.com/1138093/102391757-6f6e8f80-3fd6-11eb-85ac-e8b47da4de5d.png)
![Sélection_019](https://user-images.githubusercontent.com/1138093/102392490-68944c80-3fd7-11eb-9c7c-d2c2c2befbb7.png)
![Sélection_014](https://user-images.githubusercontent.com/1138093/102391766-739aad00-3fd6-11eb-9314-a65f1106d8fb.png)
![Sélection_015](https://user-images.githubusercontent.com/1138093/102391791-78f7f780-3fd6-11eb-99ed-1011009e3653.png)
![Sélection_016](https://user-images.githubusercontent.com/1138093/102391801-7c8b7e80-3fd6-11eb-81a8-300e31675204.png)
![Sélection_018](https://user-images.githubusercontent.com/1138093/102392082-e6a42380-3fd6-11eb-86d4-02129feccef7.png)

**Comment by natman** [comment]
no prompted inventory set, therefore, I tried with a prompted inventory, with or without it the result is the same.

**Comment by jakemcdermott** [comment]
possibly related: https://github.com/ansible/awx/issues/8933

**Comment by Chaos-Work** [comment]
I am experiencing the same issue on 16.0.0; however, I noticed that the "Some of the previous step(s) have errors" error only happens when the previous steps have default values. If I manually select something different then re-select the default values, that error goes away and the play runs just fine.

The inventory deleted message never goes away, though.

**Comment by mabashian** [comment]
@natman @Chaos-Work I'm having trouble reproducing this on the latest devel.  I suspect @jakemcdermott is right that #8933 might be related.  A fix for that went in here: https://github.com/ansible/awx/pull/9028 which would mean a fix went in in AWX 17.0.0 (I think).  Are you all still seeing this bug on versions greater than 17.0.0?

**Comment by mabashian** [comment]
@tiagodread @one-t @akus062381 I suspect this bug was fixed when we fixed #9028

**Comment by akus062381** [comment]
I also tested this, cannot reproduce. We already have coverage.
