### ISSUE TITLE
Job Output / Time Elapsed not updating until the job finishes

### ISSUE THREAD

**Issue by tstahnke2** [ansible/awx#8930]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When launching jobs, all websockets appear to be working correctly, but only the indicator for the job running appears to update. The time elapsed and the output from the job does not appear until the job has completed.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Windows 10
* Web Browser: Chrome/Brave/Firefox/Edge

##### STEPS TO REPRODUCE
1. launch a template
2. the elapsed time will be 0 until the job finishes
3. no output will appear until the job finishes

##### EXPECTED RESULTS
The job output/time elapsed should continuously update as the job runs

##### ACTUAL RESULTS
The job output and time elapsed don't update until the job finishes

##### ADDITIONAL INFORMATION
Screen shot of job right after launching (while the project SCM is updating)
![image](https://user-images.githubusercontent.com/45852091/102403897-f01c9400-3fb4-11eb-9d9d-e93ac0e66a4e.png)

Screen shot after SCM project has updated and the job has run for a few seconds
![image](https://user-images.githubusercontent.com/45852091/102403920-fad72900-3fb4-11eb-8cc5-f1fc611c24f5.png)

Screen shot after the job has finished
![image](https://user-images.githubusercontent.com/45852091/102403983-13474380-3fb5-11eb-9147-56593456ec4a.png)

Note that event the job finished indicator doesn't show up until I reload the view:
![image](https://user-images.githubusercontent.com/45852091/102404079-3245d580-3fb5-11eb-9c1b-2127e28f163e.png)

**Comment by jakemcdermott** [comment]
:wave: Hello, @tstahnke2  Thanks for creating this issue.

The elapsed time display issue is being tracked here: https://github.com/ansible/awx/issues/8931

And the job output update bug you described is caused by https://github.com/ansible/awx/issues/8596. 

We'll have fixes for both in an upcoming awx release.

**Comment by robinduerhager** [comment]
Hey, i've got the same problem with AWX 20.0.0.
It seems like awx-web is just doing an api call at the start and the end of the job. No `elapsed` variables are sent via the websockets. However, i do see real-time stdout Output after adding websocket support to my nginx-proxy-manager. Although, the Job Status and elapsed time does update when the job finishes (probably due to an api request happening after initializing the job and one after the end of the job).

In the image, the highlighted request is the last that happened, a few requests before (the `/api/v2/jobs/119/` request) is the one that happened after initializing the job.

Didn't know if i should create a new issue for this, because this one matches perfectly to my problem :).

![ansible-awx network](https://user-images.githubusercontent.com/18482238/156401373-4ac7574d-ce91-4cda-b45d-edf0583293f8.png)

**Comment by ryanmerolle** [comment]
@robinduerhager I can confirm I have the same issue with AWX 20.0.0

**Comment by matsonfruit** [comment]
please reopen. still having this issue on AWX 21.0.0
