### ISSUE TITLE
Credential type override default credential type options on credentials form

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8944]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The credential type select on credentials form show all default options BUT when. you start creating custom credentials types these new credential types override the default options displayed on Credentials form -> credential type select.

##### STEPS TO REPRODUCE

1. Navigate to credential types
2. Create many credential types
3. Navigate to Credential -> Add form
4. Click on credential type select

##### EXPECTED RESULTS

The Credential type list should contain all default options + custom credential types

##### ACTUAL RESULTS

Default Options:

<img width="468" alt="Screen Shot 2020-12-17 at 16 36 25" src="https://user-images.githubusercontent.com/12464858/102536069-d5ffb600-4087-11eb-8af7-29bb54545a0a.png">

List with custom credential types:

<img width="447" alt="Screen Shot 2020-12-17 at 16 44 34" src="https://user-images.githubusercontent.com/12464858/102536121-e879ef80-4087-11eb-8667-5a65fe37b827.png">

Then, trying to edit any credential the page crash:

![image](https://user-images.githubusercontent.com/12464858/102536975-1ca1e000-4089-11eb-82a1-8f1397eb3c1c.png)

**Comment by tstahnke2** [comment]
@jakemcdermott I've got a fix for this that's working in local, basically all that needs to happen is a QS_CONFIG that specifies page size (I set it to 2000), and pass the params to the .read() on the CredentialTypesAPI. Otherwise the default is used and it only pulls the first page without any params (which happens to be the most recent entries; or some other unsorted list, not sure exactly).
