### ISSUE TITLE
Upgrade to 16.00

### ISSUE THREAD

**Issue by dugs951** [ansible/awx#8955]
Hi,

how can i upgrade from 15.01 to 16.00?

Thanks

**Comment by TownGeekAus** [comment]
Backup you old awx installer  because there is the inventory where you need all the  password need to create the yml file

make  a yaml file  like update.yml  in the same installer directory include the following:
admin_password: 'password'
pg_password: 'awxpass'
secret_key: 'awxsecret'

of course put the correspond value to you admin password pg password and secretkey that comes from your previous installation

to start the upgrade  just run   ansible-playbook -i inventory install.yml  -e @update.yml  

that's all enjoy the new awx

**Comment by diegorebolledo** [comment]
Hi @TownGeekAus 

do you have to stop the awx containers for doing the upgrade?

when I do the upgrade my awx_postgres container get in an eternal restarting state.

**Comment by dugs951** [comment]
I make what do you say but now i have this Problem:
AWX is installing.

This page will refresh when complete.

What i can do?

**Comment by TownGeekAus** [comment]
Sorry mate for the delay in my response until now i saw you message you right i miss that part

Stop all you containers

make docker images  
redis               latest              62f1d3402b78        7 weeks ago         104MB
ansible/awx         15.0.1              04558a4dc475        2 months ago        1.29GB
postgres            10                  3cfd168e7b61        2 months ago        200MB

Remove onlyy the redis image and the ansible/awx image

After that just run the installer and that's all works like a charm just to let you know the version 16 is missing some stuff like the ability to configure authentication  it's looks like was a version just before christmas and still buggy
