### ISSUE TITLE
How to edit LDAP settings in 16.0.0

### ISSUE THREAD

**Issue by jconallen** [ansible/awx#8960]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

New 16.0.0 installation via Docker Compose.  Not sure how to configure LDAP.  It says that the form is coming.  Is there a configuration file I can use to specify the LDAP information ?

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Centos8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

New 16.0.0 install via Docker Compose.  Log in with admin id and password.  Select Settings > LDAP default.

I see the form but pressing the Edit button at the bottom the response is "Edit form coming soon :)"

##### EXPECTED RESULTS

a form to edit LDAP setting with.

##### ACTUAL RESULTS

"Edit form coming soon :)"

**Comment by hungpr0** [comment]
workaround: you can use the API https://your_tower/api/v2/settings/ldap/

**Comment by nv30** [comment]
Same here. Any updates or ETA?

**Comment by fouram** [comment]
This pull request adds the functionality to the new UI: https://github.com/ansible/awx/pull/8781
it looks like testing isn't complete yet but this is in the works and should be ready "soon"

EDIT: I should mention I'm not involved with the project in any way and this is just information i found poking around here trying to answer this same question.

**Comment by unlikelyzero** [comment]
@fouram is exactly right! We're testing this as we speak. Tests which required external infrastructure or modify global state seem to take the longest. :)

Hope to see it in the next release! I'm going to close this issue so that we can follow it here https://github.com/ansible/awx/pull/8781, https://github.com/ansible/awx/issues/8291, and on awx releases.

https://github.com/ansible/awx/issues/8960#issuecomment-749479487 this workaround is perfect
