### ISSUE TITLE
Notify user that a sync has started and completed

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#9013]
On the details view for Inventory Sources the user can click a sync button.  There is no notification to the user of the start, success, or failure of that action.  We should notify the user some how.  Consider adding websockets to this view and rendering the JobCancelButton when syncing is in progress.  https://github.com/ansible/awx/pull/10113

##### ISSUE TYPE
 - Feature Idea

**Comment by unlikelyzero** [comment]
Marking as enhancement instead of feature as this is not required for feature parity

**Comment by john-westcott-iv** [comment]
What if clicking the sync button on the details page took you to the job screen? At least then you would know that Tower is "doing something" once the button is pushed.

**Comment by mabashian** [comment]
Before anyone works on this lets discuss with Bill/Taufique

**Comment by wenottingham** [comment]
We do now have very minimal feedback that the sync button was presed, you do still have to go to another page to see the status.

**Comment by nixocio** [comment]
After following up with @mabashian about this issue, in order to be consistent we should add the same UX already implemented on project details page. Not allowing the user to start multiple `syncs` from the details page.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/9053044/130455353-440c81dc-b5b7-4e6a-b370-668e4c382023.png">

**Comment by akus062381** [comment]
resolved
