### ISSUE TITLE
inventory file field should be typable

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#9043]
![Screenshot from 2021-01-08 10-53-40](https://user-images.githubusercontent.com/9753817/104035302-fb23a800-519f-11eb-8c05-98b50d103d51.png)

**Comment by ntfc** [comment]
Old 15.0 UI used to be like this: https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#sourced-from-a-project

**Comment by CaptainStealthy** [comment]
+10000!

I just installed a new instance of AWX to tinker with, before trying the time-limited trial of Tower. And I've been so discouraged by the fact that I can't even do something as simple as import my inventory from Git!

The inventory file dropdown doesn't pick up my inventory files, which had `.yml` extensions. I found #174 and #232 in my searches, which made me think all I had to do was remove the `.yml` extensions, so I did.

And now, even after syncing the project I added with Git (even with a clean and delete done first), the "inventory file" dropdown **STILL** doesn't list my inventory files.

On top of all that, the docs say that you can enter a freeform text path - but that is clearly not the case.

I've been so pleased with my experience using Ansible so far - until I tried AWX - with the hope of selling Tower to the bean counters. I can't justify using company money to buy a product when I'm not even inclined to use the open-source app that it's derived from.

Sorry for the rant. Please fix this. 😢

**Comment by kakkotetsu** [comment]
+100000

**Comment by sc01194** [comment]
Same here with release 16.0.0. Inventory files from my gitlab repo cannot be imported, I cannot type or select my inventory files.
Old setup made with former version are still functionnal however and inventories are imported correctly

**Comment by bimmerkiev** [comment]
the same problem here( with release 16.0.0
please, fix it ASAP:((

**Comment by fidanf** [comment]
Gotta rollback to 15.0.1 because of this. Our project is based on multiple inventory files which could all be loaded typing the containing folder.

**Comment by sangeethdba** [comment]
it would be great if someone reply to this .this is absolute necessary feature where one should be able to chose the inventory file from any path.

**Comment by enscogit** [comment]
I am in the same situation as @sangeethdba ...I am trying to configure a fresh AWX install using the latest version (I don't have an old version to rollback to). This is for the purpose of assessing whether I will be recommending Ansible or Puppet to my company. Ansible was winning until I started trying to get AWX configured to be useful. The authentication forms are not accepting input in the AWX 16.0.0 docker model. I don't really like puppet but if the Ansible developers are releasing partially baked software I will have to recommend Puppet.

**Comment by CaptainStealthy** [comment]
@enscogit I do agree that this is a game-breaking bug that needs to be fixed. FWIW, I was able to rollback to 15.0.2 from 16.0.0.

That said, however, I would say that AWX is "in development" rather than "partially baked" - AWX is not intended to be a production solution, or at least that's what I gather. It's good for playing around with, but if you're looking to evaluate something for commercial use, I would recommend the trial version of Ansible Tower. (That's actually the next step for me after I get more time to play with AWX)

But back to the topic at hand, I really did like the interface of AWX 16, and I wish that I didn't have to rollback just for this one thing. @jakemcdermott would you be able to elevate the priority on this issue?

**Comment by jakemcdermott** [comment]
> it would be great if someone reply to this .this is absolute necessary feature where one should be able to chose the inventory file from any path.

We intend to fix this, which is why it has the `needs_devel` label.

**Comment by artainis** [comment]
As a neat hack/workaround, you can edit the html source in the current page to add an option or edit an existing option for the file that's not listed. This worked for me and I didn't have to roll back!
![image](https://user-images.githubusercontent.com/12302696/107108545-6774e400-67fe-11eb-8dfb-2aa1f4012271.png)

**Comment by jheinitz** [comment]
Hello,

we have the same situation after upgrading from 15.01 to 17.0.1. This issue is linked to #9214 which is closed and to be fixed in one of the next releases. Do you have a roadmap for new releases especially for 17.0.2?

Kind regards

Jens

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/9120

**Comment by danielo515** [comment]
This is happening on 17.0.1 using docker-compose install. Luckly I can just hack the html and select the proper file

**Comment by kladiv** [comment]
+1 Inventory scripts in SCM with .py extension does not appear in drop-down list and not typable.
At the moment i set it via awx CLI/API

**Comment by bdoublet91** [comment]
Rollback to 15.0.1 to make it works. If u don't need feature of version 16 and 17, use 15.0.1.
I could import project from github, import inventory by type in and create job template with schedule, all  I wanted.
You ll have to use postgres 10

**Comment by laschalkh** [comment]
> As a neat hack/workaround, you can edit the html source in the current page to add an option or edit an existing option for the file that's not listed. This worked for me and I didn't have to roll back!
> ![image](https://user-images.githubusercontent.com/12302696/107108545-6774e400-67fe-11eb-8dfb-2aa1f4012271.png)

what is the path to edit this manually?

**Comment by Hetti** [comment]
I can add some more Info to this:

My setup: ansible/awx:17.0.1 via Docker

I took me some time to figure out the broken logic:

So what currently is shown in the drop down dialogue (in the specified inventory folder):
- empty files with no content and no extension
- files with .ini extension (empty or with content - doesn't matter)

What should also work
- files with content and without an .ini extension

it is totally possible to add the empty file with no extension and push aftwards the inventory content into it, it will sync it correctly.

This is in my opinion a bug, because in the Ansible documentation inventory files without extensions are documented: https://docs.ansible.com/ansible/2.3/intro_inventory.html

**Comment by k-y** [comment]
> > As a neat hack/workaround, you can edit the html source in the current page to add an option or edit an existing option for the file that's not listed. This worked for me and I didn't have to roll back!
> > ![image](https://user-images.githubusercontent.com/12302696/107108545-6774e400-67fe-11eb-8dfb-2aa1f4012271.png)
> 
> what is the path to edit this manually?

There's no path, per se, this workaround is suggesting using the "Inspect" (Ctrl+Shift+I in Chrome) feature in your browser to edit the HTML to allow you enter an arbitrary value in the form and then save it.

We had to use this workaround in 17.0.1 as well since we use a monorepo and the drop-down seems to have a limit on how many files it will populate.

It would be nice if there was a user-definable filter for paths so we can help AWX narrow down paths to our inventory files/dirs.

**Comment by unlikelyzero** [comment]
Covered in https://github.com/ansible/awx/pull/9120
