### ISSUE TITLE
Table column rows break from toolbar when in responsive resolutions between 600 < x < 1024

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9049]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Table column rows break from toolbar when in responsive resolutions between 600 < x < 1024

##### ENVIRONMENT
* AWX version: aa87a99441b595c3760a0950968b64a664382bfd

##### STEPS TO REPRODUCE
1. Open up the inventories list view
2. Narrow the width of the browser window between 600 and 1024 pixels

##### EXPECTED RESULTS

Table to match toolbar width

##### ACTUAL RESULTS

Table width recalculated and out of alignment with toolbar

##### ADDITIONAL INFORMATION

<img width="1327" alt="Screen Shot 2021-01-08 at 3 37 35 PM" src="https://user-images.githubusercontent.com/12446869/104062321-3f2aa300-51c8-11eb-9c5c-e876c72719dd.png">

**Comment by keithjgrant** [comment]
after discussion with @trahman73, we decided to hide the Groups, Hosts, and Sources columns for viewports that are too narrow to accommodate them. This is an approach that some other teams are taking in similar circumstances, and since we have the details view to see this data, it's simply a nice-to-have in the table view.

**Comment by tiagodread** [comment]
worked as expected, we have already a visual test to cover this list in /visualintegration/inventory.spec.js
