### ISSUE TITLE
Status icon on job page inconsistent

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9061]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

If I am on the projects page and I click the status icon (the little green/red square) I am taken to the job details of the sync. Clicking the same icon on the jobs page toggles the checkbox next to it.

**Comment by mabashian** [comment]
This issue actually goes away with our new list tables.  The old list rows had the behavior where if you clicked somewhere on the row where there wasn't a link it would check the checkbox.  Since the status on the jobs list wasn't a link, clicking it would check the checkbox.

That work is being tracked here #6189
