### ISSUE TITLE
Update EE Add/List/Edit/Details with latest API changes

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9087]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Update EE Add/List/Edit/Details with latest API changes. There is a field name now, for instance. Evaluate the latest API changes, and update UI accordingly.

**Comment by jakemcdermott** [comment]
Addressed in this PR: https://github.com/ansible/awx/pull/9179 via https://github.com/ansible/awx/pull/9179/commits/7d7a1e5095652e928f91eb5fe418db38f8ce304c

**Comment by tiagodread** [comment]
@nixocio note that the field Pull has `No pull option has been selected` as a valid selection, is this the expected behaviour or this option is only the "label" for this field?

![image](https://user-images.githubusercontent.com/12464858/107686646-43912280-6c84-11eb-9d2d-59a95ec2b008.png)
![image](https://user-images.githubusercontent.com/12464858/107686674-4ab83080-6c84-11eb-9120-726299f4f872.png)
