### ISSUE TITLE
[Question] new UI and upgrade

### ISSUE THREAD

**Issue by mo-saeed** [ansible/awx#9136]
Hello, we are using AWX version 15.0.0, version 16.0.0, and 17.0.0 are introducing breaking changes for the UI. we decided to upgrade when the UI is completely ready and all changes are implemented. the question how can I track that? and will it be written on the release notes when the UI is completely ready?

**Comment by ryanpetrello** [comment]
👋 @mo-saeed the new UI is pretty close, though it doesn't have 100% feature parity with the old UI yet.  I've been using it as a daily driver since 16.0.0 (early December).

I'd suggest setting up a sample install and giving it a whirl and seeing what you think - we don't have an estimate for full feature parity.

@jakemcdermott @mabashian is there a place you all are tracking the major "what's left" items?

**Comment by jakemcdermott** [comment]
:wave: Hello! 

>  how can I track that

We track the ui work here: https://github.com/ansible/awx/projects/11

> will it be written on the release notes when the UI is completely ready

We'll continue to add announcements to the release notes as remaining features are completed.

That said, the AWX project is the location of our upstream development efforts. It's a fast-moving project that changes often. If by "completely ready" you mean "bug-free and production ready" then we won't be making such an announcement. We don't recommend you use AWX for production.

If you have questions, please reach out to the community mailing list or stop by the `ansible-awx` irc channel on freenode.

Thanks and happy automating!
