### ISSUE TITLE
No output or result is empty in the Jobs

### ISSUE THREAD

**Issue by kunaludapi** [ansible/awx#9206]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have freshly setup my AWX server multiple time, whenever I execute template there is no Output and status is red in the jobs as attached screenshot,

I have followed these blogs to install and configure Ansible AWX.
http://vcloud-lab.com/entries/devops/install-ansible-awx-tower-on-ubuntu-linux
http://vcloud-lab.com/entries/devops/getting-started-ansible-awx-tower-for-it-automation-run-first-playbook

![image](https://user-images.githubusercontent.com/10530852/106634275-a52b0000-65a5-11eb-9009-6ef2d9d79afa.png)

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Docker
* Ansible version:  2.9.17
* Operating System: Ubuntu 20
* Web Browser: Edge and chrome

##### STEPS TO REPRODUCE

Execute Template but no output.
I am following below procedure.
http://vcloud-lab.com/entries/devops/getting-started-ansible-awx-tower-for-it-automation-run-first-playbook

##### EXPECTED RESULTS

No output, so not able to determine what is going wrong

##### ACTUAL RESULTS

There should be some output on the job output why it failed

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/10530852/106635375-c3ddc680-65a6-11eb-9ee5-ce99559fbc43.png)

**Comment by jakemcdermott** [comment]
:wave: Hello @kunaludapi .

We'll need to surface the error and traceback information in the output panel for you to see what's going on. This information comes from a different source than the regular output so some code updates were needed.

We're tracking the work here: https://github.com/ansible/awx/issues/8709 

I've [opened a PR to devel](https://github.com/ansible/awx/pull/8726) to address this and it'll be fixed in an upcoming AWX release.

**Comment by kunaludapi** [comment]
Is there any ETA for this?
