### ISSUE TITLE
Cannot type inventory file for synced from project

### ISSUE THREAD

**Issue by ProfileAdmin** [ansible/awx#9214]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not able to type in inventory file for inventory that is synced from project?

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 18.04 LTS
* Web Browser: Chrome Enterprise

##### STEPS TO REPRODUCE

Create inventory sourced from project

##### EXPECTED RESULTS

Be able to type in the location path of inventory file for inventory sync

##### ACTUAL RESULTS

Can only click on Inventory file and select what is shown, non yml files and root path.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/76785344/106664972-5e201900-656b-11eb-9e98-f084dafa8078.png)

**Comment by jakemcdermott** [comment]
:wave: Hi  @ProfileAdmin. Thanks for the issue. We're tracking work for this here: https://github.com/ansible/awx/issues/9043

There's a PR open with a patch for this bug and it will be merged into devel soon: https://github.com/ansible/awx/pull/9120. It will be fixed in an upcoming awx release.

Thanks and happy automating.

**Comment by ProfileAdmin** [comment]
Thank You!
