### ISSUE TITLE
Unable to add survey as any user

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#922]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

"add survey" hangs browser tab. F5 works to get back but not in to survey.
##### ENVIRONMENT
* AWX version: 1.0.2.319
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: linux
* Web Browser:  Firefox and chrome

##### STEPS TO REPRODUCE

fresh install of latest awx. add template,  save template. push "add survey"
##### EXPECTED RESULTS

open survey wizard.
##### ACTUAL RESULTS

template page hangs

**Comment by steaksauce-** [comment]
Similar to other issues I have been browsing around in.
When's the last time you upgraded? They pushed a fix in this week, and updated the docker containers sometime yesterday it seems.

If upgrading doesn't do the trick, I've had luck doing the following (pulled directly from my response in #891 ):

Using the docker option to pull from source, I was able to get this working. The reported version is AWX 1.0.2.301

To pursue this option, I simply commended out two lines in my inventory.yml in my install directory:
`dockerhub_base=ansible dokcerhub_version=latest`

Afterwards, I stopped and removed my docker containers:
```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker ps -a -q)

```
Finally, I ran the playbook from the install directory again:

> ansible-playbook -i inventory install.yml

After several minutes, AWX was made available. Please note: in my testing, I was able to retain projects, job templates, etc...

PLEASE NOTE: Per the continued discussion in #891, it seems like the code was pulled from a branch using version 1.0.2.301, but the fix was applied.

**Comment by mkempster22** [comment]
Related to #875

**Comment by hemskgren** [comment]
This is fixed and work as expected in 1.0.2.327.

**Comment by madeinoz67** [comment]
can also confirm that is working in 1.0.2.337

**Comment by matburt** [comment]
closing as confirmed working
