### ISSUE TITLE
Accept vars in requirements.yml

### ISSUE THREAD

**Issue by fvzwieten** [ansible/awx#9271]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This has already been discussed in an issue for the ansible project. See https://github.com/ansible/ansible/issues/44374
Although that issue is closed, the larger issue is still open and in need for a good solution. AFAICT Galaxy / Automation Hub doesn't provide for this. 

user-story:
As a company, i want to use a separate gitlab repo to store all my roles and collections. We use branching/tagging in that repository. Now, we want to control in a project, using something like vars, which branch/tag of that roles/collecitons repository we want to use.

suggested solution:
Accept vars in requirements.yml and have ansible-galaxy interpret them correctly in such a way that it would work also in AWX/Tower. Example:
    in requirement.yml:
    src: https://www.github.com/acme_roles/my_webserver
    version: "{{ my_roles_version }}"

in i.e. group_vars/all:
my_roles_version: "1.0"

**Comment by wenottingham** [comment]
If it's not being done in ansible-galaxy, it's not being done here. Sorry.

**Comment by fvzwieten** [comment]
So how would users of awx solve this, then?

**Comment by wenottingham** [comment]
awx only calls ansible-galaxy, and does not attempt to read or otherwise interpret the requirements file in any way other than "it's present". That is unlikely to ever change.

If you want a particular branch of content assembled and used for execution, that is planned to be solved with execution environments. See https://github.com/ansible/awx/issues/5157
