### ISSUE TITLE
Job type incorrect for "check" jobs on AWX17.0.1

### ISSUE THREAD

**Issue by mattthehearn** [ansible/awx#9319]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
All jobs have a "job type" of "Playbook Run," even if they were run in "check" mode.  There is no other indication in the job details that the job was a "check" job.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 18
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Run a job in a template in "check" mode and look at the job details.

##### EXPECTED RESULTS
I would expect the "Job Type" to read "Check", or some other field in the details to indicate that the job was run in "check" mode.

##### ACTUAL RESULTS
The "Job Type" is always "Playbook Run."

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/14980647/107992100-f96eb080-6fa5-11eb-8965-bcdac672f3ce.png)
![image](https://user-images.githubusercontent.com/14980647/107992205-376bd480-6fa6-11eb-82b9-d1608943664f.png)

**Comment by unlikelyzero** [comment]
Note: we're seeing similar problems with Prompt on launch defaults for Job Type not being respected. Looks like it was unrelated to POL.

**Comment by mattthehearn** [comment]
I should note, it does seem to run the job in check mode as requested; I just ran a test, and it made no actual changes.  So it seems to be a simple UI bug.  A check of the job in the API reports "job_type": "check".

**Comment by jakemcdermott** [comment]
There's two types of types for jobs:

```
job.type
-------------
adhoc command
project update
job (aka: playbook run)
inventory update
workflow job

job.job_type
-----------
run
check

```


We disambiguate "Check" vs "Run" jobs in the old ui through the displayed "Job Type" field. The only way to tell what `job.type` you were viewing was by inspecting the url. In the new UI, we (perhaps incorrectly) show the `job.type` instead of `job.job_type` for "Job Type". 

Having recently addressed another issue where users didn't know what `job.type` they were viewing, I think it's important we show both the `job.type` _and_ the `job.job_type`, but I don't want to display the words "Type" and "Job Type" on the job details, because that could be confusing.

Since the "Check" vs "Run" construct only seems to apply to playbook jobs, I propose we add the "Check" to the current type display for playbook jobs, e.g:

```
"Job Type: Playbook (Check)"   <--- check jobs
"Job Type: Playbook"           <--- run jobs (no change)
```

Thoughts?

**Comment by ryanpetrello** [comment]
@jakemcdermott 


![](https://media.giphy.com/media/oGO1MPNUVbbk4/giphy.gif)

**Comment by mattthehearn** [comment]
Out of curiosity, what strings can "job.type" contain, other than "playbook"?  Seems odd to have both "job.type" and "job.job_type", though I'd be lying if I said there weren't a billion similarly confusing variables in my own code. :)
