### ISSUE TITLE
Disable fields name, surname and email due to GDPR requirements

### ISSUE THREAD

**Issue by lucas-benedito** [ansible/awx#9376]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As per GDPR requirement the data name, surname and email cannot be stored in the systems but those fields cannot be disabled in Ansible Tower UI at the moment.
Suggestions:
- Create toggle option for GDPR where you can disable specific fields
- Create user role in order to disable those fields if not system administrator

**Comment by xstasi** [comment]
FWIW I'm not entirely convinced that this is not a bug: if a system is not GDPR compliant when it holds personal data that users may not be able to retain control of, it should not be possible for unprivileged users to "force" the system out of compliance.

This is even more true when authentication is done externally, so tower should be holding virtually no user data.

Rather than disabling specific fields, I think that there should be an optional role that allows users to self-edit. It could be enabled by default for retrocompatibility.

**Comment by wenottingham** [comment]
> As per GDPR requirement the data name, surname and email cannot be stored in the systems

While I don't want to speak for their auditor, on the face of it that's either an overly restrictive corporate policy that goes well above and beyond, or an incorrect reading of the standard.

For a deployment with internal users only to that company, it's *definitely* incorrect - all of the username fields are already covered under the normal legal basis for data collection. Even with external users it's likely covered under whatever agreement that they're granting them accounts to the automation system under. and the GDPR then just specifies how that data is protected.

In any case, they're all optional fields regardless in the API, and in AWX most of them are now optional in the UI.

**Comment by xstasi** [comment]
@wenottingham the customer's use case is to address users with "self-harming" behaviour, who go and input their personal data in their Tower account. By doing so, the users turn the tower node to a "GDPR-relevant" machine which it would otherwise not be.

That is why they would like users to not be able to self edit, and I believe it makes sense: it should not be obvious that users are in charge of defining their own account parameters. Being optional in this case is, while appreciated, not enough.

**Comment by wenottingham** [comment]
By default, fields that come from an IDP (LDAP, etc) are replaced by the IDP data on every login; beyond that, there are service accounts and tokens if they are not interested in having user accounts tied to individuals.

**Comment by xstasi** [comment]
They want to have individual accounts tied to each users, they just don't want any personal data other than the login to be recorded.

Their "threat model" is a user that goes and inputs their personal data on their account page against the admin's will. Even if all personal data were to be wiped at the next login that does not change the fact that the data was there for a while and that would make tower GDPR-relevant. Not to mention that if the user does not log in again after putting their personal data it will stay there indefinitely.

**Comment by unlikelyzero** [comment]
Test drift was addressed

**Comment by xstasi** [comment]
@unlikelyzero sorry, what was the resolution for this issue?

**Comment by unlikelyzero** [comment]
@xstasi sorry! The issue has been addressed as a part of https://github.com/ansible/awx/pull/9381 and will be available in the next release of AWX!

**Comment by xstasi** [comment]
@unlikelyzero thank you for the reply :) I understand that that commit is relevant for this issue, but that alone is not enough to consider it solved.

The problem at hand is that users can modify their own data and there is no way to prevent them from doing so, email being mandatory was just tangential to it.

**Comment by unlikelyzero** [comment]
@xstasi I see. In that case, I can re-open this issue, but I'd ask that you update the title and description to be a bit more specific about desired implementation. 

Re-reading this issue makes me think that you're ultimately asking for three things:
1. The ability for a non-privileged-user to delete records of their activity
2. The ability for a non-privileged-user to delete records of their optional fields
3. The ability for an admin-role to "sanitize" or "scrub" an instance by removing all optional fields from all users

Is that right?

**Comment by xstasi** [comment]
@unlikelyzero let me try to rephrase the requirement: the customer needs a way to make it impossible for users to edit their own fields, optional or otherwise.

Currently any user that can log in can also enter their first name / last name / etc in their profile. There needs to be a way to forbid them to do so. Removing the data after some time is not enough.

**Comment by wenottingham** [comment]
I don't think that is particularly relevant for AWX.

A user that has the ability to create any object (inventory, job template, etc) has the same ability to maliciously 'store' names/emails/phone numbers in a way that they are tracked. A user that can only launch jobs, but can provide survey parameters or extra_vars, can do the same.

The only case where restricting this could actually cause a restriction is for accounts that don't have any of those capabilities, and those are best solved by external integrations.
