### ISSUE TITLE
Organizations- Tabs include Teams view, should be removed

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9396]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When accessing the detail view of an organization, one of the tabs allows access to Teams. The Teams tab should be removed.

##### STEPS TO REPRODUCE

Click on the organizations resource tab on the left side of the screen.
Click on one of the individual organizations.
Note the presence of "Teams" as one of the available tabs.

![image](https://user-images.githubusercontent.com/63685497/108906369-cf913b80-75ee-11eb-896e-c10366d287cb.png)

**Comment by mabashian** [comment]
I'd like to discuss this a little more before anyone works this one.  I think this tab is actually quite useful and can't be wholesale replaced by the access tab.

Here's an example:

<img width="1473" alt="Screen Shot 2021-03-03 at 9 11 10 AM" src="https://user-images.githubusercontent.com/9889020/109818326-dfb5a600-7c00-11eb-9af6-3bdde558ba7f.png">
<img width="1468" alt="Screen Shot 2021-03-03 at 9 11 17 AM" src="https://user-images.githubusercontent.com/9889020/109818330-dfb5a600-7c00-11eb-8f9a-cbdce7b41731.png">

In this scenario the Foo team has no members.  Since the access list shows what _users_ have roles on the org (including via teams), the team does not show up in the access list.

cc @wenottingham

**Comment by mabashian** [comment]
Marking as blocked until we figure out how to proceed

**Comment by wenottingham** [comment]
In the old UI, this was a route (/organizations/N/teams) that you could get to from the org card, but wasn't a tab. I think keeping it as a tab makes more sense - otherwise there's no easy way to get a list of teams in an org other than by listing all teams and filtering.

**Comment by unlikelyzero** [comment]
Keeping, then
