### ISSUE TITLE
Installation without kubernetes or openshift (no openshift, no kubernetes)

### ISSUE THREAD

**Issue by AleksandrKls** [ansible/awx#9422]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
- Installer

##### ENVIRONMENT
- AWX version: 17.0.1
- AWX install method: without kubernetes or openshift
- Operating System: Debian

##### QUESTION
We do not use system for automating deployment. How can we deploy an application without using Kubernetes or OpenShift?

**Comment by kladiv** [comment]
+1 why no more local_docker (from 17.0.1)?

**Comment by yigitpolat** [comment]
take a look at https://github.com/ansible/awx/tree/devel/tools/docker-compose

**Comment by kladiv** [comment]
Hi,
i'm not talking about build Ansible development docker images but standard installation of AWX (there was a role local_docker in the installer dir). It uses images from DockerHub

**Comment by yigitpolat** [comment]
You can follow 'Run AWX - start the containers' subtopic inside that readme.

**Comment by jon4hz** [comment]
Yeah it's a bummer that they removed the local_docker installation...

**Comment by ryanpetrello** [comment]
👋 

I want to chime in - 17.0.1 still definitely supports the current "local Docker" install method.  If it's not working, or you're having trouble, make sure you've actually cloned the appropriate 17.0.1 tag (or downloaded the proper release tarball: https://github.com/ansible/awx/releases/tag/17.0.1).

In the near future (the next major release), we're making changes to how you deploy AWX on Docker.  It's still `docker-compose` based, but one notable difference is that you'll have to build the image yourself instead of pulling from DockerHub (there's a simple one-line `make` target for doing so).  There's also a migration path from the old install method to the new one: https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md.  Here's a mailing list post from late last year where we announced these changes (including the reasoning behind it):

https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/En0NrUiqAAAJ?pli=1

...and (as @yigitpolat mentioned) here's a README you can begin tinkering with pre-release if you're so inclined:

https://github.com/ansible/awx/tree/devel/tools/docker-compose

**Comment by kladiv** [comment]
@ryanpetrello in next release (major too) will you still update the AWX docker images in Docker Hub?

**Comment by shanemcd** [comment]
@kladiv The images on Docker Hub will not work for the development environment.

The next major release we will also remove the existing Kubernetes installer in favor of https://github.com/ansible/awx-operator. The images for this Operator will live on quay.io.

**Comment by AlexanderKls** [comment]
One more question. Why are so many connections created?
![image](https://user-images.githubusercontent.com/79723362/110720629-f7ec7d00-821f-11eb-8b34-977bab8a9815.png)
