### ISSUE TITLE
RFE: add rsync to postgres container

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#954]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
I wanted to use the ansible synchronize module to copy db dump off the postgres container. However unlike the task and web containers, rsync isn't installed. 

Can we get it added. 

##### ENVIRONMENT
* AWX version: 1.0.1.173
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: RHEL 7.4
* Web Browser: Chrome

**Comment by shanemcd** [comment]
We use the official Postgres container image from Docker Hub, so this would require maintaining our own which we want to avoid doing if possible.

Is there another route you could take? The Postgres client tools (including pg_dump) are installed in both the task and web containers.

You might also want to try the Docker connection plugin, but I have less experience with this.

It's also worth mentioning that since the data is stored in a bind-mount volume, you could just back up that directory on the host.

**Comment by akcrisp** [comment]
Thanks - ok - I will go with one of the other options - didn’t realise actually pg_dump was in the other containers - thanks for heads up
