### ISSUE TITLE
[ui_next] Add testability to the JT & WFJT form

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9582]
##### ISSUE TYPE
 - Task

##### SUMMARY
Add testability to the WFJT and JT forms, fields, buttons, modals

**Comment by mabashian** [comment]
@tiagodread @unlikelyzero @akus062381 @one-t there are a lot of _potential_ things that could have locators added to them on these forms.  It may be easier to work with a developer to identify what you all need specifically to avoid a bunch of back and forth.  Forms/fields will likely need data-cy's since ouia-id's aren't support on things like inputs and textareas.  Buttons and modals would have ouia-id's.

**Comment by unlikelyzero** [comment]
@mabashian in this case, we have direct links in our codebase to the missing components in the form of //TBR stubs. We didn't expect you (or want y'all to) to get to these tasks before feature parity was completed and filed them as `priority:medium`

**Comment by tiagodread** [comment]
> @tiagodread @unlikelyzero @akus062381 @one-t there are a lot of _potential_ things that could have locators added to them on these forms. It may be easier to work with a developer to identify what you all need specifically to avoid a bunch of back and forth. Forms/fields will likely need data-cy's since ouia-id's aren't support on things like inputs and textareas. Buttons and modals would have ouia-id's.

@mabashian I verified that after your PR the missing testability components were added, thanks.
