### ISSUE TITLE
Global Configuration for Connection Variables

### ISSUE THREAD

**Issue by nmajin** [ansible/awx#9583]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Looking to manage groupings of variables in a global configuration that is managed by System Admins in Tower/AWX. For example, connection variables for Windows and Linux hosts, which currently are defined in every single playbook or every single inventory, duplicating the configuration of these variables.

A similar configuration for a shared configuration would be:
- Settings > System > Jobs configuration with global environmental variables shared across jobs
- Settings > System > Logging for logging aggregators like Splunk also shared across the platform

Yes there are workarounds to define a single inventory and then maybe create multiple Smart Inventories if multiple inventories still need to be managed, but this requires a very specific setup of how inventories are created.

**Comment by wenottingham** [comment]
I don't think this is a correct pattern for doing this.
You end up in one of two scenarios:
- if the global settings cannot be overriden, a system administrator leaves the inventory admin no ability to "fix" their connection, which is changed by things that admin can't even see
- if the global settings *can* be overriden, the admin can't enforce anything here, and the benefit is lost

I don't think we'd do this.

**Comment by nmajin** [comment]
I would say it really comes down to one scenario for my particular feature request where the global settings can be overridden; provide the flexibility like the extreme flexibility that is already in place with variable precedence today with ansible.

As a system admin, I would rather provide best practices and control the default configuration in one spot as opposed to rely on developers to do this.

I believe this should be reviewed. With a small group of developers, sure, just have that small group manage their connection configuration, but at a much bigger scale I don't think the developer should be controlling the connection parameters here (unless they absolutely need to override them).

**Comment by wenottingham** [comment]
> that is already in place with variable precedence today with ansible

This speaks to why we'd be unlikely to do this. We are trying to minimize the reasons why playbooks may behave differently in AWX than outside of AWX (which is one of the motivators for our move to execution environments); having a free-form field that would apply to all jobs in this way works against this - the same playbook would behave differently based on where it's executed.

I know that AWX_TASK_ENV is there; that is primarily designed for tasks executed by AWX itself (notifications, credential plugins, and so on) - while it can be used to pass arbitrary parameters to ansible, it's not why it's there.

I get that this is sort of a complexity of how ansible defines connections - the default parameters work for Unix+SSH, and requires overriding multiple things for any other device type (Windows, network devices, etc.). That's why the recommendation is to have that as close to as possible where the devices are defined (host_vars or group_vars) - that's where it's known how the connections are used.

**Comment by nmajin** [comment]
Thanks for the response, and I do understand to keep Ansible Engine and AWX/Tower in synch, that is a very valid point. I guess the `AWX_TASK_ENV` and the global configuration I noted that already exists in AWX/Tower is what continues to make me think that there should be something global for it. Is there anything in Ansible Engine globally (not on a project-by-project basis) such as ansible.cfg that we could conditionally configure vars for Linux and Windows for example?

**Comment by wenottingham** [comment]
I don't think so, but that is more a question for https://github.com/ansible/ansible, not AWX. I could see a feature in core Ansible where it sets certain defaults on the type of device connected to... the biggest question would be how it would know the device type to key this off of.
