### ISSUE TITLE
RFE: Pass in sslcert and sslkey when required for Postgres connection

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#9615]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Certain database providers require sslkey and sslcert to be passed in to the psql command in order to connect (GCP for example). Although this is not something we test directly, several customers use cloud provided databases such as this in production. This could be solved by adding those options to the postgres.py file when required. 

Example failing commands:
```
[root@host ansible-automation-platform-setup-bundle-1.2.2-1]# psql \"sslmode=verify-ca sslrootcert=/root/server-ca.pem hostaddr=10.42.10.10 port=5432 
psql \"sslmode=verify-full sslrootcert=/root/server-ca.pem  hostaddr=10.163.80.7 port=5432 user=postgres dbname=postgres\"
psql: host name must be specified for a verified SSL connection
[root@host ansible-automation-platform-setup-bundle-1.2.2-1]# psql \"sslmode=verify-ca sslrootcert=/root/server-ca.pem sslcert=/root/client-cert.pem sslkey=/root/client-key.pem hostaddr=10.42.10.10 port=5432 user=postgres dbname=postgres\"
```

**Comment by khokarv** [comment]
Without SSL on on GCP CloudSQL, tower installer works perfect to start with.

GCP CloudSQL being managed service, there is no control on DB config, which make sense for security and many other reasons.

All you get from them is an IP Address and 3 files once you enable SSL:

server-ca.pem
client-key.pem
client-cert.pem

GCP CloudSQL PostgreSQL need all 3 files:
psql "sslmode=verify-ca sslrootcert=/path/server-ca.pem sslcert=/path/client-cert.pem sslkey=/path/client-key.pem hostaddr=<IP Address> port=5432 user=postgres dbname=postgres"

`# you can't use hostname, since Certs are created for hostname from GCP like this project-name:hostname, which doesn't work in real life due to ":" and project-name added in front.

From tower side:
inventory file:

since we are not installing DB but using an external one, [database] will stay empty

[database]

pg_host='<IP Address>'
pg_port='5432'

pg_database='postgres'
pg_username='postgres'
pg_password='PASSWORD'
pg_sslmode='verify-ca'  # Due to hostname issue with GCP, use verify-ca not verify-full else it will fail on hostname verification

custom_ca_cert=/path/server-ca.pem
postgres_use_ssl = True
postgres_ssl_cert = /path/client-cert.pem
postgres_ssl_key = /path/client-key.pem

now since we are not installing DB and you have not admin access to CloudSQL, we are not copying these files to DB at all, but just use them and copied to appropriate path from where PostgreSQL connection will be made. 
Where to keep them and how to securely save them is up-to tower Engineering team.

**Comment by wenottingham** [comment]
This isn't relevant to AWX. Closing.
