### ISSUE TITLE
When Prompt on Launch Content Error is closed, the Prompt on Launch Modal Open

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#9676]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Force a content Error on a job template that has a prompt on launch.  

##### STEPS TO REPRODUCE

For a content Error on a prompt on launch job template.  A content Error is rendered inside a modal. Close the modal
https://github.com/ansible/awx/issues/7914#issuecomment-773422343

##### EXPECTED RESULTS

Just the template list is rendered
##### ACTUAL RESULTS

The Prompt on Launch Wizard appears.

**Comment by AlexSCorey** [comment]
Actually looks like the contentError within the prompt on launch workflow might be dead code. We can probably remove it.

**Comment by AlexSCorey** [comment]
QE can you confirm whether there is a way to trigger a content Error before the modal opens?

**Comment by kdelee** [comment]
![Screenshot from 2021-04-13 12-45-41](https://user-images.githubusercontent.com/29239279/114590050-45f90400-9c56-11eb-8a92-78d82eba6824.png)

after selecting a Prompt on Launch inventory and going to the next part of the wizard, I went and deleted the inventory before launching. I got this error modal. I think it is a good experience, because it told me it messed up and why. I'm going to close this bug because it is working in a good way.
