### ISSUE TITLE
AWX 18.0.0 in Kubernetes: ansible version is not shown (not detected)

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9829]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 18.0.0 deployed in K3s with the operator, "Info->About" shows "ansible version: unknown"

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: kubernetes (k3s) using the awx operator
* Ansible version:  unknown (see above)
* Operating System: K3s running on debian buster
* Web Browser: Firefox 87

##### STEPS TO REPRODUCE
deploy AWX 18 in k3s using the awx-operator

##### EXPECTED RESULTS

I would expect awx to be able to detect the ansible version used

##### ACTUAL RESULTS

ansible version is unknown

**Comment by ryanpetrello** [comment]
Hey @lemmy04,

This should be addressed in the next version of AWX:

https://github.com/ansible/awx/pull/9697

It'll actually be addressed by no longer displaying this information, because as of AWX 18, there's no longer a "global" version of ansible installed under the hood - it's dependent on the Execution Environment used on the job, and it's only available inside of the container(s) where playbooks run.

**Comment by lemmy04** [comment]
that makes sense. would there be a way to inspect the different EE's for the versions of ansible inside?

**Comment by ryanpetrello** [comment]
AWX doesn't proactively do this and report it in the API, but it's something we could maybe do as an enhancement somewhere down the line.
